import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { BiotechCompanyDirectorySummary, BusinessPremisesPublicLiabilityInsuranceSummary, BusinessRegistrationChangeSummary, ChildMedicalSubsidyContractedProviderSummary, CivicGroupSummary, CompanyRegistrationChangeSummary, ConsumerDisputeAbsentBusinessOperatorSummary, ContractedVaccinationMedicalProviderSummary, DentureSubsidyMedicalProviderSummary, DisabilityEmploymentResourceSummary, ElderlyWelfareInstitutionSummary, InfantCareCenterEvaluationSummary, IndustryGrantSummary, LaborStandardActViolationSummary, MetroProcurementScheduleSummary, NangangSoftwareParkCompanySummary, PerformingArtsGroupSummary, PubliclyFundedHpvVaccinationProviderSummary, QuasiPublicInfantCareCenterSummary, RegisteredAnimalHospitalSummary, RegisteredCramSchoolSummary, RegisteredHotelSummary, RegisteredLaborUnionSummary, ShelteredWorkshopDirectorySummary, TaipeiTravelAccommodationZhSummary, TelepsychologyCounselingInstitutionSummary } from '../src/types';

const dataDir = join(process.cwd(), 'public/data');
const [civicGroups, performingArtsGroups, vaccinationProviders, hpvProviders, childMedicalSubsidyProviders, dentureSubsidyProviders, disabilityEmploymentResources, shelteredWorkshops, elderlyWelfare, biotechCompanies, telepsychology, publicLiabilityInsurance, businessChanges, companyChanges, laborUnions, infantCare, infantCareEvaluations, travelAccommodations, industryGrants, metroProcurement, registeredCramSchools, registeredHotels, laborViolations, consumerDisputeAbsence, nangangCompanies, animalHospitals] = await Promise.all([
  readFile(join(dataDir, 'civic-group-summary.json'), 'utf8').then((text) => JSON.parse(text) as CivicGroupSummary),
  readFile(join(dataDir, 'performing-arts-group-summary.json'), 'utf8').then((text) => JSON.parse(text) as PerformingArtsGroupSummary),
  readFile(join(dataDir, 'contracted-vaccination-medical-provider-summary.json'), 'utf8').then((text) => JSON.parse(text) as ContractedVaccinationMedicalProviderSummary),
  readFile(join(dataDir, 'publicly-funded-hpv-vaccination-provider-summary.json'), 'utf8').then((text) => JSON.parse(text) as PubliclyFundedHpvVaccinationProviderSummary),
  readFile(join(dataDir, 'child-medical-subsidy-contracted-provider-summary.json'), 'utf8').then((text) => JSON.parse(text) as ChildMedicalSubsidyContractedProviderSummary),
  readFile(join(dataDir, 'denture-subsidy-medical-provider-summary.json'), 'utf8').then((text) => JSON.parse(text) as DentureSubsidyMedicalProviderSummary),
  readFile(join(dataDir, 'disability-employment-resource-map-summary.json'), 'utf8').then((text) => JSON.parse(text) as DisabilityEmploymentResourceSummary),
  readFile(join(dataDir, 'sheltered-workshop-directory-summary.json'), 'utf8').then((text) => JSON.parse(text) as ShelteredWorkshopDirectorySummary),
  readFile(join(dataDir, 'elderly-welfare-institution-summary.json'), 'utf8').then((text) => JSON.parse(text) as ElderlyWelfareInstitutionSummary),
  readFile(join(dataDir, 'biotech-company-directory-summary.json'), 'utf8').then((text) => JSON.parse(text) as BiotechCompanyDirectorySummary),
  readFile(join(dataDir, 'telepsychology-counseling-institution-summary.json'), 'utf8').then((text) => JSON.parse(text) as TelepsychologyCounselingInstitutionSummary),
  readFile(join(dataDir, 'business-premises-public-liability-insurance-summary.json'), 'utf8').then((text) => JSON.parse(text) as BusinessPremisesPublicLiabilityInsuranceSummary),
  readFile(join(dataDir, 'business-registration-change-summary.json'), 'utf8').then((text) => JSON.parse(text) as BusinessRegistrationChangeSummary),
  readFile(join(dataDir, 'company-registration-change-summary.json'), 'utf8').then((text) => JSON.parse(text) as CompanyRegistrationChangeSummary),
  readFile(join(dataDir, 'registered-labor-union-summary.json'), 'utf8').then((text) => JSON.parse(text) as RegisteredLaborUnionSummary),
  readFile(join(dataDir, 'quasi-public-infant-care-center-summary.json'), 'utf8').then((text) => JSON.parse(text) as QuasiPublicInfantCareCenterSummary),
  readFile(join(dataDir, 'infant-care-center-evaluation-summary.json'), 'utf8').then((text) => JSON.parse(text) as InfantCareCenterEvaluationSummary),
  readFile(join(dataDir, 'taipei-travel-accommodation-zh-summary.json'), 'utf8').then((text) => JSON.parse(text) as TaipeiTravelAccommodationZhSummary),
  readFile(join(dataDir, 'industry-grant-summary.json'), 'utf8').then((text) => JSON.parse(text) as IndustryGrantSummary),
  readFile(join(dataDir, 'metro-procurement-summary.json'), 'utf8').then((text) => JSON.parse(text) as MetroProcurementScheduleSummary),
  readFile(join(dataDir, 'registered-cram-school-summary.json'), 'utf8').then((text) => JSON.parse(text) as RegisteredCramSchoolSummary),
  readFile(join(dataDir, 'registered-hotel-summary.json'), 'utf8').then((text) => JSON.parse(text) as RegisteredHotelSummary),
  readFile(join(dataDir, 'labor-standard-act-violation-summary.json'), 'utf8').then((text) => JSON.parse(text) as LaborStandardActViolationSummary),
  readFile(join(dataDir, 'consumer-dispute-absent-business-operator-summary.json'), 'utf8').then((text) => JSON.parse(text) as ConsumerDisputeAbsentBusinessOperatorSummary),
  readFile(join(dataDir, 'nangang-software-park-company-summary.json'), 'utf8').then((text) => JSON.parse(text) as NangangSoftwareParkCompanySummary),
  readFile(join(dataDir, 'registered-animal-hospital-summary.json'), 'utf8').then((text) => JSON.parse(text) as RegisteredAnimalHospitalSummary),
]);
await writeFile(join(dataDir, 'public-records-summary.json'), JSON.stringify({
  generatedAt: new Date().toISOString(),
  modules: {
    civicGroups: { recordCount: civicGroups.total },
    performingArtsGroups: { recordCount: performingArtsGroups.totalRecords, districtCount: performingArtsGroups.districtCount, recordsWithWebsite: performingArtsGroups.recordsWithWebsite },
    contractedVaccinationMedicalProviders: { recordCount: vaccinationProviders.totalRecords, districtCount: vaccinationProviders.districtCount, recordsWithPhone: vaccinationProviders.recordsWithPhone },
    publiclyFundedHpvVaccinationProviders: { recordCount: hpvProviders.totalRecords, districtCount: hpvProviders.districtCount, recordsWithPhone: hpvProviders.recordsWithPhone, recordsWithDistrictMismatch: hpvProviders.recordsWithDistrictMismatch },
    childMedicalSubsidyContractedProviders: { recordCount: childMedicalSubsidyProviders.totalRecords, administrativeAreaCount: childMedicalSubsidyProviders.administrativeAreaCount, taipeiDistrictCount: childMedicalSubsidyProviders.taipeiDistrictCount, outsideTaipeiProviderCount: childMedicalSubsidyProviders.outsideTaipeiProviderCount, recordsWithPhone: childMedicalSubsidyProviders.recordsWithPhone },
    dentureSubsidyMedicalProviders: { recordCount: dentureSubsidyProviders.totalRecords, subsidyTypeCount: dentureSubsidyProviders.subsidyTypeCount, administrativeAreaCount: dentureSubsidyProviders.administrativeAreaCount, taipeiDistrictCount: dentureSubsidyProviders.taipeiDistrictCount, recordsWithPhone: dentureSubsidyProviders.recordsWithPhone },
    disabilityEmploymentResourceMap: { recordCount: disabilityEmploymentResources.totalRecords, latestSourceYear: disabilityEmploymentResources.latestSourceYear, disabilityTypeCount: disabilityEmploymentResources.disabilityTypeCount, businessItemCount: disabilityEmploymentResources.businessItemCount, serviceCategoryCount: disabilityEmploymentResources.serviceCategoryCount, taipeiDistrictCount: disabilityEmploymentResources.taipeiDistrictCount, recordsWithContact: disabilityEmploymentResources.recordsWithContact, recordsWithPhone: disabilityEmploymentResources.recordsWithPhone },
    shelteredWorkshopDirectory: { recordCount: shelteredWorkshops.totalRecords, latestSourceYear: shelteredWorkshops.latestSourceYear, businessItemCount: shelteredWorkshops.uniqueBusinessItemCount, businessItemCategoryCount: shelteredWorkshops.businessItemCategoryCount, serviceCategoryCount: shelteredWorkshops.serviceCategoryCount, taipeiDistrictCount: shelteredWorkshops.taipeiDistrictCount, recordsWithContact: shelteredWorkshops.recordsWithContact, recordsWithPhone: shelteredWorkshops.recordsWithPhone, recordsWithUnifiedBusinessNumber: shelteredWorkshops.recordsWithUnifiedBusinessNumber },
    elderlyWelfareInstitutions: { recordCount: elderlyWelfare.totalRecords, districtCount: elderlyWelfare.districtCount, recordsWithPhone: elderlyWelfare.recordsWithPhone, totalApprovedBeds: elderlyWelfare.totalApprovedBeds },
    biotechCompanyDirectory: { recordCount: biotechCompanies.totalRecords, districtCount: biotechCompanies.districtCount, industryCategoryCount: biotechCompanies.industryCategoryCount, recordsWithValidCoordinates: biotechCompanies.recordsWithValidCoordinates },
    telepsychologyCounselingInstitutions: { recordCount: telepsychology.totalRecords, districtCount: telepsychology.districtCount, recordsWithPhone: telepsychology.recordsWithPhone, recordsWithMobile: telepsychology.recordsWithMobile },
    businessPremisesPublicLiabilityInsuranceRecords: { recordCount: publicLiabilityInsurance.totalRecords, districtCount: publicLiabilityInsurance.districtCount, recordsWithValidCoordinates: publicLiabilityInsurance.recordsWithValidCoordinates, recordsWithPolicyExpiryDate: publicLiabilityInsurance.recordsWithPolicyExpiryDate },
    businessRegistrationChangeRecords: { recordCount: businessChanges.totalRecords, districtCount: businessChanges.districtCount, recordsWithValidCoordinates: businessChanges.recordsWithValidCoordinates, recordsWithEventDate: businessChanges.recordsWithEventDate },
    companyRegistrationChangeRecords: { recordCount: companyChanges.totalRecords, districtCount: companyChanges.districtCount, recordsWithValidCoordinates: companyChanges.recordsWithValidCoordinates, recordsWithEventDate: companyChanges.recordsWithEventDate },
    registeredLaborUnions: { recordCount: laborUnions.totalRecords, districtCount: laborUnions.districtCount, taipeiAddressCount: laborUnions.taipeiAddressCount },
    quasiPublicInfantCareCenters: { recordCount: infantCare.totalRecords, districtCount: infantCare.districtCount, totalApprovedCapacity: infantCare.totalApprovedCapacity, totalActualEnrollment: infantCare.totalActualEnrollment },
    infantCareCenterEvaluationResults: { institutionCount: infantCareEvaluations.totalInstitutions, yearRecordCount: infantCareEvaluations.totalInstitutionYearRecords, districtCount: infantCareEvaluations.districtCount, latestEvaluationYear: infantCareEvaluations.latestEvaluationYear },
    taipeiTravelAccommodationsZh: { recordCount: travelAccommodations.totalRecords, districtCount: travelAccommodations.districtCount, totalRoomCount: travelAccommodations.totalRoomCount },
    industryGrantRecipients: { recordCount: industryGrants.totalRecords, uniqueCompanyCount: industryGrants.uniqueCompanyCount },
    metroProcurementSchedule: { recordCount: metroProcurement.totalRecords, periodCount: metroProcurement.periodCount },
    registeredCramSchools: { recordCount: registeredCramSchools.totalRecords, districtCount: registeredCramSchools.districtCount },
    registeredHotels: { recordCount: registeredHotels.totalRecords, districtCount: registeredHotels.districtCount, totalRoomCount: registeredHotels.totalRoomCount },
    laborStandardActViolationRecords: { recordCount: laborViolations.totalRecords, uniqueBusinessOrEmployerNameCount: laborViolations.uniqueBusinessOrEmployerNameCount, totalPenaltyAmountNtd: laborViolations.totalPenaltyAmountNtd },
    consumerDisputeAbsentBusinessOperators: { recordCount: consumerDisputeAbsence.totalRecords, uniqueRespondentNameCount: consumerDisputeAbsence.uniqueRespondentNameCount, recordsWithNegotiationDate: consumerDisputeAbsence.recordsWithNegotiationDate, recordsWithYearMismatch: consumerDisputeAbsence.recordsWithYearMismatch },
    nangangSoftwareParkCompanies: { recordCount: nangangCompanies.totalRecords, uniqueBusinessIdCount: nangangCompanies.uniqueBusinessIdCount, recordsWithValidCoordinates: nangangCompanies.recordsWithValidCoordinates },
    registeredAnimalHospitals: { recordCount: animalHospitals.totalRecords, districtCount: animalHospitals.districtCount, uniqueAddressCount: animalHospitals.uniqueAddressCount },
  },
}));
console.log('Built public records summary.');
