import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parseCsv } from './convertCivicGroups';

const root = process.cwd();
const input = join(root, 'data/raw/internal-medicine-institutions/source.csv');
const output = join(root, 'public/data/internal-medicine-institutions');
const rootReportPath = join(root, 'public/data/conversion-report.json');
const clean = (value?: string) => (value ?? '').replace(/[\r\n]+/g, ' ').replace(/\s+/g, ' ').trim();
const normalize = (value?: string) => clean(value).replace(/臺/g, '台').toLocaleLowerCase();
const districts = ['中正區', '大同區', '中山區', '松山區', '大安區', '萬華區', '信義區', '士林區', '北投區', '內湖區', '南港區', '文山區'];
const postalDistricts: Record<string, string> = { '100': '中正區', '103': '大同區', '104': '中山區', '105': '松山區', '106': '大安區', '108': '萬華區', '110': '信義區', '111': '士林區', '112': '北投區', '114': '內湖區', '115': '南港區', '116': '文山區' };
const bytes = await readFile(input); let text: string; try { text = new TextDecoder('utf-8', { fatal: true }).decode(bytes); } catch { text = new TextDecoder('big5').decode(bytes); }
const [rawHeaders, ...rows] = parseCsv(text); const headers = rawHeaders.map((header) => clean(header.replace(/^\uFEFF/, ''))); const seen = new Set<string>();
const issues = { missingInstitutionName: [] as string[], missingAddress: [] as string[], missingTelephone: [] as string[], malformedTelephone: [] as string[], invalidPostalCode: [] as string[], unresolvedDistrict: [] as string[], duplicateSequenceNumber: [] as string[], exactDuplicateRows: [] as string[], sameInstitutionMultipleAddresses: [] as string[], sameAddressMultipleInstitutions: [] as string[], postalAddressConflict: [] as string[] };
const records = rows.flatMap((row, index) => { const sourceValues = Object.fromEntries(headers.map((header, column) => [header, clean(row[column])])) as Record<string, string>; const signature = JSON.stringify(sourceValues); const rowNumber = String(index + 2); if (seen.has(signature)) { issues.exactDuplicateRows.push(rowNumber); return []; } seen.add(signature); const sourceSequenceNumber = sourceValues['序號'] ?? ''; const institutionName = sourceValues['機構名稱'] ?? ''; const postalCode = sourceValues['郵遞區號'] ?? ''; const address = sourceValues['地址'] ?? ''; const phoneRaw = sourceValues['電話'] ?? ''; const districtFromAddress = districts.find((district) => address.includes(district)) ?? null; const districtName = districtFromAddress ?? postalDistricts[postalCode] ?? ''; if (!institutionName) issues.missingInstitutionName.push(rowNumber); if (!address) issues.missingAddress.push(rowNumber); if (!phoneRaw) issues.missingTelephone.push(rowNumber); if (phoneRaw && !/^[0-9()+\-\s、,，#]+$/.test(phoneRaw)) issues.malformedTelephone.push(rowNumber); if (postalCode && !/^\d{3}(?:\d{2})?$/.test(postalCode)) issues.invalidPostalCode.push(rowNumber); if (!districtName) issues.unresolvedDistrict.push(rowNumber); if (postalCode && districtFromAddress && postalDistricts[postalCode] && postalDistricts[postalCode] !== districtFromAddress) issues.postalAddressConflict.push(rowNumber); return [{ id: sourceSequenceNumber || createHash('sha256').update(signature).digest('hex').slice(0, 16), sourceSequenceNumber, institutionName, postalCode, districtName, address, phoneRaw, phoneNumbers: phoneRaw.split(/[、,，]/).map(clean).filter(Boolean), hasAddress: Boolean(address), hasPhone: Boolean(phoneRaw), hasResolvedDistrict: Boolean(districtName), externalMapQuery: clean(`${address} ${institutionName}`), sourceValues }]; });
const grouped = (key: (record: (typeof records)[number]) => string) => records.reduce((all, record) => { const groupKey = key(record); if (groupKey) all.set(groupKey, [...(all.get(groupKey) ?? []), record]); return all; }, new Map<string, (typeof records)[number][]>()); const sourceRowsFor = (group: (typeof records)[number][]) => group.map((record) => String(records.indexOf(record) + 2));
for (const group of grouped((record) => record.sourceSequenceNumber).values()) if (group.length > 1) issues.duplicateSequenceNumber.push(...sourceRowsFor(group)); for (const group of grouped((record) => normalize(record.institutionName)).values()) if (new Set(group.map((record) => normalize(record.address))).size > 1) issues.sameInstitutionMultipleAddresses.push(...sourceRowsFor(group)); for (const group of grouped((record) => normalize(record.address)).values()) if (new Set(group.map((record) => normalize(record.institutionName))).size > 1) issues.sameAddressMultipleInstitutions.push(...sourceRowsFor(group));
const issueCount = Object.values(issues).reduce((total, values) => total + values.length, 0); const summary = { totalRecords: records.length, uniqueInstitutions: new Set(records.map((record) => normalize(record.institutionName)).filter(Boolean)).size, districtsCovered: new Set(records.map((record) => record.districtName).filter(Boolean)).size, postalCodes: new Set(records.map((record) => record.postalCode).filter(Boolean)).size, recordsWithPhone: records.filter((record) => record.hasPhone).length, recordsWithAddress: records.filter((record) => record.hasAddress).length, recordsWithResolvedDistrict: records.filter((record) => record.hasResolvedDistrict).length };
const report = { internalMedicineInstitutions: { sourcePage: 'https://data.taipei/dataset/detail?id=dbb54bf8-74a8-475d-ae88-a0ec4262c39a', sourceAgency: '臺北市政府衛生局', sourceFileUpdatedAt: '2025-06-11T16:40:31+08:00', metadataUpdatedAt: '2026-07-14T13:02:54+08:00', updateFrequency: 'annual', headers, inputRows: rows.length, outputRecords: records.length, issueCount, issues, notes: ['All five official source fields are preserved in sourceValues.', 'District is derived from an explicit address district or a conservative Taipei postal-code mapping.', 'No official coordinates, appointments, capacity, or medical service details are supplied or inferred.'] } };
const metadata = { key: 'internal_medicine_institutions', label: { zh: '臺北市內科醫療機構', en: 'Taipei Internal Medicine Institutions' }, ...report.internalMedicineInstitutions, recordCount: records.length };
await mkdir(output, { recursive: true }); const existing = await readFile(rootReportPath, 'utf8').then(JSON.parse).catch(() => ({})); await Promise.all([writeFile(join(output, 'records.json'), JSON.stringify(records, null, 2)), writeFile(join(output, 'summary.json'), JSON.stringify(summary, null, 2)), writeFile(join(output, 'metadata.json'), JSON.stringify(metadata, null, 2)), writeFile(join(output, 'conversion-report.json'), JSON.stringify(report, null, 2)), writeFile(rootReportPath, JSON.stringify({ ...existing, ...report }, null, 2))]); console.log(`Converted ${records.length} internal-medicine records.`);
