import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const input = join(process.cwd(), 'public/data/influenza-vaccine-providers-children-3plus-source.csv');
const output = join(process.cwd(), 'public/data/influenza-vaccine-providers-children-3plus');
const districtMap: Record<string, string> = { '63000010': '松山區', '63000020': '信義區', '63000030': '大安區', '63000040': '中山區', '63000050': '中正區', '63000060': '大同區', '63000070': '萬華區', '63000080': '文山區', '63000090': '南港區', '63000100': '內湖區', '63000110': '士林區', '63000120': '北投區' };

function clean(value: string | undefined) { return (value ?? '').replace(/\r?\n/g, ' ').replace(/\s+/g, ' ').trim(); }
function parseCsv(text: string) { const rows: string[][] = []; let row: string[] = []; let cell = ''; let quoted = false; for (let i = 0; i < text.length; i += 1) { const char = text[i]; if (char === '"' && text[i + 1] === '"' && quoted) { cell += '"'; i += 1; continue; } if (char === '"') { quoted = !quoted; continue; } if (char === ',' && !quoted) { row.push(cell); cell = ''; continue; } if (char === '\n' && !quoted) { row.push(cell); rows.push(row); row = []; cell = ''; continue; } cell += char; } if (cell || row.length) { row.push(cell); rows.push(row); } return rows.filter((row) => row.some(Boolean)); }
function splitPhones(raw: string) { return raw.split(/\s*(?:、|；|;|\/|\\|,|，)\s*/).filter(Boolean); }
function voiceStatus(value: string): 'available' | 'not_available' | 'conditional' | 'unknown' { if (!value) return 'unknown'; if (/無|否|不可|未提供/.test(value)) return 'not_available'; if (/視|條件|部分|限|需/.test(value)) return 'conditional'; return 'available'; }

const bytes = await readFile(input); let text: string; try { text = new TextDecoder('utf-8', { fatal: true }).decode(bytes); } catch { text = new TextDecoder('big5').decode(bytes); }
const [headers, ...rows] = parseCsv(text).map((row) => row.map(clean));
const records = rows.map((row, index) => { const sourceValues = Object.fromEntries(headers.map((header, column) => [header, row[column] ?? ''])); const sourceSequenceNumber = String(sourceValues['序號'] ?? ''); const districtRaw = String(sourceValues['行政區'] ?? ''); const institutionName = String(sourceValues['院所名稱'] ?? ''); const address = String(sourceValues['地址'] ?? ''); const phoneRaw = String(sourceValues['電話'] ?? ''); const voiceReservationRaw = String(sourceValues['語音預約'] ?? ''); const districtName = districtMap[districtRaw] ?? ''; const key = sourceSequenceNumber || `${institutionName}|${districtRaw}|${address}` || JSON.stringify(sourceValues); return { id: sourceSequenceNumber || createHash('sha1').update(key).digest('hex').slice(0, 12), module: 'influenza_vaccine_providers_children_3plus', sourceSequenceNumber, districtRaw, districtName, institutionName, address, phoneRaw, phoneNumbers: splitPhones(phoneRaw), voiceReservationRaw, voiceReservationStatus: voiceStatus(voiceReservationRaw), hasAddress: Boolean(address), hasPhone: /\d{6,}/.test(phoneRaw), hasVoiceReservationInfo: Boolean(voiceReservationRaw), externalMapQuery: address ? `${address} ${institutionName}` : institutionName, sourceValues, sourceRowNumber: String(index + 2), source: '臺北市流感疫苗合約醫療院所名冊(3歲以上(含3歲)幼童)', sourceAgency: '臺北市政府衛生局' }; });
const metadata = { module: 'influenza_vaccine_providers_children_3plus', source: '臺北市流感疫苗合約醫療院所名冊(3歲以上(含3歲)幼童)', sourceUrl: 'https://data.taipei/dataset/detail?id=f2a66aec-9b15-4580-9d04-9e991d45e908', csvResourceUrl: 'https://data.taipei/api/frontstage/tpeod/dataset/resource.download?rid=caf1807b-fabf-4db9-8521-6cdd5fa97517', sourceAgency: '臺北市政府衛生局', sourceFields: headers, csvUpdateDate: '2026-03-17', metadataUpdateDate: '2026-07-13', ingestedAt: new Date().toISOString(), recordCount: records.length, ageScope: 'children age 3 years and above', notes: ['All six source fields are retained in sourceValues.', 'Official district codes are mapped to display names without replacing the raw district value.', 'Voice reservation is normalized only from the source value; blank values remain unknown.', 'No coordinates or exact map markers are created.'] };
await mkdir(output, { recursive: true }); await writeFile(join(output, 'records.json'), `${JSON.stringify(records, null, 2)}\n`); await writeFile(join(output, 'metadata.json'), `${JSON.stringify(metadata, null, 2)}\n`); console.log(`Converted ${records.length} child influenza vaccine provider records.`);
