import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parseCsv } from './convertCivicGroups';

const root = process.cwd(); const input = join(root, 'data/raw/disability-institution-capacity-and-vacancies/source.csv'); const out = join(root, 'public/data/disability-institution-capacity-and-vacancies');
const clean = (value?: string) => (value ?? '').replace(/[\r\n]+/g, ' ').replace(/\s+/g, ' ').trim();
const districts = ['松山區', '信義區', '大安區', '中山區', '中正區', '大同區', '萬華區', '文山區', '南港區', '內湖區', '士林區', '北投區'];
const aliases: Record<string, string[]> = { sequence: ['序號'], district: ['行政區'], attribute: ['屬性'], name: ['機構名稱'], type: ['機構類型'], adult: ['成人日間照顧床位數量'], full: ['全日型住宿床位數量'], early: ['早療日間照顧'], night: ['夜間型住宿床位數量'], emergency: ['緊急短期安置床位數量'], address: ['地址'], website: ['網址'] };
const value = (row: Record<string, string>, keys: string[]) => keys.map((key) => row[key]).find((item) => item != null) ?? '';
const parseQuantity = (raw: string) => { const normalized = raw.replace(/[\s,，人床位名額]/g, ''); return /^\d+$/.test(normalized) ? Number(normalized) : null; };
const validUrl = (raw: string) => { try { const url = new URL(raw); return ['http:', 'https:'].includes(url.protocol) ? url.toString() : null; } catch { return null; } };
const buffer = await readFile(input); const candidates = ['utf-8', 'big5'].flatMap((encoding) => { try { const text = new TextDecoder(encoding).decode(buffer).replace(/^\uFEFF/, ''); return text.includes(',') ? [{ text, bad: (text.match(/�/g) ?? []).length }] : []; } catch { return []; } }); const source = candidates.sort((a, b) => a.bad - b.bad)[0]?.text; if (!source) throw new Error('Unsupported CSV encoding.');
const [header, ...rows] = parseCsv(source); const headers = header.map(clean); const malformed: string[] = [];
const records = rows.map((cells) => { const sourceValues = Object.fromEntries(headers.map((key, index) => [key, clean(cells[index])])) as Record<string, string>; const raw = { sequence: value(sourceValues, aliases.sequence), district: value(sourceValues, aliases.district), attribute: value(sourceValues, aliases.attribute), name: value(sourceValues, aliases.name), type: value(sourceValues, aliases.type), adult: value(sourceValues, aliases.adult), full: value(sourceValues, aliases.full), early: value(sourceValues, aliases.early), night: value(sourceValues, aliases.night), emergency: value(sourceValues, aliases.emergency), address: value(sourceValues, aliases.address), website: value(sourceValues, aliases.website) }; const capacity = (serviceType: string, sourceRaw: string) => { const quantity = parseQuantity(sourceRaw); if (sourceRaw && quantity === null) malformed.push(sourceRaw); return { serviceType, sourceRaw, quantity, valueMeaning: 'capacity' as const }; }; const serviceCapacities = [capacity('adult_day_care', raw.adult), capacity('full_time_residential', raw.full), capacity('early_intervention_day_care', raw.early), capacity('night_residential', raw.night), capacity('emergency_short_term_placement', raw.emergency)]; const identity = `${raw.name}|${raw.district}|${raw.address}`.toLocaleLowerCase(); return { id: createHash('sha256').update(identity || JSON.stringify(sourceValues)).digest('hex').slice(0, 16), sourceSequenceNumber: raw.sequence, districtName: raw.district, organizationAttributeRaw: raw.attribute, organizationAttribute: raw.attribute, institutionName: raw.name, institutionTypeRaw: raw.type, institutionType: raw.type, adultDayCareRaw: raw.adult, adultDayCareBeds: serviceCapacities[0].quantity, fullTimeResidentialRaw: raw.full, fullTimeResidentialBeds: serviceCapacities[1].quantity, earlyInterventionDayCareRaw: raw.early, earlyInterventionDayCareBeds: serviceCapacities[2].quantity, nightResidentialRaw: raw.night, nightResidentialBeds: serviceCapacities[3].quantity, emergencyShortTermPlacementRaw: raw.emergency, emergencyShortTermPlacementBeds: serviceCapacities[4].quantity, serviceCapacities, supportedServiceTypes: serviceCapacities.filter((item) => item.quantity !== null && item.quantity > 0).map((item) => item.serviceType), vacancyStatusRaw: '', sourceRecordDate: null, address: raw.address, websiteRaw: raw.website, website: validUrl(raw.website), hasAddress: Boolean(raw.address), hasWebsite: Boolean(validUrl(raw.website)), hasAnyServiceCapacity: serviceCapacities.some((item) => item.quantity !== null), externalMapQuery: raw.address ? `${raw.address} ${raw.name}`.trim() : '', sourceValues }; });
const unique = records.filter((record, index, all) => all.findIndex((candidate) => JSON.stringify(candidate.sourceValues) === JSON.stringify(record.sourceValues)) === index); const count = (items: string[]) => Object.entries(items.filter(Boolean).reduce<Record<string, number>>((all, item) => ({ ...all, [item]: (all[item] ?? 0) + 1 }), {})).map(([label, value]) => ({ label, value })).sort((a, b) => b.value - a.value);
const updatedAt = new Date().toISOString(); const summary = { updatedAt, totalRecords: unique.length, uniqueInstitutions: new Set(unique.map((r) => r.institutionName).filter(Boolean)).size, districtsCovered: count(unique.map((r) => r.districtName)).length, institutionTypes: count(unique.map((r) => r.institutionType)).length, recordsWithWebsite: unique.filter((r) => r.hasWebsite).length, recordsWithSourceQuantity: unique.filter((r) => r.hasAnyServiceCapacity).length, byDistrict: count(unique.map((r) => r.districtName)), byInstitutionType: count(unique.map((r) => r.institutionType)), byAttribute: count(unique.map((r) => r.organizationAttribute)), byServiceModel: count(unique.flatMap((r) => r.supportedServiceTypes)), quantitiesByServiceModel: ['adult_day_care', 'full_time_residential', 'early_intervention_day_care', 'night_residential', 'emergency_short_term_placement'].map((serviceType) => ({ label: serviceType, value: unique.reduce((sum, r) => sum + (r.serviceCapacities.find((item) => item.serviceType === serviceType)?.quantity ?? 0), 0) })), fieldMeaning: 'capacity' };
const report = { disabilityInstitutionCapacityAndVacancies: { updatedAt, headers, inputRows: rows.length, outputRecords: unique.length, exactDuplicatesRemoved: records.length - unique.length, missingInstitutionName: unique.filter((r) => !r.institutionName).length, missingDistrict: unique.filter((r) => !r.districtName).length, unknownDistrict: unique.filter((r) => r.districtName && !districts.includes(r.districtName)).length, missingAddress: unique.filter((r) => !r.address).length, unknownInstitutionType: unique.filter((r) => !r.institutionType).length, unknownOrganizationalAttribute: unique.filter((r) => !r.organizationAttribute).length, malformedQuantities: malformed.length, invalidWebsiteUrl: unique.filter((r) => r.websiteRaw && !r.website).length, fieldSemantics: 'Verified from actual headers: each service-model field is labelled 床位數, so values are displayed as source-recorded capacity, not real-time vacancies.', notes: ['No occupancy, utilisation, or live-vacancy calculation is made.', 'Addresses are not geocoded and no exact map markers are created.'] } };
await mkdir(out, { recursive: true }); await Promise.all([writeFile(join(out, 'records.json'), JSON.stringify(unique, null, 2)), writeFile(join(out, 'summary.json'), JSON.stringify(summary, null, 2)), writeFile(join(out, 'conversion-report.json'), JSON.stringify(report, null, 2)), writeFile(join(root, 'public/data/conversion-report.json'), JSON.stringify(report, null, 2))]); console.log(`Converted ${unique.length} disability institution records.`);
