import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parseCsv } from './convertCivicGroups';
const sourcePath = join(process.cwd(), 'data/raw/community-integrated-care-level-c-units/source.csv'), outputDirectory = join(process.cwd(), 'public/data/community-integrated-care-level-c-units'); const clean = (value?: string) => value?.replace(/[\r\n\t ]+/g, ' ').trim() ?? ''; const districtCodes: Record<string, string> = { '63000010': '松山區', '63000020': '信義區', '63000030': '大安區', '63000040': '中山區', '63000050': '中正區', '63000060': '大同區', '63000070': '萬華區', '63000080': '文山區', '63000090': '南港區', '63000100': '內湖區', '63000110': '士林區', '63000120': '北投區' };
function decode(bytes: Uint8Array) { try { return { text: new TextDecoder('utf-8', { fatal: true }).decode(bytes).replace(/^\uFEFF/, ''), encoding: 'UTF-8-SIG / UTF-8' }; } catch { return { text: new TextDecoder('big5', { fatal: true }).decode(bytes).replace(/^\uFEFF/, ''), encoding: 'CP950 / Big5-compatible' }; } }
const { text, encoding } = decode(await readFile(sourcePath)); const [rawHeaders, ...rows] = parseCsv(text); const headers = rawHeaders.map(clean), required = ['序號', '據點名稱', '行政區', '行政區代碼', '據點地址', '電話']; const missing = required.filter((field) => !headers.includes(field)); if (missing.length) throw new Error(`Missing official source columns: ${missing.join(', ')}`);
const duplicateRows: string[] = [], missingSiteNames: string[] = [], missingAddresses: string[] = [], missingPhones: string[] = [], malformedDistrictCodes: string[] = [], unresolvedDistricts: string[] = [], districtConflicts: string[] = []; const seen = new Set<string>();
const records = rows.flatMap((row, index) => { const sourceValues = Object.fromEntries(headers.map((header, column) => [header, clean(row[column])])) as Record<string, string>; const sourceSequenceNumber = sourceValues['序號'], siteName = sourceValues['據點名稱'], districtName = sourceValues['行政區'], districtCode = sourceValues['行政區代碼'], address = sourceValues['據點地址'], phone = sourceValues['電話']; const key = headers.map((header) => sourceValues[header]).join('\u001F'), label = sourceSequenceNumber || `row ${index + 2}`; if (seen.has(key)) { duplicateRows.push(label); return []; } seen.add(key); if (!siteName) missingSiteNames.push(label); if (!address) missingAddresses.push(label); if (!phone) missingPhones.push(label); const expectedDistrict = districtCodes[districtCode]; if (!expectedDistrict) malformedDistrictCodes.push(label); const resolvedDistrict = districtName || expectedDistrict || Object.values(districtCodes).find((value) => address.includes(value)) || ''; if (!resolvedDistrict) unresolvedDistricts.push(label); if ((districtName && expectedDistrict && districtName !== expectedDistrict) || (districtName && address && !address.includes(districtName))) districtConflicts.push(label); const id = sourceSequenceNumber || createHash('sha256').update(`${siteName}|${districtCode}|${address}|${key}`).digest('hex').slice(0, 16); return [{ id, sourceSequenceNumber, siteName, districtName: resolvedDistrict, districtCode, address, phone, hasAddress: Boolean(address), hasPhone: Boolean(phone), hasValidDistrictCode: Boolean(expectedDistrict && expectedDistrict === resolvedDistrict), externalMapQuery: [siteName, address].filter(Boolean).join(' '), sourceValues }]; });
const countBy = (get: (record: typeof records[number]) => string) => Object.entries(records.reduce((counts, record) => { const label = get(record); if (label) counts[label] = (counts[label] ?? 0) + 1; return counts; }, {} as Record<string, number>)).map(([label, count]) => ({ label, count })).sort((a, b) => b.count - a.count || a.label.localeCompare(b.label)); const byDistrict = countBy((record) => record.districtName);
const sameNameAddresses = new Map<string, Set<string>>(), sameAddressNames = new Map<string, Set<string>>(); for (const record of records) { sameNameAddresses.set(record.siteName, new Set([...(sameNameAddresses.get(record.siteName) ?? []), record.address])); sameAddressNames.set(record.address, new Set([...(sameAddressNames.get(record.address) ?? []), record.siteName])); }
const summary = { totalRecords: records.length, uniqueSiteNames: new Set(records.map((record) => record.siteName).filter(Boolean)).size, districtsCovered: byDistrict.length, recordsWithAddresses: records.filter((record) => record.hasAddress).length, recordsWithPhones: records.filter((record) => record.hasPhone).length, validDistrictCodes: records.filter((record) => record.hasValidDistrictCode).length, byDistrict, sourceUpdateDate: '2025-06-11 18:47:18' };
await mkdir(outputDirectory, { recursive: true }); await Promise.all([writeFile(join(outputDirectory, 'records.json'), JSON.stringify(records)), writeFile(join(outputDirectory, 'summary.json'), JSON.stringify(summary)), writeFile(join(outputDirectory, 'conversion-report.json'), JSON.stringify({ source: '臺北市銀髮族服務_社區整體照顧服務體系C級單位一覽表', sourcePage: 'https://data.taipei/dataset/detail?id=48a04f42-094e-46a0-a279-b4d8b703a7b3', sourceUpdateDate: summary.sourceUpdateDate, encoding, sourceFields: headers, inputRows: rows.length, outputRecords: records.length, missingSiteNames, missingAddresses, missingPhones, malformedDistrictCodes, unresolvedDistricts, districtConflicts, duplicateRows, sameSiteNameMultipleAddresses: [...sameNameAddresses].filter(([, values]) => values.size > 1).map(([siteName, values]) => ({ siteName, addresses: [...values] })), sameAddressMultipleSiteNames: [...sameAddressNames].filter(([, values]) => values.size > 1).map(([address, values]) => ({ address, siteNames: [...values] })), notes: ['UTF-8-SIG, Big5, and CP950 supported.', 'Sequence numbers, district codes, and phone numbers are preserved as strings.', 'No official coordinates are supplied; no geocoding or exact markers are created.', 'The directory does not represent real-time service, capacity, operation, availability, or eligibility.'] }, null, 2))]); console.log(`Converted ${records.length} community integrated care Level C unit records (${encoding}).`);
