import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parseCsv } from './convertCivicGroups';
import { cleanHakkaOrganizationValue, normalizeHakkaOrganizationText, type HakkaOrganizationRecord } from '../src/lib/hakkaOrganizations';

const input = join(process.cwd(), 'data/raw/hakka-organizations/source.csv'); const output = join(process.cwd(), 'public/data/hakka-organizations'); const rootReportPath = join(process.cwd(), 'public/data/conversion-report.json');
const bytes = await readFile(input); let text: string;
try { text = new TextDecoder('utf-8', { fatal: true }).decode(bytes); } catch { text = new TextDecoder('big5').decode(bytes); }
const [rawHeaders, ...rows] = parseCsv(text); const headers = rawHeaders.map((value) => cleanHakkaOrganizationValue(value.replace(/^\uFEFF/, ''))); const seen = new Set<string>();
const issues = { duplicateSequenceNumber: [] as string[], duplicateOrganizationName: [] as string[], exactDuplicateRows: [] as string[], sameOrganizationDifferentLeaders: [] as string[], missingOrganizationName: [] as string[], missingLeaderValue: [] as string[] };
const records = rows.flatMap((row, index): HakkaOrganizationRecord[] => { const sourceValues = Object.fromEntries(headers.map((header, column) => [header, cleanHakkaOrganizationValue(row[column])])) as Record<string, string>; const signature = JSON.stringify(sourceValues); const sourceRow = String(index + 2); if (seen.has(signature)) { issues.exactDuplicateRows.push(sourceRow); return []; } seen.add(signature); const sourceSequenceNumber = sourceValues['編號'] ?? ''; const organizationName = sourceValues['單位名稱'] ?? ''; const leaderRaw = sourceValues['理事長/會長'] ?? ''; if (!organizationName) issues.missingOrganizationName.push(sourceRow); if (!leaderRaw) issues.missingLeaderValue.push(sourceRow); const baseId = sourceSequenceNumber || `${normalizeHakkaOrganizationText(organizationName)}|${signature}`; return [{ id: createHash('sha256').update(baseId).digest('hex').slice(0, 16), sourceSequenceNumber, organizationName, leaderRaw, leaderName: leaderRaw, hasOrganizationName: Boolean(organizationName), hasLeaderName: Boolean(leaderRaw), sourceValues }]; });
const groupedRows = (key: (record: HakkaOrganizationRecord) => string) => records.reduce((groups, record) => { const groupKey = key(record); if (groupKey) groups.set(groupKey, [...(groups.get(groupKey) ?? []), record]); return groups; }, new Map<string, HakkaOrganizationRecord[]>());
const sourceRowsFor = (group: HakkaOrganizationRecord[]) => group.map((record) => String(records.indexOf(record) + 2));
for (const group of groupedRows((record) => record.sourceSequenceNumber).values()) if (group.length > 1) issues.duplicateSequenceNumber.push(...sourceRowsFor(group));
for (const group of groupedRows((record) => normalizeHakkaOrganizationText(record.organizationName)).values()) { if (group.length > 1) issues.duplicateOrganizationName.push(...sourceRowsFor(group)); if (new Set(group.map((record) => normalizeHakkaOrganizationText(record.leaderRaw))).size > 1) issues.sameOrganizationDifferentLeaders.push(...sourceRowsFor(group)); }
const duplicateNameRecords = new Set(issues.duplicateOrganizationName); const issueCount = Object.values(issues).reduce((total, values) => total + values.length, 0);
const summary = { totalRecords: records.length, uniqueOrganizationNames: new Set(records.map((record) => normalizeHakkaOrganizationText(record.organizationName)).filter(Boolean)).size, recordsWithLeader: records.filter((record) => record.hasLeaderName).length, recordsMissingLeader: records.filter((record) => !record.hasLeaderName).length, suspectedDuplicateOrganizationNames: duplicateNameRecords.size, leadershipCompletenessPercent: records.length ? Math.round(records.filter((record) => record.hasLeaderName).length / records.length * 1000) / 10 : 0 };
const report = { hakkaOrganizations: { sourcePage: 'https://data.taipei/dataset/detail?id=0be09825-0507-4624-8c4b-3872b5117fae', sourceAgency: '臺北市政府客家事務委員會', sourceFileUpdatedAt: '2025-06-12T16:16:44+08:00', metadataUpdatedAt: '2025-12-18T13:45:28+08:00', updateFrequency: 'irregular', headers, inputRows: rows.length, outputRecords: records.length, issueCount, issues, notes: ['All actual source columns are preserved in sourceValues.', 'This is a 109 ROC year (2020) registry. A later file-update date does not establish current organization status or leadership.', 'No address, contact, district, website, or coordinates are supplied or inferred.'] } };
const metadata = { key: 'hakka_organizations', datasetName: '109年臺北市客家社團名冊', datasetUrl: report.hakkaOrganizations.sourcePage, label: { zh: '臺北市客家社團', en: 'Taipei Hakka Organizations' }, ...report.hakkaOrganizations, recordCount: records.length };
await mkdir(output, { recursive: true }); const existing = await readFile(rootReportPath, 'utf8').then(JSON.parse).catch(() => ({})); await Promise.all([writeFile(join(output, 'records.json'), JSON.stringify(records, null, 2)), writeFile(join(output, 'summary.json'), JSON.stringify(summary, null, 2)), writeFile(join(output, 'metadata.json'), JSON.stringify(metadata, null, 2)), writeFile(join(output, 'conversion-report.json'), JSON.stringify(report, null, 2)), writeFile(rootReportPath, JSON.stringify({ ...existing, ...report }, null, 2))]);
console.log(`Converted ${records.length} Hakka organization records.`);
