import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parseCsv } from './convertCivicGroups';
const sourcePath = join(process.cwd(), 'data/raw/public-influenza-antiviral-providers/source.csv'); const outputDirectory = join(process.cwd(), 'public/data/public-influenza-antiviral-providers');
const clean = (value?: string) => value?.replace(/[\r\n\t ]+/g, ' ').trim() ?? ''; const districts = ['松山區', '信義區', '大安區', '中山區', '中正區', '大同區', '萬華區', '文山區', '南港區', '內湖區', '士林區', '北投區'];
function decode(bytes: Uint8Array) { try { return { text: new TextDecoder('utf-8', { fatal: true }).decode(bytes).replace(/^\uFEFF/, ''), encoding: 'UTF-8-SIG / UTF-8' }; } catch { return { text: new TextDecoder('big5', { fatal: true }).decode(bytes).replace(/^\uFEFF/, ''), encoding: 'CP950 / Big5-compatible' }; } }
const { text, encoding } = decode(await readFile(sourcePath)); const [rawHeaders, ...rows] = parseCsv(text); const headers = rawHeaders.map(clean); const required = ['十碼章', '醫院名稱', '縣市別', '行政區', '地址', '連絡電話']; const missing = required.filter((field) => !headers.includes(field)); if (missing.length) throw new Error(`Missing official source columns: ${missing.join(', ')}`);
const duplicateRows: string[] = [], missingInstitutionNames: string[] = [], missingInstitutionCodes: string[] = [], unexpectedInstitutionCodes: string[] = [], missingAddresses: string[] = [], missingPhones: string[] = [], unresolvedDistricts: string[] = []; const seen = new Set<string>();
const records = rows.flatMap((row, index) => { const sourceValues = Object.fromEntries(headers.map((header, column) => [header, clean(row[column])])) as Record<string, string>; const institutionCode = sourceValues['十碼章'], institutionName = sourceValues['醫院名稱'], cityName = sourceValues['縣市別'], officialDistrict = sourceValues['行政區'], address = sourceValues['地址'], phone = sourceValues['連絡電話']; const key = headers.map((header) => sourceValues[header]).join('\u001F'); const label = `row ${index + 2}`; if (seen.has(key)) { duplicateRows.push(label); return []; } seen.add(key); if (!institutionName) missingInstitutionNames.push(label); if (!institutionCode) missingInstitutionCodes.push(label); if (institutionCode && !/^[0-9A-Za-z]{8,12}$/.test(institutionCode)) unexpectedInstitutionCodes.push(label); if (!address) missingAddresses.push(label); if (!phone) missingPhones.push(label); const districtName = officialDistrict || districts.find((district) => address.includes(district)) || ''; if (!districtName) unresolvedDistricts.push(label); const id = institutionCode || createHash('sha256').update(`${institutionName}|${districtName}|${address}|${key}`).digest('hex').slice(0, 16); return [{ id, institutionCode, institutionName, cityName, districtName, address, phone, hasAddress: Boolean(address), hasPhone: Boolean(phone), externalMapQuery: [institutionName, address].filter(Boolean).join(' '), sourceValues }]; });
const countBy = (get: (record: typeof records[number]) => string) => Object.entries(records.reduce((counts, record) => { const label = get(record); if (label) counts[label] = (counts[label] ?? 0) + 1; return counts; }, {} as Record<string, number>)).map(([label, count]) => ({ label, count })).sort((a, b) => b.count - a.count || a.label.localeCompare(b.label));
const codeNames = new Map<string, Set<string>>(); const nameAddressCodes = new Map<string, Set<string>>(); for (const record of records) { if (record.institutionCode) codeNames.set(record.institutionCode, new Set([...(codeNames.get(record.institutionCode) ?? []), record.institutionName])); nameAddressCodes.set(`${record.institutionName}|${record.address}`, new Set([...(nameAddressCodes.get(`${record.institutionName}|${record.address}`) ?? []), record.institutionCode])); }
const summary = { totalRecords: records.length, uniqueInstitutions: new Set(records.map((record) => record.institutionName).filter(Boolean)).size, uniqueInstitutionCodes: new Set(records.map((record) => record.institutionCode).filter(Boolean)).size, districtsCovered: new Set(records.map((record) => record.districtName).filter(Boolean)).size, recordsWithAddresses: records.filter((record) => record.hasAddress).length, recordsWithPhones: records.filter((record) => record.hasPhone).length, byDistrict: countBy((record) => record.districtName), byCity: countBy((record) => record.cityName), sourceUpdateDate: '2024-12-05 14:40:55' };
await mkdir(outputDirectory, { recursive: true }); await Promise.all([writeFile(join(outputDirectory, 'records.json'), JSON.stringify(records)), writeFile(join(outputDirectory, 'summary.json'), JSON.stringify(summary)), writeFile(join(outputDirectory, 'conversion-report.json'), JSON.stringify({ source: '臺北市公費流感抗病毒藥劑合約院所', sourcePage: 'https://data.taipei/dataset/detail?id=c9ad5931-42e5-4698-96b8-1353cf4f5416', sourceUpdateDate: summary.sourceUpdateDate, encoding, sourceFields: headers, inputRows: rows.length, outputRecords: records.length, missingInstitutionNames, missingInstitutionCodes, unexpectedInstitutionCodes, missingAddresses, missingPhones, unresolvedDistricts, duplicateRows, conflictingInstitutionCodeMappings: [...codeNames].filter(([, values]) => values.size > 1).map(([code, values]) => ({ code, values: [...values] })), multipleCodesForSameNameAndAddress: [...nameAddressCodes].filter(([, values]) => values.size > 1).map(([key, values]) => ({ key, values: [...values] })), notes: ['UTF-8-SIG, Big5, and CP950 supported.', 'Institution codes and phone numbers are preserved as strings.', 'No official coordinates are supplied; no geocoding or exact markers are created.', 'This directory does not represent real-time medicine inventory, eligibility, appointments, or treatment availability.'] }, null, 2))]); console.log(`Converted ${records.length} public influenza antiviral provider records (${encoding}).`);
