import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parseCsv } from './convertCivicGroups';
const inputPath = join(process.cwd(), 'data/raw/street-performer-venues/records.csv'), outputDirectory = join(process.cwd(), 'public/data/street-performer-venues'), reportPath = join(process.cwd(), 'public/data/conversion-report.json');
const clean = (value?: string) => value?.replace(/\s+/g, ' ').trim() || undefined, normalize = (value?: string) => clean(value)?.replace(/[臺台]/g, '台').toLocaleLowerCase(), normalizePhone = (value?: string) => clean(value)?.replace(/[\s（）()－–—-]/g, '');
function decode(bytes: Uint8Array) { try { return { text: new TextDecoder('utf-8', { fatal: true }).decode(bytes).replace(/^\uFEFF/, ''), encoding: 'UTF-8-SIG / UTF-8' }; } catch { return { text: new TextDecoder('big5', { fatal: true }).decode(bytes).replace(/^\uFEFF/, ''), encoding: 'CP950 / Big5-compatible' }; } }
const { text, encoding } = decode(await readFile(inputPath)); const [rawHeaders, ...rows] = parseCsv(text), headers = rawHeaders.map((header) => clean(header) ?? '');
const required = ['項次', '展演地', '主管機關', '市話', '分機', '開放時段', '開放表演類型', '申請方式']; const missingColumns = required.filter((header) => !headers.includes(header)); if (missingColumns.length) throw new Error(`Missing source columns: ${missingColumns.join(', ')}`);
const duplicates: string[] = [], missingNames: string[] = [], unknownPerformanceTypes: string[] = [], malformedPhones: string[] = [], seen = new Set<string>();
const records = rows.flatMap((row, index) => { const values = Object.fromEntries(headers.map((header, columnIndex) => [header, clean(row[columnIndex])])) as Record<string, string | undefined>; const venueName = values['展演地'], managingAuthority = values['主管機關'], applicationMethod = values['申請方式']; if (!venueName) { missingNames.push(`row ${index + 2}`); return []; } const key = `${normalize(venueName)}|${normalize(managingAuthority)}|${normalize(applicationMethod)}`; if (seen.has(key)) { duplicates.push(key); return []; } seen.add(key); const phone = values['市話'], extension = values['分機'], phoneNormalized = normalizePhone(phone); if (phone && (!phoneNormalized || !/\d{6,}/.test(phoneNormalized))) malformedPhones.push(`row ${index + 2}: ${phone}`); const allowedPerformanceTypesRaw = values['開放表演類型']; const allowedPerformanceTypes = allowedPerformanceTypesRaw?.split(/[、；;\n]+/).map(clean).filter(Boolean) ?? []; if (allowedPerformanceTypesRaw && !allowedPerformanceTypes.length) unknownPerformanceTypes.push(`row ${index + 2}`); const districtNameFromVenueText = venueName.replace(/臺/g, '台').match(/(松山|信義|大安|中山|中正|大同|萬華|文山|南港|內湖|士林|北投)區/)?.[0]; return [{ id: values['項次'] || createHash('sha1').update(key).digest('hex').slice(0, 12), module: 'street_performer_venues', sourceSequenceNumber: values['項次'], venueName, venueNameNormalized: normalize(venueName), managingAuthority, managingAuthorityNormalized: normalize(managingAuthority), phone, extension, phoneNormalized, fullPhone: clean([phone, extension && `分機${extension}`].filter(Boolean).join(' ')), hasPhone: Boolean(phone), openingHoursRaw: values['開放時段'], openingHoursNormalized: normalize(values['開放時段']), allowedPerformanceTypesRaw, allowedPerformanceTypes, applicationMethod, applicationMethodNormalized: normalize(applicationMethod), districtNameFromVenueText, externalMapQuery: venueName, source: '臺北市街頭藝人展演場地資訊', sourceAgency: '臺北市政府文化局' }]; });
const count = (values: string[]) => Object.entries(values.filter(Boolean).reduce((map: Record<string, number>, value) => { map[value] = (map[value] ?? 0) + 1; return map; }, {})).map(([label, count]) => ({ label, count })).sort((a, b) => b.count - a.count || a.label.localeCompare(b.label));
const summary = { totalRecords: records.length, uniqueManagingAuthorityCount: new Set(records.map((record: any) => record.managingAuthorityNormalized).filter(Boolean)).size, performanceTypeCategoryCount: new Set(records.flatMap((record: any) => record.allowedPerformanceTypes)).size, recordsWithPhone: records.filter((record: any) => record.hasPhone).length, recordsWithoutPhone: records.filter((record: any) => !record.hasPhone).length, recordsWithOpeningHours: records.filter((record: any) => record.openingHoursRaw).length, recordsWithoutOpeningHours: records.filter((record: any) => !record.openingHoursRaw).length, byManagingAuthority: count(records.map((record: any) => record.managingAuthority)), byPerformanceType: count(records.flatMap((record: any) => record.allowedPerformanceTypes)), byDistrict: count(records.map((record: any) => record.districtNameFromVenueText)) };
await mkdir(outputDirectory, { recursive: true }); await writeFile(join(outputDirectory, 'records.json'), JSON.stringify(records)); await writeFile(join(outputDirectory, 'summary.json'), JSON.stringify(summary)); const priorReport = await readFile(reportPath, 'utf8').then(JSON.parse).catch(() => ({})); await writeFile(reportPath, JSON.stringify({ ...priorReport, streetPerformerVenues: { convertedAt: new Date().toISOString(), encoding, headers, outputRecords: records.length, duplicates, missingNames, unknownPerformanceTypes, malformedPhones, notes: ['Venue text was inspected before conversion; it is not automatically geocoded and does not create map markers.', 'Opening hours are source text, not real-time availability.'] } }, null, 2)); console.log(`Converted ${records.length} street performer venues.`);
