import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parseCsv } from './convertCivicGroups';
import { parseApprovalDate, parseNaturalGasContractorCoordinates } from '../src/lib/licensedNaturalGasPipelineContractors';

const base = process.cwd(), input = join(base, 'data/raw/licensed-natural-gas-pipeline-contractors/source.csv'), output = join(base, 'public/data/licensed-natural-gas-pipeline-contractors'), reportPath = join(base, 'public/data/conversion-report.json'), metadataPath = join(base, 'data/raw/licensed-natural-gas-pipeline-contractors/fetch-metadata.json');
const districts = ['中正區', '大同區', '中山區', '松山區', '大安區', '萬華區', '信義區', '士林區', '北投區', '內湖區', '南港區', '文山區']; const clean = (value: string | undefined) => value?.replace(/[\r\n]+/g, ' ').replace(/\s+/g, ' ').trim() ?? '', normalize = (value: string) => clean(value).replace(/[\s　]/g, '').toLowerCase();
const bytes = await readFile(input); let text: string; try { text = new TextDecoder('utf-8', { fatal: true }).decode(bytes); } catch { try { text = new TextDecoder('big5', { fatal: true }).decode(bytes); } catch { text = new TextDecoder('cp950').decode(bytes); } }
const [headerRow, ...rows] = parseCsv(text.replace(/^\uFEFF/, '')), headers = headerRow.map(clean), duplicateRows: number[] = [], missingContractorName: number[] = [], missingLicenceNumber: number[] = [], malformedBusinessRegistrationNumber: number[] = [], missingAddress: number[] = [], unresolvedDistrict: number[] = [], malformedApprovalDate: number[] = [], invalidCoordinates: number[] = [];
const exactRows = new Set<string>(), stableIds = new Set<string>();
const records = rows.map((row, index) => { const sourceValues = Object.fromEntries(headers.map((header, column) => [header, clean(row[column])])) as Record<string, string>, contractorName = sourceValues.NAME, licenceNumber = sourceValues.CERT, businessRegistrationNumber = sourceValues.BAN_NO, businessAddress = sourceValues.SUMADDR, responsiblePerson = sourceValues.RNAME, approvalDateRaw = sourceValues.ESTAB_DATE, approvalReference = sourceValues.ESTAB_NO, sourceXRaw = sourceValues.ADDR_X, sourceYRaw = sourceValues.ADDR_Y, rowNumber = index + 2, fingerprint = createHash('sha256').update(JSON.stringify(sourceValues)).digest('hex'); if (exactRows.has(fingerprint)) { duplicateRows.push(rowNumber); return null; } exactRows.add(fingerprint);
  if (!contractorName) missingContractorName.push(rowNumber); if (!licenceNumber) missingLicenceNumber.push(rowNumber); if (businessRegistrationNumber && !/^\d{8}$/.test(businessRegistrationNumber)) malformedBusinessRegistrationNumber.push(rowNumber); if (!businessAddress) missingAddress.push(rowNumber); const districtName = districts.find((district) => businessAddress.includes(district)) ?? ''; if (!districtName) unresolvedDistrict.push(rowNumber); const date = parseApprovalDate(approvalDateRaw); if (approvalDateRaw && !date.approvalDate) malformedApprovalDate.push(rowNumber); const coordinates = parseNaturalGasContractorCoordinates(sourceXRaw, sourceYRaw); if (!coordinates.hasValidCoordinates) invalidCoordinates.push(rowNumber);
  const preferred = licenceNumber || businessRegistrationNumber || `natural-gas-${createHash('sha1').update(`${normalize(contractorName)}|${normalize(businessAddress)}` || fingerprint).digest('hex').slice(0, 16)}`, id = stableIds.has(preferred) ? `${preferred}-${fingerprint.slice(0, 8)}` : preferred; stableIds.add(id);
  return { id, contractorName, licenceNumber, businessRegistrationNumber, businessAddress, districtName, responsiblePerson, approvalDateRaw, ...date, approvalReference, sourceXRaw, sourceYRaw, sourceX: Number.isFinite(Number(sourceXRaw)) ? Number(sourceXRaw) : null, sourceY: Number.isFinite(Number(sourceYRaw)) ? Number(sourceYRaw) : null, longitude: coordinates.hasValidCoordinates ? coordinates.longitude : null, latitude: coordinates.hasValidCoordinates ? coordinates.latitude : null, hasValidCoordinates: coordinates.hasValidCoordinates, coordinateSystem: coordinates.coordinateSystem, externalMapQuery: businessAddress ? clean(`${businessAddress} ${contractorName}`) : '', sourceValues };
}).filter(Boolean) as Array<Record<string, unknown>>;
const group = (field: string) => Object.entries(records.reduce<Record<string, number>>((all, record) => { const value = String(record[field] ?? ''); if (value) all[value] = (all[value] ?? 0) + 1; return all; }, {})).map(([label, value]) => ({ label, value })).sort((a, b) => b.value - a.value || a.label.localeCompare(b.label, 'zh-Hant'));
const conflicts = (left: string, right: string) => Object.entries(records.reduce<Record<string, Set<string>>>((all, record) => { const key = normalize(String(record[left] ?? '')), value = normalize(String(record[right] ?? '')); if (key && value) (all[key] ??= new Set()).add(value); return all; }, {})).filter(([, values]) => values.size > 1).map(([key]) => key);
const metadata = await readFile(metadataPath, 'utf8').then(JSON.parse).catch(() => ({})), years = group('approvalYear'), cumulativeApprovals = years.slice().sort((a, b) => Number(a.label) - Number(b.label)).reduce<Array<{ label: string; value: number }>>((all, item) => { all.push({ label: item.label, value: (all.at(-1)?.value ?? 0) + item.value }); return all; }, []), numericX = records.map((record) => Number(record.sourceX)).filter(Number.isFinite), numericY = records.map((record) => Number(record.sourceY)).filter(Number.isFinite);
const summary = { totalRecords: records.length, uniqueContractors: new Set(records.map((record) => normalize(String(record.contractorName ?? ''))).filter(Boolean)).size, uniqueLicenceNumbers: new Set(records.map((record) => String(record.licenceNumber ?? '')).filter(Boolean)).size, uniqueBusinessRegistrationNumbers: new Set(records.map((record) => String(record.businessRegistrationNumber ?? '')).filter(Boolean)).size, districtsCovered: group('districtName').length, recordsWithParsedApprovalDates: records.filter((record) => record.approvalDate).length, validMapLocations: records.filter((record) => record.hasValidCoordinates).length, missingValidCoordinates: records.filter((record) => !record.hasValidCoordinates).length, earliestApprovalDate: records.map((record) => String(record.approvalDate ?? '')).filter(Boolean).sort()[0] ?? '', latestApprovalDate: records.map((record) => String(record.approvalDate ?? '')).filter(Boolean).sort().at(-1) ?? '', byDistrict: group('districtName'), approvalsByYear: years, cumulativeApprovals, coordinateStatus: [{ label: 'valid', value: records.filter((record) => record.hasValidCoordinates).length }, { label: 'invalid', value: records.filter((record) => !record.hasValidCoordinates).length }], licenceStatus: [{ label: 'with_licence', value: records.filter((record) => record.licenceNumber).length }, { label: 'without_licence', value: records.filter((record) => !record.licenceNumber).length }], coordinateSystem: group('coordinateSystem'), sourceCoordinateRange: { x: numericX.length ? [Math.min(...numericX), Math.max(...numericX)] : [], y: numericY.length ? [Math.min(...numericY), Math.max(...numericY)] : [] }, sourceFileUpdatedAt: metadata.sourceFileUpdatedAt ?? '', metadataUpdatedAt: metadata.metadataUpdatedAt ?? '', sourceUrl: metadata.sourceUrl ?? '' };
const priorReport = await readFile(reportPath, 'utf8').then(JSON.parse).catch(() => ({})); await mkdir(output, { recursive: true }); await Promise.all([writeFile(join(output, 'records.json'), JSON.stringify(records)), writeFile(join(output, 'summary.json'), JSON.stringify(summary, null, 2)), writeFile(reportPath, JSON.stringify({ ...priorReport, licensedNaturalGasPipelineContractors: { convertedAt: new Date().toISOString(), headers, inputRows: rows.length, outputRecords: records.length, duplicateRows, missingContractorName, missingLicenceNumber, malformedBusinessRegistrationNumber, missingAddress, unresolvedDistrict, malformedApprovalDate, invalidCoordinates, sameLicenceDifferentContractors: conflicts('licenceNumber', 'contractorName'), sameBusinessRegistrationDifferentNames: conflicts('businessRegistrationNumber', 'contractorName'), coordinateSystem: 'TWD97 / TM2 zone 121 detected from source numeric ranges and converted to WGS84 only after Taipei-bound validation.', sourceCoordinateRange: summary.sourceCoordinateRange, notes: ['Licence and business-registration values are preserved as strings.', 'Approval dates are historical source records, not current-licence confirmation.', 'No pipeline routes, inferred work sites, service areas, or invalid-coordinate markers are created.'] } }, null, 2))]); console.log(`Converted ${records.length} licensed natural gas pipeline contractor records.`);
