import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { parseCsv } from './convertCivicGroups';
import { buildDawannanIndustrialAreaCompanySummary, cleanDawannanText, convertProjectedTaipeiCoordinateToWgs84, createDawannanCompanyMapQuery, parseDawannanCompanyAddress, parseIndustrialAreaCompanyName, parseProjectedCoordinate, parseUnifiedBusinessNumber } from '../src/lib/dawannanIndustrialAreaCompanies';
import { normalizeColumnName } from '../src/lib/civicGroups';
import type { DawannanIndustrialAreaCompanyRecord } from '../src/types';

const rawDir = join(process.cwd(), 'data/raw/dawannan-industrial-area-company-directory'), outputDir = join(process.cwd(), 'public/data'), reportPath = join(outputDir, 'conversion-report.json');
const source = '臺北市大彎南段工業區廠商名錄', sourceAgency = '臺北市政府產業發展局';
const decode = (bytes: Uint8Array) => { try { return { text: new TextDecoder('utf-8', { fatal: true }).decode(bytes).replace(/^\uFEFF/, ''), encoding: 'UTF-8-SIG / UTF-8' }; } catch { return { text: new TextDecoder('big5', { fatal: true }).decode(bytes).replace(/^\uFEFF/, ''), encoding: 'CP950 / Big5-compatible' }; } };
const duplicates = (values: Array<string | undefined>) => [...values.reduce((map, value) => value ? map.set(value, (map.get(value) ?? 0) + 1) : map, new Map<string, number>())].filter(([, count]) => count > 1).slice(0, 20).map(([value, count]) => ({ value, count }));

export async function convertDawannanIndustrialAreaCompanies(filePath?: string) {
  const csvFile = filePath ? undefined : (await readdir(rawDir)).find((file) => file.toLowerCase().endsWith('.csv'));
  if (!filePath && !csvFile) throw new Error('No Dawannan Industrial Area company CSV found. Run npm run data:fetch:dawannan-companies.');
  const inputPath = filePath ?? join(rawDir, csvFile!), { text, encoding } = decode(await readFile(inputPath)), [rawHeaders, ...rows] = parseCsv(text);
  if (!rawHeaders) throw new Error('Invalid Dawannan Industrial Area company CSV: file is empty.');
  const headers = rawHeaders.map(normalizeColumnName), required = ['統編', '公司名稱', '公司地址', 'ADDR_X', 'ADDR_Y'], missing = required.filter((header) => !headers.includes(header));
  if (missing.length) throw new Error(`Invalid Dawannan Industrial Area company CSV: missing columns ${missing.join(', ')}.`);
  const invalidUnifiedBusinessNumbers: string[] = [], addressWarnings: string[] = [], coordinateWarnings: string[] = [];
  const records = rows.flatMap((row, index): DawannanIndustrialAreaCompanyRecord[] => {
    const values = Object.fromEntries(headers.map((header, column) => [header, cleanDawannanText(row[column])]));
    const ubn = parseUnifiedBusinessNumber(values['統編']), name = parseIndustrialAreaCompanyName(values['公司名稱']), address = parseDawannanCompanyAddress(values['公司地址']), x = parseProjectedCoordinate(values['ADDR_X']), y = parseProjectedCoordinate(values['ADDR_Y']);
    if (!ubn.unifiedBusinessNumber || !name.companyName || !address.companyAddress) return [];
    if (!ubn.unifiedBusinessNumberValidFormat && invalidUnifiedBusinessNumbers.length < 20) invalidUnifiedBusinessNumbers.push(ubn.unifiedBusinessNumber);
    if (!address.taipeiDistrict && addressWarnings.length < 20) addressWarnings.push(address.companyAddress);
    const hasProjectedCoordinates = x.value !== undefined && y.value !== undefined, converted = convertProjectedTaipeiCoordinateToWgs84({ projectedX: x.value, projectedY: y.value });
    if (converted.coordinateConversionStatus !== 'converted_to_wgs84' && coordinateWarnings.length < 20) coordinateWarnings.push(`${x.raw ?? ''},${y.raw ?? ''}`);
    const record: DawannanIndustrialAreaCompanyRecord = { id: createHash('sha1').update(`${ubn.unifiedBusinessNumberNormalized}|${name.companyNameNormalized}|${index}`).digest('hex').slice(0, 12), module: 'dawannan_industrial_area_company_directory' as const, unifiedBusinessNumber: ubn.unifiedBusinessNumber, unifiedBusinessNumberNormalized: ubn.unifiedBusinessNumberNormalized, unifiedBusinessNumberValidFormat: ubn.unifiedBusinessNumberValidFormat, companyName: name.companyName, companyNameNormalized: name.companyNameNormalized, companyAddress: address.companyAddress, companyAddressNormalized: address.companyAddressNormalized, postalCode: address.postalCode, districtFromAddress: address.districtFromAddress, isTaipeiDistrict: address.isTaipeiDistrict, taipeiDistrict: address.taipeiDistrict, roadName: address.roadName, projectedXRaw: x.raw, projectedYRaw: y.raw, projectedX: x.value, projectedY: y.value, hasProjectedCoordinates, projectedCoordinateSystemAssumption: converted.projectedCoordinateSystemAssumption, wgs84Longitude: converted.longitude, wgs84Latitude: converted.latitude, coordinateConversionStatus: converted.coordinateConversionStatus, locationPrecision: converted.coordinateConversionStatus === 'converted_to_wgs84' ? 'projected_coordinate_converted' as const : hasProjectedCoordinates ? 'projected_coordinate_unconverted' as const : address.companyAddress ? 'address_only' as const : 'missing' as const, source, sourceAgency, industrialAreaName: '大彎南段工業區' as const };
    return [{ ...record, googleMapsQuery: createDawannanCompanyMapQuery(record) }];
  });
  const summary = buildDawannanIndustrialAreaCompanySummary(records), fileInfo = await stat(inputPath), report = await readFile(reportPath, 'utf8').then(JSON.parse).catch(() => ({}));
  const dawannanIndustrialAreaCompanyDirectory = { source, sourceAgency: '產業局', sourcePage: 'https://data.taipei/dataset/detail?id=dd950d9c-01c0-452d-b8d0-f9cf38f3a55d', theme: '經濟', serviceCategory: '開創事業', updateFrequency: '不定期更新', officialResourceUpdateTime: '2026-06-02 09:03:06', officialMetadataUpdateTime: '2026-06-02 15:07:42', collectionPeriodStart: '2007-01-01', inputFile: basename(inputPath), convertedAt: new Date().toISOString(), fileSize: fileInfo.size, encoding, inputRows: rows.length, outputRecords: records.length, invalidUnifiedBusinessNumbers, addressWarnings, coordinateWarnings, duplicateUnifiedBusinessNumbers: duplicates(records.map((r) => r.unifiedBusinessNumberNormalized)), duplicateCompanyNames: duplicates(records.map((r) => r.companyNameNormalized)), duplicateCompanyAddresses: duplicates(records.map((r) => r.companyAddressNormalized)), duplicateCoordinatePairs: duplicates(records.map((r) => r.projectedX !== undefined && r.projectedY !== undefined ? `${r.projectedX},${r.projectedY}` : undefined)), coordinateQuality: summary.coordinateQuality, dataQuality: summary.dataQuality, sampleConvertedCoordinates: records.filter((r) => r.coordinateConversionStatus === 'converted_to_wgs84').slice(0, 5).map((r) => ({ projectedX: r.projectedX, projectedY: r.projectedY, longitude: r.wgs84Longitude, latitude: r.wgs84Latitude })), notes: ['UTF-8-SIG decoded with Big5 fallback', 'Unified business numbers preserved as strings', 'ADDR_X / ADDR_Y are treated as projected coordinates, not longitude / latitude', 'TWD97 TM2 zone 121 conversion is reused from the existing Taipei coordinate helper and validated against Taipei bounds'] };
  await mkdir(outputDir, { recursive: true }); await Promise.all([writeFile(join(outputDir, 'dawannan-industrial-area-company-directory.json'), JSON.stringify(records)), writeFile(join(outputDir, 'dawannan-industrial-area-company-summary.json'), JSON.stringify(summary)), writeFile(reportPath, JSON.stringify({ ...report, dawannanIndustrialAreaCompanyDirectory }, null, 2))]);
  console.log(`Converted ${records.length} Dawannan Industrial Area company records from ${basename(inputPath)}.`);
}
if (import.meta.url === `file://${process.argv[1]}`) await convertDawannanIndustrialAreaCompanies(process.argv.find((arg) => arg.startsWith('--file='))?.slice(7));
