import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parseCsv } from './convertCivicGroups';

const base = process.cwd(), input = join(base, 'data/raw/indigenous-community-organizations/source.csv'), output = join(base, 'public/data/indigenous-community-organizations'), reportPath = join(base, 'public/data/conversion-report.json'), metadataPath = join(base, 'data/raw/indigenous-community-organizations/fetch-metadata.json');
const taipeiDistricts = ['中正區', '大同區', '中山區', '松山區', '大安區', '萬華區', '信義區', '士林區', '北投區', '內湖區', '南港區', '文山區'];
const postalDistrict: Record<string, string> = { '100': '中正區', '103': '大同區', '104': '中山區', '105': '松山區', '106': '大安區', '108': '萬華區', '110': '信義區', '111': '士林區', '112': '北投區', '114': '內湖區', '115': '南港區', '116': '文山區' };
const clean = (value: string | undefined) => value?.replace(/[\r\n]+/g, ' ').replace(/\s+/g, ' ').trim() ?? '';
const normalize = (value: string) => clean(value).replace(/[\s　]/g, '').toLowerCase();
const bytes = await readFile(input); let text: string;
try { text = new TextDecoder('utf-8', { fatal: true }).decode(bytes); } catch { try { text = new TextDecoder('big5', { fatal: true }).decode(bytes); } catch { text = new TextDecoder('cp950').decode(bytes); } }
const [headerRow, ...rows] = parseCsv(text.replace(/^\uFEFF/, '')); const headers = headerRow.map(clean);
const duplicateRows: number[] = [], missingOrganizationName: number[] = [], missingAddress: number[] = [], missingCityCode: number[] = [], malformedCityCode: number[] = [], invalidPostalCode: number[] = [], unresolvedDistrict: number[] = [], locationConflicts: number[] = [];
const exactRows = new Set<string>(), stableIds = new Set<string>();
const records = rows.map((row, index) => {
  const sourceValues = Object.fromEntries(headers.map((header, column) => [header, clean(row[column])])) as Record<string, string>;
  const sourceSequenceNumber = sourceValues['項次編號'] || sourceValues['序號']; const organizationName = sourceValues['社團/團體'] || sourceValues['社團名稱'] || sourceValues['團體名稱']; const address = sourceValues['地址']; const cityName = sourceValues['縣市名稱']; const districtName = sourceValues['行政區域'] || sourceValues['行政區']; const cityCode = sourceValues['縣市別代碼'] || sourceValues['縣市代碼']; const postalCode = sourceValues['郵遞區號']; const rowNumber = index + 2;
  const fingerprint = createHash('sha256').update(JSON.stringify(sourceValues)).digest('hex'); if (exactRows.has(fingerprint)) { duplicateRows.push(rowNumber); return null; } exactRows.add(fingerprint);
  if (!organizationName) missingOrganizationName.push(rowNumber); if (!address) missingAddress.push(rowNumber); if (!cityCode) missingCityCode.push(rowNumber); if (cityCode && !/^\d{5,8}$/.test(cityCode)) malformedCityCode.push(rowNumber); if (postalCode && !/^\d{3,6}$/.test(postalCode.replace(/[\s-]/g, ''))) invalidPostalCode.push(rowNumber);
  const addressDistrict = taipeiDistricts.find((name) => address.includes(name)) ?? ''; const postalDistrictName = postalDistrict[postalCode.slice(0, 3)] ?? ''; const hasValidDistrict = taipeiDistricts.includes(districtName); if (!hasValidDistrict) unresolvedDistrict.push(rowNumber);
  const locationConsistent = (!addressDistrict || !districtName || addressDistrict === districtName) && (!postalDistrictName || !districtName || postalDistrictName === districtName); if (!locationConsistent) locationConflicts.push(rowNumber);
  const candidate = sourceSequenceNumber || `indigenous-org-${createHash('sha1').update(`${normalize(organizationName)}|${normalize(address)}` || fingerprint).digest('hex').slice(0, 16)}`; const id = stableIds.has(candidate) ? `${candidate}-${fingerprint.slice(0, 8)}` : candidate; stableIds.add(id);
  return { id, sourceSequenceNumber, organizationName, address, cityName, districtName, cityCode, postalCode, hasAddress: Boolean(address), hasCompleteAddress: Boolean(address && cityName && districtName && postalCode), hasValidDistrict, locationConsistent, externalMapQuery: address ? clean(`${address} ${organizationName}`) : '', sourceValues };
}).filter(Boolean) as Array<Record<string, unknown>>;
const group = (field: string) => Object.entries(records.reduce<Record<string, number>>((all, record) => { const value = String(record[field] ?? ''); if (value) all[value] = (all[value] ?? 0) + 1; return all; }, {})).map(([label, value]) => ({ label, value })).sort((a, b) => b.value - a.value || a.label.localeCompare(b.label, 'zh-Hant'));
const conflicts = (left: string, right: string) => Object.entries(records.reduce<Record<string, Set<string>>>((all, record) => { const key = normalize(String(record[left] ?? '')), value = normalize(String(record[right] ?? '')); if (key && value) (all[key] ??= new Set()).add(value); return all; }, {})).filter(([, values]) => values.size > 1).map(([key]) => key);
const metadata = await readFile(metadataPath, 'utf8').then(JSON.parse).catch(() => ({})); const summary = { totalRecords: records.length, uniqueOrganizationNames: new Set(records.map((record) => normalize(String(record.organizationName ?? ''))).filter(Boolean)).size, districtsRepresented: group('districtName').length, citiesRepresented: group('cityName').length, postalCodesRepresented: group('postalCode').length, completeAddressRecords: records.filter((record) => record.hasCompleteAddress).length, validDistrictRecords: records.filter((record) => record.hasValidDistrict).length, districtWithMostOrganizations: group('districtName')[0]?.label ?? '', byDistrict: group('districtName'), byCity: group('cityName'), byPostalCode: group('postalCode'), addressCompleteness: [{ label: 'complete', value: records.filter((record) => record.hasCompleteAddress).length }, { label: 'incomplete', value: records.filter((record) => !record.hasCompleteAddress).length }], districtPostalConsistency: [{ label: 'consistent', value: records.filter((record) => record.locationConsistent).length }, { label: 'conflict', value: records.filter((record) => !record.locationConsistent).length }], sourceFileUpdatedAt: metadata.sourceFileUpdatedAt ?? '', metadataUpdatedAt: metadata.metadataUpdatedAt ?? '', sourceUrl: metadata.sourceUrl ?? '' };
const oldReport = await readFile(reportPath, 'utf8').then(JSON.parse).catch(() => ({})); await mkdir(output, { recursive: true }); await Promise.all([writeFile(join(output, 'records.json'), JSON.stringify(records)), writeFile(join(output, 'summary.json'), JSON.stringify(summary, null, 2)), writeFile(reportPath, JSON.stringify({ ...oldReport, indigenousCommunityOrganizations: { convertedAt: new Date().toISOString(), headers, inputRows: rows.length, outputRecords: records.length, duplicateRows, missingOrganizationName, missingAddress, missingCityCode, malformedCityCode, invalidPostalCode, unresolvedDistrict, locationConflicts, sameOrganizationNameMultipleAddresses: conflicts('organizationName', 'address'), sameAddressMultipleOrganizations: conflicts('address', 'organizationName'), notes: ['Official city and district fields are preserved without address-based replacement.', 'No coordinates, automatic geocoding, or exact map markers are created.'] } }, null, 2))]);
console.log(`Converted ${records.length} Indigenous community organization records.`);
