import { useEffect, useMemo, useState } from 'react';
import { UI_FAMILIES } from './lib/uiFamilies';
import AccessibleTabs, { AccessibleTabPanel } from './AccessibleTabs';

type Provider = { id: string; sourceSequenceNumber: string; districtCode: string; districtName: string; institutionName: string; address: string; phone: string; hasPhone: boolean; googleMapsQuery: string };
type View = 'find' | 'districts' | 'directory' | 'quality' | 'notes';
const dash = '—';
function mapUrl(query: string) { return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`; }
function csvEscape(value: string) { return `"${value.replaceAll('"', '""')}"`; }
function telHref(value: string) { const digits = value.replace(/[^\d+]/g, ''); return digits.length >= 7 ? `tel:${digits}` : ''; }
function BarChart({ title, rows }: { title: string; rows: Array<{ label: string; value: number }> }) { const max = Math.max(1, ...rows.map((row) => row.value)); return <article className="ivp-chart"><div className="ivp-chart-title"><h3>{title}</h3><span>{rows.reduce((sum, row) => sum + row.value, 0).toLocaleString()}</span></div><div className="ivp-bars">{rows.map((row) => <div className="ivp-bar" key={row.label}><span>{row.label}</span><div><i style={{ width: `${row.value ? Math.max(3, row.value / max * 100) : 0}%` }} /></div><b>{row.value}</b></div>)}</div></article>; }

export default function AdultInfluenzaVaccineProvidersModule({ language }: { language: 'zh' | 'en' }) {
  const zh = language === 'zh';
  const t = (chinese: string, english: string) => zh ? chinese : english;
  const [records, setRecords] = useState<Provider[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState(false);
  const [view, setView] = useState<View>('find');
  const [search, setSearch] = useState('');
  const [district, setDistrict] = useState('');
  const [phone, setPhone] = useState('');
  const [address, setAddress] = useState('');
  const [sort, setSort] = useState<'name' | 'district'>('name');
  const [page, setPage] = useState(1);
  const [copied, setCopied] = useState('');
  const pageSize = 20;

  useEffect(() => {
    let active = true;
    fetch(`${import.meta.env.BASE_URL}data/adult-influenza-vaccine-providers/records.json`)
      .then((response) => { if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json(); })
      .then((data) => { if (!Array.isArray(data)) throw new Error('Records payload must be an array.'); if (active) setRecords(data); })
      .catch(() => { if (active) setLoadError(true); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);

  const districts = useMemo(() => [...new Set(records.map((record) => record.districtName).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'zh-Hant')), [records]);
  const filtered = useMemo(() => {
    const query = search.trim().toLocaleLowerCase();
    return records.filter((record) => (!query || [record.institutionName, record.districtName, record.districtCode, record.address, record.phone].join(' ').toLocaleLowerCase().includes(query))
      && (!district || record.districtName === district)
      && (!phone || (phone === 'yes' ? record.hasPhone : !record.hasPhone))
      && (!address || (address === 'yes' ? Boolean(record.address) : !record.address)));
  }, [records, search, district, phone, address]);
  const sorted = useMemo(() => [...filtered].sort((a, b) => (sort === 'district' ? a.districtName.localeCompare(b.districtName, 'zh-Hant') : a.institutionName.localeCompare(b.institutionName, 'zh-Hant')) || a.sourceSequenceNumber.localeCompare(b.sourceSequenceNumber)), [filtered, sort]);
  const byDistrict = useMemo(() => districts.map((label) => ({ label, value: filtered.filter((record) => record.districtName === label).length })).filter((row) => row.value), [districts, filtered]);
  const stats = useMemo(() => ({ total: filtered.length, unique: new Set(filtered.map((record) => record.institutionName).filter(Boolean)).size, districts: new Set(filtered.map((record) => record.districtName).filter(Boolean)).size, phones: filtered.filter((record) => record.hasPhone).length, addresses: filtered.filter((record) => record.address).length, complete: filtered.filter((record) => record.hasPhone && record.address).length }), [filtered]);
  const totalPages = Math.max(1, Math.ceil(sorted.length / pageSize));
  const currentPage = Math.min(page, totalPages);
  const pageRows = sorted.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const updateFilter = (action: () => void) => { action(); setPage(1); };
  const clear = () => { setSearch(''); setDistrict(''); setPhone(''); setAddress(''); setPage(1); };
  const copy = async (key: string, value: string) => { if (!value) return; await navigator.clipboard?.writeText(value); setCopied(key); window.setTimeout(() => setCopied(''), 1200); };
  const exportCsv = () => { const headers = ['ID', 'Institution', 'District', 'Address', 'Phone']; const lines = [headers, ...filtered.map((record) => [record.sourceSequenceNumber, record.institutionName, record.districtName, record.address, record.phone])].map((row) => row.map((value) => csvEscape(value ?? '')).join(',')); const url = URL.createObjectURL(new Blob([`\uFEFF${lines.join('\n')}`], { type: 'text/csv;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'adult-influenza-vaccine-providers-filtered.csv'; anchor.click(); URL.revokeObjectURL(url); };
  const tabs: Array<[View, string, string]> = [['find', t('找成人流感疫苗院所', 'Find a Vaccine Provider'), '01'], ['districts', t('行政區分布', 'District Distribution'), '02'], ['directory', t('院所名錄', 'Provider Directory'), '03'], ['quality', t('資料品質', 'Data Quality'), '04'], ['notes', t('資料說明', 'Data Notes'), '05']];

  if (loading) return <section className="workspace influenza-provider-module" data-ui-family={UI_FAMILIES.healthcareRichDirectory}><p className="module-loading" role="status">{t('正在載入成人流感疫苗院所資料…', 'Loading adult influenza vaccine provider data…')}</p></section>;
  if (loadError) return <section className="workspace influenza-provider-module" data-ui-family={UI_FAMILIES.healthcareRichDirectory}><p className="notice error" role="alert">{t('無法載入本機資料快照。請稍後再試或查閱原始資料來源。', 'The local data snapshot could not be loaded. Please try again later or consult the source dataset.')}</p></section>;

  return <section className="workspace influenza-provider-module adult-influenza-module" data-ui-family={UI_FAMILIES.healthcareRichDirectory}>
    <div className="ivp-hero"><div><p className="eyebrow">HEALTHCARE / PREVENTIVE CARE / ADULT</p><h2>{t('流感疫苗合約醫療院所（成人）', 'Adult Influenza Vaccine Providers')}</h2><p>{t('從來源名錄搜尋成人流感疫苗合約院所，依院所名稱、行政區、地址或電話縮小查找範圍。', 'Search source-recorded adult influenza vaccination providers by institution, district, address, or telephone.')}</p></div><div className="ivp-scope"><span>{t('目錄範圍', 'DIRECTORY SCOPE')}</span><strong>{t('成人流感疫苗合約院所', 'Adult influenza contracted providers')}</strong><small>{t('來源地址僅供外部地圖查詢', 'Source addresses support external map lookup only')}</small></div></div>
    <div className="ivp-warning"><b>!</b><p>{t('本名錄是公開資料快照，不代表目前疫苗庫存、預約、接種資格、接種適用性、服務時間、費用、醫療品質或推薦。前往前請向院所或臺北市政府衛生局確認。', 'This directory is a public-data snapshot. It does not establish current vaccine stock, appointments, eligibility, suitability, service hours, fees, medical quality, or recommendation. Confirm with the institution or Taipei City Department of Health before visiting.')}</p></div>
    <AccessibleTabs tabs={tabs} value={view} onChange={(id) => { setView(id); setPage(1); }} ariaLabel={t('成人流感疫苗院所導覽', 'Adult influenza provider views')} idPrefix="adult-influenza" className="ivp-tabs" controlsPanel />
    <div className="ivp-filters"><div className="ivp-filter-head"><div><p className="eyebrow">{t('找可聯絡的來源院所', 'FIND A CONTACT')}</p><h3>{t('搜尋院所名錄', 'Search provider records')}</h3></div><strong>{filtered.length.toLocaleString()} {t('筆符合', 'matching records')}</strong></div><input className="ivp-search" aria-label={t('關鍵字搜尋', 'Keyword search')} value={search} onChange={(event) => updateFilter(() => setSearch(event.target.value))} placeholder={t('搜尋院所、行政區、地址或電話…', 'Search institution, district, address, or phone…')} /><div className="ivp-filter-grid"><label>{t('行政區', 'District')}<select value={district} onChange={(event) => updateFilter(() => setDistrict(event.target.value))}><option value="">{t('全部行政區', 'All districts')}</option>{districts.map((value) => <option key={value}>{value}</option>)}</select></label><label>{t('電話', 'Telephone')}<select value={phone} onChange={(event) => updateFilter(() => setPhone(event.target.value))}><option value="">{t('不限', 'Any')}</option><option value="yes">{t('有電話', 'Has telephone')}</option><option value="no">{t('未提供電話', 'No telephone')}</option></select></label><label>{t('地址', 'Address')}<select value={address} onChange={(event) => updateFilter(() => setAddress(event.target.value))}><option value="">{t('不限', 'Any')}</option><option value="yes">{t('有地址', 'Has address')}</option><option value="no">{t('未提供地址', 'No address')}</option></select></label></div><div className="ivp-filter-actions"><button className="ghost-button" type="button" onClick={clear}>{t('清除篩選', 'Clear filters')}</button><button className="outline-button" type="button" onClick={exportCsv}>⇩ {t('匯出篩選 CSV', 'Export filtered CSV')}</button></div></div>
    <AccessibleTabPanel idPrefix="adult-influenza" value={view}>
    {view === 'find' && <><div className="ivp-stat-grid">{[[t('來源紀錄', 'Source records'), stats.total], [t('不重複院所', 'Unique institutions'), stats.unique], [t('涵蓋行政區', 'Districts covered'), stats.districts], [t('有電話', 'With telephone'), stats.phones], [t('有地址', 'With address'), stats.addresses], [t('電話＋地址', 'Phone + address'), stats.complete]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{Number(value).toLocaleString()}</strong></article>)}</div><div className="ivp-insights"><div><p className="eyebrow">{t('搜尋便利性', 'SEARCH CONVENIENCE')}</p><h3>{district ? `${district} · ${t('目前篩選', 'current filter')}` : t('聯絡前先確認', 'Confirm before visiting')}</h3></div><p>{t(`目前有 ${stats.total} 筆來源紀錄，其中 ${stats.phones} 筆有電話、${stats.addresses} 筆有地址。這些欄位協助聯絡與查找，不表示疫苗目前有貨或可預約。`, `${stats.total} source records match; ${stats.phones} include telephone information and ${stats.addresses} include addresses. These fields support lookup and contact, not current vaccine stock or appointment availability.`)}</p></div><div className="ivp-card-grid">{pageRows.slice(0, 6).map((record) => <article className="ivp-card" key={record.id}><div className="ivp-card-top"><span>#{record.sourceSequenceNumber || dash}</span><span className="ivp-pill">{record.districtName || t('行政區未註明', 'District unspecified')}</span></div><h4>{record.institutionName || dash}</h4><p><b>{record.districtName || dash}</b><br />{record.address || dash}</p><div className="ivp-actions">{record.phone ? (telHref(record.phone) ? <a href={telHref(record.phone)}>☎ {record.phone}</a> : <span>{record.phone}</span>) : <span>{dash}</span>}<button type="button" onClick={() => copy(`card-${record.id}`, `${record.institutionName} ${record.address} ${record.phone}`)}>{copied === `card-${record.id}` ? '✓' : t('複製', 'Copy')}</button>{record.googleMapsQuery && <a href={mapUrl(record.googleMapsQuery)} target="_blank" rel="noreferrer">↗ {t('地圖查詢', 'Map lookup')}</a>}</div><small>{t('來源紀錄；請向院所確認目前接種安排。', 'Source record; confirm current vaccination arrangements with the institution.')}</small></article>)}</div></>}
    {view === 'districts' && <div className="ivp-view-grid"><BarChart title={t('來源院所／行政區', 'Provider records by district')} rows={byDistrict} /><div className="ivp-copy"><p className="eyebrow">{t('描述性比較', 'DESCRIPTIVE COMPARISON')}</p><h3>{t('行政區紀錄分布', 'District coverage')}</h3><p>{t('院所筆數僅表示來源名錄中的紀錄數，不代表疫苗供應、醫療品質、需求或可近性。', 'Provider counts describe source rows only; they do not establish vaccine supply, medical quality, demand, or accessibility.')}</p></div></div>}
    {view === 'directory' && <div className="ivp-directory"><div className="ivp-directory-head"><h3>{sorted.length.toLocaleString()} {t('筆來源院所紀錄', 'source provider records')}</h3><label>{t('排序', 'Sort')}<select value={sort} onChange={(event) => { setSort(event.target.value as 'name' | 'district'); setPage(1); }}><option value="name">{t('院所名稱', 'Institution')}</option><option value="district">{t('行政區', 'District')}</option></select></label></div><div className="ivp-table-wrap"><table><thead><tr>{[t('序號 / ID', 'ID'), t('院所名稱', 'Institution'), t('行政區', 'District'), t('地址', 'Address'), t('電話', 'Telephone'), t('地圖查詢', 'Map lookup')].map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{pageRows.map((record) => <tr key={record.id}><td>{record.sourceSequenceNumber || dash}</td><td><strong>{record.institutionName || dash}</strong></td><td>{record.districtName || dash}</td><td>{record.address || dash}{record.address && <button className="ivp-copy" type="button" onClick={() => copy(`address-${record.id}`, record.address)}>{copied === `address-${record.id}` ? '✓' : t('複製', 'Copy')}</button>}</td><td>{record.phone ? <>{telHref(record.phone) ? <a href={telHref(record.phone)}>{record.phone}</a> : record.phone}<button className="ivp-copy" type="button" onClick={() => copy(`phone-${record.id}`, record.phone)}>{copied === `phone-${record.id}` ? '✓' : t('複製', 'Copy')}</button></> : dash}</td><td>{record.googleMapsQuery ? <a href={mapUrl(record.googleMapsQuery)} target="_blank" rel="noreferrer">↗ {t('查地圖', 'Open map')}</a> : dash}</td></tr>)}</tbody></table>{!pageRows.length && <p className="empty">{t('沒有符合篩選條件的來源紀錄。', 'No source records match these filters.')}</p>}</div><div className="ivp-pagination"><button type="button" disabled={currentPage <= 1} onClick={() => setPage(currentPage - 1)}>←</button><span>{currentPage} / {totalPages}</span><button type="button" disabled={currentPage >= totalPages} onClick={() => setPage(currentPage + 1)}>→</button></div></div>}
    {view === 'quality' && <div className="ivp-quality"><article><p className="eyebrow">{t('資料品質檢查', 'DATA QUALITY CHECKS')}</p><strong>{records.length.toLocaleString()}</strong><span>{t('筆保留來源紀錄', 'source rows retained')}</span></article>{[[t('缺少院所名稱', 'Missing institution'), records.filter((record) => !record.institutionName).length], [t('缺少地址', 'Missing address'), records.filter((record) => !record.address).length], [t('缺少電話', 'Missing telephone'), records.filter((record) => !record.hasPhone).length], [t('行政區未解析', 'District unspecified'), records.filter((record) => !record.districtName).length]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{Number(value).toLocaleString()}</strong></article>)}</div>}
    {view === 'notes' && <div className="ivp-notes"><article><p className="eyebrow">{t('資料範圍', 'DATA SCOPE')}</p><h3>{t('成人流感疫苗合約院所', 'Adult influenza contracted providers')}</h3><p>{t('本資料不確認即時庫存、預約、接種資格、接種適用性、服務時間、費用、醫療品質或推薦，亦不提供接種或醫療建議。', 'This data does not confirm real-time stock, appointments, eligibility, suitability, service hours, fees, medical quality, or recommendation, and does not provide vaccination or medical advice.')}</p></article><article><p className="eyebrow">{t('位置限制', 'LOCATION LIMITATION')}</p><h3>{t('外部地圖查詢', 'External map lookup')}</h3><p>{t('地址只用於外部地圖搜尋，不代表官方確認座標或精確標記。', 'Addresses support external map search only and do not represent official coordinates or exact map markers.')}</p></article><article><p className="eyebrow">{t('下一步', 'NEXT STEP')}</p><h3>{t('聯絡院所確認', 'Confirm with the provider')}</h3><p>{t('若準備接種，請使用來源電話或主管機關資訊確認當日供應、資格與服務安排。', 'Before vaccination, use source contact information or the relevant authority to confirm same-day supply, eligibility, and service arrangements.')}</p></article></div>}
    </AccessibleTabPanel>
  </section>;
}
