import { useEffect, useMemo, useState } from 'react';
type Record = { id: string; year: number | null; month: number | null; groupName: string; serviceType: string; cohortDischargeCount: number | null; zeroDischargeCount: number | null; incomingTransferCount: number | null; subtotalCount: number | null };
type Report = { duplicates: string[]; invalidDates: string[]; invalidCounts: string[]; missingGroups: string[]; subtotalInconsistencies: string[] };
const dash = '—'; const number = (value: number | null) => value === null ? dash : value.toLocaleString();
export default function AlternativeServiceReserveStatisticsModule({ language }: { language: 'zh' | 'en' }) {
  const zh = language === 'zh', t = (chinese: string, english: string) => zh ? chinese : english;
  const [records, setRecords] = useState<Record[]>([]), [report, setReport] = useState<Report | null>(null), [error, setError] = useState(false), [view, setView] = useState('overview'), [mode, setMode] = useState('monthly'), [year, setYear] = useState(''), [month, setMonth] = useState(''), [group, setGroup] = useState(''), [service, setService] = useState(''), [search, setSearch] = useState(''), [sort, setSort] = useState('period'), [page, setPage] = useState(1);
  useEffect(() => { const base = `${import.meta.env.BASE_URL}data/alternative-service-reserve-statistics/`; fetch(`${base}records.json`).then((response) => { if (!response.ok) throw Error(); return response.json(); }).then(setRecords).catch(() => setError(true)); fetch(`${base}conversion-report.json`).then((response) => response.ok ? response.json() : null).then(setReport).catch(() => setReport(null)); }, []);
  const reset = (set: (value: string) => void, value: string) => { set(value); setPage(1); };
  const filtered = useMemo(() => records.filter((record) => { const query = search.trim().toLowerCase(); return (!year || String(record.year) === year) && (!month || String(record.month) === month) && (!group || record.groupName === group) && (!service || record.serviceType === service) && (!query || [record.year, record.month, record.groupName, record.serviceType].join(' ').toLowerCase().includes(query)); }), [records, year, month, group, service, search]);
  const sum = (items: Record[], field: 'subtotalCount' | 'cohortDischargeCount' | 'zeroDischargeCount' | 'incomingTransferCount') => items.reduce((total, item) => total + (item[field] ?? 0), 0);
  const series = (key: 'year' | 'groupName' | 'serviceType') => [...new Set(filtered.map((record) => String(record[key] ?? '')).filter(Boolean))].map((label) => ({ label, value: sum(filtered.filter((record) => String(record[key] ?? '') === label), 'subtotalCount') })).sort((a, b) => a.label.localeCompare(b.label, 'zh-Hant'));
  const months = useMemo(() => [...new Set(filtered.filter((record) => record.year && record.month).map((record) => `${record.year}-${String(record.month).padStart(2, '0')}`))].map((label) => ({ label, value: sum(filtered.filter((record) => `${record.year}-${String(record.month).padStart(2, '0')}` === label), 'subtotalCount') })).sort((a, b) => a.label.localeCompare(b.label)), [filtered]);
  const years = useMemo(() => series('year'), [filtered]); const groups = useMemo(() => series('groupName'), [filtered]); const services = useMemo(() => series('serviceType'), [filtered]);
  const latest = [...records].filter((record) => record.year && record.month).sort((a, b) => (b.year! - a.year!) || (b.month! - a.month!))[0]; const latestItems = latest ? records.filter((record) => record.year === latest.year && record.month === latest.month) : [];
  const previous = latest ? records.filter((record) => record.year === (latest.month === 1 ? latest.year! - 1 : latest.year) && record.month === (latest.month === 1 ? 12 : latest.month! - 1)) : []; const change = latestItems.length && previous.length ? sum(latestItems, 'subtotalCount') - sum(previous, 'subtotalCount') : null;
  const sorted = useMemo(() => [...filtered].sort((a, b) => sort === 'group' ? a.groupName.localeCompare(b.groupName, 'zh-Hant') : sort === 'service' ? a.serviceType.localeCompare(b.serviceType, 'zh-Hant') : sort === 'subtotal' ? (b.subtotalCount ?? -1) - (a.subtotalCount ?? -1) : (b.year ?? 0) - (a.year ?? 0) || (b.month ?? 0) - (a.month ?? 0)), [filtered, sort]);
  const displayed = useMemo(() => { if (mode === 'monthly') return sorted; const annual = new Map<string, Record>(); for (const record of sorted) { const key = `${record.year}|${record.groupName}|${record.serviceType}`, current = annual.get(key); if (current) { for (const field of ['cohortDischargeCount', 'zeroDischargeCount', 'incomingTransferCount', 'subtotalCount'] as const) current[field] = (current[field] ?? 0) + (record[field] ?? 0); } else annual.set(key, { ...record, id: key, month: null }); } return [...annual.values()]; }, [sorted, mode]);
  const pages = Math.max(1, Math.ceil(displayed.length / 25)), rows = displayed.slice((Math.min(page, pages) - 1) * 25, Math.min(page, pages) * 25);
  const chart = (title: string, data: { label: string; value: number }[]) => { const max = Math.max(1, ...data.map((item) => item.value)); return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) => <div className="bar-row wide-label" key={item.label}><span>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{item.value.toLocaleString()}</b></div>)}</div></section>; };
  const download = () => { const quote = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`, csv = [['Year', 'Month', 'Group', 'Service type', 'Cohort discharges', 'Zero discharges', 'Incoming transfers', 'Subtotal'], ...filtered.map((record) => [record.year, record.month, record.groupName, record.serviceType, record.cohortDischargeCount, record.zeroDischargeCount, record.incomingTransferCount, record.subtotalCount])].map((line) => line.map(quote).join(',')).join('\n'), url = URL.createObjectURL(new Blob(['\uFEFF', csv], { type: 'text/csv;charset=utf-8' })), anchor = document.createElement('a'); anchor.href = url; anchor.download = 'alternative-service-reserve-statistics-filtered.csv'; anchor.click(); URL.revokeObjectURL(url); };
  if (error) return <section className="workspace"><div className="notice">{t('無法載入本機資料檔。', 'The local data file could not be loaded.')}</div></section>;
  return <section className="workspace"><div className="section-heading"><p>MILITARY SERVICE ADMINISTRATION / ALTERNATIVE SERVICE</p><h2>{t('替代役備役列管人數分析統計', 'Alternative Service Reserve Statistics')}</h2><span>{t('公開行政統計資料；無地點欄位，不建立地圖。', 'Public administrative statistics; there are no location fields and no map.')}</span></div><div className="subtabs">{[['overview', t('總覽', 'Overview')], ['monthly', t('月趨勢', 'Monthly Trends')], ['annual', t('年趨勢', 'Annual Trends')], ['groups', t('組別', 'Groups')], ['services', t('役別', 'Service Types')], ['movement', t('異動組成', 'Movement Components')], ['table', t('資料表', 'Data Table')], ['quality', t('資料品質', 'Data Quality')], ['notes', t('資料說明', 'Data Notes')]].map(([id, label]) => <button type="button" className={view === id ? 'active' : ''} key={id} onClick={() => { setView(id); setPage(1); }}>{label}</button>)}</div><aside className="filters"><label className="search"><input value={search} onChange={(event) => reset(setSearch, event.target.value)} placeholder={t('搜尋年度、月份、組別或役別', 'Search year, month, group, or service type')} /></label><div className="filter-grid"><label>{t('年度', 'Year')}<select value={year} onChange={(event) => reset(setYear, event.target.value)}><option value="">{t('全部', 'All')}</option>{[...new Set(records.map((record) => record.year).filter(Boolean))].sort((a, b) => Number(b) - Number(a)).map((item) => <option key={item}>{item}</option>)}</select></label><label>{t('月份', 'Month')}<select value={month} onChange={(event) => reset(setMonth, event.target.value)}><option value="">{t('全部', 'All')}</option>{Array.from({ length: 12 }, (_, index) => index + 1).map((item) => <option key={item}>{item}</option>)}</select></label><label>{t('組別', 'Group')}<select value={group} onChange={(event) => reset(setGroup, event.target.value)}><option value="">{t('全部', 'All')}</option>{[...new Set(records.map((record) => record.groupName).filter(Boolean))].sort().map((item) => <option key={item}>{item}</option>)}</select></label><label>{t('役別', 'Service type')}<select value={service} onChange={(event) => reset(setService, event.target.value)}><option value="">{t('全部', 'All')}</option>{[...new Set(records.map((record) => record.serviceType).filter(Boolean))].sort().map((item) => <option key={item}>{item}</option>)}</select></label></div></aside>
    {view === 'overview' && <><div className="notice subtle">{t('本資料為替代役備役列管行政統計，欄位反映來源系統的登錄與異動紀錄，不代表可動員人員、實際出席、軍事能力或即時部署。', 'This dataset contains administrative statistics for alternative-service reservists. The fields reflect registered and movement records in the source system and do not represent mobilizable personnel, actual attendance, military capability, or real-time deployment.')}</div><div className="summary-grid">{[[t('最新期間', 'Latest available period'), latest ? `${latest.year}-${String(latest.month).padStart(2, '0')}` : dash], [t('列管小計合計', 'Total listed reserve personnel'), number(sum(filtered, 'subtotalCount'))], [t('組別數', 'Groups represented'), groups.length], [t('役別數', 'Service types represented'), services.length], [t('梯退人數', 'Cohort discharges'), number(sum(filtered, 'cohortDischargeCount'))], [t('零退人數', 'Zero discharges'), number(sum(filtered, 'zeroDischargeCount'))], [t('遷入人數', 'Incoming transfers'), number(sum(filtered, 'incomingTransferCount'))], [t('與前月差異', 'Change from previous month'), change === null ? dash : `${change > 0 ? '+' : ''}${change.toLocaleString()}`]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div></>}
    {view === 'monthly' && chart(t('每月小計人數', 'Subtotal count by month'), months)} {view === 'annual' && chart(t('每年小計人數', 'Subtotal count by year'), years)} {view === 'groups' && chart(t('依組別統計', 'Counts by group'), groups)} {view === 'services' && chart(t('依役別統計', 'Counts by service type'), services)}
    {view === 'movement' && <>{chart(t('梯退人數趨勢', 'Cohort discharge trend'), months.map((item) => ({ ...item, value: sum(filtered.filter((record) => `${record.year}-${String(record.month).padStart(2, '0')}` === item.label), 'cohortDischargeCount') })))}{chart(t('零退人數趨勢', 'Zero-discharge trend'), months.map((item) => ({ ...item, value: sum(filtered.filter((record) => `${record.year}-${String(record.month).padStart(2, '0')}` === item.label), 'zeroDischargeCount') })))}{chart(t('遷入人數趨勢', 'Incoming-transfer trend'), months.map((item) => ({ ...item, value: sum(filtered.filter((record) => `${record.year}-${String(record.month).padStart(2, '0')}` === item.label), 'incomingTransferCount') })))}</>}
    {view === 'table' && <><div className="section-heading inline"><p>{t('檢視模式', 'View mode')}</p><button type="button" className={mode === 'monthly' ? 'active' : ''} onClick={() => setMode('monthly')}>{t('月', 'Monthly')}</button><button type="button" className={mode === 'annual' ? 'active' : ''} onClick={() => setMode('annual')}>{t('年', 'Annual')}</button><button type="button" onClick={download}>{t('下載篩選後 CSV', 'Download filtered CSV')}</button><label>{t('排序', 'Sort')}<select value={sort} onChange={(event) => { setSort(event.target.value); setPage(1); }}><option value="period">{t('期間', 'Period')}</option><option value="group">{t('組別', 'Group')}</option><option value="service">{t('役別', 'Service type')}</option><option value="subtotal">{t('小計', 'Subtotal')}</option></select></label></div><div className="comparison-scroll procurement-table"><table><thead><tr>{[t('年', 'Year'), t('月', 'Month'), t('組別', 'Group'), t('役別', 'Service type'), t('梯退人數', 'Cohort discharges'), t('零退人數', 'Zero discharges'), t('遷入人數', 'Incoming transfers'), t('小計人數', 'Subtotal')].map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((record) => <tr key={record.id}><td>{record.year ?? dash}</td><td>{mode === 'annual' ? dash : record.month ?? dash}</td><th>{record.groupName || dash}</th><td>{record.serviceType || dash}</td><td>{number(record.cohortDischargeCount)}</td><td>{number(record.zeroDischargeCount)}</td><td>{number(record.incomingTransferCount)}</td><td>{number(record.subtotalCount)}</td></tr>)}</tbody></table></div><div className="pagination"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>{t('上一頁', 'Previous')}</button><span>{page} / {pages}</span><button type="button" disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>{t('下一頁', 'Next')}</button></div></>}
    {view === 'quality' && <div className="notes-grid"><article><h3>{t('資料品質', 'Data quality')}</h3><p>{t(`可瀏覽紀錄 ${records.length} 筆。重複 ${report?.duplicates.length ?? 0} 筆、無效日期 ${report?.invalidDates.length ?? 0} 筆、無效數值 ${report?.invalidCounts.length ?? 0} 筆、缺少組別 ${report?.missingGroups.length ?? 0} 筆、小計與組成數值不一致 ${report?.subtotalInconsistencies.length ?? 0} 筆。小計保留來源值，未自動修正。`, `There are ${records.length} browseable records. The conversion report has ${report?.duplicates.length ?? 0} duplicate rows, ${report?.invalidDates.length ?? 0} invalid dates, ${report?.invalidCounts.length ?? 0} invalid counts, ${report?.missingGroups.length ?? 0} missing groups, and ${report?.subtotalInconsistencies.length ?? 0} source subtotal/component inconsistencies. Source subtotals are preserved and never corrected automatically.`)}</p></article></div>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{t('資料使用說明', 'Data notes')}</h3><p>{t('本資料僅供兵役行政、替代役與公共統計資料查詢。梯退、零退、遷入與小計數不應用於推論個人身分、個人服役狀態、可動員人力、軍事能力、緊急應變能力或政策績效；數值也可能受行政程序、分類方式與更新時間影響。', 'This dataset is for analysis of military-service administration, alternative service, and public statistics. Counts must not be used to infer individual identities, service status, mobilizable manpower, military capability, emergency-response capacity, or policy performance. Values may be affected by administrative procedures, classification methods, and update timing.')}</p></article></div>}
  </section>;
}
