import { useEffect, useMemo, useState } from 'react';
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet';
import { DISTRICTS } from './lib/civicGroups';
import { BIOTECH_CATEGORY_LABELS_EN, BIOTECH_CATEGORY_LABELS_ZH, buildBiotechCompanyDirectorySummary, filterBiotechCompanyDirectory, haversineDistanceMeters } from './lib/biotechCompanyDirectory';
import type { BiotechCompanyDirectoryFilters, BiotechCompanyDirectoryRecord, BiotechCompanyDirectorySummary, BiotechIndustryCategoryType, Language } from './types';

const emptyFilters: BiotechCompanyDirectoryFilters = { search: '', industryCategory: '', district: '', roadName: '', hasValidCoordinates: '', coordinateSystem: '', phoneType: '', hasPhone: '' };
const categories = Object.keys(BIOTECH_CATEGORY_LABELS_ZH) as BiotechIndustryCategoryType[];
const colors: Record<BiotechIndustryCategoryType, string> = { applied_biotechnology: '#4f9a7b', medical_device: '#4f7fbf', pharmaceutical: '#b86b4f', other: '#777', unknown: '#999' };
const labels = (language: Language) => language === 'zh' ? BIOTECH_CATEGORY_LABELS_ZH : BIOTECH_CATEGORY_LABELS_EN;
const fmt = (value?: number) => value === undefined ? '—' : value.toLocaleString();
const disclaimer = (zh: boolean) => zh ? '生技廠商企業名錄為臺北市公開資料中的生技相關企業名錄，僅供查詢單位名稱、統一編號、負責人、登記地址、公司電話、產業範疇與來源座標等欄位使用，不代表完整產業登記、即時營業狀態、公司品質排名、投資訊號、信用評等、醫藥品許可、醫療器材許可、法規遵循判定、法律意見、財務建議或官方背書。' : 'The biotech company directory is Taipei public-data information about biotech-related companies. It is for looking up source fields only and does not represent a complete industry registry, real-time operating status, company quality ranking, investment signal, credit rating, drug approval, medical device approval, legal compliance determination, legal advice, financial advice, or official endorsement.';
const mapNotice = (zh: boolean) => zh ? '點位依來源座標偵測為 TWD97 / EPSG:3826 後轉換為 WGS84 呈現，僅供位置參考。' : 'Points are converted from detected TWD97 / EPSG:3826-style source coordinates to WGS84 for location reference only.';

function Bar({ title, rows }: { title: string; rows: Array<{ label: string; count: number }> }) {
  const max = Math.max(...rows.map((row) => row.count), 1);
  return <section className="chart"><h3>{title}</h3><div className="bars">{rows.map((row) => <div className="bar-row wide-label" key={row.label}><span title={row.label}>{row.label}</span><div><i style={{ width: `${Math.max(2, row.count / max * 100)}%` }} /></div><b>{fmt(row.count)}</b></div>)}</div></section>;
}

function Filters({ records, filters, setFilters, language }: { records: BiotechCompanyDirectoryRecord[]; filters: BiotechCompanyDirectoryFilters; setFilters: (filters: BiotechCompanyDirectoryFilters) => void; language: Language }) {
  const zh = language === 'zh', update = (key: keyof BiotechCompanyDirectoryFilters, value: string) => setFilters({ ...filters, [key]: value });
  const roads = [...new Set(records.flatMap((record) => record.roadName ?? []))].sort((a, b) => a.localeCompare(b));
  const yesNo = <><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '有' : 'Yes'}</option><option value="no">{zh ? '無' : 'No'}</option></>;
  return <aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(event) => update('search', event.target.value)} placeholder={zh ? '搜尋公司名稱、統一編號、地址、電話或產業範疇' : 'Search company name, business number, address, phone, or industry category'} /></label><div className="filter-grid grant-filters">
    <label>{zh ? '產業範疇' : 'Industry category'}<select value={filters.industryCategory} onChange={(event) => update('industryCategory', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{categories.map((key) => <option value={key} key={key}>{labels(language)[key]}</option>)}</select></label>
    <label>{zh ? '行政區' : 'District'}<select value={filters.district} onChange={(event) => update('district', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{DISTRICTS.map((district) => <option key={district}>{district}</option>)}</select></label>
    <label>{zh ? '道路' : 'Road'}<select value={filters.roadName} onChange={(event) => update('roadName', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{roads.map((road) => <option key={road}>{road}</option>)}</select></label>
    <label>{zh ? '有有效座標' : 'Has valid coordinates'}<select value={filters.hasValidCoordinates} onChange={(event) => update('hasValidCoordinates', event.target.value)}>{yesNo}</select></label>
    <label>{zh ? '座標系統' : 'Coordinate system'}<select value={filters.coordinateSystem} onChange={(event) => update('coordinateSystem', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="twd97">TWD97</option><option value="wgs84">WGS84</option><option value="unknown">{zh ? '未知' : 'Unknown'}</option></select></label>
    <label>{zh ? '電話類型' : 'Phone type'}<select value={filters.phoneType} onChange={(event) => update('phoneType', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{['taipei_landline', 'other_landline', 'mobile', 'extension', 'multiple', 'missing', 'unknown'].map((type) => <option value={type} key={type}>{type}</option>)}</select></label>
    <label>{zh ? '有電話' : 'Has phone'}<select value={filters.hasPhone} onChange={(event) => update('hasPhone', event.target.value)}>{yesNo}</select></label>
  </div>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => setFilters(emptyFilters)}>{zh ? '清除篩選' : 'Clear filters'}</button>}</aside>;
}

function Overview({ summary, language }: { summary: BiotechCompanyDirectorySummary; language: Language }) {
  const zh = language === 'zh';
  const cat = (key: BiotechIndustryCategoryType) => summary.byIndustryCategory.find((item) => item.industryCategoryType === key)?.count ?? 0;
  return <><div className="notice subtle">{disclaimer(zh)}</div><div className="summary-grid">{[
    [zh ? '生技廠商數' : 'Biotech company count', summary.totalRecords], [zh ? '涵蓋行政區數' : 'Districts covered', summary.districtCount], [zh ? '產業範疇數' : 'Industry category count', summary.industryCategoryCount], [zh ? '應用生技廠商數' : 'Applied biotechnology company count', cat('applied_biotechnology')], [zh ? '醫療器材產業廠商數' : 'Medical device company count', cat('medical_device')], [zh ? '製藥產業廠商數' : 'Pharmaceutical company count', cat('pharmaceutical')], [zh ? '有效座標數' : 'Valid coordinate count', summary.recordsWithValidCoordinates], [zh ? '廠商最多行政區' : 'Top district by company count', summary.topDistrictsByCompanyCount[0]?.district ?? '—'], [zh ? '最多產業範疇' : 'Top industry category', summary.byIndustryCategory[0] ? labels(language)[summary.byIndustryCategory[0].industryCategoryType] : '—'], [zh ? '不重複登記地址數' : 'Unique registered address count', summary.uniqueAddressCount],
  ].map(([label, value]) => <article key={label}><span>{label}</span><strong>{typeof value === 'number' ? fmt(value) : value}</strong></article>)}</div><div className="chart-grid"><Bar title={zh ? '各行政區廠商數' : 'Companies by district'} rows={summary.byDistrict.map((item) => ({ label: item.district, count: item.companyCount }))} /><Bar title={zh ? '各產業範疇廠商數' : 'Companies by industry category'} rows={summary.byIndustryCategory.map((item) => ({ label: labels(language)[item.industryCategoryType], count: item.count }))} /><Bar title={zh ? '廠商最多道路' : 'Top roads by company count'} rows={summary.byRoadName.slice(0, 20).map((item) => ({ label: item.roadName, count: item.count }))} /><Bar title={zh ? '座標品質' : 'Coordinate quality'} rows={Object.entries(summary.coordinateQuality).slice(0, 4).map(([label, count]) => ({ label, count }))} /></div></>;
}

function CompanyMap({ records, language }: { records: BiotechCompanyDirectoryRecord[]; language: Language }) {
  const zh = language === 'zh', valid = records.filter((record) => record.hasValidCoordinates && record.latitude && record.longitude);
  return <div className="map-wrap"><div className="notice">{mapNotice(zh)}</div><MapContainer center={[25.072, 121.56]} zoom={11} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap contributors &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" />{valid.map((record) => <CircleMarker key={record.id} center={[record.latitude!, record.longitude!]} radius={5} pathOptions={{ fillColor: colors[record.industryCategoryType], fillOpacity: .72, color: '#fff7e8', weight: 1 }}><Popup><div className="map-popup"><strong>{record.companyName}</strong><p>{zh ? '產業範疇' : 'Industry category'}: {labels(language)[record.industryCategoryType]}</p><p>{zh ? '統一編號' : 'Unified business number'}: {record.unifiedBusinessNumber ?? '—'}</p><p>{zh ? '登記地址' : 'Registered address'}: {record.registeredAddress ?? '—'}</p><p>{zh ? '公司電話' : 'Company phone'}: {record.companyPhoneDisplay ?? '—'}</p><p>{zh ? '座標系統' : 'Coordinate system'}: {record.coordinateSystem}</p><small>{zh ? '點位依來源座標轉換呈現，僅供位置參考，不代表即時營業狀態、產品許可、公司品質、投資價值、法規遵循或官方背書。' : 'The point is shown from converted source coordinates for location reference only. It does not represent real-time operating status, product approval, company quality, investment value, legal compliance, or official endorsement.'}</small></div></Popup></CircleMarker>)}</MapContainer></div>;
}

function Nearby({ records, filters, language }: { records: BiotechCompanyDirectoryRecord[]; filters: BiotechCompanyDirectoryFilters; language: Language }) {
  const zh = language === 'zh';
  const [nearby, setNearby] = useState<Array<{ record: BiotechCompanyDirectoryRecord; distance: number }>>([]), [error, setError] = useState('');
  const findNearby = () => navigator.geolocation?.getCurrentPosition((position) => {
    const origin = { latitude: position.coords.latitude, longitude: position.coords.longitude };
    setNearby(filterBiotechCompanyDirectory(records, filters, language).filter((record) => record.hasValidCoordinates && record.latitude && record.longitude).map((record) => ({ record, distance: haversineDistanceMeters(origin, { latitude: record.latitude!, longitude: record.longitude! }) })).sort((a, b) => a.distance - b.distance).slice(0, 10)); setError('');
  }, () => setError(zh ? '無法取得目前位置。' : 'Unable to access current location.'));
  return <div className="notice subtle"><button className="text-button" onClick={findNearby}>{zh ? '找附近生技廠商' : 'Find nearby biotech companies'}</button><p>{zh ? '附近功能僅依來源座標換算距離，不代表公司目前營業、產品許可、公司品質、投資價值、信用狀態或法規遵循狀態。' : 'The nearby feature only calculates distance from source coordinates. It does not mean the company is currently operating, product-approved, high-quality, investable, creditworthy, or legally compliant.'}</p>{error && <p>{error}</p>}{nearby.length > 0 && <ol>{nearby.map(({ record, distance }) => <li key={record.id}>{record.companyName} · {distance >= 1000 ? `${(distance / 1000).toFixed(1)} km` : `${Math.round(distance)} m`}</li>)}</ol>}</div>;
}

function Directory({ records, language }: { records: BiotechCompanyDirectoryRecord[]; language: Language }) {
  const zh = language === 'zh';
  const [limit, setLimit] = useState(80);
  useEffect(() => setLimit(80), [records]);
  return <><h3>{zh ? '生技廠商企業清單' : 'Biotech Company Directory'}</h3><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['單位名稱', '產業範疇', '行政區', '登記地址', '公司電話', '統一編號', '地圖', '來源明細'] : ['Company name', 'Industry category', 'District', 'Registered address', 'Company phone', 'Unified business number', 'Map', 'Source details']).map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{records.slice(0, limit).map((record) => <tr key={record.id}><th>{record.companyName}</th><td>{labels(language)[record.industryCategoryType]}</td><td>{record.district ?? '—'}</td><td>{record.registeredAddress ?? '—'}</td><td>{record.companyPhoneDialHref ? <a href={record.companyPhoneDialHref}>{record.companyPhoneDisplay}</a> : record.companyPhoneDisplay ?? '—'}</td><td>{record.unifiedBusinessNumber ?? '—'}</td><td>{record.googleMapsQuery ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.googleMapsQuery)}`} target="_blank" rel="noreferrer">{zh ? '地圖' : 'Map'}</a> : '—'}</td><td><details><summary>{zh ? '來源明細' : 'Source details'}</summary><p>{zh ? '負責人' : 'Responsible person'}: {record.responsiblePerson ?? '—'}<br />{zh ? '道路' : 'Road'}: {record.roadName ?? '—'}<br />X/Y: {record.sourceXRaw ?? '—'} / {record.sourceYRaw ?? '—'}<br />{zh ? '座標系統' : 'Coordinate system'}: {record.coordinateSystem}<br />{zh ? '座標狀態' : 'Coordinate status'}: {record.coordinateStatus}<br />WGS84: {record.longitude?.toFixed(6) ?? '—'}, {record.latitude?.toFixed(6) ?? '—'}<br />{record.source} / {record.sourceAgency}<br />{disclaimer(zh)}</p></details></td></tr>)}</tbody></table></div>{!records.length && <p className="empty">{zh ? '沒有符合條件的紀錄。' : 'No records match these filters.'}</p>}{limit < records.length && <button className="load-more" onClick={() => setLimit(limit + 80)}>{zh ? '載入更多' : 'Load more'} · {records.length - limit}</button>}</>;
}

export default function BiotechCompanyDirectoryModule({ records, summary, language, related }: { records: BiotechCompanyDirectoryRecord[]; summary: BiotechCompanyDirectorySummary; language: Language; related?: { grants?: number; nangang?: number; companyChanges?: number; businessChanges?: number } }) {
  const zh = language === 'zh';
  const [view, setView] = useState<'overview' | 'map' | 'districts' | 'categories' | 'directory' | 'compare' | 'notes'>('overview');
  const [filters, setFilters] = useState(emptyFilters);
  const filtered = useMemo(() => filterBiotechCompanyDirectory(records, filters, language), [records, filters, language]);
  const active = useMemo(() => Object.values(filters).some(Boolean) ? buildBiotechCompanyDirectorySummary(filtered) : summary, [filtered, filters, summary]);
  const views = [['overview', zh ? '總覽' : 'Overview'], ['map', zh ? '地圖' : 'Map'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['categories', zh ? '產業範疇' : 'Industry Categories'], ['directory', zh ? '企業清單' : 'Company Directory'], ['compare', zh ? '與其他產業資料比較' : 'Compare Industry Records'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  return <><Filters records={records} filters={filters} setFilters={setFilters} language={language} /><section className="workspace"><div className="section-heading"><p>07 / INDUSTRY & COMPANY PUBLIC RECORDS</p><h2>{zh ? '生技廠商企業名錄' : 'Biotech Company Directory'}</h2><span>{zh ? '查詢臺北市生技廠商企業名錄，包含單位名稱、統一編號、登記地址、公司電話、產業範疇與來源座標，並依行政區與產業範疇呈現分布。' : 'Explore Taipei biotech company directory records, including company name, unified business number, registered address, company phone, industry category, and source coordinates, with district and industry-category distribution.'}</span></div><div className="subtabs">{views.map(([id, label]) => <button className={view === id ? 'active' : ''} onClick={() => setView(id)} key={id}>{label}</button>)}</div><div className="section-heading inline"><div><p>{zh ? '篩選結果' : 'Filtered records'}</p></div><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆' : 'records'}</span></strong></div>
    {view === 'overview' && <Overview summary={active} language={language} />}
    {view === 'map' && <><Nearby records={records} filters={filters} language={language} /><CompanyMap records={filtered} language={language} /></>}
    {view === 'districts' && <div className="chart-grid"><Bar title={zh ? '各行政區廠商數' : 'Companies by district'} rows={active.byDistrict.map((item) => ({ label: item.district, count: item.companyCount }))} /><Bar title={zh ? '各行政區有效座標數' : 'Valid coordinates by district'} rows={active.byDistrict.map((item) => ({ label: item.district, count: item.validCoordinateCount }))} /></div>}
    {view === 'categories' && <div className="chart-grid"><Bar title={zh ? '各產業範疇廠商數' : 'Companies by industry category'} rows={active.byIndustryCategory.map((item) => ({ label: labels(language)[item.industryCategoryType], count: item.count }))} /><Bar title={zh ? '廠商最多道路' : 'Top roads by company count'} rows={active.byRoadName.slice(0, 20).map((item) => ({ label: item.roadName, count: item.count }))} /></div>}
    {view === 'directory' && <Directory records={filtered} language={language} />}
    {view === 'compare' && <><div className="notice subtle">{zh ? '生技廠商企業名錄、南港軟體工業園區廠商資料、產業補助資料、公司異動與商業異動資料性質不同，不應合併解讀為同一產業清冊、即時營業狀態或公司推薦。' : 'The biotech company directory, Nangang Software Park companies, industry grants, company changes, and business changes have different meanings and should not be merged as one industry registry, real-time operating status, or company recommendation.'}</div><Bar title={zh ? '相關產業/企業資料紀錄數比較' : 'Related industry/company record counts'} rows={[{ label: zh ? '生技廠商' : 'Biotech companies', count: summary.totalRecords }, { label: zh ? '南港軟體園區廠商' : 'Nangang park companies', count: related?.nangang ?? 0 }, { label: zh ? '產業補助' : 'Industry grants', count: related?.grants ?? 0 }, { label: zh ? '公司異動' : 'Company changes', count: related?.companyChanges ?? 0 }, { label: zh ? '商業異動' : 'Business changes', count: related?.businessChanges ?? 0 }].filter((row) => row.count)} /></>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料內容' : 'Data contents'}</h3><p>{zh ? '生技廠商企業名錄提供臺北市生技相關廠商公開資料，欄位包含單位名稱、統一編號、負責人、登記地址、公司電話、產業範疇、位置X座標與位置Y座標。本網站將來源座標偵測為 TWD97 / EPSG:3826 格式並轉換為 WGS84 後顯示於地圖，同時依登記地址解析行政區與道路名稱。' : 'The biotech company directory provides Taipei public records for biotech-related companies. Fields include company name, unified business number, responsible person, registered address, company phone, industry category, source X coordinate, and source Y coordinate. This site detects TWD97 / EPSG:3826-style coordinates and converts them to WGS84 for map display.'}</p></article><article><h3>{zh ? '解讀限制' : 'Interpretation limits'}</h3><p>{disclaimer(zh)}</p></article><article><h3>{zh ? '資料來源' : 'Source'}</h3><p><a href="https://data.taipei/dataset/detail?id=a05ee8ee-d7f1-4024-86c1-e2f97f2120bf" target="_blank" rel="noreferrer">{zh ? '臺北市生技廠商企業名錄' : 'Taipei biotech company directory'} ↗</a></p></article></div>}
  </section></>;
}
