import { useEffect, useMemo, useState } from 'react';
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet';
import { DISTRICTS } from './lib/civicGroups';
import {
  buildBusinessPremisesPublicLiabilityInsuranceSummary,
  filterBusinessPremisesPublicLiabilityInsuranceRecords,
  haversineDistanceMeters,
  PUBLIC_LIABILITY_CATEGORY_LABELS_EN,
  PUBLIC_LIABILITY_CATEGORY_LABELS_ZH,
  PUBLIC_LIABILITY_EXPIRY_STATUS_LABELS_EN,
  PUBLIC_LIABILITY_EXPIRY_STATUS_LABELS_ZH,
} from './lib/businessPremisesPublicLiabilityInsurance';
import type { BusinessPremisesPublicLiabilityInsuranceFilters, BusinessPremisesPublicLiabilityInsuranceRecord, BusinessPremisesPublicLiabilityInsuranceSummary, Language, PublicLiabilityBusinessCategory, PublicLiabilityPolicyExpiryStatus } from './types';

const emptyFilters: BusinessPremisesPublicLiabilityInsuranceFilters = { search: '', businessCategory: '', district: '', roadName: '', policyExpiryStatus: '', policyExpiryYear: '', policyExpiryMonth: '', policyExpiryFrom: '', policyExpiryTo: '', hasRegistrationNumber: '', hasValidCoordinates: '', coordinateStatus: '' };
const categoryKeys = Object.keys(PUBLIC_LIABILITY_CATEGORY_LABELS_ZH) as PublicLiabilityBusinessCategory[];
const statusKeys = Object.keys(PUBLIC_LIABILITY_EXPIRY_STATUS_LABELS_ZH) as PublicLiabilityPolicyExpiryStatus[];
const fmt = (value?: number) => value === undefined ? '-' : value.toLocaleString();
const categoryLabels = (language: Language) => language === 'zh' ? PUBLIC_LIABILITY_CATEGORY_LABELS_ZH : PUBLIC_LIABILITY_CATEGORY_LABELS_EN;
const statusLabels = (language: Language) => language === 'zh' ? PUBLIC_LIABILITY_EXPIRY_STATUS_LABELS_ZH : PUBLIC_LIABILITY_EXPIRY_STATUS_LABELS_EN;
const notice = (zh: boolean) => zh ? '營業場所投保公共意外險清冊為臺北市公開資料中的公司／商業登記投保公共意外責任險資料，僅供查詢統一立案編號、類別、名稱、營業地址、保單到期日與來源座標等欄位使用，不代表即時營業狀態、保單即時有效狀態、完整保險內容、理賠資格、法規遵循判定、場所安全保證、風險評分、法律意見、保險建議或官方背書。實際投保狀態、保單內容、承保範圍、理賠條件、營業狀態與最新資料請以業者、保險公司、主管機關或官方公告為準。' : 'Business premises public liability insurance records are Taipei public-data records for company / business registration public accident liability insurance information. They are for looking up source fields such as registration number, category, name, business address, policy expiry date, and source coordinates only. They do not represent real-time operating status, real-time policy validity, complete insurance terms, claim eligibility, legal compliance determination, venue safety guarantee, risk scoring, legal advice, insurance advice, or official endorsement. Actual insurance status, policy terms, coverage scope, claim conditions, operating status, and latest information should be verified with the business, insurer, competent authority, or official announcements.';
const popupNotice = (zh: boolean) => zh ? '點位與到期狀態僅依來源資料呈現，不代表即時營業狀態、即時保單有效狀態、完整保險內容、理賠資格、場所安全保證或法規遵循判定。' : 'The point and expiry status are shown only from source data. They do not represent real-time operating status, real-time policy validity, complete insurance terms, claim eligibility, venue safety guarantee, or legal compliance determination.';
const nearbyNotice = (zh: boolean) => zh ? '附近功能僅依公開資料座標計算距離，不代表場所目前營業、保單目前有效、場所安全或法規遵循狀態。' : 'The nearby feature only calculates distance from public-data coordinates. It does not mean the business is currently operating, currently insured, safe, or legally compliant.';

function BarChart({ title, data }: { title: string; data: Array<{ label: string; value: number }> }) {
  const max = Math.max(...data.map((item) => item.value), 1);
  return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) =>
    <div className="bar-row wide-label" key={item.label}><span title={item.label}>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{fmt(item.value)}</b></div>)}</div></section>;
}

function Filters({ filters, setFilters, records, language }: { filters: BusinessPremisesPublicLiabilityInsuranceFilters; setFilters: (filters: BusinessPremisesPublicLiabilityInsuranceFilters) => void; records: BusinessPremisesPublicLiabilityInsuranceRecord[]; language: Language }) {
  const zh = language === 'zh', update = (key: keyof BusinessPremisesPublicLiabilityInsuranceFilters, value: string) => setFilters({ ...filters, [key]: value });
  const options = <T extends string>(values: Array<T | undefined>) => [...new Set(values.filter(Boolean) as T[])].sort((a, b) => a.localeCompare(b));
  const cats = categoryLabels(language), statuses = statusLabels(language);
  const yesNo = <><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '有' : 'Yes'}</option><option value="no">{zh ? '無' : 'No'}</option></>;
  return <aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(event) => update('search', event.target.value)} placeholder={zh ? '搜尋名稱、類別、統一立案編號、地址或保單到期日' : 'Search name, category, registration number, address, or policy expiry date'} /></label>
    <div className="filter-grid grant-filters">
      <label>{zh ? '類別' : 'Category'}<select value={filters.businessCategory} onChange={(event) => update('businessCategory', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{categoryKeys.map((key) => <option value={key} key={key}>{cats[key]}</option>)}</select></label>
      <label>{zh ? '行政區' : 'District'}<select value={filters.district} onChange={(event) => update('district', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{DISTRICTS.map((district) => <option key={district}>{district}</option>)}</select></label>
      <label>{zh ? '道路' : 'Road'}<select value={filters.roadName} onChange={(event) => update('roadName', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.roadName)).map((road) => <option key={road}>{road}</option>)}</select></label>
      <label>{zh ? '到期狀態' : 'Expiry status'}<select value={filters.policyExpiryStatus} onChange={(event) => update('policyExpiryStatus', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{statusKeys.map((key) => <option value={key} key={key}>{statuses[key]}</option>)}</select></label>
      <label>{zh ? '保單到期年度' : 'Policy expiry year'}<select value={filters.policyExpiryYear} onChange={(event) => update('policyExpiryYear', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.policyExpiryYear ? String(record.policyExpiryYear) : undefined)).map((year) => <option key={year}>{year}</option>)}</select></label>
      <label>{zh ? '保單到期月份' : 'Policy expiry month'}<select value={filters.policyExpiryMonth} onChange={(event) => update('policyExpiryMonth', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.policyExpiryMonthKey)).map((month) => <option key={month}>{month}</option>)}</select></label>
      <label>{zh ? '起始到期日' : 'Expiry from'}<input type="date" value={filters.policyExpiryFrom} onChange={(event) => update('policyExpiryFrom', event.target.value)} /></label>
      <label>{zh ? '結束到期日' : 'Expiry to'}<input type="date" value={filters.policyExpiryTo} onChange={(event) => update('policyExpiryTo', event.target.value)} /></label>
      <label>{zh ? '有統一立案編號' : 'Has registration number'}<select value={filters.hasRegistrationNumber} onChange={(event) => update('hasRegistrationNumber', event.target.value)}>{yesNo}</select></label>
      <label>{zh ? '有有效座標' : 'Has valid coordinates'}<select value={filters.hasValidCoordinates} onChange={(event) => update('hasValidCoordinates', event.target.value)}>{yesNo}</select></label>
      <label>{zh ? '座標狀態' : 'Coordinate status'}<select value={filters.coordinateStatus} onChange={(event) => update('coordinateStatus', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{['valid', 'missing', 'outlier', 'unparsed'].map((status) => <option key={status}>{status}</option>)}</select></label>
    </div>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => setFilters(emptyFilters)}>{zh ? '清除篩選' : 'Clear filters'}</button>}</aside>;
}

function Overview({ summary, language }: { summary: BusinessPremisesPublicLiabilityInsuranceSummary; language: Language }) {
  const zh = language === 'zh', cats = categoryLabels(language), statuses = statusLabels(language);
  const statusCount = (status: PublicLiabilityPolicyExpiryStatus) => summary.byPolicyExpiryStatus.find((item) => item.policyExpiryStatus === status)?.count ?? 0;
  return <><div className="notice subtle">{zh ? '此圖僅整理營業場所投保公共意外險清冊公開資料中的類別、名稱、地址、保單到期日與座標，不代表即時營業狀態、保單即時有效狀態、完整保險內容、理賠資格、法規遵循判定、場所安全保證、法律意見或保險建議。' : 'This chart only organizes category, name, address, policy expiry date, and coordinates from business premises public liability insurance public records. It does not represent real-time operating status, real-time policy validity, complete insurance terms, claim eligibility, legal compliance determination, venue safety guarantee, legal advice, or insurance advice.'}</div>
    <div className="summary-grid">{[
      [zh ? '清冊紀錄數' : 'Record count', summary.totalRecords],
      [zh ? '不重複營業場所數' : 'Unique business count', summary.uniqueBusinessNameCount],
      [zh ? '涵蓋行政區數' : 'Districts covered', summary.districtCount],
      [zh ? '有效座標數' : 'Valid coordinate count', summary.recordsWithValidCoordinates],
      [zh ? '有統一立案編號紀錄' : 'Records with registration number', summary.recordsWithRegistrationNumber],
      [zh ? '有保單到期日紀錄' : 'Records with policy expiry date', summary.recordsWithPolicyExpiryDate],
      [zh ? '最早保單到期日' : 'Earliest policy expiry date', summary.minPolicyExpiryDate ?? '-'],
      [zh ? '最晚保單到期日' : 'Latest policy expiry date', summary.maxPolicyExpiryDate ?? '-'],
      [zh ? '30日內到期紀錄' : 'Expiring within 30 days', statusCount('expiring_soon_30_days')],
      [zh ? '90日內到期紀錄' : 'Expiring within 90 days', statusCount('expiring_soon_90_days')],
      [zh ? '依來源到期日已逾期紀錄' : 'Expired by source date', statusCount('expired_by_source_date')],
      [zh ? '紀錄最多行政區' : 'Top district by record count', summary.byDistrict[0]?.district ?? '-'],
      [zh ? '紀錄最多類別' : 'Top category by record count', summary.byBusinessCategory[0] ? cats[summary.byBusinessCategory[0].businessCategory] : '-'],
    ].map(([label, value]) => <article key={label}><span>{label}</span><strong>{typeof value === 'number' ? fmt(value) : value}</strong></article>)}</div>
    <div className="chart-grid"><BarChart title={zh ? '各行政區公共意外險清冊紀錄數' : 'Insurance records by district'} data={summary.byDistrict.map((item) => ({ label: item.district, value: item.recordCount }))} /><BarChart title={zh ? '各類別公共意外險清冊紀錄數' : 'Insurance records by category'} data={summary.byBusinessCategory.map((item) => ({ label: cats[item.businessCategory], value: item.count }))} /><BarChart title={zh ? '保單到期狀態分布' : 'Policy expiry status distribution'} data={summary.byPolicyExpiryStatus.map((item) => ({ label: statuses[item.policyExpiryStatus], value: item.count }))} /><BarChart title={zh ? '保單到期月份分布' : 'Policy expiry month distribution'} data={summary.byPolicyExpiryMonth.map((item) => ({ label: item.monthKey, value: item.count }))} /><BarChart title={zh ? '座標有無' : 'Coordinate availability'} data={Object.entries(summary.coordinateQuality).map(([label, value]) => ({ label, value }))} /><BarChart title={zh ? '道路紀錄數' : 'Records by road'} data={summary.byRoadName.slice(0, 30).map((item) => ({ label: item.roadName, value: item.count }))} /></div></>;
}

function InsuranceMap({ records, language }: { records: BusinessPremisesPublicLiabilityInsuranceRecord[]; language: Language }) {
  const zh = language === 'zh', cats = categoryLabels(language), statuses = statusLabels(language), points = records.filter((record) => record.coordinateStatus === 'valid' && record.latitude !== undefined && record.longitude !== undefined).slice(0, 1200);
  return <div className="map-wrap"><div className="notice">{popupNotice(zh)}</div><MapContainer center={[25.072, 121.54]} zoom={11} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap contributors &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" />{points.map((record) => <CircleMarker key={record.id} center={[record.latitude!, record.longitude!]} radius={5} pathOptions={{ fillColor: record.policyExpiryStatus === 'expired_by_source_date' ? '#b85c38' : '#2f7f90', fillOpacity: .7, color: '#fff7e8', weight: 1 }}><Popup><div className="map-popup"><strong>{record.businessName}</strong><p>{zh ? '類別' : 'Category'}: {cats[record.businessCategory]}</p><p>{zh ? '營業地址' : 'Business address'}: {record.businessAddress ?? '-'}</p><p>{zh ? '保單到期日' : 'Policy expiry date'}: {record.policyExpiryDate ?? record.policyExpiryDateRaw ?? '-'}</p><p>{zh ? '到期狀態' : 'Expiry status'}: {statuses[record.policyExpiryStatus]}</p><p>{zh ? '資料來源' : 'Source'}: {record.source}</p><small>{popupNotice(zh)}</small></div></Popup></CircleMarker>)}</MapContainer></div>;
}

function Directory({ records, language }: { records: BusinessPremisesPublicLiabilityInsuranceRecord[]; language: Language }) {
  const zh = language === 'zh', cats = categoryLabels(language), statuses = statusLabels(language);
  const [limit, setLimit] = useState(80);
  useEffect(() => setLimit(80), [records]);
  return <><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['名稱', '類別', '行政區', '營業地址', '保單到期日', '到期狀態', '統一立案編號', '地圖', '來源明細'] : ['Name', 'Category', 'District', 'Business address', 'Policy expiry date', 'Expiry status', 'Registration number', 'Map', 'Source details']).map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{records.slice(0, limit).map((record) => <tr key={record.id}><th>{record.businessName}</th><td>{cats[record.businessCategory]}</td><td>{record.district ?? '-'}</td><td>{record.businessAddress ?? '-'}</td><td>{record.policyExpiryDate ?? record.policyExpiryDateRaw ?? '-'}</td><td>{statuses[record.policyExpiryStatus]}</td><td>{record.registrationNumber ?? '-'}</td><td>{record.hasCoordinates ? <a href={`https://www.google.com/maps/search/?api=1&query=${record.latitude},${record.longitude}`} target="_blank" rel="noreferrer">{zh ? '地圖' : 'Map'}</a> : '-'}</td><td><details><summary>{zh ? '來源明細' : 'Source details'}</summary><dl><div><dt>{zh ? '序號' : 'Sequence number'}</dt><dd>{record.sourceSequenceNumber ?? '-'}</dd></div><div><dt>{zh ? '原始類別' : 'Raw category'}</dt><dd>{record.businessCategoryRaw ?? '-'}</dd></div><div><dt>{zh ? '標準化名稱' : 'Normalized name'}</dt><dd>{record.businessNameNormalized ?? '-'}</dd></div><div><dt>{zh ? '標準化地址' : 'Normalized address'}</dt><dd>{record.businessAddressNormalized ?? '-'}</dd></div><div><dt>{zh ? '道路' : 'Road'}</dt><dd>{record.roadName ?? '-'}</dd></div><div><dt>{zh ? '來源經度' : 'Source longitude'}</dt><dd>{record.sourceLongitudeRaw ?? '-'}</dd></div><div><dt>{zh ? '來源緯度' : 'Source latitude'}</dt><dd>{record.sourceLatitudeRaw ?? '-'}</dd></div><div><dt>{zh ? '座標狀態' : 'Coordinate status'}</dt><dd>{record.coordinateStatus}</dd></div><div><dt>{zh ? '座標系統' : 'Coordinate system'}</dt><dd>{record.coordinateSystem}</dd></div><div><dt>{zh ? '資料來源' : 'Source'}</dt><dd>{record.source}</dd></div><div><dt>{zh ? '來源機關' : 'Source agency'}</dt><dd>{record.sourceAgency}</dd></div><div><dt>{zh ? '解讀限制' : 'Disclaimer'}</dt><dd>{notice(zh)}</dd></div></dl></details></td></tr>)}</tbody></table></div>{!records.length && <p className="empty">{zh ? '沒有符合條件的紀錄。' : 'No records match these filters.'}</p>}{limit < records.length && <button className="load-more" onClick={() => setLimit(limit + 80)}>{zh ? '載入更多' : 'Load more'} · {records.length - limit}</button>}</>;
}

export default function BusinessPremisesPublicLiabilityInsuranceModule({ records, summary, language }: { records: BusinessPremisesPublicLiabilityInsuranceRecord[]; summary: BusinessPremisesPublicLiabilityInsuranceSummary; language: Language }) {
  const zh = language === 'zh';
  const [view, setView] = useState<'overview' | 'map' | 'districts' | 'categories' | 'expiry' | 'directory' | 'notes'>('overview');
  const [filters, setFilters] = useState(emptyFilters);
  const [nearby, setNearby] = useState<Array<{ record: BusinessPremisesPublicLiabilityInsuranceRecord; distance: number }>>([]);
  const [nearbyError, setNearbyError] = useState('');
  const filtered = useMemo(() => filterBusinessPremisesPublicLiabilityInsuranceRecords(records, filters, language), [records, filters, language]);
  const activeSummary = useMemo(() => Object.values(filters).some(Boolean) ? buildBusinessPremisesPublicLiabilityInsuranceSummary(filtered) : summary, [filtered, filters, summary]);
  const findNearby = () => {
    setNearbyError('');
    navigator.geolocation.getCurrentPosition(({ coords }) => {
      const origin = { latitude: coords.latitude, longitude: coords.longitude };
      setNearby(filtered.filter((record) => record.coordinateStatus === 'valid' && record.latitude !== undefined && record.longitude !== undefined)
        .map((record) => ({ record, distance: haversineDistanceMeters(origin, { latitude: record.latitude!, longitude: record.longitude! }) }))
        .sort((a, b) => a.distance - b.distance).slice(0, 10));
    }, () => setNearbyError(zh ? '無法取得目前位置。' : 'Could not get current location.'));
  };
  const views = [['overview', zh ? '總覽' : 'Overview'], ['map', zh ? '地圖' : 'Map'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['categories', zh ? '類別' : 'Categories'], ['expiry', zh ? '保單到期日' : 'Policy Expiry Dates'], ['directory', zh ? '清冊' : 'Directory'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  const cats = categoryLabels(language), statuses = statusLabels(language);
  return <><Filters filters={filters} setFilters={setFilters} records={records} language={language} /><section className="workspace"><div className="section-heading"><p>05 / BUSINESS REGISTRATION & PUBLIC LIABILITY INSURANCE RECORDS</p><h2>{zh ? '營業場所投保公共意外險清冊' : 'Business Premises Public Liability Insurance Records'}</h2><span>{zh ? '查詢臺北市營業場所投保公共意外責任險公開清冊，包含統一立案編號、類別、名稱、營業地址、保單到期日與來源座標。' : 'Explore Taipei public records for business premises public accident liability insurance, including registration number, category, name, business address, policy expiry date, and source coordinates.'}</span></div><div className="subtabs">{views.map(([id, label]) => <button className={view === id ? 'active' : ''} onClick={() => setView(id)} key={id}>{label}</button>)}</div><div className="notice subtle">{notice(zh)}</div>
    <div className="notice subtle"><button className="text-button" onClick={findNearby}>{zh ? '找附近公共意外險清冊場所' : 'Find nearby public-liability insurance records'}</button><p>{nearbyNotice(zh)}</p>{nearbyError && <p>{nearbyError}</p>}{nearby.length > 0 && <ol>{nearby.map(({ record, distance }) => <li key={record.id}>{record.businessName} · {distance >= 1000 ? `${(distance / 1000).toFixed(1)} km` : `${Math.round(distance)} m`}</li>)}</ol>}</div>
    {view === 'overview' && <Overview summary={activeSummary} language={language} />}{view === 'map' && <InsuranceMap records={filtered} language={language} />}{view === 'districts' && <div className="chart-grid"><BarChart title={zh ? '各行政區公共意外險清冊紀錄數' : 'Insurance records by district'} data={activeSummary.byDistrict.map((item) => ({ label: item.district, value: item.recordCount }))} /><BarChart title={zh ? '各行政區已逾期紀錄' : 'Expired records by district'} data={activeSummary.byDistrict.map((item) => ({ label: item.district, value: item.expiredBySourceDateCount }))} /></div>}{view === 'categories' && <div className="chart-grid"><BarChart title={zh ? '各類別公共意外險清冊紀錄數' : 'Insurance records by category'} data={activeSummary.byBusinessCategory.map((item) => ({ label: cats[item.businessCategory], value: item.count }))} /></div>}{view === 'expiry' && <div className="chart-grid"><BarChart title={zh ? '保單到期狀態分布' : 'Policy expiry status distribution'} data={activeSummary.byPolicyExpiryStatus.map((item) => ({ label: statuses[item.policyExpiryStatus], value: item.count }))} /><BarChart title={zh ? '保單到期月份分布' : 'Policy expiry month distribution'} data={activeSummary.byPolicyExpiryMonth.map((item) => ({ label: item.monthKey, value: item.count }))} /></div>}{view === 'directory' && <><div className="section-heading inline"><div><h3>{zh ? '公共意外險清冊' : 'Public Liability Insurance Directory'}</h3></div><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆符合紀錄' : 'matching records'}</span></strong></div><Directory records={filtered} language={language} /></>}{view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料內容' : 'Data contents'}</h3><p>{zh ? '營業場所投保公共意外險清冊提供臺北市公司／商業登記投保公共意外責任險公開資料，欄位包含序號、統一立案編號、類別、名稱、營業地址、保單到期日、經度與緯度。本網站依來源座標顯示點位，並依營業地址解析行政區與道路名稱，供資料查詢與統計整理。' : 'Business premises public liability insurance records provide Taipei public-data records for company / business registration public accident liability insurance information. Fields include sequence number, registration number, category, name, business address, policy expiry date, longitude, and latitude. This site displays source-coordinate points and parses business addresses into district and road name for lookup and statistical organization.'}</p></article><article><h3>{zh ? '解讀限制' : 'Interpretation limits'}</h3><p>{notice(zh)}</p></article><article><h3>{zh ? '到期狀態' : 'Expiry status'}</h3><p>{zh ? '到期狀態僅依來源資料中的保單到期日與資料建置日期計算，不代表即時投保狀態、法規遵循判定或保險公司承保確認。' : 'Expiry status is calculated only from the policy expiry date in the source data and the data build date. It does not represent real-time insurance status, legal compliance determination, or insurer confirmation of coverage.'}</p></article><article><h3>{zh ? '資料來源' : 'Source'}</h3><p><a href="https://data.taipei/dataset/detail?id=5880bb98-ab6a-476c-ae55-37564b0d0fc9" target="_blank" rel="noreferrer">{zh ? '臺北市營業場所投保公共意外險清冊' : 'Taipei Business Premises Public Liability Insurance Records'} ↗</a></p></article></div>}</section></>;
}
