import { useEffect, useMemo, useState } from 'react';

type RecordItem = {
  id: string; institutionName: string; programmeName: string; phoneRaw: string; phone: string; address: string; districtName: string;
  serviceAreaRaw: string; serviceAreas: string[]; hasPhone: boolean; hasAddress: boolean; hasProgramme: boolean; hasServiceArea: boolean;
  externalMapQuery: string; sourceValues: Record<string, string>;
};
type SortKey = 'institutionName' | 'programmeName' | 'districtName' | 'serviceAreaRaw';
type View = 'find' | 'sites' | 'programmes' | 'areas' | 'districts' | 'contact' | 'quality' | 'notes';
const pageSize = 12;

const text = (zh: boolean, chinese: string, english: string) => zh ? chinese : english;
const normalize = (value: string) => value.toLocaleLowerCase().trim();
const countBy = (items: string[]) => Object.entries(items.filter(Boolean).reduce<Record<string, number>>((all, item) => ({ ...all, [item]: (all[item] ?? 0) + 1 }), {})).map(([label, value]) => ({ label, value })).sort((a, b) => b.value - a.value || a.label.localeCompare(b.label, 'zh-Hant'));
const BarChart = ({ title, data }: { title: string; data: Array<{ label: string; value: number }> }) => {
  const max = Math.max(...data.map((item) => item.value), 1);
  return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) => <div className="bar-row wide-label" key={item.label}><span>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{item.value.toLocaleString()}</b></div>)}</div></section>;
};

export default function ChildYouthFriendlyWelfareServiceSitesModule({ language }: { language: 'zh' | 'en' }) {
  const zh = language === 'zh';
  const [records, setRecords] = useState<RecordItem[]>([]); const [report, setReport] = useState<Record<string, number> | null>(null);
  const [view, setView] = useState<View>('find'); const [keyword, setKeyword] = useState(''); const [district, setDistrict] = useState('');
  const [serviceArea, setServiceArea] = useState(''); const [programme, setProgramme] = useState(''); const [institution, setInstitution] = useState('');
  const [hasPhone, setHasPhone] = useState(''); const [sort, setSort] = useState<SortKey>('institutionName'); const [page, setPage] = useState(1);
  const [visibleColumns, setVisibleColumns] = useState<Record<string, boolean>>({ district: true, address: true, area: true, phone: true });
  const [expanded, setExpanded] = useState<string | null>(null);
  useEffect(() => { const load = async () => {
    const [items, conversion] = await Promise.all([
      fetch(`${import.meta.env.BASE_URL}data/child-youth-friendly-welfare-service-sites/records.json`).then((response) => response.json()),
      fetch(`${import.meta.env.BASE_URL}data/conversion-report.json`).then((response) => response.ok ? response.json() : {}),
    ]); setRecords(items); setReport((conversion as { childYouthFriendlyWelfareServiceSites?: Record<string, number> }).childYouthFriendlyWelfareServiceSites ?? null);
  }; load().catch(() => setRecords([])); }, []);
  const districts = useMemo(() => [...new Set(records.map((record) => record.districtName).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'zh-Hant')), [records]);
  const areas = useMemo(() => [...new Set(records.map((record) => record.serviceAreaRaw).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'zh-Hant')), [records]);
  const programmes = useMemo(() => [...new Set(records.map((record) => record.programmeName).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'zh-Hant')), [records]);
  const institutions = useMemo(() => [...new Set(records.map((record) => record.institutionName).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'zh-Hant')), [records]);
  const filtered = useMemo(() => records.filter((record) => {
    const searchable = [record.institutionName, record.programmeName, record.serviceAreaRaw, record.districtName, record.address, record.phone].join(' ');
    return (!keyword || normalize(searchable).includes(normalize(keyword))) && (!district || record.districtName === district) && (!serviceArea || record.serviceAreaRaw === serviceArea)
      && (!programme || record.programmeName === programme) && (!institution || record.institutionName === institution) && (!hasPhone || (hasPhone === 'yes' ? record.hasPhone : !record.hasPhone));
  }).sort((a, b) => a[sort].localeCompare(b[sort], 'zh-Hant')), [records, keyword, district, serviceArea, programme, institution, hasPhone, sort]);
  useEffect(() => setPage(1), [keyword, district, serviceArea, programme, institution, hasPhone, sort]);
  const metrics = useMemo(() => ({
    total: filtered.length, institutions: new Set(filtered.map((record) => record.institutionName)).size, programmes: new Set(filtered.map((record) => record.programmeName)).size,
    districts: new Set(filtered.map((record) => record.districtName).filter(Boolean)).size, areas: new Set(filtered.map((record) => record.serviceAreaRaw).filter(Boolean)).size,
    phone: filtered.filter((record) => record.hasPhone).length, address: filtered.filter((record) => record.hasAddress).length,
    complete: filtered.filter((record) => record.institutionName && record.programmeName && record.phoneRaw && record.address && record.serviceAreaRaw).length,
    byDistrict: countBy(filtered.map((record) => record.districtName)), byProgramme: countBy(filtered.map((record) => record.programmeName)), byArea: countBy(filtered.map((record) => record.serviceAreaRaw)),
  }), [filtered]);
  const currentPage = filtered.slice((page - 1) * pageSize, page * pageSize); const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize));
  const clear = () => { setKeyword(''); setDistrict(''); setServiceArea(''); setProgramme(''); setInstitution(''); setHasPhone(''); };
  const copy = async (value: string) => { if (value && navigator.clipboard) await navigator.clipboard.writeText(value); };
  const exportCsv = () => {
    const headings = ['institutionName', 'programmeName', 'districtName', 'address', 'serviceAreaRaw', 'phone'];
    const csv = [headings, ...filtered.map((record) => headings.map((key) => String(record[key as keyof RecordItem] ?? '').replaceAll('"', '""')))].map((row) => row.map((value) => `"${value}"`).join(',')).join('\n');
    const url = URL.createObjectURL(new Blob(['\uFEFF', csv], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'child-youth-friendly-welfare-service-sites-filtered.csv'; link.click(); URL.revokeObjectURL(url);
  };
  const tabs: Array<[View, string]> = [['find', text(zh, '尋找服務', 'Find a Service')], ['sites', text(zh, '服務據點', 'Service Sites')], ['programmes', text(zh, '服務方案', 'Programmes')], ['areas', text(zh, '服務區域', 'Service Areas')], ['districts', text(zh, '行政區分布', 'District Distribution')], ['contact', text(zh, '聯絡資訊', 'Contact Information')], ['quality', text(zh, '資料品質', 'Data Quality')], ['notes', text(zh, '資料說明', 'Data Notes')]];
  const disclaimer = text(zh, '本資料為臺北市兒少友善福利服務據點公開名冊，僅供查詢機構、方案、電話、地址及來源記載的服務區域。資料不代表即時服務、資格、名額、預約、轉介、個案或緊急應變資訊；請向機構或臺北市政府社會局確認。', 'This dataset is for reference when locating child and youth welfare services and community-support resources. Source records do not establish current operation, availability, eligibility, capacity, appointments, referrals, or individual case information. Confirm current information with the organization or Taipei City Department of Social Welfare.');

  return <section className="workspace"><div className="section-heading"><p>CHILD WELFARE / YOUTH SERVICES / COMMUNITY SUPPORT</p><h2>{text(zh, '兒少友善福利服務據點', 'Child and Youth Friendly Welfare Service Sites')}</h2><span>{text(zh, '以來源記載的機構、方案、服務區域與聯絡方式協助查找；不建立精確地圖標記。', 'Find source-recorded institutions, programmes, service areas, and contact information; no exact map markers are created.')}</span></div>
    <div className="subtabs">{tabs.map(([id, label]) => <button className={view === id ? 'active' : ''} key={id} onClick={() => setView(id)}>{label}</button>)}</div>
    <aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder={text(zh, '搜尋機構、方案、服務區域、行政區、地址或電話', 'Search institution, programme, service area, district, address, or telephone')} /></label><div className="filter-grid">
      {[[text(zh, '行政區', 'District'), district, setDistrict, districts], [text(zh, '服務區域', 'Service area'), serviceArea, setServiceArea, areas], [text(zh, '服務方案', 'Programme'), programme, setProgramme, programmes], [text(zh, '機構', 'Institution'), institution, setInstitution, institutions]].map(([label, value, setter, values]) => <label key={String(label)}>{String(label)}<select value={String(value)} onChange={(event) => (setter as (value: string) => void)(event.target.value)}><option value="">{text(zh, '全部', 'All')}</option>{(values as string[]).map((item) => <option key={item} value={item}>{item}</option>)}</select></label>)}
      <label>{text(zh, '有電話', 'Has telephone')}<select value={hasPhone} onChange={(event) => setHasPhone(event.target.value)}><option value="">{text(zh, '全部', 'All')}</option><option value="yes">{text(zh, '有', 'Yes')}</option><option value="no">{text(zh, '無', 'No')}</option></select></label></div>{(keyword || district || serviceArea || programme || institution || hasPhone) && <button className="text-button" onClick={clear}>{text(zh, '清除篩選', 'Clear filters')}</button>}</aside>
    {view === 'find' && <><div className="notice subtle">{disclaimer}</div><div className="summary-grid">{[[text(zh, '來源紀錄', 'Source records'), metrics.total], [text(zh, '不重複機構', 'Unique institutions'), metrics.institutions], [text(zh, '不重複方案', 'Unique programmes'), metrics.programmes], [text(zh, '服務據點行政區', 'Site districts'), metrics.districts], [text(zh, '來源服務區域', 'Source service areas'), metrics.areas], [text(zh, '有電話紀錄', 'Records with telephone'), metrics.phone], [text(zh, '有地址紀錄', 'Records with address'), metrics.address], [text(zh, '核心欄位完整', 'Complete core fields'), metrics.complete]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="chart-grid"><BarChart title={text(zh, '各行政區服務據點數', 'Service sites by district')} data={metrics.byDistrict} /><BarChart title={text(zh, '電話欄位完整度', 'Records with and without telephone')} data={[{ label: text(zh, '有電話', 'With telephone'), value: metrics.phone }, { label: text(zh, '無電話', 'Without telephone'), value: metrics.total - metrics.phone }]} /></div></>}
    {view === 'sites' && <><div className="table-actions"><label>{text(zh, '排序', 'Sort')}<select value={sort} onChange={(event) => setSort(event.target.value as SortKey)}><option value="institutionName">{text(zh, '機構名稱', 'Institution')}</option><option value="programmeName">{text(zh, '方案名稱', 'Programme')}</option><option value="districtName">{text(zh, '行政區', 'District')}</option><option value="serviceAreaRaw">{text(zh, '服務區域', 'Service area')}</option></select></label><button onClick={exportCsv}>{text(zh, '匯出篩選結果 CSV', 'Export filtered CSV')}</button>{Object.entries(visibleColumns).map(([key, shown]) => <label key={key}><input type="checkbox" checked={shown} onChange={() => setVisibleColumns({ ...visibleColumns, [key]: !shown })} />{text(zh, key === 'area' ? '服務區域' : key === 'district' ? '行政區' : key === 'address' ? '地址' : '電話', key)}</label>)}</div><div className="comparison-scroll procurement-table"><table><thead><tr><th>{text(zh, '機構', 'Institution')}</th><th>{text(zh, '方案', 'Programme')}</th>{visibleColumns.district && <th>{text(zh, '據點行政區', 'Site district')}</th>}{visibleColumns.address && <th>{text(zh, '地址', 'Address')}</th>}{visibleColumns.area && <th>{text(zh, '來源服務區域', 'Service area')}</th>}{visibleColumns.phone && <th>{text(zh, '電話', 'Telephone')}</th>}<th>{text(zh, '操作', 'Actions')}</th></tr></thead><tbody>{currentPage.map((record) => <><tr key={record.id}><th>{record.institutionName || '-'}</th><td>{record.programmeName || '-'}</td>{visibleColumns.district && <td>{record.districtName || '-'}</td>}{visibleColumns.address && <td>{record.address || '-'}</td>}{visibleColumns.area && <td>{record.serviceAreaRaw || '-'}</td>}{visibleColumns.phone && <td>{record.phone ? <a href={`tel:${record.phone.replace(/[^+\d]/g, '')}`}>{record.phone}</a> : '-'}</td>}<td><button onClick={() => setExpanded(expanded === record.id ? null : record.id)}>{text(zh, '來源詳情', 'Source details')}</button>{record.address && <button onClick={() => copy(record.address)}>{text(zh, '複製地址', 'Copy address')}</button>}{record.phone && <button onClick={() => copy(record.phone)}>{text(zh, '複製電話', 'Copy phone')}</button>}{record.externalMapQuery && <a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.externalMapQuery)}`}>{text(zh, '地圖查詢', 'Map lookup')}</a>}</td></tr>{expanded === record.id && <tr key={`${record.id}-raw`}><td colSpan={7}><details open><summary>{text(zh, '原始來源欄位', 'Raw source fields')}</summary><pre>{JSON.stringify(record.sourceValues, null, 2)}</pre></details></td></tr>}</>)}</tbody></table>{!currentPage.length && <p className="empty">{text(zh, '沒有符合篩選條件的紀錄。', 'No records match these filters.')}</p>}</div><div className="pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>{text(zh, '上一頁', 'Previous')}</button><span>{page} / {pageCount}</span><button disabled={page === pageCount} onClick={() => setPage(page + 1)}>{text(zh, '下一頁', 'Next')}</button></div></>}
    {view === 'programmes' && <BarChart title={text(zh, '方案紀錄數', 'Programme records')} data={metrics.byProgramme.slice(0, 20)} />}
    {view === 'areas' && <><div className="notice">{text(zh, '服務區域為來源記載文字，不代表資格邊界、服務保證或排除規則。', 'Service areas are source-recorded text. They do not establish eligibility boundaries, service guarantees, or exclusion rules.')}</div><BarChart title={text(zh, '來源服務區域紀錄數', 'Records by source-recorded service area')} data={metrics.byArea.slice(0, 20)} /></>}
    {view === 'districts' && <><div className="notice">{text(zh, '行政區是由來源地址可明確辨識時取得的實體據點行政區，與來源記載的服務區域不同。', 'Districts represent physical site locations derived only when the source address is clear; they differ from source-recorded service areas.')}</div><BarChart title={text(zh, '各行政區服務據點數', 'Service sites by district')} data={metrics.byDistrict} /></>}
    {view === 'contact' && <BarChart title={text(zh, '電話欄位完整度', 'Telephone completeness')} data={[{ label: text(zh, '有電話', 'With telephone'), value: metrics.phone }, { label: text(zh, '無電話', 'Without telephone'), value: metrics.total - metrics.phone }]} />}
    {view === 'quality' && <div className="notes-grid"><article><h3>{text(zh, '欄位完整度', 'Field completeness')}</h3><p>{text(zh, `目前篩選結果共有 ${metrics.complete} 筆核心欄位完整紀錄；${metrics.total - metrics.complete} 筆至少缺少一項核心欄位。`, `${metrics.complete} filtered records have complete core fields; ${metrics.total - metrics.complete} records miss at least one core field.`)}</p></article><article><h3>{text(zh, '轉換檢查', 'Conversion checks')}</h3><p>{report ? `${text(zh, '未解析行政區', 'Unresolved districts')}: ${report.unresolvedDistrict ?? 0}；${text(zh, '精確重複列', 'Exact duplicate rows')}: ${report.exactDuplicatesRemoved ?? 0}；${text(zh, '疑似同方案多地址', 'Same programme, multiple addresses')}: ${report.sameInstitutionAndProgrammeMultipleAddresses ?? 0}` : text(zh, '轉換報告載入中。', 'Loading conversion report.')}</p></article></div>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{text(zh, '資料使用說明', 'Data notes')}</h3><p>{disclaimer}</p></article><article><h3>{text(zh, '兒少安全與隱私', 'Child safety and privacy')}</h3><p>{text(zh, '本模組只呈現官方公開的機構層級欄位，不收集或推論兒少、家庭、個案、診斷、學校紀錄、安置原因或法律身分資訊。', 'This module displays only official public institution-level fields. It does not collect or infer child, family, case, diagnosis, school-record, placement-reason, or legal-status information.')}</p></article></div>}
  </section>;
}
