import { useEffect, useMemo, useState } from 'react';
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet';
import { DISTRICTS, TAIPEI_DISTRICT_CENTROIDS } from './lib/civicGroups';
import { buildChildMedicalSubsidyContractedProviderSummary, filterChildMedicalSubsidyContractedProviders } from './lib/childMedicalSubsidyContractedProviders';
import type { ChildMedicalSubsidyContractedProviderFilters, ChildMedicalSubsidyContractedProviderRecord, ChildMedicalSubsidyContractedProviderSummary, ContractedVaccinationMedicalProviderSummary, Language, PubliclyFundedHpvVaccinationProviderSummary, TelepsychologyCounselingInstitutionSummary } from './types';

const emptyFilters: ChildMedicalSubsidyContractedProviderFilters = { search: '', administrativeArea: '', taipeiDistrict: '', outsideTaipeiArea: '', isTaipeiDistrict: '', roadName: '', hasPhone: '', phoneType: '', districtMismatch: '', duplicateProviderCode: '' };
const fmt = (value?: number) => value === undefined ? '-' : value.toLocaleString();

function BarChart({ title, data }: { title: string; data: Array<{ label: string; value: number }> }) {
  const max = Math.max(...data.map((item) => item.value), 1);
  return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) =>
    <div className="bar-row wide-label" key={item.label}><span title={item.label}>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{fmt(item.value)}</b></div>)}</div></section>;
}

function Filters({ filters, setFilters, records, language }: { filters: ChildMedicalSubsidyContractedProviderFilters; setFilters: (filters: ChildMedicalSubsidyContractedProviderFilters) => void; records: ChildMedicalSubsidyContractedProviderRecord[]; language: Language }) {
  const zh = language === 'zh', update = (key: keyof ChildMedicalSubsidyContractedProviderFilters, value: string) => setFilters({ ...filters, [key]: value });
  const options = <T extends string>(values: Array<T | undefined>) => [...new Set(values.filter(Boolean) as T[])].sort((a, b) => a.localeCompare(b));
  return <aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(event) => update('search', event.target.value)} placeholder={zh ? '搜尋診所名稱、院所代碼、行政區、地址或電話' : 'Search clinic name, provider code, administrative area, address, or phone'} /></label>
    <div className="filter-grid grant-filters">
      <label>{zh ? '行政區' : 'Administrative area'}<select value={filters.administrativeArea} onChange={(event) => update('administrativeArea', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.areaDisplayName)).map((area) => <option key={area}>{area}</option>)}</select></label>
      <label>{zh ? '臺北市行政區' : 'Taipei district'}<select value={filters.taipeiDistrict} onChange={(event) => update('taipeiDistrict', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{DISTRICTS.map((district) => <option key={district}>{district}</option>)}</select></label>
      <label>{zh ? '外縣市或非臺北地區' : 'Outside-Taipei area'}<select value={filters.outsideTaipeiArea} onChange={(event) => update('outsideTaipeiArea', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.outsideTaipeiArea)).map((area) => <option key={area}>{area}</option>)}</select></label>
      <label>{zh ? '是否為臺北市行政區' : 'Is Taipei district'}<select value={filters.isTaipeiDistrict} onChange={(event) => update('isTaipeiDistrict', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>
      <label>{zh ? '道路' : 'Road'}<select value={filters.roadName} onChange={(event) => update('roadName', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.roadName)).map((road) => <option key={road}>{road}</option>)}</select></label>
      <label>{zh ? '有電話' : 'Has phone'}<select value={filters.hasPhone} onChange={(event) => update('hasPhone', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '有' : 'Yes'}</option><option value="no">{zh ? '無' : 'No'}</option></select></label>
      <label>{zh ? '電話類型' : 'Phone type'}<select value={filters.phoneType} onChange={(event) => update('phoneType', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.phoneType)).map((type) => <option key={type}>{type}</option>)}</select></label>
      <label>{zh ? '行政區與地址不一致' : 'Area / address mismatch'}<select value={filters.districtMismatch} onChange={(event) => update('districtMismatch', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>
      <label>{zh ? '院所代碼重複' : 'Duplicate provider code'}<select value={filters.duplicateProviderCode} onChange={(event) => update('duplicateProviderCode', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>
    </div>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => setFilters(emptyFilters)}>{zh ? '清除篩選' : 'Clear filters'}</button>}</aside>;
}

function Overview({ summary, language }: { summary: ChildMedicalSubsidyContractedProviderSummary; language: Language }) {
  const zh = language === 'zh';
  const cards = [
    [zh ? '兒童醫療補助特約院所數' : 'Child medical subsidy provider count', summary.totalRecords],
    [zh ? '臺北市內院所數' : 'Taipei provider count', summary.taipeiProviderCount],
    [zh ? '外縣市或非臺北地區院所數' : 'Outside-Taipei provider count', summary.outsideTaipeiProviderCount],
    [zh ? '涵蓋行政區數' : 'Administrative areas covered', summary.administrativeAreaCount],
    [zh ? '涵蓋臺北市行政區數' : 'Taipei districts covered', summary.taipeiDistrictCount],
    [zh ? '不重複院所代碼數' : 'Unique provider code count', summary.uniqueProviderCodeCount],
    [zh ? '不重複地址數' : 'Unique address count', summary.uniqueAddressCount],
    [zh ? '不重複電話數' : 'Unique phone count', summary.uniquePhoneCount],
    [zh ? '有電話紀錄數' : 'Records with phone', summary.recordsWithPhone],
    [zh ? '院所最多行政區' : 'Top administrative area', summary.byAdministrativeArea[0]?.administrativeArea ?? '-'],
    [zh ? '重複院所代碼數' : 'Duplicate provider code count', summary.dataQuality.duplicateProviderCodeCount],
  ];
  return <><div className="notice subtle">{zh ? '此圖僅整理兒童醫療補助特約院所名冊中的編號、院所代碼、診所名稱、行政區、地址與電話，不代表即時門診時間、即時預約名額、補助資格判定、補助金額、費用標準、醫療建議、兒科就醫建議或服務品質排名。' : 'This chart only organizes sequence number, provider code, clinic name, administrative area, address, and phone from child medical subsidy contracted provider public data. It does not represent real-time clinic hours, real-time appointment availability, subsidy eligibility determination, subsidy amount, fees, medical advice, pediatric care advice, or service quality ranking.'}</div>
    <div className="summary-grid">{cards.map(([label, value]) => <article key={label}><span>{label}</span><strong>{typeof value === 'number' ? fmt(value) : value}</strong></article>)}</div>
    <div className="chart-grid"><BarChart title={zh ? '各行政區院所數' : 'Providers by administrative area'} data={summary.byAdministrativeArea.map((item) => ({ label: item.administrativeArea, value: item.providerCount }))} /><BarChart title={zh ? '各臺北市行政區院所數' : 'Providers by Taipei district'} data={summary.byTaipeiDistrict.map((item) => ({ label: item.district, value: item.providerCount }))} /><BarChart title={zh ? '臺北市內與外縣市院所數' : 'Taipei vs outside-Taipei provider count'} data={[{ label: zh ? '臺北市內' : 'Taipei', value: summary.taipeiProviderCount }, { label: zh ? '外縣市或非臺北地區' : 'Outside Taipei', value: summary.outsideTaipeiProviderCount }]} /><BarChart title={zh ? '電話有無' : 'Phone availability'} data={[{ label: zh ? '有電話' : 'Has phone', value: summary.phoneQuality.hasPhone }, { label: zh ? '無電話' : 'Missing phone', value: summary.phoneQuality.missingPhone }]} /><BarChart title={zh ? '電話類型分布' : 'Phone type distribution'} data={Object.entries(summary.phoneQuality).filter(([key]) => key !== 'hasPhone').map(([label, value]) => ({ label, value }))} /><BarChart title={zh ? '院所最多道路' : 'Top roads by provider count'} data={summary.byRoadName.slice(0, 30).map((item) => ({ label: item.roadName, value: item.count }))} /></div></>;
}

function ProviderMap({ summary, language, viewDistrict }: { summary: ChildMedicalSubsidyContractedProviderSummary; language: Language; viewDistrict: (district: string) => void }) {
  const zh = language === 'zh', max = Math.max(...summary.byTaipeiDistrict.map((district) => district.providerCount), 1);
  return <div className="map-wrap"><div className="notice">{zh ? '兒童醫療補助特約院所名冊未提供官方經緯度。臺北市內資料以行政區彙總呈現，外縣市或非臺北行政區資料保留於清單與統計中，不強制轉換為臺北行政區點位。本模組不代表精確院所位置、即時門診時間、預約名額、補助資格、費用標準或醫療建議。' : 'Child medical subsidy contracted provider data does not provide official coordinates. Taipei records are summarized by district, while outside-Taipei or non-Taipei area records are preserved in the directory and summaries and are not forced into Taipei district map points. This module does not represent exact provider locations, real-time clinic hours, appointment availability, subsidy eligibility, fees, or medical advice.'}</div>
    <MapContainer center={[25.072, 121.54]} zoom={11} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap contributors &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" />{summary.byTaipeiDistrict.map((district) => {
      const point = TAIPEI_DISTRICT_CENTROIDS[district.district];
      return point && <CircleMarker key={district.district} center={[point.latitude, point.longitude]} radius={10 + 26 * Math.sqrt(district.providerCount / max)} pathOptions={{ fillColor: '#4f7fb8', fillOpacity: .76, color: '#fff7e8', weight: 2 }}><Popup><div className="map-popup"><strong>{zh ? '兒童醫療補助特約院所行政區分布' : 'Child Medical Subsidy Provider District Distribution'}</strong><p>{zh ? '行政區' : 'District'}: {district.district}</p><p>{zh ? '院所數' : 'Provider count'}: {fmt(district.providerCount)}</p><p>{zh ? '本圖以臺北市行政區彙總呈現，不代表精確院所位置、即時門診時間、預約名額、補助資格、費用標準或醫療建議。' : 'This map shows Taipei district-level summaries and does not represent exact provider locations, real-time clinic hours, appointment availability, subsidy eligibility, fees, or medical advice.'}</p><button onClick={() => viewDistrict(district.district)}>{zh ? '查看清單' : 'View directory'}</button></div></Popup></CircleMarker>;
    })}</MapContainer></div>;
}

function Directory({ records, language }: { records: ChildMedicalSubsidyContractedProviderRecord[]; language: Language }) {
  const zh = language === 'zh';
  const [limit, setLimit] = useState(80);
  useEffect(() => setLimit(80), [records]);
  return <><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['診所名稱', '行政區', '地址', '電話', '院所代碼', '地圖查詢', '來源明細'] : ['Clinic name', 'Administrative area', 'Address', 'Phone', 'Provider code', 'Map lookup', 'Source details']).map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{records.slice(0, limit).map((record) => <tr key={record.id}><th>{record.providerName}</th><td>{record.areaDisplayName ?? '-'}</td><td>{record.address ?? '-'}</td><td>{record.phoneDialHref ? <a href={record.phoneDialHref}>{record.phoneDisplay ?? record.phone}</a> : record.phoneDisplay ?? record.phone ?? '-'}</td><td>{record.providerCode ?? '-'}</td><td>{record.googleMapsQuery ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.googleMapsQuery)}`} target="_blank" rel="noreferrer">{zh ? '地圖查詢' : 'Map lookup'}</a> : '-'}</td><td><details><summary>{zh ? '來源明細' : 'Source details'}</summary><dl><div><dt>{zh ? '編號' : 'Sequence number'}</dt><dd>{record.sourceSequenceNumber ?? '-'}</dd></div><div><dt>{zh ? '行政區原始值' : 'Administrative area raw'}</dt><dd>{record.administrativeAreaRaw ?? '-'}</dd></div><div><dt>{zh ? '是否為臺北市行政區' : 'Is Taipei district'}</dt><dd>{record.isTaipeiDistrict ? (zh ? '是' : 'Yes') : (zh ? '否' : 'No')}</dd></div><div><dt>{zh ? '臺北市行政區' : 'Taipei district'}</dt><dd>{record.taipeiDistrict ?? '-'}</dd></div><div><dt>{zh ? '外縣市或非臺北地區' : 'Outside-Taipei area'}</dt><dd>{record.outsideTaipeiArea ?? '-'}</dd></div><div><dt>{zh ? '地址解析行政區' : 'District from address'}</dt><dd>{record.districtFromAddress ?? '-'}</dd></div><div><dt>{zh ? '行政區與地址不一致' : 'Area / address mismatch'}</dt><dd>{record.districtMismatch ? (zh ? '是' : 'Yes') : (zh ? '否' : 'No')}</dd></div><div><dt>{zh ? '道路' : 'Road'}</dt><dd>{record.roadName ?? '-'}</dd></div><div><dt>{zh ? '電話類型' : 'Phone type'}</dt><dd>{record.phoneType}</dd></div><div><dt>{zh ? '資料來源' : 'Source'}</dt><dd>{record.source}</dd></div><div><dt>{zh ? '解讀限制' : 'Disclaimer'}</dt><dd>{zh ? '不代表即時門診時間、即時預約名額、補助資格判定、補助金額、費用標準、醫療建議、兒科就醫建議、服務品質排名、急診或緊急醫療服務、即時營運狀態或官方背書。' : 'Does not represent real-time clinic hours, appointment availability, subsidy eligibility, subsidy amount, fees, medical advice, pediatric care advice, service quality ranking, emergency medical service, real-time operating status, or official endorsement.'}</dd></div></dl></details></td></tr>)}</tbody></table></div>{!records.length && <p className="empty">{zh ? '沒有符合條件的紀錄。' : 'No records match these filters.'}</p>}{limit < records.length && <button className="load-more" onClick={() => setLimit(limit + 80)}>{zh ? '載入更多' : 'Load more'} · {records.length - limit}</button>}</>;
}

function Compare({ summary, related, language }: { summary: ChildMedicalSubsidyContractedProviderSummary; related: { vaccination?: ContractedVaccinationMedicalProviderSummary; hpv?: PubliclyFundedHpvVaccinationProviderSummary; telepsychology?: TelepsychologyCounselingInstitutionSummary }; language: Language }) {
  const zh = language === 'zh';
  return <div className="notes-grid"><article><h3>{zh ? '與其他醫療資料比較' : 'Compare healthcare records'}</h3><p>{zh ? '兒童醫療補助特約院所是兒童醫療補助相關特約院所名冊，與預防接種、HPV疫苗或通訊心理諮商資料不應合併解讀為相同服務清冊。' : 'Child medical subsidy contracted providers are a medical subsidy provider directory and should not be merged with vaccination, HPV vaccination, or telepsychology records as the same service directory.'}</p></article>
    <article><h3>{zh ? '模組紀錄數' : 'Module record counts'}</h3><div className="bars"><div className="bar-row wide-label"><span>{zh ? '兒童醫療補助院所' : 'Child subsidy providers'}</span><div><i style={{ width: '100%' }} /></div><b>{fmt(summary.totalRecords)}</b></div>{related.vaccination && <div className="bar-row wide-label"><span>{zh ? '預防接種合約院所' : 'Vaccination providers'}</span><div><i style={{ width: `${Math.max(2, related.vaccination.totalRecords / Math.max(summary.totalRecords, related.vaccination.totalRecords) * 100)}%` }} /></div><b>{fmt(related.vaccination.totalRecords)}</b></div>}{related.hpv && <div className="bar-row wide-label"><span>{zh ? 'HPV疫苗院所' : 'HPV providers'}</span><div><i style={{ width: `${Math.max(2, related.hpv.totalRecords / Math.max(summary.totalRecords, related.hpv.totalRecords) * 100)}%` }} /></div><b>{fmt(related.hpv.totalRecords)}</b></div>}</div></article>
    {related.vaccination && <article><h3>{zh ? '預防接種資料區別' : 'Vaccination distinction'}</h3><p>{zh ? '兒童醫療補助特約院所與各項預防接種合約醫療院所資料性質相關但不完全相同。前者聚焦兒童醫療補助特約服務，後者涵蓋預防接種服務類別；兩者不應直接合併解讀為相同服務清冊。' : 'Child medical subsidy contracted providers and broader contracted vaccination medical provider records are related but not identical. The former focuses on child medical subsidy contracted services, while the latter covers vaccination service categories. They should not be merged as the same service directory.'}</p></article>}
    {related.hpv && <article><h3>{zh ? 'HPV資料區別' : 'HPV distinction'}</h3><p>{zh ? '兒童醫療補助特約院所與公費HPV疫苗特約醫療院所資料性質不同。前者是兒童醫療補助相關特約院所，後者是公費HPV疫苗接種服務特約院所，不應直接解讀為相同補助或相同服務。' : 'Child medical subsidy contracted providers and publicly funded HPV vaccination providers have different meanings. The former describes providers contracted for child medical subsidy services, while the latter describes providers contracted for publicly funded HPV vaccination services. They should not be interpreted as the same subsidy or service.'}</p></article>}
    {related.telepsychology && <article><h3>{zh ? '通訊心理諮商資料區別' : 'Telepsychology distinction'}</h3><p>{zh ? '兒童醫療補助特約院所與通訊心理諮商機構資料性質不同，不應直接比較服務容量、服務品質或補助資格。' : 'Child medical subsidy contracted providers and telepsychology counseling institutions have different meanings. Their service capacity, service quality, or subsidy eligibility should not be directly compared.'}</p></article>}</div>;
}

export default function ChildMedicalSubsidyContractedProvidersModule({ records, summary, related, language }: { records: ChildMedicalSubsidyContractedProviderRecord[]; summary: ChildMedicalSubsidyContractedProviderSummary; related: { vaccination?: ContractedVaccinationMedicalProviderSummary; hpv?: PubliclyFundedHpvVaccinationProviderSummary; telepsychology?: TelepsychologyCounselingInstitutionSummary }; language: Language }) {
  const zh = language === 'zh';
  const [view, setView] = useState<'overview' | 'map' | 'directory' | 'compare' | 'notes'>('overview');
  const [filters, setFilters] = useState(emptyFilters);
  const filtered = useMemo(() => filterChildMedicalSubsidyContractedProviders(records, filters), [records, filters]);
  const activeSummary = useMemo(() => Object.values(filters).some(Boolean) ? buildChildMedicalSubsidyContractedProviderSummary(filtered) : summary, [filtered, filters, summary]);
  const openDistrict = (district: string) => { setFilters({ ...emptyFilters, taipeiDistrict: district }); setView('directory'); };
  const views = [['overview', zh ? '總覽' : 'Overview'], ['map', zh ? '行政區與地區分布' : 'District & Area Distribution'], ['directory', zh ? '院所清單' : 'Provider Directory'], ['compare', zh ? '與其他醫療資料比較' : 'Compare Healthcare Records'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  return <><Filters filters={filters} setFilters={setFilters} records={records} language={language} /><section className="workspace"><div className="section-heading"><p>03 / HEALTHCARE & CHILD WELFARE PUBLIC RECORDS</p><h2>{zh ? '兒童醫療補助特約院所名冊' : 'Child Medical Subsidy Contracted Providers'}</h2><span>{zh ? '查詢臺北市兒童醫療補助特約院所公開資料，包含院所代碼、診所名稱、行政區、地址與電話，作為兒童醫療補助與醫療院所公開資訊。' : 'Look up Taipei child medical subsidy contracted provider public records, including provider code, clinic name, administrative area, address, and phone as child medical subsidy and healthcare provider public information.'}</span></div><div className="subtabs">{views.map(([id, label]) => <button className={view === id ? 'active' : ''} onClick={() => setView(id)} key={id}>{label}</button>)}</div><div className="notice subtle">{zh ? '兒童醫療補助特約院所名冊為臺北市公開資料中的兒童醫療補助特約醫療院所清冊，僅供查詢編號、院所代碼、診所名稱、行政區、地址與電話等來源欄位使用，不代表即時門診時間、即時預約名額、補助資格判定、補助金額、費用標準、醫療建議、兒科就醫建議、服務品質排名、急診或緊急醫療服務、即時營運狀態或官方背書。' : 'Child medical subsidy contracted provider data is Taipei public-data directory information for medical institutions contracted for child medical subsidy services. It is for looking up source fields only and does not represent real-time clinic hours, appointment availability, subsidy eligibility, fees, medical advice, emergency service, operating status, or endorsement.'}</div>
    {view === 'overview' && <Overview summary={activeSummary} language={language} />}{view === 'map' && <><ProviderMap summary={activeSummary} language={language} viewDistrict={openDistrict} /><div className="chart-grid"><BarChart title={zh ? '外縣市或非臺北地區' : 'Outside-Taipei areas'} data={activeSummary.outsideTaipeiAreas.map((item) => ({ label: item.area, value: item.providerCount }))} /></div></>}{view === 'directory' && <><div className="section-heading inline"><div /><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆符合紀錄' : 'matching records'}</span></strong></div><Directory records={filtered} language={language} /></>}{view === 'compare' && <Compare summary={activeSummary} related={related} language={language} />}{view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料內容' : 'Data contents'}</h3><p>{zh ? '兒童醫療補助特約院所名冊提供臺北市兒童醫療補助特約醫療院所公開資料，欄位包含編號、院所代碼、診所名稱、行政區、地址與電話。本網站保留來源行政區欄位，並從地址解析臺北市行政區與道路名稱，整理為行政區分布與院所清單。資料未提供官方經緯度，因此預設不顯示精確點位。' : 'Child medical subsidy contracted provider data provides Taipei public records for medical institutions contracted for child medical subsidy services. Fields include sequence number, provider code, clinic name, administrative area, address, and phone. This site preserves the source administrative area field, parses Taipei districts and road names from addresses, and organizes the data into district distribution and a provider directory. The data does not provide official coordinates, so exact points are not shown by default.'}</p></article><article><h3>{zh ? '解讀限制' : 'Interpretation limits'}</h3><p>{zh ? '本資料為兒童醫療補助特約院所公開名冊，僅供查詢來源欄位與統計整理，不代表即時門診時間、即時預約名額、補助資格判定、補助金額、費用標準、醫療建議、兒科就醫建議、服務品質排名、急診或緊急醫療服務、即時營運狀態或官方背書。實際補助資格、補助範圍、申請方式、門診時間、預約方式、費用、醫療評估與最新資訊請以醫療院所、臺北市政府衛生局、衛生福利部、健保署及主管機關公告為準。' : 'This data is a public directory of medical institutions contracted for child medical subsidy services for source-field lookup and statistical organization only. It does not represent real-time clinic hours, real-time appointment availability, subsidy eligibility determination, subsidy amount, fees, medical advice, pediatric care advice, service quality ranking, emergency medical service, real-time operating status, or official endorsement. Actual eligibility, subsidy scope, application method, clinic hours, appointment method, fees, medical evaluation, and latest information should be verified with the medical institution, Taipei City Department of Health, Ministry of Health and Welfare, National Health Insurance Administration, and competent-authority announcements.'}</p></article><article><h3>{zh ? '資料來源' : 'Source'}</h3><p><a href="https://data.taipei/dataset/detail?id=3cc250f5-9f5a-4670-ac7b-f13ecd316032" target="_blank" rel="noreferrer">{zh ? '臺北市兒童醫療補助特約院所名冊' : 'Taipei Child Medical Subsidy Contracted Providers'} ↗</a></p></article></div>}</section></>;
}
