import { useEffect, useMemo, useState } from 'react';

interface CulturalArtsFoundation { id: string; sourceId: string; foundationName: string; cityCode: string; cityName: string; registeredAddress: string; districtNameFromAddress: string; hasRegisteredAddress: boolean; googleMapsQuery: string; }
const MISSING = '—';
const DISTRICTS = ['中正區', '大同區', '中山區', '松山區', '大安區', '萬華區', '信義區', '士林區', '北投區', '內湖區', '南港區', '文山區'];
function Chart({ title, data }: { title: string; data: Array<{ label: string; value: number }> }) { const max = Math.max(1, ...data.map((item) => item.value)); return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) => <div className="bar-row wide-label" key={item.label}><span>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{item.value}</b></div>)}</div></section>; }

export default function CulturalArtsFoundationsModule({ language }: { language: 'zh' | 'en' }) {
  const zh = language === 'zh'; const [records, setRecords] = useState<CulturalArtsFoundation[]>([]); const [loadError, setLoadError] = useState(false); const [view, setView] = useState<'overview' | 'districts' | 'directory' | 'quality' | 'notes'>('overview'); const [search, setSearch] = useState(''); const [city, setCity] = useState(''); const [district, setDistrict] = useState(''); const [address, setAddress] = useState(''); const [sort, setSort] = useState('name'); const [page, setPage] = useState(1);
  useEffect(() => { fetch(`${import.meta.env.BASE_URL}data/cultural-arts-foundations/records.json`).then((response) => { if (!response.ok) throw new Error(String(response.status)); return response.json(); }).then(setRecords).catch(() => setLoadError(true)); }, []);
  const filtered = useMemo(() => { const query = search.trim().toLocaleLowerCase(); return records.filter((record) => (!query || [record.foundationName, record.cityName, record.cityCode, record.districtNameFromAddress, record.registeredAddress].join(' ').toLocaleLowerCase().includes(query)) && (!city || record.cityName === city) && (!district || record.districtNameFromAddress === district) && (!address || (address === 'yes' ? record.hasRegisteredAddress : !record.hasRegisteredAddress))); }, [records, search, city, district, address]);
  const byDistrict = useMemo(() => DISTRICTS.map((label) => ({ label, value: filtered.filter((record) => record.districtNameFromAddress === label).length })).filter((item) => item.value), [filtered]);
  const byCity = useMemo(() => [...new Set(filtered.map((record) => record.cityName).filter(Boolean))].map((label) => ({ label, value: filtered.filter((record) => record.cityName === label).length })), [filtered]);
  const summary = useMemo(() => ({ total: filtered.length, unique: new Set(filtered.map((record) => record.foundationName).filter(Boolean)).size, cities: byCity.length, districts: byDistrict.length, withAddress: filtered.filter((record) => record.hasRegisteredAddress).length, topDistrict: [...byDistrict].sort((a, b) => b.value - a.value)[0]?.label ?? '' }), [filtered, byCity, byDistrict]);
  const quality = useMemo(() => ({ duplicateRows: records.length - new Set(records.map((record) => `${record.foundationName}|${record.registeredAddress}`)).size, missingNames: records.filter((record) => !record.foundationName).length, missingAddresses: records.filter((record) => !record.registeredAddress).length, unknownCityCodes: records.filter((record) => record.cityCode && record.cityCode !== '63000').length, unresolvedDistricts: records.filter((record) => record.registeredAddress && !record.districtNameFromAddress).length }), [records]);
  const sorted = useMemo(() => [...filtered].sort((a, b) => sort === 'city' ? a.cityName.localeCompare(b.cityName, 'zh-Hant') : sort === 'district' ? a.districtNameFromAddress.localeCompare(b.districtNameFromAddress, 'zh-Hant') : a.foundationName.localeCompare(b.foundationName, 'zh-Hant')), [filtered, sort]); const pageSize = 25; const pages = Math.max(1, Math.ceil(sorted.length / pageSize)); const rows = sorted.slice((Math.min(page, pages) - 1) * pageSize, Math.min(page, pages) * pageSize);
  const reset = (action: () => void) => { action(); setPage(1); };
  const download = () => { const headings = ['ID', 'Foundation name', 'City code', 'City', 'District', 'Registered address']; const quote = (value: string) => `"${value.replaceAll('"', '""')}"`; const csv = [headings, ...filtered.map((record) => [record.sourceId, record.foundationName, record.cityCode, record.cityName, record.districtNameFromAddress, record.registeredAddress])].map((row) => row.map(quote).join(',')).join('\n'); const url = URL.createObjectURL(new Blob(['\uFEFF', csv], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'cultural-arts-foundations-filtered.csv'; link.click(); URL.revokeObjectURL(url); };
  const map = (value: string) => value ? <a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(value)}`}>{zh ? '地圖查詢' : 'Map lookup'}</a> : MISSING;
  const copyAddress = (value: string) => value && <button type="button" className="copy-button" onClick={() => navigator.clipboard?.writeText(value)}>{zh ? '複製' : 'Copy'}</button>;
  if (loadError) return <section className="workspace"><div className="notice">{zh ? '無法載入本機資料檔。' : 'The local data file could not be loaded.'}</div></section>;
  return <section className="workspace"><div className="section-heading"><p>CULTURE, ARTS & FOUNDATION ORGANIZATIONS</p><h2>{zh ? '文化藝術財團法人一覽表' : 'Culture and Arts Foundations'}</h2><span>{zh ? '以登記會址為資料來源地址，僅提供外部地圖查詢，不建立精確地圖標記。' : 'Registered addresses are source-record addresses; external map lookup only, with no exact map markers.'}</span></div><div className="subtabs">{([['overview', zh ? '總覽' : 'Overview'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['directory', zh ? '基金會名冊' : 'Foundation Directory'], ['quality', zh ? '資料品質' : 'Data Quality'], ['notes', zh ? '資料說明' : 'Data Notes']] as const).map(([id, label]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => { setView(id); setPage(1); }}>{label}</button>)}</div><aside className="filters"><label className="search"><input value={search} onChange={(event) => reset(() => setSearch(event.target.value))} placeholder={zh ? '搜尋基金會、縣市、行政區、登記會址或縣市代碼' : 'Search foundation, city, district, registered address, or city code'} /></label><div className="filter-grid"><label>{zh ? '縣市' : 'City'}<select value={city} onChange={(event) => reset(() => setCity(event.target.value))}><option value="">{zh ? '全部' : 'All'}</option>{[...new Set(records.map((record) => record.cityName).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select></label><label>{zh ? '行政區' : 'District'}<select value={district} onChange={(event) => reset(() => setDistrict(event.target.value))}><option value="">{zh ? '全部' : 'All'}</option>{DISTRICTS.filter((value) => records.some((record) => record.districtNameFromAddress === value)).map((value) => <option key={value}>{value}</option>)}</select></label><label>{zh ? '有登記會址' : 'Has registered address'}<select value={address} onChange={(event) => reset(() => setAddress(event.target.value))}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '有' : 'Yes'}</option><option value="no">{zh ? '無' : 'No'}</option></select></label></div></aside>
    {view === 'overview' && <><div className="notice subtle">{zh ? '本資料為臺北市文化局文化藝術財團法人公開名冊。登記會址為來源紀錄地址，未必是目前辦公處、服務地點或可公開進入場所。列入名冊不代表目前營運、持續登記、財務狀況、募款資格、活動、社會影響、服務品質或官方推薦；請向基金會、臺北市文化局或相關主管機關確認最新資訊。' : 'This dataset is a public directory of culture and arts foundations registered with the Taipei Department of Cultural Affairs. Registered addresses are source-record addresses and may not represent current offices, service locations, or publicly accessible premises. Directory inclusion does not confirm current operation, continuing registration, financial condition, fundraising eligibility, activities, social impact, service quality, or official recommendation. Verify current information with the foundation, Taipei City Department of Cultural Affairs, or the relevant authority.'}</div><div className="summary-grid">{[[zh ? '基金會紀錄數' : 'Total foundation records', summary.total], [zh ? '不重複基金會名稱' : 'Unique foundation names', summary.unique], [zh ? '涵蓋縣市' : 'Cities represented', summary.cities], [zh ? '臺北行政區' : 'Taipei districts represented', summary.districts], [zh ? '有登記會址紀錄' : 'Records with registered addresses', summary.withAddress], [zh ? '紀錄最多行政區' : 'District with most records', summary.topDistrict || MISSING]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div><Chart title={zh ? '各行政區基金會數' : 'Foundations by district'} data={byDistrict} /><Chart title={zh ? '各縣市基金會數' : 'Foundations by city'} data={byCity} /></>}
    {view === 'districts' && <><Chart title={zh ? '各行政區基金會數' : 'Foundations by district'} data={byDistrict} /><Chart title={zh ? '各縣市基金會數' : 'Foundations by city'} data={byCity} /><Chart title={zh ? '有無登記會址紀錄' : 'Records with and without registered addresses'} data={[{ label: zh ? '有' : 'With', value: summary.withAddress }, { label: zh ? '無' : 'Without', value: summary.total - summary.withAddress }]} /></>}
    {view === 'directory' && <><div className="section-heading inline"><p>{zh ? '篩選後紀錄' : 'Filtered records'}</p><strong>{sorted.length}</strong><button type="button" onClick={download}>{zh ? '下載篩選 CSV' : 'Download filtered CSV'}</button><label>{zh ? '排序' : 'Sort'}<select value={sort} onChange={(event) => { setSort(event.target.value); setPage(1); }}><option value="name">{zh ? '依基金會名稱' : 'Foundation name'}</option><option value="city">{zh ? '依縣市' : 'City'}</option><option value="district">{zh ? '依行政區' : 'District'}</option></select></label></div><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['編號', '基金會名稱', '縣市', '行政區', '登記會址', '地圖查詢'] : ['ID', 'Foundation name', 'City', 'District', 'Registered address', 'Map lookup']).map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((record) => <tr key={record.id}><td>{record.sourceId || MISSING}</td><th>{record.foundationName || MISSING}</th><td>{record.cityName || MISSING}</td><td>{record.districtNameFromAddress || MISSING}</td><td>{record.registeredAddress || MISSING} {copyAddress(record.registeredAddress)}</td><td>{map(record.googleMapsQuery)}</td></tr>)}</tbody></table></div><div className="pagination"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>{zh ? '上一頁' : 'Previous'}</button><span>{page} / {pages}</span><button type="button" disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>{zh ? '下一頁' : 'Next'}</button></div></>}
    {view === 'quality' && <div className="notes-grid"><article><h3>{zh ? '資料品質報告' : 'Data quality report'}</h3><p>{zh ? `重複列 ${quality.duplicateRows} 筆；缺少基金會名稱 ${quality.missingNames} 筆；缺少登記會址 ${quality.missingAddresses} 筆；未知縣市代碼 ${quality.unknownCityCodes} 筆；有地址但無法解析臺北行政區 ${quality.unresolvedDistricts} 筆。` : `Duplicate rows: ${quality.duplicateRows}; missing foundation names: ${quality.missingNames}; missing registered addresses: ${quality.missingAddresses}; unknown city codes: ${quality.unknownCityCodes}; addresses with unresolved Taipei districts: ${quality.unresolvedDistricts}.`}</p></article><article><h3>{zh ? '處理方式' : 'Processing'}</h3><p>{zh ? '保留來源值，並僅在地址明確含有臺北市行政區時解析行政區。缺少值顯示為「—」，不會轉為 0。' : 'Source values are preserved, and a Taipei district is derived only when it is clear in the address. Missing values display as “—”, never as zero.'}</p></article></div>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料範圍' : 'Data scope'}</h3><p>{zh ? '本機 JSON 來自臺北市文化局公開資料。基金會名稱不應用於推論活動、資金、法律狀態、目前營運、財務狀況或服務範圍。' : 'The local JSON is based on Taipei Department of Cultural Affairs public data. Foundation names must not be used to infer activities, funding, legal status, current operation, financial condition, or service area.'}</p></article><article><h3>{zh ? '位置資訊' : 'Location information'}</h3><p>{zh ? '資料不含確認的官方座標，故不建立精確地圖標記或自動地理編碼；登記會址僅提供外部地圖搜尋。' : 'The source has no confirmed official coordinates, so it creates no exact map markers or automatic geocoding; registered addresses only provide external map search.'}</p></article></div>}
  </section>;
}
