import { useEffect, useMemo, useState } from 'react';
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet';
import { DISTRICTS, TAIPEI_DISTRICT_CENTROIDS } from './lib/civicGroups';
import { buildDentureSubsidyMedicalProviderSummary, filterDentureSubsidyMedicalProviders } from './lib/dentureSubsidyMedicalProviders';
import type { ChildMedicalSubsidyContractedProviderSummary, ContractedVaccinationMedicalProviderSummary, DentureSubsidyMedicalProviderFilters, DentureSubsidyMedicalProviderRecord, DentureSubsidyMedicalProviderSummary, ElderlyWelfareInstitutionSummary, Language, TelepsychologyCounselingInstitutionSummary } from './types';

const emptyFilters: DentureSubsidyMedicalProviderFilters = { search: '', subsidyType: '', administrativeArea: '', taipeiDistrict: '', roadName: '', hasPhone: '', phoneType: '', districtMismatch: '' };
const fmt = (value?: number) => value === undefined ? '-' : value.toLocaleString();

function BarChart({ title, data }: { title: string; data: Array<{ label: string; value: number }> }) {
  const max = Math.max(...data.map((item) => item.value), 1);
  return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) =>
    <div className="bar-row wide-label" key={item.label}><span title={item.label}>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{fmt(item.value)}</b></div>)}</div></section>;
}

function Filters({ filters, setFilters, records, language }: { filters: DentureSubsidyMedicalProviderFilters; setFilters: (filters: DentureSubsidyMedicalProviderFilters) => void; records: DentureSubsidyMedicalProviderRecord[]; language: Language }) {
  const zh = language === 'zh', update = (key: keyof DentureSubsidyMedicalProviderFilters, value: string) => setFilters({ ...filters, [key]: value });
  const options = <T extends string>(values: Array<T | undefined>) => [...new Set(values.filter(Boolean) as T[])].sort((a, b) => a.localeCompare(b));
  return <aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(event) => update('search', event.target.value)} placeholder={zh ? '搜尋補助類型、院所名稱、區域、地址或電話' : 'Search subsidy type, provider name, area, address, or phone'} /></label>
    <div className="filter-grid grant-filters">
      <label>{zh ? '補助類型' : 'Subsidy type'}<select value={filters.subsidyType} onChange={(event) => update('subsidyType', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.subsidyType)).map((type) => <option key={type}>{type}</option>)}</select></label>
      <label>{zh ? '區域' : 'Area'}<select value={filters.administrativeArea} onChange={(event) => update('administrativeArea', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.areaDisplayName)).map((area) => <option key={area}>{area}</option>)}</select></label>
      <label>{zh ? '臺北市行政區' : 'Taipei district'}<select value={filters.taipeiDistrict} onChange={(event) => update('taipeiDistrict', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{DISTRICTS.map((district) => <option key={district}>{district}</option>)}</select></label>
      <label>{zh ? '道路' : 'Road'}<select value={filters.roadName} onChange={(event) => update('roadName', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.roadName)).map((road) => <option key={road}>{road}</option>)}</select></label>
      <label>{zh ? '有電話' : 'Has phone'}<select value={filters.hasPhone} onChange={(event) => update('hasPhone', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '有' : 'Yes'}</option><option value="no">{zh ? '無' : 'No'}</option></select></label>
      <label>{zh ? '電話類型' : 'Phone type'}<select value={filters.phoneType} onChange={(event) => update('phoneType', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.phoneType)).map((type) => <option key={type}>{type}</option>)}</select></label>
      <label>{zh ? '區域與地址不一致' : 'Area / address mismatch'}<select value={filters.districtMismatch} onChange={(event) => update('districtMismatch', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>
    </div>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => setFilters(emptyFilters)}>{zh ? '清除篩選' : 'Clear filters'}</button>}</aside>;
}

function Overview({ summary, language }: { summary: DentureSubsidyMedicalProviderSummary; language: Language }) {
  const zh = language === 'zh';
  const cards = [
    [zh ? '假牙補助醫療院所數' : 'Denture subsidy provider count', summary.totalRecords],
    [zh ? '補助類型數' : 'Subsidy type count', summary.subsidyTypeCount],
    [zh ? '涵蓋區域數' : 'Areas covered', summary.administrativeAreaCount],
    [zh ? '涵蓋臺北市行政區數' : 'Taipei districts covered', summary.taipeiDistrictCount],
    [zh ? '不重複地址數' : 'Unique address count', summary.uniqueAddressCount],
    [zh ? '不重複電話數' : 'Unique phone count', summary.uniquePhoneCount],
    [zh ? '有電話紀錄數' : 'Records with phone', summary.recordsWithPhone],
    [zh ? '院所最多區域' : 'Top area by provider count', summary.byAdministrativeArea[0]?.administrativeArea ?? '-'],
    [zh ? '重複院所名稱數' : 'Duplicate provider name count', summary.dataQuality.duplicateProviderNameCount],
  ];
  return <><div className="notice subtle">{zh ? '此圖僅整理假牙補助醫療院所名單中的補助類型、區域、院所名稱、地址與連絡電話，不代表即時門診時間、即時預約名額、補助資格判定、補助金額、費用標準、牙科治療建議、醫療建議或服務品質排名。' : 'This chart only organizes subsidy type, area, medical institution name, address, and contact phone from denture subsidy medical provider public data. It does not represent real-time clinic hours, real-time appointment availability, subsidy eligibility determination, subsidy amount, fees, dental treatment advice, medical advice, or service quality ranking.'}</div>
    <div className="summary-grid">{cards.map(([label, value]) => <article key={label}><span>{label}</span><strong>{typeof value === 'number' ? fmt(value) : value}</strong></article>)}</div>
    <div className="chart-grid"><BarChart title={zh ? '各區域院所數' : 'Providers by area'} data={summary.byAdministrativeArea.map((item) => ({ label: item.administrativeArea, value: item.providerCount }))} /><BarChart title={zh ? '各臺北市行政區院所數' : 'Providers by Taipei district'} data={summary.byTaipeiDistrict.map((item) => ({ label: item.district, value: item.providerCount }))} /><BarChart title={zh ? '各補助類型院所數' : 'Providers by subsidy type'} data={summary.bySubsidyType.map((item) => ({ label: item.subsidyType, value: item.providerCount }))} /><BarChart title={zh ? '電話有無' : 'Phone availability'} data={[{ label: zh ? '有電話' : 'Has phone', value: summary.phoneQuality.hasPhone }, { label: zh ? '無電話' : 'Missing phone', value: summary.phoneQuality.missingPhone }]} /><BarChart title={zh ? '電話類型分布' : 'Phone type distribution'} data={Object.entries(summary.phoneQuality).filter(([key]) => key !== 'hasPhone').map(([label, value]) => ({ label, value }))} /><BarChart title={zh ? '院所最多道路' : 'Top roads by provider count'} data={summary.byRoadName.slice(0, 30).map((item) => ({ label: item.roadName, value: item.count }))} /></div></>;
}

function ProviderMap({ summary, language, viewDistrict }: { summary: DentureSubsidyMedicalProviderSummary; language: Language; viewDistrict: (district: string) => void }) {
  const zh = language === 'zh', max = Math.max(...summary.byTaipeiDistrict.map((district) => district.providerCount), 1);
  return <div className="map-wrap"><div className="notice">{zh ? '假牙補助醫療院所名單未提供官方經緯度。本模組以行政區彙總呈現，不代表精確院所位置、即時門診時間、預約名額、補助資格、補助金額、費用標準、牙科治療建議或醫療建議。' : 'Denture subsidy medical provider data does not provide official coordinates. This module summarizes records by administrative district and does not represent exact provider locations, real-time clinic hours, appointment availability, subsidy eligibility, subsidy amount, fees, dental treatment advice, or medical advice.'}</div>
    <MapContainer center={[25.072, 121.54]} zoom={11} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap contributors &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" />{summary.byTaipeiDistrict.map((district) => {
      const point = TAIPEI_DISTRICT_CENTROIDS[district.district];
      return point && <CircleMarker key={district.district} center={[point.latitude, point.longitude]} radius={10 + 26 * Math.sqrt(district.providerCount / max)} pathOptions={{ fillColor: '#8b6f47', fillOpacity: .76, color: '#fff7e8', weight: 2 }}><Popup><div className="map-popup"><strong>{zh ? '假牙補助醫療院所行政區分布' : 'Denture Subsidy Provider District Distribution'}</strong><p>{zh ? '行政區' : 'District'}: {district.district}</p><p>{zh ? '院所數' : 'Provider count'}: {fmt(district.providerCount)}</p><p>{zh ? '本圖以行政區彙總呈現，不代表精確院所位置、即時門診時間、預約名額、補助資格、補助金額、費用標準、牙科治療建議或醫療建議。' : 'This map shows district-level summaries and does not represent exact provider locations, real-time clinic hours, appointment availability, subsidy eligibility, subsidy amount, fees, dental treatment advice, or medical advice.'}</p><button onClick={() => viewDistrict(district.district)}>{zh ? '查看清單' : 'View directory'}</button></div></Popup></CircleMarker>;
    })}</MapContainer></div>;
}

function Directory({ records, language }: { records: DentureSubsidyMedicalProviderRecord[]; language: Language }) {
  const zh = language === 'zh';
  const [limit, setLimit] = useState(80);
  useEffect(() => setLimit(80), [records]);
  return <><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['補助類型', '院所名稱', '區域', '地址', '連絡電話', '地圖查詢', '來源明細'] : ['Subsidy type', 'Provider name', 'Area', 'Address', 'Contact phone', 'Map lookup', 'Source details']).map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{records.slice(0, limit).map((record) => <tr key={record.id}><td>{record.subsidyType ?? '-'}</td><th>{record.providerName}</th><td>{record.areaDisplayName ?? '-'}</td><td>{record.address ?? '-'}</td><td>{record.phoneDialHref ? <a href={record.phoneDialHref}>{record.phoneDisplay ?? record.phone}</a> : record.phoneDisplay ?? record.phone ?? '-'}</td><td>{record.googleMapsQuery ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.googleMapsQuery)}`} target="_blank" rel="noreferrer">{zh ? '地圖查詢' : 'Map lookup'}</a> : '-'}</td><td><details><summary>{zh ? '來源明細' : 'Source details'}</summary><dl><div><dt>{zh ? '區域原始值' : 'Area raw'}</dt><dd>{record.administrativeAreaRaw ?? '-'}</dd></div><div><dt>{zh ? '臺北市行政區' : 'Taipei district'}</dt><dd>{record.taipeiDistrict ?? '-'}</dd></div><div><dt>{zh ? '地址解析行政區' : 'District from address'}</dt><dd>{record.districtFromAddress ?? '-'}</dd></div><div><dt>{zh ? '區域與地址不一致' : 'Area / address mismatch'}</dt><dd>{record.districtMismatch ? (zh ? '是' : 'Yes') : (zh ? '否' : 'No')}</dd></div><div><dt>{zh ? '道路' : 'Road'}</dt><dd>{record.roadName ?? '-'}</dd></div><div><dt>{zh ? '電話類型' : 'Phone type'}</dt><dd>{record.phoneType}</dd></div><div><dt>{zh ? '資料來源' : 'Source'}</dt><dd>{record.source}</dd></div><div><dt>{zh ? '解讀限制' : 'Disclaimer'}</dt><dd>{zh ? '不代表即時門診時間、即時預約名額、補助資格判定、補助金額、費用標準、牙科治療建議、醫療建議、服務品質排名、急診或緊急醫療服務、即時營運狀態或官方背書。' : 'Does not represent real-time clinic hours, appointment availability, subsidy eligibility, subsidy amount, fees, dental treatment advice, medical advice, service quality ranking, emergency dental or medical service, real-time operating status, or official endorsement.'}</dd></div></dl></details></td></tr>)}</tbody></table></div>{!records.length && <p className="empty">{zh ? '沒有符合條件的紀錄。' : 'No records match these filters.'}</p>}{limit < records.length && <button className="load-more" onClick={() => setLimit(limit + 80)}>{zh ? '載入更多' : 'Load more'} · {records.length - limit}</button>}</>;
}

function Compare({ summary, related, language }: { summary: DentureSubsidyMedicalProviderSummary; related: { elderlyWelfare?: ElderlyWelfareInstitutionSummary; childMedical?: ChildMedicalSubsidyContractedProviderSummary; vaccination?: ContractedVaccinationMedicalProviderSummary; telepsychology?: TelepsychologyCounselingInstitutionSummary }; language: Language }) {
  const zh = language === 'zh';
  return <div className="notes-grid"><article><h3>{zh ? '與老人福利及醫療資料比較' : 'Compare elderly welfare & healthcare records'}</h3><p>{zh ? '假牙補助醫療院所是醫療補助相關院所清冊，與老人福利機構、兒童醫療補助、預防接種或通訊心理諮商資料不應合併解讀為相同服務清冊。' : 'Denture subsidy medical providers are a medical subsidy provider directory and should not be merged with elderly welfare, child medical subsidy, vaccination, or telepsychology records as the same service directory.'}</p></article>
    {related.elderlyWelfare && <article><h3>{zh ? '老人福利機構資料區別' : 'Elderly welfare distinction'}</h3><p>{zh ? '假牙補助醫療院所與老人福利機構資料性質不同。前者是醫療補助相關院所清冊，後者是老人福利與照顧機構名冊；兩者不應直接合併解讀為相同服務、相同資格或相同機構類型。' : 'Denture subsidy medical providers and elderly welfare institution records have different meanings. The former is a medical subsidy provider directory, while the latter is an elderly welfare and care institution directory. They should not be merged as the same service, eligibility, or institution type.'}</p></article>}
    {related.childMedical && <article><h3>{zh ? '兒童醫療補助資料區別' : 'Child medical subsidy distinction'}</h3><p>{zh ? '假牙補助醫療院所與兒童醫療補助特約院所資料性質不同。前者屬老人福利與假牙補助相關院所，後者屬兒童醫療補助相關特約院所，不應直接解讀為相同補助或相同服務。' : 'Denture subsidy medical providers and child medical subsidy contracted providers have different meanings. The former relates to elderly welfare and denture subsidy services, while the latter relates to child medical subsidy contracted services. They should not be interpreted as the same subsidy or service.'}</p></article>}
    {related.vaccination && <article><h3>{zh ? '預防接種資料區別' : 'Vaccination distinction'}</h3><p>{zh ? '假牙補助醫療院所與各項預防接種合約醫療院所資料性質不同。前者聚焦假牙補助服務，後者涵蓋預防接種服務類別；兩者不應直接合併解讀為相同服務清冊。' : 'Denture subsidy medical providers and broader contracted vaccination medical provider records have different meanings. The former focuses on denture subsidy services, while the latter covers vaccination service categories. They should not be merged as the same service directory.'}</p></article>}
    <article><h3>{zh ? '模組紀錄數' : 'Module record counts'}</h3><div className="bars">{[{ label: zh ? '假牙補助院所' : 'Denture subsidy providers', value: summary.totalRecords }, ...(related.elderlyWelfare ? [{ label: zh ? '老人福利機構' : 'Elderly welfare institutions', value: related.elderlyWelfare.totalRecords }] : []), ...(related.childMedical ? [{ label: zh ? '兒童醫療補助院所' : 'Child medical subsidy providers', value: related.childMedical.totalRecords }] : [])].map((item) => <div className="bar-row wide-label" key={item.label}><span>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / Math.max(summary.totalRecords, related.elderlyWelfare?.totalRecords ?? 0, related.childMedical?.totalRecords ?? 0) * 100)}%` }} /></div><b>{fmt(item.value)}</b></div>)}</div></article></div>;
}

export default function DentureSubsidyMedicalProvidersModule({ records, summary, related, language }: { records: DentureSubsidyMedicalProviderRecord[]; summary: DentureSubsidyMedicalProviderSummary; related: { elderlyWelfare?: ElderlyWelfareInstitutionSummary; childMedical?: ChildMedicalSubsidyContractedProviderSummary; vaccination?: ContractedVaccinationMedicalProviderSummary; telepsychology?: TelepsychologyCounselingInstitutionSummary }; language: Language }) {
  const zh = language === 'zh';
  const [view, setView] = useState<'overview' | 'map' | 'directory' | 'compare' | 'notes'>('overview');
  const [filters, setFilters] = useState(emptyFilters);
  const filtered = useMemo(() => filterDentureSubsidyMedicalProviders(records, filters), [records, filters]);
  const activeSummary = useMemo(() => Object.values(filters).some(Boolean) ? buildDentureSubsidyMedicalProviderSummary(filtered) : summary, [filtered, filters, summary]);
  const openDistrict = (district: string) => { setFilters({ ...emptyFilters, taipeiDistrict: district }); setView('directory'); };
  const views = [['overview', zh ? '總覽' : 'Overview'], ['map', zh ? '行政區分布' : 'District Distribution'], ['directory', zh ? '院所清單' : 'Provider Directory'], ['compare', zh ? '與老人福利及醫療資料比較' : 'Compare Elderly Welfare & Healthcare Records'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  return <><Filters filters={filters} setFilters={setFilters} records={records} language={language} /><section className="workspace"><div className="section-heading"><p>03 / ELDERLY WELFARE & MEDICAL SUBSIDY PUBLIC RECORDS</p><h2>{zh ? '假牙補助醫療院所名單' : 'Denture Subsidy Medical Providers'}</h2><span>{zh ? '查詢臺北市假牙補助醫療院所公開資料，包含補助類型、區域、院所名稱、地址與連絡電話，作為老人福利與醫療補助公開資訊。' : 'Look up Taipei denture subsidy medical provider public records, including subsidy type, area, medical institution name, address, and contact phone as elderly welfare and medical subsidy public information.'}</span></div><div className="subtabs">{views.map(([id, label]) => <button className={view === id ? 'active' : ''} onClick={() => setView(id)} key={id}>{label}</button>)}</div><div className="notice subtle">{zh ? '假牙補助醫療院所名單為臺北市公開資料中的假牙補助相關醫療院所清冊，僅供查詢補助類型、區域、院所名稱、地址與連絡電話等來源欄位使用，不代表即時門診時間、即時預約名額、補助資格判定、補助金額、費用標準、牙科治療建議、醫療建議、服務品質排名、急診或緊急醫療服務、即時營運狀態或官方背書。' : 'Denture subsidy medical provider data is Taipei public-data directory information for medical institutions related to denture subsidy services. It is for looking up source fields only and does not represent real-time clinic hours, appointment availability, subsidy eligibility, subsidy amount, fees, dental treatment advice, medical advice, service quality ranking, emergency service, operating status, or endorsement.'}</div>
    {view === 'overview' && <Overview summary={activeSummary} language={language} />}{view === 'map' && <ProviderMap summary={activeSummary} language={language} viewDistrict={openDistrict} />}{view === 'directory' && <><div className="section-heading inline"><div /><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆符合紀錄' : 'matching records'}</span></strong></div><Directory records={filtered} language={language} /></>}{view === 'compare' && <Compare summary={activeSummary} related={related} language={language} />}{view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料內容' : 'Data contents'}</h3><p>{zh ? '假牙補助醫療院所名單提供臺北市假牙補助相關醫療院所公開資料，欄位包含補助類型、區域、院所名稱、地址與連絡電話。本網站保留來源區域欄位，並從地址解析臺北市行政區與道路名稱，整理為行政區分布與院所清單。資料未提供官方經緯度，因此預設不顯示精確點位。' : 'Denture subsidy medical provider data provides Taipei public records for medical institutions related to denture subsidy services. Fields include subsidy type, area, medical institution name, address, and contact phone. This site preserves the source area field, parses Taipei districts and road names from addresses, and organizes the data into district distribution and a provider directory. The data does not provide official coordinates, so exact points are not shown by default.'}</p></article><article><h3>{zh ? '解讀限制' : 'Interpretation limits'}</h3><p>{zh ? '本資料為假牙補助醫療院所公開名冊，僅供查詢來源欄位與統計整理，不代表即時門診時間、即時預約名額、補助資格判定、補助金額、費用標準、牙科治療建議、醫療建議、服務品質排名、急診或緊急醫療服務、即時營運狀態或官方背書。實際補助資格、補助範圍、申請方式、門診時間、預約方式、費用、醫療評估與最新資訊請以醫療院所、臺北市政府社會局、衛生主管機關、健保署及主管機關公告為準。' : 'This data is a public directory of medical institutions related to denture subsidy services for source-field lookup and statistical organization only. It does not represent real-time clinic hours, real-time appointment availability, subsidy eligibility determination, subsidy amount, fees, dental treatment advice, medical advice, service quality ranking, emergency dental or medical service, real-time operating status, or official endorsement. Actual eligibility, subsidy scope, application method, clinic hours, appointment method, fees, medical evaluation, and latest information should be verified with the medical institution, Taipei City Department of Social Welfare, health authorities, National Health Insurance Administration, and competent-authority announcements.'}</p></article><article><h3>{zh ? '資料來源' : 'Source'}</h3><p><a href="https://data.taipei/dataset/detail?id=76b8b514-e793-4cca-8dcf-065d5af4b760" target="_blank" rel="noreferrer">{zh ? '臺北市假牙補助醫療院所名單' : 'Taipei Denture Subsidy Medical Providers'} ↗</a></p></article></div>}</section></>;
}
