import { useEffect, useMemo, useState } from 'react';
import { loadLocalJson } from './lib/loadLocalJson';

type RecognitionRecord = { id: string; volunteerName?: string; serviceOrganization?: string; reviewAuthority?: string; gender?: string; serviceHours?: string; serviceHoursNumber?: number | null; sourceValues: Record<string, unknown> };

export default function EducationVolunteerRecognitionRecordsModule({ language }: { language: 'zh' | 'en' }) {
  const [records, setRecords] = useState<RecognitionRecord[]>([]);
  const [loadError, setLoadError] = useState(false);
  const [query, setQuery] = useState(''); const [organization, setOrganization] = useState(''); const [authority, setAuthority] = useState(''); const [gender, setGender] = useState(''); const [minimumHours, setMinimumHours] = useState(''); const [maximumHours, setMaximumHours] = useState('');

  useEffect(() => {
    let active = true;
    loadLocalJson<RecognitionRecord[]>('data/education-volunteer-recognition-records/records.json')
      .then((loadedRecords) => { if (active && Array.isArray(loadedRecords)) setRecords(loadedRecords); else if (active) setLoadError(true); })
      .catch(() => { if (active) setLoadError(true); });
    return () => { active = false; };
  }, []);

  const filtered = useMemo(() => records.filter((record) => (!query || [record.volunteerName, record.serviceOrganization, record.reviewAuthority].join(' ').includes(query)) && (!organization || record.serviceOrganization === organization) && (!authority || record.reviewAuthority === authority) && (!gender || record.gender === gender) && (!minimumHours || (record.serviceHoursNumber ?? -Infinity) >= Number(minimumHours)) && (!maximumHours || (record.serviceHoursNumber ?? Infinity) <= Number(maximumHours))), [records, query, organization, authority, gender, minimumHours, maximumHours]);
  const totalHours = filtered.reduce((total, record) => total + (record.serviceHoursNumber ?? 0), 0);
  const organizations = [...new Set(records.map((record) => record.serviceOrganization).filter(Boolean))]; const authorities = [...new Set(records.map((record) => record.reviewAuthority).filter(Boolean))]; const genders = [...new Set(records.map((record) => record.gender).filter(Boolean))];
  const zh = language === 'zh';

  return <section className="module-panel generated-module"><h1>{zh ? '教育局志工表揚名單' : 'Education Bureau Volunteer Recognition Records'}</h1><p className="notice subtle">{zh ? '本資料為臺北市政府教育局公開之志願服務表揚紀錄，僅供公共資料與志願服務統計探索使用。服務時數及表揚紀錄應依原始資料與主管機關公告為準，本系統不應用於個人評分、排名、身分推論或人物背景分析。' : 'This dataset contains public volunteer recognition records published by the Taipei City Government Department of Education. It is provided for public-data and volunteer-service statistical exploration only. Service hours and recognition records should be verified against the original source. The dashboard must not be used for individual scoring, ranking, identity inference, or personal profiling.'}</p>{loadError ? <p className="notice error">{zh ? '無法載入本機資料快照。請稍後再試或查閱原始資料來源。' : 'The local data snapshot could not be loaded. Please try again later or consult the source dataset.'}</p> : <><div className="filters filter-grid"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={zh ? '搜尋姓名、服務單位或審查機關' : 'Search name, organization, or review authority'} /><select value={organization} onChange={(event) => setOrganization(event.target.value)}><option value="">{zh ? '全部服務單位' : 'All organizations'}</option>{organizations.map((value) => <option key={value}>{value}</option>)}</select><select value={authority} onChange={(event) => setAuthority(event.target.value)}><option value="">{zh ? '全部審查機關' : 'All authorities'}</option>{authorities.map((value) => <option key={value}>{value}</option>)}</select><select value={gender} onChange={(event) => setGender(event.target.value)}><option value="">{zh ? '全部性別' : 'All genders'}</option>{genders.map((value) => <option key={value}>{value}</option>)}</select><input type="number" value={minimumHours} onChange={(event) => setMinimumHours(event.target.value)} placeholder={zh ? '最低時數' : 'Minimum hours'} /><input type="number" value={maximumHours} onChange={(event) => setMaximumHours(event.target.value)} placeholder={zh ? '最高時數' : 'Maximum hours'} /></div><div className="summary-grid"><Summary label={zh ? '表揚記錄' : 'Recognition records'} value={filtered.length} /><Summary label={zh ? '記錄服務時數' : 'Recorded service hours'} value={totalHours} /><Summary label={zh ? '平均服務時數' : 'Average service hours'} value={filtered.length ? Math.round(totalHours / filtered.length) : 0} /><Summary label={zh ? '服務單位' : 'Service organizations'} value={new Set(filtered.map((record) => record.serviceOrganization).filter(Boolean)).size} /></div><div className="notes-grid">{filtered.map((record) => <article key={record.id}><h2>{record.serviceOrganization || '—'}</h2><p>{zh ? '服務時數' : 'Service hours'}: {record.serviceHours || '—'}</p><p>{zh ? '審查機關' : 'Review authority'}: {record.reviewAuthority || '—'}</p><details><summary>{zh ? '官方來源欄位' : 'Source fields'}</summary><dl>{Object.entries(record.sourceValues).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl></details></article>)}</div></>}</section>;
}

function Summary({ label, value }: { label: string; value: number }) { return <article><span>{label}</span><strong>{value}</strong></article>; }
