import { useMemo, useState } from 'react';
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet';
import { buildEnterpriseHeadquartersSummary, filterEnterpriseHeadquarters } from './lib/enterpriseHeadquartersDistribution';
import type { EnterpriseHeadquartersCoordinateConversionStatus, EnterpriseHeadquartersCoordinateQuality, EnterpriseHeadquartersFilters, EnterpriseHeadquartersIndustryCategoryGroup, EnterpriseHeadquartersLocationPrecision, EnterpriseHeadquartersRecord, EnterpriseHeadquartersSummary, Language } from './types';

const empty: EnterpriseHeadquartersFilters = { search: '', districtNameFromAddress: '', roadName: '', industryCategoryRaw: '', industryCategoryNormalized: '', industryCategoryGroup: '', recognitionStartYear: '', recognitionEndYear: '', recognitionStatusRelativeToBuildDate: '', addressLooksLikeMultiFloorOrUnit: '', coordinateConversionStatus: '', coordinateQuality: '', locationPrecision: '', hasValidConvertedCoordinates: '' };
const groupLabel = (v: EnterpriseHeadquartersIndustryCategoryGroup | string, zh: boolean) => ({ electronic_information: zh ? '電子資訊' : 'Electronic information', consumer_life_chemical: zh ? '民生化工' : 'Consumer / life / chemical', metal_machinery_electrical: zh ? '金屬機電' : 'Metal, machinery & electrical', technical_services: zh ? '技術服務' : 'Technical services', other: zh ? '其他' : 'Other', unknown: zh ? '未知' : 'Unknown' }[v] ?? v);
const statusLabel = (v: string | undefined, zh: boolean) => ({ active_on_build_date: zh ? '建置日仍在認定期間' : 'Active on build date', expired_on_build_date: zh ? '建置日時已逾期' : 'Expired on build date', future_on_build_date: zh ? '建置日尚未開始' : 'Future on build date', unknown: zh ? '未知' : 'Unknown' }[v ?? 'unknown'] ?? (v ?? (zh ? '未知' : 'Unknown')));
const conversionLabel = (v: EnterpriseHeadquartersCoordinateConversionStatus | string, zh: boolean) => ({ converted_from_twd97_tm2: zh ? '已由TWD97/TM2轉換' : 'Converted from TWD97/TM2', already_wgs84: zh ? '已是WGS84' : 'Already WGS84', invalid_source_coordinate: zh ? '來源座標無效' : 'Invalid source coordinate', outside_taipei_bounds_after_conversion: zh ? '轉換後超出臺北範圍' : 'Outside Taipei bounds after conversion', missing: zh ? '缺少座標' : 'Missing', conversion_failed: zh ? '轉換失敗' : 'Conversion failed', unknown: zh ? '未知' : 'Unknown' }[v] ?? v);
const qualityLabel = (v: EnterpriseHeadquartersCoordinateQuality | string, zh: boolean) => ({ valid_converted_wgs84_taipei: zh ? '有效轉換WGS84座標' : 'Valid converted WGS84 coordinate', valid_wgs84_taipei: zh ? '有效WGS84座標' : 'Valid WGS84 coordinate', outside_taipei_bounds: zh ? '超出臺北範圍' : 'Outside Taipei bounds', invalid: zh ? '無效座標' : 'Invalid coordinate', missing: zh ? '缺少座標' : 'Missing coordinate' }[v] ?? v);
const precisionLabel = (v: EnterpriseHeadquartersLocationPrecision | string, zh: boolean) => ({ converted_source_coordinate: zh ? '來源座標轉換' : 'Converted source coordinate', official_wgs84_coordinate: zh ? '官方WGS84座標' : 'Official WGS84 coordinate', district_address: zh ? '行政區與地址' : 'District and address', district_only: zh ? '僅行政區' : 'District only', missing: zh ? '缺漏' : 'Missing' }[v] ?? v);
const notice = (zh: boolean) => zh ? '臺北市企業營運總部分布圖提供企業名稱、日期、公司地址、產業類別、座標X與座標Y等來源欄位，僅供企業營運總部公開資料查詢、產業設施分布、企業地理與經濟設施目錄資料探索使用。本資料不代表即時營業狀態、完整公司登記狀態、投資建議、股票建議、信用評等、就業或徵才資訊、法規遵循保證、企業品質、辦公室邊界、辦公室入口、房地產估價、租金預測、消費建議、法律意見或官方背書。' : 'Taipei enterprise operational headquarters distribution records provide company name, date period, company address, industry category, coordinate X, and coordinate Y. They are for enterprise headquarters public-record lookup, industrial facility distribution, enterprise geography, and economic facility directory data exploration only. This data does not represent real-time operating status, complete company registration status, investment advice, stock advice, credit rating, employment or hiring information, compliance guarantee, company quality, office boundary, office entrance, real-estate appraisal, rent forecast, consumer advice, legal advice, or official endorsement.';

function BarChart({ title, data }: { title: string; data: Array<{ label: string; value: number }> }) {
  const max = Math.max(...data.map((d) => d.value), 1);
  return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((d) => <div className="bar-row" key={d.label}><span title={d.label}>{d.label}</span><div><i style={{ width: `${Math.max(2, d.value / max * 100)}%` }} /></div><b>{d.value.toLocaleString()}</b></div>)}</div></section>;
}
const options = (records: EnterpriseHeadquartersRecord[], key: (r: EnterpriseHeadquartersRecord) => string | undefined) => [...new Set(records.map(key).filter(Boolean) as string[])].sort((a, b) => a.localeCompare(b, 'zh-Hant'));

function Filters({ records, filters, setFilters, language }: { records: EnterpriseHeadquartersRecord[]; filters: EnterpriseHeadquartersFilters; setFilters: (filters: EnterpriseHeadquartersFilters) => void; language: Language }) {
  const zh = language === 'zh';
  const select = (key: keyof EnterpriseHeadquartersFilters, label: string, values: string[], render = (v: string) => v) => <label><span>{label}</span><select value={filters[key]} onChange={(e) => setFilters({ ...filters, [key]: e.target.value })}><option value="">{zh ? '全部' : 'All'}</option>{values.map((v) => <option value={v} key={v}>{render(v)}</option>)}</select></label>;
  return <section className="filters"><label className="search"><span>{zh ? '搜尋' : 'Search'}</span><input value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} placeholder={zh ? '搜尋企業名稱、公司地址、行政區或產業類別' : 'Search company name, address, district, or industry category'} /></label>
    {select('districtNameFromAddress', zh ? '行政區' : 'District', options(records, (r) => r.districtNameFromAddress))}
    {select('roadName', zh ? '道路' : 'Road', options(records, (r) => r.roadName))}
    {select('industryCategoryGroup', zh ? '產業類別群組' : 'Industry category group', options(records, (r) => r.industryCategoryGroup), (v) => groupLabel(v, zh))}
    {select('industryCategoryRaw', zh ? '來源產業類別' : 'Raw industry category', options(records, (r) => r.industryCategoryRaw))}
    {select('recognitionStatusRelativeToBuildDate', zh ? '相對建置日認定狀態' : 'Recognition status', options(records, (r) => r.recognitionStatusRelativeToBuildDate), (v) => statusLabel(v, zh))}
    {select('coordinateConversionStatus', zh ? '座標轉換狀態' : 'Coordinate conversion status', options(records, (r) => r.coordinateConversionStatus), (v) => conversionLabel(v, zh))}
    {select('coordinateQuality', zh ? '座標品質' : 'Coordinate quality', options(records, (r) => r.coordinateQuality), (v) => qualityLabel(v, zh))}
    {select('hasValidConvertedCoordinates', zh ? '有有效轉換座標' : 'Has valid converted coordinates', ['yes', 'no'], (v) => v === 'yes' ? (zh ? '是' : 'Yes') : (zh ? '否' : 'No'))}
    <button onClick={() => setFilters(empty)}>{zh ? '清除篩選' : 'Clear filters'}</button></section>;
}

function MapView({ records, language }: { records: EnterpriseHeadquartersRecord[]; language: Language }) {
  const zh = language === 'zh';
  const groups = useMemo(() => [...records.filter((r) => r.coordinateValid && r.latitude !== undefined && r.longitude !== undefined).reduce((m, r) => m.set(r.coordinatePairKey ?? r.id, [...(m.get(r.coordinatePairKey ?? r.id) ?? []), r]), new Map<string, EnterpriseHeadquartersRecord[]>()).values()], [records]);
  return <div className="map-wrap"><div className="notice">{zh ? '企業營運總部分布圖提供座標X與座標Y，本模組會將來源投影座標轉換為WGS84經緯度後顯示點位。點位僅供企業營運總部公開資料查詢與位置參考，不代表公司邊界、辦公室邊界、入口位置、即時營業狀態、法規遵循狀態、投資價值、信用狀態、徵才狀態或官方推薦。' : 'Enterprise headquarters distribution records provide coordinate X and coordinate Y. This module converts the source projected coordinates to WGS84 longitude and latitude before displaying points. Points are for enterprise headquarters public-record lookup and location reference only and do not represent company boundaries, office boundaries, entrance locations, real-time operating status, compliance status, investment value, credit status, hiring status, or official recommendation.'}</div><MapContainer center={[25.072, 121.54]} zoom={11} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap contributors &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" />{groups.map((items) => <CircleMarker key={items[0].coordinatePairKey ?? items[0].id} center={[items[0].latitude!, items[0].longitude!]} radius={7 + Math.min(16, items.length * 2)} pathOptions={{ fillColor: '#2f7b74', fillOpacity: .72, color: '#fff7e8', weight: 2 }}><Popup><div className="map-popup"><strong>{items.length > 1 ? `${items.length} ${zh ? '筆企業總部紀錄' : 'enterprise headquarters records'}` : items[0].companyName}</strong>{items.slice(0, 8).map((r) => <p key={r.id}>{r.companyName} · {r.industryCategoryRaw}<br />{r.companyAddress}</p>)}<p>{items[0].latitude?.toFixed(6)}, {items[0].longitude?.toFixed(6)}</p><small>{zh ? '此資料為企業營運總部分布圖來源紀錄，僅供公開資料查詢。請勿將其解讀為即時營業狀態、公司品質、投資建議、信用評等、就業資訊、法規遵循保證、辦公室邊界或官方推薦。' : 'This is a source record from the enterprise headquarters distribution dataset and is for public-data lookup only. Do not interpret it as real-time operating status, company quality, investment advice, credit rating, employment information, compliance guarantee, office boundary, or official recommendation.'}</small></div></Popup></CircleMarker>)}</MapContainer></div>;
}

function Directory({ records, language }: { records: EnterpriseHeadquartersRecord[]; language: Language }) {
  const zh = language === 'zh', [limit, setLimit] = useState(120);
  return <><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['企業名稱', '認定日期期間', '產業類別', '行政區', '公司地址', '座標轉換狀態', '地圖查詢', '來源明細'] : ['Company name', 'Recognition period', 'Industry category', 'District', 'Company address', 'Coordinate conversion status', 'Map lookup', 'Source details']).map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{records.slice(0, limit).map((r) => <tr key={r.id}><th>{r.companyName}</th><td>{r.recognitionPeriodRaw}</td><td>{r.industryCategoryRaw}</td><td>{r.districtNameFromAddress ?? '—'}</td><td>{r.companyAddress}</td><td>{conversionLabel(r.coordinateConversionStatus, zh)}</td><td>{r.googleMapsQuery ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(r.googleMapsQuery)}`} target="_blank" rel="noreferrer">{zh ? '地圖查詢' : 'Map lookup'}</a> : '—'}</td><td><details><summary>{zh ? '來源明細' : 'Source details'}</summary><dl><div><dt>{zh ? '認定狀態' : 'Recognition status'}</dt><dd>{statusLabel(r.recognitionStatusRelativeToBuildDate, zh)}</dd></div><div><dt>{zh ? '認定起訖' : 'Recognition dates'}</dt><dd>{r.recognitionStartRocDate ?? '—'} / {r.recognitionEndRocDate ?? '—'} · {r.recognitionStartGregorianDate ?? '—'} / {r.recognitionEndGregorianDate ?? '—'}</dd></div><div><dt>{zh ? '道路' : 'Road'}</dt><dd>{r.roadName ?? '—'}</dd></div><div><dt>{zh ? '標準化產業類別' : 'Normalized industry category'}</dt><dd>{r.industryCategoryNormalized ?? '—'} · {groupLabel(r.industryCategoryGroup, zh)}</dd></div><div><dt>{zh ? '來源座標' : 'Source coordinates'}</dt><dd>X {r.sourceCoordinateX} / Y {r.sourceCoordinateY}</dd></div><div><dt>{zh ? '轉換座標' : 'Converted coordinates'}</dt><dd>{r.latitude?.toFixed(6) ?? '—'}, {r.longitude?.toFixed(6) ?? '—'}</dd></div><div><dt>{zh ? '座標品質' : 'Coordinate quality'}</dt><dd>{qualityLabel(r.coordinateQuality, zh)}</dd></div><div><dt>{zh ? '位置精度' : 'Location precision'}</dt><dd>{precisionLabel(r.locationPrecision, zh)}</dd></div><div><dt>{zh ? '資料來源' : 'Source'}</dt><dd>{r.source} · {r.sourceAgency}</dd></div></dl></details></td></tr>)}</tbody></table></div>{limit < records.length && <button className="load-more" onClick={() => setLimit(limit + 120)}>{zh ? '載入更多' : 'Load more'} · {records.length - limit}</button>}</>;
}

export default function EnterpriseHeadquartersDistributionModule({ records, summary, related, language }: { records: EnterpriseHeadquartersRecord[]; summary: EnterpriseHeadquartersSummary; related?: { factories?: number; dawannan?: number; businessChanges?: number; companyChanges?: number }; language: Language }) {
  const zh = language === 'zh', [view, setView] = useState<'overview' | 'map' | 'districts' | 'categories' | 'directory' | 'quality' | 'compare' | 'notes'>('overview'), [filters, setFilters] = useState(empty);
  const filtered = useMemo(() => filterEnterpriseHeadquarters(records, filters), [records, filters]);
  const activeSummary = useMemo(() => filters === empty ? summary : buildEnterpriseHeadquartersSummary(filtered), [filtered, filters, summary]);
  const tabs = [['overview', zh ? '總覽' : 'Overview'], ['map', zh ? '企業總部地圖' : 'Enterprise Headquarters Map'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['categories', zh ? '產業類別' : 'Industry Categories'], ['directory', zh ? '企業清單' : 'Enterprise Directory'], ['quality', zh ? '資料品質' : 'Data Quality'], ['compare', zh ? '與產業資料比較' : 'Compare Industrial Records'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  return <section className="workspace"><div className="section-heading"><p>ENTERPRISE HEADQUARTERS</p><h2>{zh ? '企業營運總部分布圖' : 'Enterprise Operational Headquarters Distribution'}</h2><span>{zh ? '查詢臺北市企業營運總部公開資料，包含企業名稱、認定日期期間、公司地址、產業類別與來源座標。' : 'Look up Taipei enterprise operational headquarters public records, including company name, recognition period, company address, industry category, and source coordinates.'}</span></div><div className="notice subtle">{notice(zh)}</div><div className="subtabs">{tabs.map(([id, label]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}>{label}</button>)}</div><Filters records={records} filters={filters} setFilters={setFilters} language={language} />
    {view === 'overview' && <><div className="summary-grid">{[[zh ? '企業營運總部紀錄數' : 'Enterprise headquarters record count', activeSummary.totalRecords], [zh ? '涵蓋行政區數' : 'Districts covered', activeSummary.districtCount], [zh ? '不重複企業名稱數' : 'Unique company name count', activeSummary.uniqueCompanyNameCount], [zh ? '不重複公司地址數' : 'Unique company address count', activeSummary.uniqueCompanyAddressCount], [zh ? '產業類別群組數' : 'Industry category group count', activeSummary.uniqueIndustryCategoryGroupCount], [zh ? '有效轉換座標紀錄數' : 'Valid converted coordinate record count', activeSummary.recordsWithValidConvertedCoordinates], [zh ? '重複座標組數' : 'Duplicate coordinate pair count', activeSummary.coordinateQuality.duplicateCoordinatePairCount], [zh ? '建置日仍在認定期間紀錄數' : 'Records active on build date', activeSummary.recordsActiveOnBuildDate], [zh ? '多樓層或單位地址數' : 'Multi-floor or unit address count', activeSummary.recordsWithMultiFloorOrUnitAddress]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{typeof value === 'number' ? value.toLocaleString() : value}</strong></article>)}</div><div className="chart-grid"><BarChart title={zh ? '各行政區企業營運總部數' : 'Enterprise headquarters by district'} data={activeSummary.byDistrict.map((d) => ({ label: d.districtName, value: d.count }))} /><BarChart title={zh ? '各產業類別群組企業營運總部數' : 'Enterprise headquarters by industry category group'} data={activeSummary.byIndustryCategoryGroup.map((d) => ({ label: groupLabel(d.industryCategoryGroup, zh), value: d.count }))} /><BarChart title={zh ? '認定狀態分布' : 'Recognition status distribution'} data={activeSummary.byRecognitionStatus.map((d) => ({ label: statusLabel(d.recognitionStatusRelativeToBuildDate, zh), value: d.count }))} /><BarChart title={zh ? '座標品質分布' : 'Coordinate quality distribution'} data={activeSummary.byCoordinateQuality.map((d) => ({ label: qualityLabel(d.coordinateQuality, zh), value: d.count }))} /></div></>}
    {view === 'map' && <MapView records={filtered} language={language} />}
    {view === 'districts' && <div className="chart-grid"><BarChart title={zh ? '各行政區企業營運總部數' : 'Enterprise headquarters by district'} data={activeSummary.byDistrict.map((d) => ({ label: d.districtName, value: d.count }))} /><BarChart title={zh ? '各道路企業營運總部數' : 'Headquarters by road name'} data={activeSummary.byRoadName.slice(0, 30).map((d) => ({ label: d.roadName, value: d.count }))} /></div>}
    {view === 'categories' && <div className="chart-grid"><BarChart title={zh ? '各產業類別群組企業營運總部數' : 'Enterprise headquarters by industry category group'} data={activeSummary.byIndustryCategoryGroup.map((d) => ({ label: groupLabel(d.industryCategoryGroup, zh), value: d.count }))} /><BarChart title={zh ? '各來源產業類別企業營運總部數' : 'Enterprise headquarters by raw industry category'} data={activeSummary.byIndustryCategoryRaw.map((d) => ({ label: d.industryCategoryRaw, value: d.count }))} /></div>}
    {view === 'directory' && <><div className="section-heading inline"><div /><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆符合紀錄' : 'matching records'}</span></strong></div><Directory records={filtered} language={language} /></>}
    {view === 'quality' && <div className="chart-grid"><BarChart title={zh ? '座標轉換狀態分布' : 'Coordinate conversion status distribution'} data={activeSummary.byCoordinateConversionStatus.map((d) => ({ label: conversionLabel(d.coordinateConversionStatus, zh), value: d.count }))} /><BarChart title={zh ? '共用地址數' : 'Shared address count'} data={activeSummary.topSharedAddresses.map((d) => ({ label: d.companyAddress, value: d.count }))} /><BarChart title={zh ? '共用座標數' : 'Shared coordinate count'} data={activeSummary.byCoordinatePair.filter((d) => d.count > 1).map((d) => ({ label: d.sampleAddress ?? d.key, value: d.count }))} /></div>}
    {view === 'compare' && <><div className="notice subtle">{zh ? '企業營運總部分布圖與登記工廠、大彎南段工業區廠商、商業或公司登記異動資料性質不同；可並列觀察產業空間分布，但不應合併解讀為相同登記、相同設施、即時營業狀態、法規遵循、信用狀態、投資價值或公司品質。' : 'Enterprise headquarters, registered factories, Dawannan industrial-area companies, and business/company registration change records have different meanings. They can be shown together as industrial spatial context, but should not be merged as the same registration, facility, operating status, compliance, credit status, investment value, or company quality.'}</div><div className="chart-grid"><BarChart title={zh ? '企業營運總部與相關產業資料比較' : 'Enterprise headquarters vs related records'} data={[{ label: zh ? '企業營運總部' : 'Enterprise headquarters', value: activeSummary.totalRecords }, { label: zh ? '登記工廠' : 'Registered factories', value: related?.factories ?? 0 }, { label: zh ? '大彎南段廠商' : 'Dawannan companies', value: related?.dawannan ?? 0 }, { label: zh ? '商業異動' : 'Business changes', value: related?.businessChanges ?? 0 }, { label: zh ? '公司異動' : 'Company changes', value: related?.companyChanges ?? 0 }]} /></div></>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料內容' : 'Data contents'}</h3><p>{zh ? '臺北市企業營運總部分布圖提供臺北市企業營運總部公開資料，欄位包含企業名稱、日期、公司地址、產業類別、座標X與座標Y。本網站保留來源欄位，將來源投影座標轉換為WGS84經緯度後整理為企業總部地圖、行政區分布、產業類別與企業清單。' : 'Taipei enterprise headquarters distribution records provide public information about enterprise operational headquarters in Taipei. Fields include company name, date period, company address, industry category, coordinate X, and coordinate Y. This site preserves the source fields, converts projected coordinates to WGS84, and organizes map, district, category, and directory views.'}</p></article><article><h3>{zh ? '座標轉換' : 'Coordinate conversion'}</h3><p>{zh ? '本資料提供座標X與座標Y，並非直接可用之WGS84經緯度。本網站依 TWD97 / TM2 zone 121 假設轉換並驗證臺北範圍後顯示點位。來源點位不代表公司邊界、辦公室邊界、入口或樓層可進入位置。' : 'This data provides coordinate X and coordinate Y, not directly usable WGS84 longitude and latitude. This site converts them using a TWD97 / TM2 zone 121 assumption and validates Taipei bounds before showing points. Source points do not represent company boundaries, office boundaries, entrances, or accessible floors.'}</p></article><article><h3>{zh ? '解讀限制' : 'Interpretation limits'}</h3><p>{notice(zh)}</p></article><article><h3>{zh ? '資料來源' : 'Source'}</h3><p><a href="https://data.taipei/dataset/detail?id=d23e6ef4-3b78-4e74-8f8e-93cbe0c66515" target="_blank" rel="noreferrer">{zh ? '臺北市企業營運總部分布圖' : 'Taipei Enterprise Operational Headquarters Distribution'} ↗</a></p></article></div>}
  </section>;
}
