import { useEffect, useMemo, useState } from 'react';

type Availability = boolean | null;
type Provider = {
  id: string; districtName: string; institutionCode: string; institutionName: string; address: string; phone: string; reminder: string; googleMapsQuery: string;
  cervicalCancerScreeningRaw: string; oralCancerScreeningRaw: string; colorectalCancerScreeningRaw: string; breastCancerScreeningRaw: string; lungCancerScreeningRaw: string;
  hasCervicalCancerScreening: Availability; hasOralCancerScreening: Availability; hasColorectalCancerScreening: Availability; hasBreastCancerScreening: Availability; hasLungCancerScreening: Availability;
  screeningTypes: string[]; screeningTypeCount: number;
};
const missing = '—';
const services = [
  ['cervical', 'hasCervicalCancerScreening', 'cervicalCancerScreeningRaw', '子宮頸癌篩檢', 'Cervical screening'],
  ['oral', 'hasOralCancerScreening', 'oralCancerScreeningRaw', '口腔癌篩檢', 'Oral screening'],
  ['colorectal', 'hasColorectalCancerScreening', 'colorectalCancerScreeningRaw', '大腸癌篩檢', 'Colorectal screening'],
  ['breast', 'hasBreastCancerScreening', 'breastCancerScreeningRaw', '乳癌篩檢', 'Breast screening'],
  ['lung', 'hasLungCancerScreening', 'lungCancerScreeningRaw', '肺癌篩檢', 'Lung screening'],
] as const;
const grouped = (records: Provider[], key: keyof Provider) => [...new Set(records.map(record => String(record[key] ?? '')).filter(Boolean))]
  .map(label => ({ label, value: records.filter(record => String(record[key] ?? '') === label).length })).sort((a, b) => b.value - a.value);
function Chart({ title, data }: { title: string; data: { label: string; value: number }[] }) {
  const max = Math.max(1, ...data.map(item => item.value));
  return <section className="chart"><h3>{title}</h3><div className="bars">{data.map(item => <div className="bar-row wide-label" key={item.label}><span>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{item.value}</b></div>)}</div></section>;
}
export default function FiveCancerScreeningProvidersModule({ language }: { language: 'zh' | 'en' }) {
  const zh = language === 'zh';
  const [records, setRecords] = useState<Provider[]>([]), [error, setError] = useState(false), [view, setView] = useState('overview'), [search, setSearch] = useState(''), [district, setDistrict] = useState(''), [phone, setPhone] = useState(''), [minimum, setMinimum] = useState(''), [flags, setFlags] = useState<Record<string, string>>({}), [sort, setSort] = useState('name'), [page, setPage] = useState(1);
  useEffect(() => { fetch(`${import.meta.env.BASE_URL}data/five-cancer-screening-providers/records.json`).then(response => { if (!response.ok) throw Error(String(response.status)); return response.json(); }).then(setRecords).catch(() => setError(true)); }, []);
  const reset = (action: () => void) => { action(); setPage(1); };
  const filtered = useMemo(() => records.filter(record => {
    const query = search.trim().toLowerCase();
    if (query && ![record.institutionName, record.institutionCode, record.districtName, record.address, record.phone, record.reminder].join(' ').toLowerCase().includes(query)) return false;
    if (district && record.districtName !== district) return false;
    if (phone && (phone === 'yes' ? !record.phone : Boolean(record.phone))) return false;
    if (minimum && record.screeningTypeCount < Number(minimum)) return false;
    return services.every(([id, flag]) => !flags[id] || (flags[id] === 'yes' ? record[flag] === true : flags[id] === 'no' ? record[flag] === false : record[flag] === null));
  }), [records, search, district, phone, minimum, flags]);
  const byDistrict = useMemo(() => grouped(filtered, 'districtName'), [filtered]);
  const byService = useMemo(() => services.map(([id, flag, , zhLabel, enLabel]) => ({ label: zh ? zhLabel : enLabel, value: filtered.filter(record => record[flag] === true).length })), [filtered, zh]);
  const combinations = useMemo(() => grouped(filtered.map(record => ({ ...record, combination: record.screeningTypes.join('、') || (zh ? '未確認服務' : 'No confirmed services') })) as (Provider & { combination: string })[], 'combination' as keyof Provider), [filtered, zh]);
  const summary = useMemo(() => ({ total: filtered.length, districts: byDistrict.length, phones: filtered.filter(record => Boolean(record.phone)).length, multi: filtered.filter(record => record.screeningTypeCount > 1).length, types: Object.fromEntries(services.map(([id, flag]) => [id, filtered.filter(record => record[flag] === true).length])) as Record<string, number> }), [filtered, byDistrict]);
  const sorted = useMemo(() => [...filtered].sort((a, b) => sort === 'district' ? a.districtName.localeCompare(b.districtName, 'zh-Hant') : sort === 'types' ? b.screeningTypeCount - a.screeningTypeCount : a.institutionName.localeCompare(b.institutionName, 'zh-Hant')), [filtered, sort]);
  const pages = Math.max(1, Math.ceil(sorted.length / 20)), rows = sorted.slice((Math.min(page, pages) - 1) * 20, Math.min(page, pages) * 20);
  const label = (z: string, e: string) => zh ? z : e;
  const status = (raw: string, value: Availability) => raw || (value === null ? missing : value ? label('是', 'Yes') : label('否', 'No'));
  const copy = (value: string) => value && <button className="copy-button" type="button" onClick={() => navigator.clipboard?.writeText(value)}>{label('複製', 'Copy')}</button>;
  const map = (query: string) => query ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`} target="_blank" rel="noreferrer">{label('地圖查詢', 'Map lookup')}</a> : missing;
  const download = () => { const headers = ['Institution code', 'Institution', 'District', 'Address', 'Phone', ...services.map(([, , , , en]) => en), 'Reminder']; const quote = (value: string) => `"${value.replaceAll('"', '""')}"`; const lines = [headers, ...filtered.map(record => [record.institutionCode, record.institutionName, record.districtName, record.address, record.phone, ...services.map(([, flag, raw]) => status(record[raw], record[flag])), record.reminder])].map(row => row.map(value => quote(String(value ?? ''))).join(',')).join('\n'); const url = URL.createObjectURL(new Blob(['\uFEFF', lines], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'five-cancer-screening-providers-filtered.csv'; link.click(); URL.revokeObjectURL(url); };
  if (error) return <section className="workspace"><div className="notice">{label('無法載入本機資料檔。', 'The local data file could not be loaded.')}</div></section>;
  return <section className="workspace"><div className="section-heading"><p>MEDICAL PROVIDERS / CANCER SCREENING</p><h2>{label('五癌篩檢醫療院所', 'Five-Cancer Screening Providers')}</h2><span>{label('公開目錄、篩檢服務摘要與外部地址查詢；不顯示精確地圖標記。', 'Public directory and service summaries with external address lookup only; no exact map markers.')}</span></div>
    <div className="subtabs">{[['overview', label('總覽', 'Overview')], ['districts', label('行政區分布', 'District Distribution')], ['services', label('篩檢服務', 'Screening Services')], ['combinations', label('服務組合', 'Service Combinations')], ['directory', label('醫療院所名錄', 'Medical Provider Directory')], ['quality', label('資料品質', 'Data Quality')], ['notes', label('資料說明', 'Data Notes')]].map(([id, text]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => { setView(id); setPage(1); }}>{text}</button>)}</div>
    <aside className="filters"><label className="search"><input value={search} onChange={event => reset(() => setSearch(event.target.value))} placeholder={label('搜尋院所、代碼、行政區、地址、電話或提醒', 'Search institution, code, district, address, phone, or reminder')} /></label><div className="filter-grid"><label>{label('行政區', 'District')}<select value={district} onChange={event => reset(() => setDistrict(event.target.value))}><option value="">{label('全部', 'All')}</option>{[...new Set(records.map(record => record.districtName).filter(Boolean))].map(value => <option key={value}>{value}</option>)}</select></label><label>{label('最少確認篩檢項目', 'Minimum confirmed services')}<select value={minimum} onChange={event => reset(() => setMinimum(event.target.value))}><option value="">{label('全部', 'All')}</option>{[1, 2, 3, 4, 5].map(value => <option key={value} value={value}>{value}</option>)}</select></label><label>{label('有電話', 'Has phone')}<select value={phone} onChange={event => reset(() => setPhone(event.target.value))}><option value="">{label('全部', 'All')}</option><option value="yes">{label('是', 'Yes')}</option><option value="no">{label('否', 'No')}</option></select></label>{services.map(([id, , , z, e]) => <label key={id}>{label(z, e)}<select value={flags[id] ?? ''} onChange={event => reset(() => setFlags(current => ({ ...current, [id]: event.target.value })))}><option value="">{label('全部', 'All')}</option><option value="yes">{label('確認提供', 'Confirmed')}</option><option value="no">{label('確認未提供', 'Confirmed unavailable')}</option><option value="unknown">{label('未確認', 'Unknown')}</option></select></label>)}</div></aside>
    {view === 'overview' && <><div className="notice subtle">{label('本資料為臺北市五癌篩檢醫療院所公開名錄；名列服務及提醒屬來源紀錄，不代表即時可用性、預約、篩檢或公費資格、時段、費用、適用性、診斷、醫療品質或官方推薦。實際資格與服務請向醫療院所或臺北市政府衛生局確認。', 'This dataset is a public directory of Taipei medical institutions providing five major cancer-screening services. Listed screening services and reminders are source records and do not confirm real-time availability, appointments, screening eligibility, public subsidy eligibility, service hours, fees, screening suitability, diagnosis, medical quality, or official recommendation. Confirm current eligibility and services with the institution or Taipei City Department of Health.')}</div><div className="summary-grid">{[[label('醫療院所總數', 'Total medical institutions'), summary.total], [label('涵蓋行政區', 'Districts covered'), summary.districts], ...services.map(([id, , , z, e]) => [label(z, e), summary.types[id]]), [label('提供多項篩檢', 'Multiple confirmed services'), summary.multi], [label('有電話紀錄', 'Records with phone'), summary.phones]].map(([name, value]) => <article key={String(name)}><span>{name}</span><strong>{value}</strong></article>)}</div><Chart title={label('各行政區院所數', 'Institutions by district')} data={byDistrict} /></>}
    {view === 'districts' && <><Chart title={label('各行政區院所數', 'Institutions by district')} data={byDistrict} /><Chart title={label('各行政區確認篩檢服務數', 'Confirmed screening services by district')} data={byDistrict.map(item => ({ ...item, value: filtered.filter(record => record.districtName === item.label).reduce((total, record) => total + record.screeningTypeCount, 0) }))} /><Chart title={label('有無電話紀錄', 'Records with and without phone')} data={[{ label: label('有電話', 'With phone'), value: summary.phones }, { label: label('無電話', 'Without phone'), value: summary.total - summary.phones }]} /></>}
    {view === 'services' && <><Chart title={label('各篩檢服務院所數', 'Providers by screening type')} data={byService} /><Chart title={label('確認篩檢項目數分布', 'Confirmed screening-type count distribution')} data={[0, 1, 2, 3, 4, 5].map(value => ({ label: `${value}`, value: filtered.filter(record => record.screeningTypeCount === value).length }))} /></>}
    {view === 'combinations' && <Chart title={label('常見篩檢服務組合', 'Most common screening-service combinations')} data={combinations.slice(0, 12)} />}
    {view === 'directory' && <><div className="section-heading inline"><p>{label('篩選後紀錄', 'Filtered records')}</p><strong>{sorted.length}</strong><button type="button" onClick={download}>{label('下載篩選後 CSV', 'Download filtered CSV')}</button><label>{label('排序', 'Sort')}<select value={sort} onChange={event => { setSort(event.target.value); setPage(1); }}><option value="name">{label('院所名稱', 'Institution')}</option><option value="district">{label('行政區', 'District')}</option><option value="types">{label('篩檢項目數', 'Service count')}</option></select></label></div><div className="comparison-scroll procurement-table"><table><thead><tr>{[label('院所', 'Institution'), label('行政區', 'District'), label('地址', 'Address'), label('電話', 'Phone'), ...services.map(([, , , z, e]) => label(z, e)), label('貼心小提醒', 'Reminder'), label('地圖查詢', 'Map lookup')].map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map(record => <tr key={record.id}><th><small>{record.institutionCode || missing}</small><br />{record.institutionName || missing}</th><td>{record.districtName || missing}</td><td>{record.address || missing} {copy(record.address)}</td><td>{record.phone ? <><a href={`tel:${record.phone.replace(/[^\d+]/g, '')}`}>{record.phone}</a> {copy(record.phone)}</> : missing}</td>{services.map(([id, flag, raw]) => <td key={id}>{status(record[raw], record[flag])}</td>)}<td>{record.reminder || missing}</td><td>{map(record.googleMapsQuery)}</td></tr>)}</tbody></table></div><div className="pagination"><button type="button" disabled={page <= 1} onClick={() => setPage(value => value - 1)}>{label('上一頁', 'Previous')}</button><span>{page} / {pages}</span><button type="button" disabled={page >= pages} onClick={() => setPage(value => value + 1)}>{label('下一頁', 'Next')}</button></div></>}
    {view === 'quality' && <div className="notes-grid"><article><h3>{label('資料品質', 'Data quality')}</h3><p>{label(`目前篩選結果共有 ${summary.total} 筆紀錄。空白或未對應的篩檢欄位會保留為「未確認」，不會當作未提供。`, `The current selection has ${summary.total} records. Blank or unmapped screening fields remain unknown and are never treated as unavailable.`)}</p></article></div>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{label('資料範圍', 'Data scope')}</h3><p>{label('本目錄只呈現來源列出的篩檢服務與聯絡資訊，不應據以判定即時可用性、資格、補助、醫療品質或任何診斷與治療建議。地址僅供外部地圖搜尋，沒有官方座標與精確地圖標記。', 'This directory only presents source-listed services and contact details. It must not be used to determine current availability, eligibility, subsidy, medical quality, diagnosis, or treatment. Addresses support external map search only; there are no official coordinates or exact map markers.')}</p></article></div>}
  </section>;
}
