import { useEffect, useMemo, useState } from 'react';
import { normalizeFuneralText, type FuneralServiceBusinessRecord } from './lib/funeralServiceBusinesses';

type Language = 'zh' | 'en';
type View = 'find' | 'directory' | 'districts' | 'contacts' | 'coverage' | 'insights' | 'quality' | 'notes';
const root = `${import.meta.env.BASE_URL}data/funeral-service-businesses`;
const sourceUrl = 'https://data.taipei/dataset/detail?id=20143c69-a790-4dec-bb5e-1f0ed7e76c1e';
const viewLabels: Record<View, { zh: string; en: string }> = {
  find: { zh: '查找業者', en: 'Find' }, directory: { zh: '業者名冊', en: 'Directory' }, districts: { zh: '行政區分布', en: 'District Distribution' }, contacts: { zh: '聯絡方式', en: 'Contact' }, coverage: { zh: '地址涵蓋', en: 'Address Coverage' }, insights: { zh: '名冊概況', en: 'Registry Insights' }, quality: { zh: '資料品質', en: 'Quality' }, notes: { zh: '資料說明', en: 'Notes' },
};
const csvCell = (value: string | undefined) => `"${(value ?? '').replaceAll('"', '""')}"`;
const t = (language: Language, zh: string, en: string) => language === 'zh' ? zh : en;

export default function FuneralServiceBusinessesModule({ language }: { language: Language }) {
  const [records, setRecords] = useState<FuneralServiceBusinessRecord[]>([]); const [report, setReport] = useState<any>(null); const [error, setError] = useState(false);
  const [view, setView] = useState<View>('find'); const [query, setQuery] = useState(''); const [district, setDistrict] = useState(''); const [postal, setPostal] = useState(''); const [phone, setPhone] = useState(''); const [address, setAddress] = useState(''); const [sort, setSort] = useState('company'); const [page, setPage] = useState(1);
  useEffect(() => { Promise.all([fetch(`${root}/records.json`).then((r) => r.ok ? r.json() : Promise.reject()), fetch(`${root}/conversion-report.json`).then((r) => r.ok ? r.json() : null)]).then(([rows, nextReport]) => { setRecords(rows); setReport(nextReport); }).catch(() => setError(true)); }, []);
  const districts = useMemo(() => [...new Set(records.map((r) => r.districtName).filter(Boolean))].sort(), [records]); const postals = useMemo(() => [...new Set(records.map((r) => r.postalCode).filter(Boolean))].sort(), [records]);
  const filtered = useMemo(() => { const needle = normalizeFuneralText(query); return records.filter((r) => (!needle || normalizeFuneralText([r.companyName, r.districtName, r.postalCode, r.companyAddress, r.phoneRaw].join(' ')).includes(needle)) && (!district || r.districtName === district) && (!postal || r.postalCode === postal) && (!phone || (phone === 'yes' ? r.hasPhone : !r.hasPhone)) && (!address || (address === 'yes' ? r.hasAddress : !r.hasAddress))).sort((a, b) => sort === 'district' ? (a.districtName || '').localeCompare(b.districtName || '', 'zh-Hant') || a.companyName.localeCompare(b.companyName, 'zh-Hant') : a.companyName.localeCompare(b.companyName, 'zh-Hant')); }, [records, query, district, postal, phone, address, sort]);
  useEffect(() => setPage(1), [query, district, postal, phone, address, sort]); const pageSize = 12; const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const rows = filtered.slice((page - 1) * pageSize, page * pageSize);
  const byDistrict = useMemo(() => [...filtered.reduce((map, r) => { const key = r.districtName || t(language, '未解析行政區', 'Unresolved district'); map.set(key, (map.get(key) ?? 0) + 1); return map; }, new Map<string, number>())].map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count || a.name.localeCompare(b.name, 'zh-Hant')), [filtered, language]);
  const copy = async (value: string) => { try { await navigator.clipboard.writeText(value); } catch { /* permission is browser-dependent */ } };
  const exportCsv = () => { const headers = Object.keys(records[0]?.sourceValues ?? {}); const text = [headers, ...filtered.map((r) => headers.map((h) => r.sourceValues[h]))].map((line) => line.map(csvCell).join(',')).join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([`\uFEFF${text}`], { type: 'text/csv;charset=utf-8' })); a.download = 'taipei-funeral-service-businesses.csv'; a.click(); URL.revokeObjectURL(a.href); };
  if (error) return <section className="module-panel"><h1>{t(language, '臺北市殯葬禮儀服務業', 'Taipei Funeral Service Businesses')}</h1><p>{t(language, '無法載入本機資料快照；請先執行此資料集的轉換指令。', 'The local data snapshot could not be loaded. Run this dataset’s conversion command first.')}</p></section>;
  return <section className="module-panel generated-module"><p className="eyebrow">{t(language, '行政名冊資料', 'ADMINISTRATIVE REGISTRY')}</p><h1>{t(language, '臺北市殯葬禮儀服務業', 'Taipei Funeral Service Businesses')}</h1><p className="module-intro">{t(language, '依公司名稱、行政區、郵遞區號、地址或電話，查閱官方備查核准名冊的來源登記資料。', 'Search the official filed-and-approved registry by company, district, postal code, address, or phone.')}</p><p className="notice subtle">{t(language, '本名冊僅反映來源檔的行政登記；不代表目前營業、服務範圍、費用、品質、資格或推薦。請於聯絡前自行確認。', 'This registry reflects only the source file’s administrative record. It does not establish current operation, services, prices, quality, eligibility, or a recommendation. Confirm directly before relying on it.')}</p>
    <div className="subtabs" role="tablist">{(Object.keys(viewLabels) as View[]).map((item) => <button key={item} type="button" role="tab" aria-selected={view === item} className={view === item ? 'active' : ''} onClick={() => setView(item)}>{viewLabels[item][language]}</button>)}</div>
    <div className="filters filter-grid"><label>{t(language, '關鍵字', 'Keyword')}<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={t(language, '公司、行政區、郵遞區號、地址或電話', 'Company, district, postal code, address, or phone')} /></label><label>{t(language, '行政區', 'District')}<select value={district} onChange={(e) => setDistrict(e.target.value)}><option value="">{t(language, '全部', 'All')}</option>{districts.map((item) => <option key={item}>{item}</option>)}</select></label><label>{t(language, '郵遞區號', 'Postal code')}<select value={postal} onChange={(e) => setPostal(e.target.value)}><option value="">{t(language, '全部', 'All')}</option>{postals.map((item) => <option key={item}>{item}</option>)}</select></label><label>{t(language, '電話', 'Phone')}<select value={phone} onChange={(e) => setPhone(e.target.value)}><option value="">{t(language, '全部', 'All')}</option><option value="yes">{t(language, '有資料', 'Present')}</option><option value="no">{t(language, '缺漏', 'Missing')}</option></select></label><label>{t(language, '地址', 'Address')}<select value={address} onChange={(e) => setAddress(e.target.value)}><option value="">{t(language, '全部', 'All')}</option><option value="yes">{t(language, '有資料', 'Present')}</option><option value="no">{t(language, '缺漏', 'Missing')}</option></select></label><label>{t(language, '排序', 'Sort')}<select value={sort} onChange={(e) => setSort(e.target.value)}><option value="company">{t(language, '公司名稱', 'Company name')}</option><option value="district">{t(language, '行政區、公司名稱', 'District, company')}</option></select></label><button type="button" className="button-secondary" onClick={exportCsv}>{t(language, '匯出篩選後 CSV', 'Export filtered CSV')}</button></div>
    <div className="summary-grid"><article><span>{t(language, '來源筆數', 'Source records')}</span><strong>{filtered.length}</strong></article><article><span>{t(language, '行政區', 'Districts')}</span><strong>{new Set(filtered.map((r) => r.districtName).filter(Boolean)).size}</strong></article><article><span>{t(language, '有電話', 'With phone')}</span><strong>{filtered.filter((r) => r.hasPhone).length}</strong></article><article><span>{t(language, '有地址', 'With address')}</span><strong>{filtered.filter((r) => r.hasAddress).length}</strong></article></div>
    {view === 'find' && <><p className="muted">{t(language, `篩選後共有 ${filtered.length} 筆來源記錄。負責人欄位僅於來源細節中呈現，且不納入預設搜尋。`, `${filtered.length} source records match the filters. The responsible-person field is shown only in source details and is excluded from default search.`)}</p><div className="notes-grid">{rows.map((r) => <Card key={r.id} record={r} language={language} copy={copy} />)}</div><Pager page={page} pages={pages} setPage={setPage} language={language} /></>}
    {view === 'directory' && <><div className="comparison-scroll"><table className="procurement-table"><thead><tr><th>{t(language, '公司名稱', 'Company')}</th><th>{t(language, '行政區', 'District')}</th><th>{t(language, '郵遞區號', 'Postal')}</th><th>{t(language, '公司地址', 'Address')}</th><th>{t(language, '電話', 'Phone')}</th><th>{t(language, '來源細節', 'Source details')}</th></tr></thead><tbody>{rows.map((r) => <tr key={r.id}><th>{r.companyName || '—'}</th><td>{r.districtName || '—'}</td><td>{r.postalCode || '—'}</td><td>{r.companyAddress || '—'}</td><td>{r.phoneRaw ? <a href={`tel:${r.phoneRaw.replace(/[^+\d]/g, '')}`}>{r.phoneRaw}</a> : '—'}</td><td><SourceDetails record={r} language={language} /></td></tr>)}</tbody></table></div><Pager page={page} pages={pages} setPage={setPage} language={language} /></>}
    {view === 'districts' && <Bars language={language} title={t(language, '來源登記地址的行政區分布', 'Source registered-address distribution by district')} rows={byDistrict} note={t(language, '這是登記地址的分布，不代表服務範圍或可用性。', 'This is a distribution of registered addresses, not service coverage or availability.')} />}
    {view === 'contacts' && <Bars language={language} title={t(language, '電話欄位完整度', 'Phone-field completeness')} rows={[{ name: t(language, '有電話', 'With phone'), count: filtered.filter((r) => r.hasPhone).length }, { name: t(language, '缺漏電話', 'Missing phone'), count: filtered.filter((r) => !r.hasPhone).length }]} />}
    {view === 'coverage' && <Bars language={language} title={t(language, '地址欄位與行政區解析', 'Address-field and district resolution')} rows={[{ name: t(language, '有公司地址', 'With company address'), count: filtered.filter((r) => r.hasAddress).length }, { name: t(language, '已解析行政區', 'Resolved district'), count: filtered.filter((r) => r.hasResolvedDistrict).length }, { name: t(language, '有郵遞區號', 'With postal code'), count: filtered.filter((r) => r.hasPostalCode).length }]} note={t(language, '地址為來源文字；本模組不進行座標化或顯示地圖標記。', 'Addresses remain source text; this module does not geocode or show map markers.')} />}
    {view === 'insights' && <div className="notes-grid"><article><h2>{t(language, '名冊閱讀方式', 'How to read this registry')}</h2><p>{t(language, `目前篩選條件下有 ${new Set(filtered.map((r) => normalizeFuneralText(r.companyName)).filter(Boolean)).size} 個規範化公司名稱與 ${byDistrict.length} 個行政區值。相同公司名稱或地址可能是不同的來源登記記錄，不會被合併。`, `The current filters contain ${new Set(filtered.map((r) => normalizeFuneralText(r.companyName)).filter(Boolean)).size} normalized company names and ${byDistrict.length} district values. Repeated company names or addresses may be separate source registrations and are not merged.`)}</p></article><article><h2>{t(language, '不做的推論', 'Deliberate non-inferences')}</h2><p>{t(language, '不以筆數排行業者，不推論服務項目、價格、評價、現況或服務區域；需要服務時請直接向業者與主管機關確認。', 'The dashboard does not rank businesses or infer services, prices, quality, current status, or service areas. Confirm needs directly with the business and competent authority.')}</p></article></div>}
    {view === 'quality' && <div className="notes-grid"><article><h2>{t(language, '轉換檢查', 'Conversion checks')}</h2><p>{t(language, `轉換報告記錄 ${report?.funeralServiceBusinesses?.issueCount ?? '—'} 項檢查結果。只有完全相同的來源列會去除；同名或同址的不同列均保留。`, `The conversion report records ${report?.funeralServiceBusinesses?.issueCount ?? '—'} check results. Only exact duplicate source rows are removed; distinct same-name or same-address rows remain.`)}</p></article><article><h2>{t(language, '個人資料處理', 'Personal-data handling')}</h2><p>{t(language, '負責人欄位依來源保留於展開的來源細節，未作人物檔案、排序或預設搜尋用途。', 'The responsible-person field is preserved in expandable source details and is not used for profiles, ranking, or default search.')}</p></article></div>}
    {view === 'notes' && <div className="notes-grid"><article><h2>{t(language, '來源與更新', 'Source and updates')}</h2><p><a href={sourceUrl} target="_blank" rel="noreferrer">{t(language, '臺北市殯葬禮儀服務業備查核准清冊（臺北市資料大平臺）', 'Taipei Funeral Service Businesses Filed-and-Approved Registry (Taipei Open Data Platform)')}</a></p><p>{t(language, '提供機關：臺北市殯葬管理處。來源檔更新：2025-06-11 10:33:01；資料集詮釋資料更新：2025-06-11 10:33:18；更新頻率：每年。', 'Provider: Taipei Mortuary Services Office. Source file updated 2025-06-11 10:33:01; metadata updated 2025-06-11 10:33:18; update frequency: annual.')}</p></article><article><h2>{t(language, '使用提醒', 'Use note')}</h2><p>{t(language, '儀表板為本機產製的公開資料快照，不是即時服務名單。聯絡前請確認目前營業、可提供的服務、費用與安排。', 'This dashboard is a locally generated public-data snapshot, not a real-time service directory. Confirm current operation, services, pricing, and arrangements before contacting a business.')}</p></article></div>}
  </section>;
}

function Card({ record, language, copy }: { record: FuneralServiceBusinessRecord; language: Language; copy: (value: string) => void }) { return <article><h2>{record.companyName || '—'}</h2><p><span className="status-badge">{t(language, '來源行政名冊記錄', 'Source registry record')}</span></p><p>{[record.districtName, record.postalCode].filter(Boolean).join(' · ') || '—'}</p><p>{record.companyAddress || '—'}</p><p>{record.phoneRaw ? <a href={`tel:${record.phoneRaw.replace(/[^+\d]/g, '')}`}>{record.phoneRaw}</a> : '—'}</p><p>{record.externalMapQuery && <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.externalMapQuery)}`} target="_blank" rel="noreferrer">{t(language, '外部地圖查詢', 'External map lookup')}</a>}{record.phoneRaw && <> · <button className="link-button" type="button" onClick={() => copy(record.phoneRaw)}>{t(language, '複製電話', 'Copy phone')}</button></>}{record.companyAddress && <> · <button className="link-button" type="button" onClick={() => copy(record.companyAddress)}>{t(language, '複製地址', 'Copy address')}</button></>}</p><SourceDetails record={record} language={language} /></article>; }
function SourceDetails({ record, language }: { record: FuneralServiceBusinessRecord; language: Language }) { return <details><summary>{t(language, '來源細節', 'Source details')}</summary><dl>{Object.entries(record.sourceValues).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value || '—'}</dd></div>)}</dl></details>; }
function Bars({ language, title, rows, note }: { language: Language; title: string; rows: Array<{ name: string; count: number }>; note?: string }) { const max = Math.max(1, ...rows.map((r) => r.count)); return <section className="chart"><h2>{title}</h2>{note && <p className="muted">{note}</p>}<div className="bars">{rows.map((r) => <div key={r.name} className="bar-row wide-label"><span>{r.name}</span><div><i style={{ width: `${r.count / max * 100}%` }} /></div><b>{r.count}</b></div>)}</div>{!rows.length && <p>{t(language, '沒有可顯示的來源值。', 'No source values to display.')}</p>}</section>; }
function Pager({ page, pages, setPage, language }: { page: number; pages: number; setPage: (next: number | ((current: number) => number)) => void; language: Language }) { return <div className="pagination"><button type="button" disabled={page <= 1} onClick={() => setPage((current) => current - 1)}>{t(language, '上一頁', 'Previous')}</button><span>{page} / {pages}</span><button type="button" disabled={page >= pages} onClick={() => setPage((current) => current + 1)}>{t(language, '下一頁', 'Next')}</button></div>; }
