import { useEffect, useMemo, useState } from 'react';

type Record = { id: string; sourceSequenceNumber: string; institutionName: string; postalCode: string; districtName: string; address: string; phone: string; hasPhone: boolean; hasAddress: boolean; googleMapsQuery: string };
type Report = { duplicates: string[]; missingNames: string[]; missingAddresses: string[]; malformedPhones: string[]; unknownPostalCodes: string[]; unresolvedDistricts: string[] };
const empty = '—';
export default function GeneralChineseMedicineInstitutionsModule({ language }: { language: 'zh' | 'en' }) {
  const zh = language === 'zh', t = (chinese: string, english: string) => zh ? chinese : english;
  const [records, setRecords] = useState<Record[]>([]), [report, setReport] = useState<Report | null>(null), [error, setError] = useState(false), [view, setView] = useState('overview'), [search, setSearch] = useState(''), [district, setDistrict] = useState(''), [postal, setPostal] = useState(''), [phone, setPhone] = useState(''), [address, setAddress] = useState(''), [sort, setSort] = useState('name'), [page, setPage] = useState(1);
  useEffect(() => { const base = `${import.meta.env.BASE_URL}data/general-chinese-medicine-institutions/`; fetch(`${base}records.json`).then((response) => { if (!response.ok) throw Error(); return response.json(); }).then(setRecords).catch(() => setError(true)); fetch(`${base}conversion-report.json`).then((response) => response.ok ? response.json() : null).then(setReport).catch(() => setReport(null)); }, []);
  const reset = (setter: (value: string) => void, value: string) => { setter(value); setPage(1); };
  const filtered = useMemo(() => records.filter((record) => { const query = search.trim().toLowerCase(); return (!query || [record.institutionName, record.districtName, record.postalCode, record.address, record.phone].join(' ').toLowerCase().includes(query)) && (!district || record.districtName === district) && (!postal || record.postalCode === postal) && (!phone || (phone === 'yes' ? record.hasPhone : !record.hasPhone)) && (!address || (address === 'yes' ? record.hasAddress : !record.hasAddress)); }), [records, search, district, postal, phone, address]);
  const count = (field: 'districtName' | 'postalCode') => [...new Set(filtered.map((record) => record[field]).filter(Boolean))].map((label) => ({ label, value: filtered.filter((record) => record[field] === label).length })).sort((a, b) => b.value - a.value || a.label.localeCompare(b.label, 'zh-Hant'));
  const districts = useMemo(() => count('districtName'), [filtered]), postals = useMemo(() => count('postalCode'), [filtered]);
  const summary = useMemo(() => ({ total: filtered.length, unique: new Set(filtered.map((record) => record.institutionName).filter(Boolean)).size, districts: districts.length, postals: postals.length, phones: filtered.filter((record) => record.hasPhone).length, addresses: filtered.filter((record) => record.hasAddress).length, top: districts[0]?.label || empty }), [filtered, districts, postals]);
  const sorted = useMemo(() => [...filtered].sort((a, b) => sort === 'district' ? a.districtName.localeCompare(b.districtName, 'zh-Hant') || a.institutionName.localeCompare(b.institutionName, 'zh-Hant') : sort === 'postal' ? a.postalCode.localeCompare(b.postalCode) || a.institutionName.localeCompare(b.institutionName, 'zh-Hant') : sort === 'id' ? a.sourceSequenceNumber.localeCompare(b.sourceSequenceNumber, undefined, { numeric: true }) : a.institutionName.localeCompare(b.institutionName, 'zh-Hant')), [filtered, sort]);
  const pages = Math.max(1, Math.ceil(sorted.length / 25)), rows = sorted.slice((Math.min(page, pages) - 1) * 25, Math.min(page, pages) * 25);
  const chart = (title: string, data: { label: string; value: number }[]) => { const max = Math.max(1, ...data.map((item) => item.value)); return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) => <div className="bar-row wide-label" key={item.label}><span>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{item.value}</b></div>)}</div></section>; };
  const copy = (value: string) => value && <button type="button" className="copy-button" aria-label={t('複製', 'Copy')} onClick={() => navigator.clipboard?.writeText(value)}>{t('複製', 'Copy')}</button>;
  const download = () => { const quote = (value: string) => `"${value.replaceAll('"', '""')}"`, csv = [['ID', 'Institution name', 'District', 'Postal code', 'Address', 'Phone'], ...filtered.map((record) => [record.sourceSequenceNumber, record.institutionName, record.districtName, record.postalCode, record.address, record.phone])].map((line) => line.map(quote).join(',')).join('\n'), url = URL.createObjectURL(new Blob(['\uFEFF', csv], { type: 'text/csv;charset=utf-8' })), anchor = document.createElement('a'); anchor.href = url; anchor.download = 'general-chinese-medicine-institutions-filtered.csv'; anchor.click(); URL.revokeObjectURL(url); };
  if (error) return <section className="workspace"><div className="notice">{t('無法載入本機資料檔。', 'The local data file could not be loaded.')}</div></section>;
  const phoneChart = [{ label: t('有電話', 'With phone'), value: summary.phones }, { label: t('無電話', 'Without phone'), value: summary.total - summary.phones }];
  return <section className="workspace"><div className="section-heading"><p>MEDICAL PROVIDERS / CHINESE MEDICINE</p><h2>{t('中醫一般科醫療機構', 'General Chinese Medicine Institutions')}</h2><span>{t('公開名錄、行政區統計與外部地址查詢；不建立精確地圖標記。', 'Public directory, district summaries, and external address lookup only; no exact map markers.')}</span></div>
    <div className="subtabs">{[['overview', t('總覽', 'Overview')], ['districts', t('行政區分布', 'District Distribution')], ['postals', t('郵遞區號分布', 'Postal Code Distribution')], ['directory', t('機構名錄', 'Institution Directory')], ['quality', t('資料品質', 'Data Quality')], ['notes', t('資料說明', 'Data Notes')]].map(([id, label]) => <button type="button" className={view === id ? 'active' : ''} key={id} onClick={() => { setView(id); setPage(1); }}>{label}</button>)}</div>
    <aside className="filters"><label className="search"><input value={search} onChange={(event) => reset(setSearch, event.target.value)} placeholder={t('搜尋機構、行政區、郵遞區號、地址或電話', 'Search institution, district, postal code, address, or phone')} /></label><div className="filter-grid"><label>{t('行政區', 'District')}<select value={district} onChange={(event) => reset(setDistrict, event.target.value)}><option value="">{t('全部', 'All')}</option>{[...new Set(records.map((record) => record.districtName).filter(Boolean))].map((item) => <option key={item}>{item}</option>)}</select></label><label>{t('郵遞區號', 'Postal code')}<select value={postal} onChange={(event) => reset(setPostal, event.target.value)}><option value="">{t('全部', 'All')}</option>{[...new Set(records.map((record) => record.postalCode).filter(Boolean))].sort().map((item) => <option key={item}>{item}</option>)}</select></label>{[[t('有電話', 'Has phone'), phone, setPhone], [t('有地址', 'Has address'), address, setAddress]].map(([label, value, setter]) => <label key={String(label)}>{String(label)}<select value={String(value)} onChange={(event) => reset(setter as (value: string) => void, event.target.value)}><option value="">{t('全部', 'All')}</option><option value="yes">{t('是', 'Yes')}</option><option value="no">{t('否', 'No')}</option></select></label>)}</div></aside>
    {view === 'overview' && <><div className="notice subtle">{t('本資料為臺北市中醫一般科醫療機構公開名錄，僅供醫療院所與公共資料查詢參考，不代表即時營運狀態、門診時間、預約狀態、診療項目、費用、醫療品質、醫事人員專長、診斷、治療、用藥或官方推薦。實際服務請向機構或臺北市政府衛生局確認。', 'This dataset is a public directory of general Chinese-medicine institutions in Taipei. It does not represent real-time operating status, clinic hours, appointment availability, available treatments, fees, medical quality, practitioner specialties, diagnosis, treatment, medication, or official recommendation. Confirm current services with the institution or Taipei City Department of Health.')}</div><div className="summary-grid">{[[t('機構總數', 'Total institutions'), summary.total], [t('不重複機構名稱', 'Unique institution names'), summary.unique], [t('涵蓋行政區', 'Districts covered'), summary.districts], [t('郵遞區號數', 'Postal codes represented'), summary.postals], [t('有電話紀錄', 'Records with phone'), summary.phones], [t('有地址紀錄', 'Records with addresses'), summary.addresses], [t('機構最多的行政區', 'District with most institutions'), summary.top]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div>{chart(t('各行政區機構數', 'Institutions by district'), districts)}</>}
    {view === 'districts' && <>{chart(t('各行政區機構數', 'Institutions by district'), districts)}{chart(t('有無電話紀錄', 'Records with and without phone'), phoneChart)}</>}
    {view === 'postals' && chart(t('各郵遞區號機構數', 'Institutions by postal code'), postals)}
    {view === 'directory' && <><div className="section-heading inline"><p>{t('篩選後紀錄', 'Filtered records')}</p><strong>{sorted.length}</strong><button type="button" onClick={download}>{t('下載篩選後 CSV', 'Download filtered CSV')}</button><label>{t('排序', 'Sort')}<select value={sort} onChange={(event) => { setSort(event.target.value); setPage(1); }}><option value="name">{t('機構名稱', 'Institution name')}</option><option value="district">{t('行政區', 'District')}</option><option value="postal">{t('郵遞區號', 'Postal code')}</option><option value="id">ID</option></select></label></div><div className="comparison-scroll procurement-table"><table><thead><tr>{[t('序號', 'ID'), t('機構名稱', 'Institution name'), t('行政區', 'District'), t('郵遞區號', 'Postal code'), t('地址', 'Address'), t('電話', 'Phone'), t('地圖查詢', 'Map lookup')].map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((record) => <tr key={record.id}><td>{record.sourceSequenceNumber || empty}</td><th>{record.institutionName || empty}</th><td>{record.districtName || empty}</td><td>{record.postalCode || empty}</td><td>{record.address || empty} {copy(record.address)}</td><td>{record.phone ? <><a href={`tel:${record.phone.replace(/[^\d+]/g, '')}`}>{record.phone}</a> {copy(record.phone)}</> : empty}</td><td>{record.googleMapsQuery ? <a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.googleMapsQuery)}`}>{t('地圖查詢', 'Map lookup')}</a> : empty}</td></tr>)}</tbody></table></div><div className="pagination"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>{t('上一頁', 'Previous')}</button><span>{page} / {pages}</span><button type="button" disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>{t('下一頁', 'Next')}</button></div></>}
    {view === 'quality' && <div className="notes-grid"><article><h3>{t('資料品質', 'Data quality')}</h3><p>{t(`可瀏覽紀錄 ${records.length} 筆。重複 ${report?.duplicates.length ?? 0} 筆、缺少名稱 ${report?.missingNames.length ?? 0} 筆、缺少地址 ${report?.missingAddresses.length ?? 0} 筆、電話格式待確認 ${report?.malformedPhones.length ?? 0} 筆、未知郵遞區號 ${report?.unknownPostalCodes.length ?? 0} 筆、無法可靠判定行政區 ${report?.unresolvedDistricts.length ?? 0} 筆。`, `There are ${records.length} browseable records. The conversion report has ${report?.duplicates.length ?? 0} duplicate rows, ${report?.missingNames.length ?? 0} missing names, ${report?.missingAddresses.length ?? 0} missing addresses, ${report?.malformedPhones.length ?? 0} phone values to verify, ${report?.unknownPostalCodes.length ?? 0} unknown postal codes, and ${report?.unresolvedDistricts.length ?? 0} unresolved districts.`)}</p></article></div>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{t('資料範圍', 'Data scope')}</h3><p>{t('地址僅供外部地圖查詢，不表示診療、用藥或服務可用性。本頁不提供診斷、治療、中藥或用藥建議。', 'Addresses are for external map search only and do not establish diagnosis, treatment, medication, or service availability. This page does not provide diagnosis, treatment, herbal medicine, or medication advice.')}</p></article></div>}
  </section>;
}
