import { useEffect, useMemo, useState } from 'react';
import { normalizeHakkaOrganizationText, type HakkaOrganizationRecord } from './lib/hakkaOrganizations';

type Language = 'zh' | 'en'; type View = 'overview' | 'directory' | 'names' | 'leadership' | 'quality' | 'notes';
const dataRoot = `${import.meta.env.BASE_URL}data/hakka-organizations`;
const labels: Record<View, { zh: string; en: string }> = { overview: { zh: '總覽', en: 'Overview' }, directory: { zh: '社團名冊', en: 'Organization Directory' }, names: { zh: '名稱分析', en: 'Organization Name Analysis' }, leadership: { zh: '領導欄位', en: 'Leadership Records' }, quality: { zh: '資料品質', en: 'Data Quality' }, notes: { zh: '資料說明', en: 'Data Notes' } };
const csvCell = (value: string | undefined) => `"${(value ?? '').replaceAll('"', '""')}"`;

export default function HakkaOrganizationsModule({ language }: { language: Language }) {
  const [records, setRecords] = useState<HakkaOrganizationRecord[]>([]); const [report, setReport] = useState<any>(null); const [error, setError] = useState(false); const [view, setView] = useState<View>('overview'); const [query, setQuery] = useState(''); const [leader, setLeader] = useState(''); const [duplicates, setDuplicates] = useState(''); const [sort, setSort] = useState<'id' | 'organization' | 'leader'>('id'); const [page, setPage] = useState(1);
  const t = (zh: string, en: string) => language === 'zh' ? zh : en;
  useEffect(() => { Promise.all([fetch(`${dataRoot}/records.json`).then((r) => r.ok ? r.json() : Promise.reject()), fetch(`${dataRoot}/conversion-report.json`).then((r) => r.ok ? r.json() : null)]).then(([nextRecords, nextReport]) => { setRecords(nextRecords); setReport(nextReport); }).catch(() => setError(true)); }, []);
  const repeatedNames = useMemo(() => { const counts = records.reduce<Record<string, number>>((all, record) => { const key = normalizeHakkaOrganizationText(record.organizationName); if (key) all[key] = (all[key] ?? 0) + 1; return all; }, {}); return new Set(Object.entries(counts).filter(([, count]) => count > 1).map(([name]) => name)); }, [records]);
  const filtered = useMemo(() => { const normalizedQuery = normalizeHakkaOrganizationText(query); return records.filter((record) => (!normalizedQuery || normalizeHakkaOrganizationText([record.sourceSequenceNumber, record.organizationName, record.leaderRaw].join(' ')).includes(normalizedQuery)) && (!leader || (leader === 'yes' ? record.hasLeaderName : !record.hasLeaderName)) && (!duplicates || (duplicates === 'yes' ? repeatedNames.has(normalizeHakkaOrganizationText(record.organizationName)) : !repeatedNames.has(normalizeHakkaOrganizationText(record.organizationName))))); }, [records, query, leader, duplicates, repeatedNames]);
  useEffect(() => setPage(1), [query, leader, duplicates, sort]); const ordered = [...filtered].sort((a, b) => sort === 'organization' ? a.organizationName.localeCompare(b.organizationName, 'zh-Hant') : sort === 'leader' ? a.leaderRaw.localeCompare(b.leaderRaw, 'zh-Hant') : a.sourceSequenceNumber.localeCompare(b.sourceSequenceNumber, 'zh-Hant', { numeric: true })); const pageSize = 20; const pageCount = Math.max(1, Math.ceil(ordered.length / pageSize)); const pageRows = ordered.slice((page - 1) * pageSize, page * pageSize);
  const copy = async (value: string) => { try { await navigator.clipboard.writeText(value); } catch { /* permission may be unavailable */ } }; const exportCsv = () => { const headers = Object.keys(records[0]?.sourceValues ?? { 編號: '', 單位名稱: '', '理事長/會長': '' }); const csv = [headers, ...filtered.map((record) => headers.map((header) => record.sourceValues[header]))].map((row) => row.map(csvCell).join(',')).join('\n'); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: 'text/csv;charset=utf-8' })); anchor.download = 'taipei-hakka-organizations-2020.csv'; anchor.click(); URL.revokeObjectURL(anchor.href); };
  if (error) return <section className="module-panel"><h1>{t('臺北市客家社團', 'Taipei Hakka Organizations')}</h1><p>{t('本機資料檔無法載入。請先執行資料轉換。', 'The local dataset could not be loaded. Run its conversion command first.')}</p></section>;
  return <section className="module-panel generated-module"><p className="eyebrow">{t('歷史公開名冊', 'HISTORICAL PUBLIC REGISTRY')}</p><h1>{t('109年臺北市客家社團名冊', '2020 Taipei Hakka Organizations Registry')}</h1><p className="module-intro">{t('瀏覽來源記錄的編號、社團名稱與理事長／會長欄位。', 'Browse source-recorded sequence numbers, organization names, and chairperson/president fields.')}</p><p className="notice subtle">{t('此資料集是 109 年（2020）名冊。較晚的檔案更新日期不表示社團或領導資訊已更新至現在。', 'This dataset is a 109 ROC year (2020) registry. A later file-update date does not establish that organization or leadership information is current.')}</p>
    <div className="subtabs" role="tablist" aria-label={t('資料檢視', 'Data views')}>{(Object.keys(labels) as View[]).map((item) => <button type="button" key={item} className={view === item ? 'active' : ''} role="tab" aria-selected={view === item} onClick={() => setView(item)}>{labels[item][language]}</button>)}</div>
    <div className="filters filter-grid"><label>{t('搜尋編號、社團或來源領導欄位', 'Search ID, organization, or source leader field')}<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('輸入關鍵字', 'Enter keywords')} /></label><label>{t('理事長／會長欄位', 'Leader field')}<select value={leader} onChange={(event) => setLeader(event.target.value)}><option value="">{t('全部', 'All')}</option><option value="yes">{t('有資料', 'Present')}</option><option value="no">{t('缺漏', 'Missing')}</option></select></label><label>{t('重複社團名稱', 'Repeated organization name')}<select value={duplicates} onChange={(event) => setDuplicates(event.target.value)}><option value="">{t('全部', 'All')}</option><option value="yes">{t('僅可能重複', 'Possible duplicates only')}</option><option value="no">{t('排除可能重複', 'Exclude possible duplicates')}</option></select></label><button type="button" className="button-secondary" onClick={exportCsv}>{t('匯出目前篩選 CSV', 'Export filtered CSV')}</button></div>
    <div className="summary-grid"><article><span>{t('來源紀錄', 'Source records')}</span><strong>{filtered.length}</strong></article><article><span>{t('不同社團名稱', 'Unique organization names')}</span><strong>{new Set(filtered.map((record) => normalizeHakkaOrganizationText(record.organizationName)).filter(Boolean)).size}</strong></article><article><span>{t('有領導欄位', 'Records with leader field')}</span><strong>{filtered.filter((record) => record.hasLeaderName).length}</strong></article><article><span>{t('缺漏領導欄位', 'Missing leader field')}</span><strong>{filtered.filter((record) => !record.hasLeaderName).length}</strong></article><article><span>{t('可能重複名稱紀錄', 'Possible duplicate-name records')}</span><strong>{filtered.filter((record) => repeatedNames.has(normalizeHakkaOrganizationText(record.organizationName))).length}</strong></article><article><span>{t('來源檔更新', 'Source file updated')}</span><strong>2025-06-12</strong></article></div>
    {view === 'overview' && <div className="notes-grid"><article><h2>{t('名冊規模', 'Registry size')}</h2><p>{t(`目前篩選包含 ${filtered.length} 筆客家社團紀錄，代表 ${new Set(filtered.map((record) => normalizeHakkaOrganizationText(record.organizationName)).filter(Boolean)).size} 個不同的來源社團名稱。`, `The filters contain ${filtered.length} Hakka organization records, representing ${new Set(filtered.map((record) => normalizeHakkaOrganizationText(record.organizationName)).filter(Boolean)).size} distinct source organization names.`)}</p></article><article><h2>{t('領導欄位完整度', 'Leader-field completeness')}</h2><p>{t(`有來源領導欄位 ${filtered.filter((record) => record.hasLeaderName).length} 筆；此數字僅是資料完整度，不代表治理或現況。`, `${filtered.filter((record) => record.hasLeaderName).length} records have a source leader field. This is data completeness only, not governance or current status.`)}</p></article></div>}
    {view === 'directory' && <><div className="directory-toolbar"><label>{t('排序', 'Sort')}<select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="id">{t('編號', 'ID')}</option><option value="organization">{t('社團名稱', 'Organization')}</option><option value="leader">{t('領導欄位', 'Leader field')}</option></select></label><span>{t(`顯示 ${ordered.length} 筆`, `Showing ${ordered.length} records`)}</span></div><div className="comparison-scroll"><table className="procurement-table"><thead><tr><th>{t('編號', 'ID')}</th><th>{t('社團', 'Organization')}</th><th>{t('理事長／會長', 'Chairperson or president')}</th><th>{t('資料細節', 'Details')}</th></tr></thead><tbody>{pageRows.map((record) => <tr key={record.id}><td>{record.sourceSequenceNumber || '—'}</td><th>{record.organizationName || '—'}{repeatedNames.has(normalizeHakkaOrganizationText(record.organizationName)) && <small className="status-badge">{t('可能重複；請查原始資料', 'Possible duplicate; review source')}</small>}<br /><button type="button" className="link-button" onClick={() => copy(record.organizationName)}>{t('複製名稱', 'Copy name')}</button></th><td>{record.leaderRaw || '—'}</td><td><details><summary>{t('原始欄位', 'Source fields')}</summary><dl>{Object.entries(record.sourceValues).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value || '—'}</dd></div>)}</dl></details></td></tr>)}</tbody></table></div><Pager page={page} pageCount={pageCount} setPage={setPage} language={language} /></>}
    {view === 'names' && <Bar title={t('名稱重複檢視', 'Organization-name duplicate review')} rows={[{ name: t('唯一名稱紀錄', 'Unique-name records'), count: filtered.filter((record) => !repeatedNames.has(normalizeHakkaOrganizationText(record.organizationName))).length }, { name: t('可能重複名稱紀錄', 'Possible duplicate-name records'), count: filtered.filter((record) => repeatedNames.has(normalizeHakkaOrganizationText(record.organizationName))).length }]} note={t('完全相同的名稱可能是不同來源紀錄，並不表示資料錯誤或組織相同。', 'An exact repeated name may be a distinct source record; it does not establish an error or organization equivalence.')} />}
    {view === 'leadership' && <Bar title={t('領導欄位資料完整度', 'Leader-field data completeness')} rows={[{ name: t('有來源欄位', 'Source field present'), count: filtered.filter((record) => record.hasLeaderName).length }, { name: t('欄位缺漏', 'Field missing'), count: filtered.filter((record) => !record.hasLeaderName).length }]} />}
    {view === 'quality' && <div className="notes-grid"><article><h2>{t('轉換檢查', 'Conversion checks')}</h2><p>{t(`轉換報告問題計數：${report?.hakkaOrganizations?.issueCount ?? '—'}。只移除完全相同的來源列；相似社團名稱和相同人名均不會合併。`, `Conversion-report issue count: ${report?.hakkaOrganizations?.issueCount ?? '—'}. Only exact duplicate source rows are removed; similar organization names and personal names are never merged.`)}</p></article><article><h2>{t('沒有推論的欄位', 'No inferred fields')}</h2><p>{t('來源沒有地址、行政區、電話、網站或座標；本模組不會補建、地理編碼或連結個人資訊。', 'The source has no address, district, phone, website, or coordinates; this module does not infer, geocode, or enrich personal information.')}</p></article></div>}
    {view === 'notes' && <div className="notes-grid"><article><h2>{t('來源與更新', 'Source and updates')}</h2><p><a href="https://data.taipei/dataset/detail?id=0be09825-0507-4624-8c4b-3872b5117fae" target="_blank" rel="noreferrer">{t('109年臺北市客家社團名冊（臺北市資料大平臺）', '2020 Taipei Hakka Organizations Registry (Taipei Open Data Platform)')}</a></p><p>{t('資料檔更新：2025-06-12；詮釋資料更新：2025-12-18；更新頻率：不定期。', 'Source file updated 2025-06-12; metadata updated 2025-12-18; update frequency: irregular.')}</p></article><article><h2>{t('使用提醒', 'Use note')}</h2><p>{t('本資料集為 2020 年來源名冊；不表示目前運作、持續登記、活動、未變動的領導人、會員數、財務情況或政府推薦。請向社團或臺北市政府客家事務委員會確認現況。', 'This is a 2020 source registry. It does not establish current operation, registration, activities, unchanged leadership, membership, finances, or government recommendation. Confirm current status with the organization or Taipei Hakka Affairs Commission.')}</p></article></div>}
  </section>;
}
function Bar({ title, rows, note }: { title: string; rows: Array<{ name: string; count: number }>; note?: string }) { const max = Math.max(1, ...rows.map((row) => row.count)); return <section className="chart"><h2>{title}</h2>{note && <p className="muted">{note}</p>}<div className="bars">{rows.map((row) => <div className="bar-row wide-label" key={row.name}><span>{row.name}</span><div><i style={{ width: `${row.count / max * 100}%` }} /></div><b>{row.count}</b></div>)}</div></section>; }
function Pager({ page, pageCount, setPage, language }: { page: number; pageCount: number; setPage: (value: number | ((current: number) => number)) => void; language: Language }) { return <div className="pagination"><button type="button" disabled={page <= 1} onClick={() => setPage((current) => current - 1)}>{language === 'zh' ? '上一頁' : 'Previous'}</button><span>{page} / {pageCount}</span><button type="button" disabled={page >= pageCount} onClick={() => setPage((current) => current + 1)}>{language === 'zh' ? '下一頁' : 'Next'}</button></div>; }
