import { useEffect, useMemo, useState } from 'react';
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet';
import { DISTRICTS, TAIPEI_DISTRICT_CENTROIDS } from './lib/civicGroups';
import { buildInfantCareCenterEvaluationSummary, filterInfantCareCenterEvaluationInstitutions, normalizeInfantCareInstitutionName } from './lib/infantCareCenterEvaluationResults';
import type {
  InfantCareCenterEvaluationFilters, InfantCareCenterEvaluationGrade, InfantCareCenterEvaluationInstitutionRecord,
  InfantCareCenterEvaluationStatus, InfantCareCenterEvaluationSummary, InfantCareCenterEvaluationYearRecord, Language, QuasiPublicInfantCareCenter,
} from './types';

const emptyFilters: InfantCareCenterEvaluationFilters = { search: '', district: '', districtCode: '', evaluationYear: '', latestEvaluationGrade: '', latestEvaluationStatus: '', anyYearGrade: '', hasLatestResult: '', closedOrSuspended: '', specialNote: '' };
const grades: Record<Language, Record<InfantCareCenterEvaluationGrade, string>> = {
  zh: { excellent: '優等', a: '甲等', b: '乙等', c: '丙等', d: '丁等', not_evaluated: '未評鑑或無資料', closed_or_suspended: '停業或歇業', other: '其他', unknown: '未知' },
  en: { excellent: 'Excellent', a: 'A', b: 'B', c: 'C', d: 'D', not_evaluated: 'Not evaluated / no data', closed_or_suspended: 'Closed or suspended', other: 'Other', unknown: 'Unknown' },
};
const statuses: Record<Language, Record<InfantCareCenterEvaluationStatus, string>> = {
  zh: { evaluated: '已評鑑', guidance_passed: '輔導通過', guidance_required: '列入輔導', closed: '已停業或歇業', suspended: '停業中', not_evaluated: '未評鑑或無資料', special_note: '特殊註記', unknown: '未知' },
  en: { evaluated: 'Evaluated', guidance_passed: 'Guidance passed', guidance_required: 'Guidance required', closed: 'Closed', suspended: 'Suspended', not_evaluated: 'Not evaluated / no data', special_note: 'Special note', unknown: 'Unknown' },
};
const notice = (zh: boolean) => zh ? '托嬰中心評鑑結果資料為臺北市公開資料中的托嬰中心評鑑公開紀錄，僅供查詢編號、機構名稱、行政區、行政區碼與各年度評鑑結果等來源欄位使用，不代表即時收托名額、收費標準、服務品質保證、兒童安全保證、家長選擇建議、違規裁罰結論、即時營運狀態、官方排名、法律意見或官方背書。' : 'Infant care center evaluation result data is Taipei public-data record information about infant care center evaluations for source-field lookup only. It does not represent real-time vacancy, fee levels, service quality guarantee, child safety guarantee, parent selection advice, violation or penalty conclusions, real-time operating status, official ranking, legal advice, or official endorsement.';
const mapNotice = (zh: boolean) => zh ? '托嬰中心評鑑結果資料提供行政區與行政區碼，但未提供地址或官方經緯度。本模組以行政區彙總呈現，不代表機構精確位置、即時收托名額、收費標準、營運狀態、服務品質保證或家長選擇建議。' : 'Infant care center evaluation result data provides district and district code, but no addresses or official coordinates. This module shows district-level summaries only and does not represent exact institution locations, real-time vacancy, fees, operating status, service quality guarantees, or parent selection advice.';

function Bar({ title, rows }: { title: string; rows: Array<{ label: string; count: number }> }) {
  const max = Math.max(...rows.map((row) => row.count), 1);
  return <section className="chart"><h3>{title}</h3><div className="bars">{rows.slice(0, 40).map((row) => <div className="bar-row wide-label" key={row.label}><span title={row.label}>{row.label}</span><div><i style={{ width: `${Math.max(2, row.count / max * 100)}%` }} /></div><b>{row.count.toLocaleString()}</b></div>)}</div></section>;
}

function Filters({ records, summary, filters, setFilters, language }: { records: InfantCareCenterEvaluationInstitutionRecord[]; summary: InfantCareCenterEvaluationSummary; filters: InfantCareCenterEvaluationFilters; setFilters: (filters: InfantCareCenterEvaluationFilters) => void; language: Language }) {
  const zh = language === 'zh', update = (key: keyof InfantCareCenterEvaluationFilters, value: string) => setFilters({ ...filters, [key]: value });
  const districtCodes = [...new Set(records.flatMap((record) => record.districtCode ?? []))].sort();
  const years = summary.byYear.map((item) => item.evaluationYear);
  return <aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(event) => update('search', event.target.value)} placeholder={zh ? '搜尋機構名稱、行政區或評鑑結果' : 'Search institution name, district, or evaluation result'} /></label>
    <div className="filter-grid grant-filters">
      <label>{zh ? '行政區' : 'District'}<select value={filters.district} onChange={(event) => update('district', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{DISTRICTS.map((district) => <option key={district}>{district}</option>)}</select></label>
      <label>{zh ? '行政區碼' : 'District code'}<select value={filters.districtCode} onChange={(event) => update('districtCode', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{districtCodes.map((code) => <option key={code}>{code}</option>)}</select></label>
      <label>{zh ? '評鑑年度' : 'Evaluation year'}<select value={filters.evaluationYear} onChange={(event) => update('evaluationYear', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{years.map((year) => <option value={year} key={year}>{year - 1911} / {year}</option>)}</select></label>
      <label>{zh ? '最新評鑑等第' : 'Latest evaluation grade'}<select value={filters.latestEvaluationGrade} onChange={(event) => update('latestEvaluationGrade', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{Object.keys(grades[language]).map((grade) => <option value={grade} key={grade}>{grades[language][grade as InfantCareCenterEvaluationGrade]}</option>)}</select></label>
      <label>{zh ? '最新評鑑狀態' : 'Latest evaluation status'}<select value={filters.latestEvaluationStatus} onChange={(event) => update('latestEvaluationStatus', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{Object.keys(statuses[language]).map((status) => <option value={status} key={status}>{statuses[language][status as InfantCareCenterEvaluationStatus]}</option>)}</select></label>
      <label>{zh ? '任一年度等第' : 'Any-year grade'}<select value={filters.anyYearGrade} onChange={(event) => update('anyYearGrade', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{Object.keys(grades[language]).map((grade) => <option value={grade} key={grade}>{grades[language][grade as InfantCareCenterEvaluationGrade]}</option>)}</select></label>
      {([['hasLatestResult', zh ? '有最新年度結果' : 'Has latest result'], ['closedOrSuspended', zh ? '停業或歇業' : 'Closed or suspended'], ['specialNote', zh ? '特殊註記' : 'Special note']] as const).map(([key, label]) => <label key={key}>{label}<select value={filters[key]} onChange={(event) => update(key, event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>)}
    </div>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => setFilters(emptyFilters)}>{zh ? '清除篩選' : 'Clear filters'}</button>}</aside>;
}

function Overview({ summary, language }: { summary: InfantCareCenterEvaluationSummary; language: Language }) {
  const zh = language === 'zh';
  const latestCount = (grade: InfantCareCenterEvaluationGrade) => summary.latestYearByGrade.find((item) => item.evaluationGrade === grade)?.count ?? 0;
  const cards = [
    [zh ? '托嬰中心數' : 'Infant care center count', summary.totalInstitutions],
    [zh ? '涵蓋行政區數' : 'Districts covered', summary.districtCount],
    [zh ? '評鑑年度範圍' : 'Evaluation year range', summary.minEvaluationYear && summary.maxEvaluationYear ? `${summary.minEvaluationYear - 1911}–${summary.maxEvaluationYear - 1911}` : '—'],
    [zh ? '最新評鑑年度' : 'Latest evaluation year', summary.latestEvaluationYear ? `${summary.latestEvaluationYear - 1911} / ${summary.latestEvaluationYear}` : '—'],
    [zh ? '最新年度有評鑑結果機構數' : 'Latest year evaluated institution count', summary.latestYearEvaluatedInstitutionCount],
    [zh ? '最新年度缺少結果機構數' : 'Latest year missing result count', summary.latestYearMissingInstitutionCount],
    [zh ? '最新年度優等數' : 'Latest year excellent count', latestCount('excellent')],
    [zh ? '最新年度甲等數' : 'Latest year A-grade count', latestCount('a')],
    [zh ? '最新年度乙等數' : 'Latest year B-grade count', latestCount('b')],
    [zh ? '最新年度丙等數' : 'Latest year C-grade count', latestCount('c')],
    [zh ? '最新年度丁等數' : 'Latest year D-grade count', latestCount('d')],
    [zh ? '停業或歇業紀錄數' : 'Closed or suspended record count', summary.byYear.reduce((sum, item) => sum + item.closedOrSuspendedCount, 0)],
    [zh ? '特殊註記數' : 'Special note count', summary.byYear.reduce((sum, item) => sum + item.specialNoteCount, 0)],
  ];
  return <><div className="summary-grid">{cards.map(([title, value]) => <article key={title}><span>{title}</span><strong>{typeof value === 'number' ? value.toLocaleString() : value}</strong></article>)}</div>
    <div className="chart-grid"><Bar title={zh ? '各行政區機構數' : 'Institution count by district'} rows={summary.byDistrictLatestYear.map((item) => ({ label: item.district, count: item.institutionCount }))} /><Bar title={zh ? '最新年度評鑑結果分布' : 'Latest-year evaluation result distribution'} rows={summary.latestYearByGrade.map((item) => ({ label: grades[language][item.evaluationGrade], count: item.count }))} /></div></>;
}

function DistrictMap({ summary, language, openDistrict }: { summary: InfantCareCenterEvaluationSummary; language: Language; openDistrict: (district: string) => void }) {
  const zh = language === 'zh', max = Math.max(...summary.byDistrictLatestYear.map((item) => item.institutionCount), 1);
  return <div className="map-wrap"><div className="notice">{mapNotice(zh)}</div><MapContainer center={[25.072, 121.54]} zoom={11} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap contributors &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" />{summary.byDistrictLatestYear.map((district) => {
    const point = TAIPEI_DISTRICT_CENTROIDS[district.district];
    return point && <CircleMarker key={district.district} center={[point.latitude, point.longitude]} radius={10 + 26 * Math.sqrt(district.institutionCount / max)} pathOptions={{ fillColor: '#9d6bce', fillOpacity: .76, color: '#fff7e8', weight: 2 }}><Popup><div className="map-popup"><strong>{district.district}</strong><p>{zh ? '機構數' : 'Institution count'}: {district.institutionCount}</p><p>{zh ? '最新年度有評鑑結果數' : 'Latest-year evaluated count'}: {district.evaluatedCount}</p><p>{zh ? '優/甲/乙/丙/丁' : 'Excellent/A/B/C/D'}: {district.excellentCount}/{district.aCount}/{district.bCount}/{district.cCount}/{district.dCount}</p><p>{zh ? '本圖以行政區彙總呈現，不代表精確位置或家長選擇建議。' : 'District-level summary only; not exact locations or parent selection advice.'}</p><button onClick={() => openDistrict(district.district)}>{zh ? '查看清單' : 'View directory'}</button></div></Popup></CircleMarker>;
  })}</MapContainer></div>;
}

function Directory({ records, language }: { records: InfantCareCenterEvaluationInstitutionRecord[]; language: Language }) {
  const zh = language === 'zh';
  const [limit, setLimit] = useState(80);
  useEffect(() => setLimit(80), [records]);
  const years = ['2021', '2022', '2023', '2024', '2025'];
  return <><h3>{zh ? '托嬰中心評鑑結果清單' : 'Infant Care Center Evaluation Directory'}</h3><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['機構名稱', '行政區', '最新評鑑年度', '最新評鑑結果', '110年', '111年', '112年', '113年', '114年', '明細'] : ['Institution name', 'District', 'Latest evaluation year', 'Latest evaluation result', 'ROC 110', 'ROC 111', 'ROC 112', 'ROC 113', 'ROC 114', 'Details']).map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{records.slice(0, limit).map((record) => <tr key={record.id}><th>{record.institutionName}</th><td>{record.district ?? '—'}</td><td>{record.latestEvaluationRocYear ? `${record.latestEvaluationRocYear} / ${record.latestEvaluationYear}` : '—'}</td><td>{record.latestEvaluationResultRaw ?? '—'}</td>{years.map((year) => <td key={year}>{record.yearlyResults[year]?.evaluationResultRaw ?? '—'}</td>)}<td><details><summary>{zh ? '查看' : 'View'}</summary><p>{zh ? '編號' : 'Sequence number'}: {record.sourceSequenceNumber ?? '—'}<br />{zh ? '行政區碼' : 'District code'}: {record.districtCode ?? '—'}<br />{zh ? '代碼對應行政區' : 'District from code'}: {record.districtFromCode ?? '—'}<br />{zh ? '行政區不一致' : 'District mismatch'}: {record.districtMismatch ? (zh ? '是' : 'Yes') : (zh ? '否' : 'No')}<br />{zh ? '標準化名稱' : 'Normalized name'}: {record.institutionNameNormalized ?? '—'}<br />{zh ? '特殊註記數' : 'Special note count'}: {record.specialNoteCount}<br />{Object.values(record.yearlyResults).map((result) => `${result.rocYear}/${result.year}: ${result.evaluationResultRaw ?? '—'} · ${grades[language][result.evaluationGrade]} · ${statuses[language][result.evaluationStatus]}`).join('\n')}<br />{record.source} / {record.sourceAgency}<br />{notice(zh)}</p></details></td></tr>)}</tbody></table></div>{!records.length && <p className="empty">{zh ? '沒有符合條件的紀錄。' : 'No records match these filters.'}</p>}{limit < records.length && <button className="load-more" onClick={() => setLimit(limit + 80)}>{zh ? '載入更多' : 'Load more'} · {records.length - limit}</button>}</>;
}

export default function InfantCareCenterEvaluationResultsModule({ institutions, yearRecords, summary, quasiPublicRecords, language }: { institutions: InfantCareCenterEvaluationInstitutionRecord[]; yearRecords: InfantCareCenterEvaluationYearRecord[]; summary: InfantCareCenterEvaluationSummary; quasiPublicRecords?: QuasiPublicInfantCareCenter[]; language: Language }) {
  const zh = language === 'zh';
  const [view, setView] = useState<'overview' | 'districts' | 'trends' | 'results' | 'directory' | 'compare' | 'notes'>('overview');
  const [filters, setFilters] = useState(emptyFilters);
  const filtered = useMemo(() => filterInfantCareCenterEvaluationInstitutions(institutions, filters), [institutions, filters]);
  const filteredYearRecords = useMemo(() => yearRecords.filter((record) => filtered.some((institution) => institution.institutionName === record.institutionName && institution.districtCode === record.districtCode)), [filtered, yearRecords]);
  const active = useMemo(() => Object.values(filters).some(Boolean) ? buildInfantCareCenterEvaluationSummary(filtered, filteredYearRecords) : summary, [filtered, filteredYearRecords, filters, summary]);
  const possibleMatches = useMemo(() => new Set((quasiPublicRecords ?? []).map((record) => normalizeInfantCareInstitutionName(record.centerName))).size ? filtered.filter((record) => new Set((quasiPublicRecords ?? []).map((item) => normalizeInfantCareInstitutionName(item.centerName))).has(record.institutionNameNormalized)).length : 0, [filtered, quasiPublicRecords]);
  const openDistrict = (district: string) => { setFilters({ ...emptyFilters, district }); setView('directory'); };
  const views = [['overview', zh ? '總覽' : 'Overview'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['trends', zh ? '年度評鑑趨勢' : 'Yearly Evaluation Trends'], ['results', zh ? '評鑑結果分布' : 'Evaluation Result Distribution'], ['directory', zh ? '機構清單' : 'Institution Directory'], ['compare', zh ? '與準公共化托嬰資料比較' : 'Compare Quasi-Public Infant Care Records'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  return <><Filters records={institutions} summary={summary} filters={filters} setFilters={setFilters} language={language} /><section className="workspace"><div className="section-heading"><p>10 / CHILDCARE & SOCIAL WELFARE PUBLIC RECORDS</p><h2>{zh ? '托嬰中心評鑑結果' : 'Infant Care Center Evaluation Results'}</h2><span>{zh ? '查詢臺北市托嬰中心評鑑結果公開資料，包含機構名稱、行政區、行政區碼與110年至114年評鑑結果，並依年度、行政區與評鑑結果整理分布。' : 'Explore Taipei infant care center evaluation result public records, including institution name, district, district code, and evaluation results from ROC 110 to 114, organized by year, district, and result category.'}</span></div><div className="subtabs">{views.map(([id, label]) => <button className={view === id ? 'active' : ''} onClick={() => setView(id)} key={id}>{label}</button>)}</div><div className="notice subtle">{notice(zh)}</div><div className="section-heading inline"><div /><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆符合機構' : 'matching institutions'}</span></strong></div>
    {view === 'overview' && <Overview summary={active} language={language} />}
    {view === 'districts' && <DistrictMap summary={active} language={language} openDistrict={openDistrict} />}
    {view === 'trends' && <div className="chart-grid"><Bar title={zh ? '各年度有無評鑑結果' : 'Evaluated vs missing result count by year'} rows={active.byYear.flatMap((item) => [{ label: `${item.evaluationRocYear} ${zh ? '有結果' : 'evaluated'}`, count: item.evaluatedCount }, { label: `${item.evaluationRocYear} ${zh ? '無資料' : 'missing'}`, count: item.missingCount }])} /><Bar title={zh ? '各年度特殊註記' : 'Special notes by year'} rows={active.byYear.map((item) => ({ label: String(item.evaluationRocYear), count: item.specialNoteCount }))} /><Bar title={zh ? '各年度停業或歇業紀錄' : 'Closed / suspended records by year'} rows={active.byYear.map((item) => ({ label: String(item.evaluationRocYear), count: item.closedOrSuspendedCount }))} /></div>}
    {view === 'results' && <div className="chart-grid"><Bar title={zh ? '最新年度評鑑結果分布' : 'Latest-year evaluation result distribution'} rows={active.latestYearByGrade.map((item) => ({ label: grades[language][item.evaluationGrade], count: item.count }))} /><Bar title={zh ? '最新年度評鑑狀態分布' : 'Latest-year evaluation status distribution'} rows={active.latestYearByStatus.map((item) => ({ label: statuses[language][item.evaluationStatus], count: item.count }))} /><Bar title={zh ? '各行政區最新年度優等數' : 'Latest-year excellent count by district'} rows={active.byDistrictLatestYear.map((item) => ({ label: item.district, count: item.excellentCount }))} /><Bar title={zh ? '各行政區最新年度丙丁等數' : 'Latest-year C/D count by district'} rows={active.byDistrictLatestYear.map((item) => ({ label: item.district, count: item.cCount + item.dCount }))} /></div>}
    {view === 'directory' && <Directory records={filtered} language={language} />}
    {view === 'compare' && <div className="notes-grid"><article><h3>{zh ? '與準公共化托嬰資料不同' : 'Different from quasi-public infant care records'}</h3><p>{zh ? '托嬰中心評鑑結果與準公共化托嬰中心資料性質不同。評鑑結果是特定年度評鑑紀錄，準公共化資料則反映準公共化服務名冊或相關公開資訊；若僅以機構名稱比對，應標示為可能比對結果，不應視為確定同一機構或即時服務狀態。' : 'Infant care center evaluation results and quasi-public infant care center records have different meanings. If matching is based only on institution name, it should be marked as a possible match and should not be treated as a confirmed same institution or real-time service status.'}</p></article><article><h3>{zh ? '可能名稱比對' : 'Possible name matches'}</h3><p>{possibleMatches.toLocaleString()} / {filtered.length.toLocaleString()}</p></article><article><h3>{zh ? '其他資料性質' : 'Other dataset distinctions'}</h3><p>{zh ? '托嬰中心評鑑結果與老人福利機構、立案補習班資料性質不同，不應直接比較服務品質、收托、收費或服務內容。' : 'Infant care evaluation results differ from elderly welfare and registered cram-school records; service quality, enrollment, fees, or service contents should not be directly compared.'}</p></article></div>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料內容' : 'Data contents'}</h3><p>{zh ? '托嬰中心評鑑結果資料提供臺北市托嬰中心評鑑公開資料，欄位包含編號、機構名稱、行政區、行政區碼與110年至114年評鑑結果。本網站將年度欄位轉換為機構層級資料與年度評鑑長表，並整理為行政區分布、年度趨勢、評鑑結果分布與機構清單。資料未提供地址或官方經緯度，因此不顯示精確點位。' : 'Infant care center evaluation result data provides Taipei public records of infant care center evaluation results. Fields include sequence number, institution name, district, district code, and evaluation results from ROC 110 to ROC 114. This site converts year columns into institution-level records and long annual evaluation records. The data does not provide addresses or official coordinates, so exact points are not shown.'}</p></article><article><h3>{zh ? '解讀限制' : 'Interpretation limits'}</h3><p>{notice(zh)}</p></article><article><h3>{zh ? '地圖' : 'Map'}</h3><p>{mapNotice(zh)}</p></article><article><h3>{zh ? '資料來源' : 'Source'}</h3><p><a href="https://data.taipei/dataset/detail?id=e7b45593-9d44-469c-97fa-f1a52c69ebaa" target="_blank" rel="noreferrer">{zh ? '臺北市托嬰中心評鑑結果' : 'Taipei Infant Care Center Evaluation Results'} ↗</a></p></article></div>}
  </section></>;
}
