import { useMemo, useState } from 'react';
import { DISTRICTS } from './lib/civicGroups';
import { buildLicensedElectronicGameArcadeOperatorSummary, filterLicensedElectronicGameArcadeOperators } from './lib/licensedElectronicGameArcadeOperators';
import type { BusinessRegistrationChangeSummary, CompanyRegistrationChangeSummary, ConsumerDisputeAbsentBusinessOperatorSummary, Language, LicensedArcadeGeocodingStatus, LicensedArcadeLocationPrecision, LicensedElectronicGameArcadeOperatorFilters, LicensedElectronicGameArcadeOperatorRecord, LicensedElectronicGameArcadeOperatorSummary, LicensedPawnshopDirectorySummary, RegisteredCramSchoolSummary, RegisteredHotelSummary } from './types';

const emptyFilters: LicensedElectronicGameArcadeOperatorFilters = { search: '', districtName: '', roadName: '', hasNote: '', addressLooksLikeComplexUnit: '', geocodingStatus: '', locationPrecision: '', validBusinessRegistrationNumberFormat: '' };
const fmt = (value?: number) => value === undefined ? '-' : value.toLocaleString();
const precisionLabels: Record<LicensedArcadeLocationPrecision, { zh: string; en: string }> = { district_address: { zh: '行政區與地址', en: 'District and address' }, geocoded_address_approximate: { zh: '近似地理編碼地址', en: 'Approximate geocoded address' }, official_coordinate: { zh: '官方座標', en: 'Official coordinate' }, district_only: { zh: '僅行政區', en: 'District only' }, missing: { zh: '缺漏', en: 'Missing' } };
const geocodingLabels: Record<LicensedArcadeGeocodingStatus, { zh: string; en: string }> = { not_attempted: { zh: '未嘗試', en: 'Not attempted' }, not_geocoded_address_only: { zh: '未地理編碼，僅地址', en: 'Not geocoded, address only' }, geocoded_approximate: { zh: '近似地理編碼', en: 'Approximate geocoded' }, official_coordinate: { zh: '官方座標', en: 'Official coordinate' }, failed: { zh: '地理編碼失敗', en: 'Failed' }, not_applicable: { zh: '不適用', en: 'Not applicable' } };
const label = (labels: { zh: string; en: string }, language: Language) => labels[language];
const options = <T extends string>(values: Array<T | undefined>) => [...new Set(values.filter(Boolean) as T[])].sort((a, b) => a.localeCompare(b, 'zh-Hant'));

function BarChart({ title, data }: { title: string; data: Array<{ label: string; value: number }> }) {
  const max = Math.max(...data.map((item) => item.value), 1);
  return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) => <div className="bar-row wide-label" key={item.label}><span title={item.label}>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{fmt(item.value)}</b></div>)}</div></section>;
}

function Filters({ filters, setFilters, records, language }: { filters: LicensedElectronicGameArcadeOperatorFilters; setFilters: (filters: LicensedElectronicGameArcadeOperatorFilters) => void; records: LicensedElectronicGameArcadeOperatorRecord[]; language: Language }) {
  const zh = language === 'zh', update = (key: keyof LicensedElectronicGameArcadeOperatorFilters, value: string) => setFilters({ ...filters, [key]: value });
  return <aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(event) => update('search', event.target.value)} placeholder={zh ? '搜尋業者名稱、統一編號、行政區或地址' : 'Search operator name, business registration number, district, or address'} /></label>
    <div className="filter-grid grant-filters">
      <label>{zh ? '行政區' : 'District'}<select value={filters.districtName} onChange={(event) => update('districtName', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{DISTRICTS.map((district) => <option key={district}>{district}</option>)}</select></label>
      <label>{zh ? '道路' : 'Road'}<select value={filters.roadName} onChange={(event) => update('roadName', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.roadName)).map((road) => <option key={road}>{road}</option>)}</select></label>
      <label>{zh ? '有備註' : 'Has note'}<select value={filters.hasNote} onChange={(event) => update('hasNote', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>
      <label>{zh ? '複合樓層或單位地址' : 'Complex floor or unit address'}<select value={filters.addressLooksLikeComplexUnit} onChange={(event) => update('addressLooksLikeComplexUnit', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>
      <label>{zh ? '地理編碼狀態' : 'Geocoding status'}<select value={filters.geocodingStatus} onChange={(event) => update('geocodingStatus', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.geocodingStatus)).map((status) => <option key={status} value={status}>{label(geocodingLabels[status], language)}</option>)}</select></label>
      <label>{zh ? '位置精度' : 'Location precision'}<select value={filters.locationPrecision} onChange={(event) => update('locationPrecision', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.locationPrecision)).map((precision) => <option key={precision} value={precision}>{label(precisionLabels[precision], language)}</option>)}</select></label>
      <label>{zh ? '統一編號格式有效' : 'Valid business registration number format'}<select value={filters.validBusinessRegistrationNumberFormat} onChange={(event) => update('validBusinessRegistrationNumberFormat', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>
    </div>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => setFilters(emptyFilters)}>{zh ? '清除篩選' : 'Clear filters'}</button>}</aside>;
}

function Overview({ summary, language }: { summary: LicensedElectronicGameArcadeOperatorSummary; language: Language }) {
  const zh = language === 'zh';
  const cards = [[zh ? '電子遊戲場業者紀錄數' : 'Electronic game arcade operator record count', summary.totalRecords], [zh ? '涵蓋行政區數' : 'Districts covered', summary.districtCount], [zh ? '不重複業者名稱數' : 'Unique operator name count', summary.uniqueCompanyOrBusinessNameCount], [zh ? '不重複統一編號數' : 'Unique business registration number count', summary.uniqueBusinessRegistrationNumberCount], [zh ? '不重複地址數' : 'Unique address count', summary.uniqueAddressCount], [zh ? '統一編號格式有效紀錄數' : 'Records with valid business registration number format', summary.recordsWithValidBusinessRegistrationNumberFormat], [zh ? '有備註紀錄數' : 'Records with note', summary.recordsWithNote], [zh ? '業者最多行政區' : 'Top district by operator count', summary.byDistrict[0]?.districtName ?? '-'], [zh ? '業者最多道路' : 'Top road by operator count', summary.byRoadName[0]?.roadName ?? '-'], [zh ? '複合樓層或單位地址數' : 'Complex floor or unit address count', summary.recordsWithComplexUnitAddress]];
  return <><div className="notice subtle">{zh ? '此圖僅整理臺北市合法電子遊戲場業者清冊中的公司或商業名稱、統一編號、行政區、營業場所地址與備註等來源欄位，不代表即時營業狀態、營業時間、入場資格、年齡限制判定、消費建議、遊戲內容評價、治安風險、違規紀錄、法律意見或官方推薦。' : 'This chart only organizes company or business name, business registration number, district, business premises address, and notes from Taipei licensed electronic game arcade operator records. It does not represent real-time operating status, opening hours, admission eligibility, age-restriction determination, consumer advice, game content evaluation, public-safety risk, violation record, legal advice, or official recommendation.'}</div><div className="summary-grid">{cards.map(([key, value]) => <article key={key}><span>{key}</span><strong>{typeof value === 'number' ? fmt(value) : value}</strong></article>)}</div>
    <div className="chart-grid"><BarChart title={zh ? '各行政區業者數' : 'Operators by district'} data={summary.byDistrict.map((item) => ({ label: item.districtName, value: item.count }))} /><BarChart title={zh ? '各道路業者數' : 'Operators by road name'} data={summary.byRoadName.map((item) => ({ label: item.roadName, value: item.count }))} /><BarChart title={zh ? '統一編號格式有效性' : 'Business registration number format validity'} data={summary.byBusinessRegistrationNumberFormatValidity.map((item) => ({ label: item.valid ? (zh ? '有效' : 'Valid') : (zh ? '無效' : 'Invalid'), value: item.count }))} /><BarChart title={zh ? '有無備註紀錄' : 'Records with / without notes'} data={summary.byNoteAvailability.map((item) => ({ label: item.hasNote ? (zh ? '有備註' : 'With note') : (zh ? '無備註' : 'Without note'), value: item.count }))} /><BarChart title={zh ? '複合樓層或單位地址數' : 'Complex floor or unit address count'} data={summary.byComplexUnitAddress.map((item) => ({ label: item.addressLooksLikeComplexUnit ? (zh ? '複合地址' : 'Complex address') : (zh ? '一般地址' : 'Simple address'), value: item.count }))} /></div></>;
}

function Directory({ records, language }: { records: LicensedElectronicGameArcadeOperatorRecord[]; language: Language }) {
  const zh = language === 'zh';
  return <><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['序號', '公司／商業名稱', '統一編號', '行政區', '營業場所地址', '備註', '地圖查詢', '來源明細'] : ['Sequence number', 'Company / business name', 'Business registration number', 'District', 'Business premises address', 'Note', 'Map lookup', 'Source details']).map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{records.map((record) => <tr key={record.id}><td>{record.sourceSequenceNumber ?? '-'}</td><th>{record.companyOrBusinessName}</th><td>{record.businessRegistrationNumber}</td><td>{record.districtName}</td><td>{record.businessPremisesAddress}</td><td>{record.note ?? '-'}</td><td>{record.googleMapsQuery ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.googleMapsQuery)}`} target="_blank" rel="noreferrer">{zh ? '地圖查詢' : 'Map lookup'}</a> : '-'}</td><td><details><summary>{zh ? '來源明細' : 'Source details'}</summary><dl><div><dt>{zh ? '道路' : 'Road'}</dt><dd>{record.roadName ?? '-'}</dd></div><div><dt>{zh ? '統一編號格式有效' : 'Valid business registration number format'}</dt><dd>{record.validBusinessRegistrationNumberFormat ? (zh ? '是' : 'Yes') : (zh ? '否' : 'No')}</dd></div><div><dt>{zh ? '複合樓層或單位地址' : 'Complex floor or unit address'}</dt><dd>{record.addressLooksLikeComplexUnit ? (zh ? '是' : 'Yes') : (zh ? '否' : 'No')}</dd></div><div><dt>{zh ? '地理編碼狀態' : 'Geocoding status'}</dt><dd>{label(geocodingLabels[record.geocodingStatus], language)}</dd></div><div><dt>{zh ? '位置精度' : 'Location precision'}</dt><dd>{label(precisionLabels[record.locationPrecision], language)}</dd></div><div><dt>{zh ? '資料來源' : 'Source'}</dt><dd>{record.source} · {record.sourceAgency}</dd></div><div><dt>{zh ? '解讀限制' : 'Disclaimer'}</dt><dd>{zh ? '此資料僅供公開資料查詢，不代表即時營業狀態、營業時間、入場資格、年齡限制判定、消費建議、治安風險、違規紀錄、法律意見或官方推薦。' : 'This record is for public-data lookup only and does not represent real-time operating status, opening hours, admission eligibility, age-restriction determination, consumer advice, public-safety risk, violation record, legal advice, or official recommendation.'}</dd></div></dl></details></td></tr>)}</tbody></table></div>{!records.length && <p className="empty">{zh ? '沒有符合條件的紀錄。' : 'No records match these filters.'}</p>}</>;
}

function Compare({ summary, related, language }: { summary: LicensedElectronicGameArcadeOperatorSummary; related: { pawnshops?: LicensedPawnshopDirectorySummary; hotels?: RegisteredHotelSummary; cramSchools?: RegisteredCramSchoolSummary; business?: BusinessRegistrationChangeSummary; company?: CompanyRegistrationChangeSummary; consumer?: ConsumerDisputeAbsentBusinessOperatorSummary }; language: Language }) {
  const zh = language === 'zh', rows = [{ label: zh ? '電子遊戲場業者' : 'Arcade operators', value: summary.totalRecords }, ...(related.pawnshops ? [{ label: zh ? '合法當舖' : 'Licensed pawnshops', value: related.pawnshops.totalRecords }] : []), ...(related.hotels ? [{ label: zh ? '一般旅館' : 'Registered hotels', value: related.hotels.totalRecords }] : []), ...(related.cramSchools ? [{ label: zh ? '立案補習班' : 'Registered cram schools', value: related.cramSchools.totalRecords }] : [])];
  return <div className="notes-grid"><article><h3>{zh ? '與其他特許行業比較' : 'Compare Regulated Industries'}</h3><p>{zh ? '合法電子遊戲場業者清冊、當舖業資料清冊、旅館名冊與補習班資料皆可作為登記或特定行業清冊，但行業性質、主管規範、服務內容與解讀方式不同，不應合併為相同業態、消費風險、治安風險或推薦清單。' : 'Licensed arcade, pawnshop, hotel, and cram-school records can all be shown as registered or regulated directories, but their industries, rules, services, and interpretation differ and should not be merged as the same business type, consumer risk, public-safety risk, or recommendation list.'}</p></article><article><h3>{zh ? '與商業登記資料比對' : 'Compare Business Registration Records'}</h3><p>{zh ? '本版未建立自動比對。即使可用統一編號或名稱比對，也不應直接推論即時營業狀態、完整法規遵循狀態、信用狀態或消費建議。' : 'This version does not create automatic matches. Even if business registration numbers or names can be matched, the combined data should not infer real-time operating status, complete compliance status, credit status, or consumer advice.'}</p></article><article><h3>{zh ? '模組紀錄數' : 'Module record counts'}</h3><BarChart title="" data={rows} /></article></div>;
}

export default function LicensedElectronicGameArcadeOperatorsModule({ records, summary, related, language }: { records: LicensedElectronicGameArcadeOperatorRecord[]; summary: LicensedElectronicGameArcadeOperatorSummary; related: { pawnshops?: LicensedPawnshopDirectorySummary; hotels?: RegisteredHotelSummary; cramSchools?: RegisteredCramSchoolSummary; business?: BusinessRegistrationChangeSummary; company?: CompanyRegistrationChangeSummary; consumer?: ConsumerDisputeAbsentBusinessOperatorSummary }; language: Language }) {
  const zh = language === 'zh';
  const [view, setView] = useState<'overview' | 'districts' | 'directory' | 'compare' | 'notes'>('overview');
  const [filters, setFilters] = useState(emptyFilters);
  const filtered = useMemo(() => filterLicensedElectronicGameArcadeOperators(records, filters), [records, filters]);
  const activeSummary = useMemo(() => Object.values(filters).some(Boolean) ? buildLicensedElectronicGameArcadeOperatorSummary(filtered) : summary, [filtered, filters, summary]);
  const views = [['overview', zh ? '總覽' : 'Overview'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['directory', zh ? '業者清單' : 'Operator Directory'], ['compare', zh ? '與其他特許行業比較' : 'Compare Regulated Industries'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  return <><Filters filters={filters} setFilters={setFilters} records={records} language={language} /><section className="workspace"><div className="section-heading"><p>05C / LICENSED BUSINESSES & REGULATED INDUSTRY DIRECTORIES</p><h2>{zh ? '合法電子遊戲場業者清冊' : 'Licensed Electronic Game Arcade Operators'}</h2><span>{zh ? '查詢臺北市合法登記電子遊戲場業者公開資料，包含序號、公司或商業名稱、統一編號、行政區、營業場所地址與備註，作為特許行業與 regulated business directory 參考。' : 'Look up Taipei public records of licensed electronic game arcade operators, including sequence number, company or business name, business registration number, district, business premises address, and notes as a regulated industry directory reference.'}</span></div><div className="subtabs">{views.map(([id, text]) => <button className={view === id ? 'active' : ''} onClick={() => setView(id)} key={id}>{text}</button>)}</div><div className="notice subtle">{zh ? '合法電子遊戲場業者清冊提供行政區與營業場所地址，但未提供官方經緯度。本模組預設以行政區彙總、地址清單與外部地圖查詢呈現，不顯示官方精確點位。' : 'Licensed electronic game arcade operator records provide district and business premises address but do not provide official coordinates. This module uses district summaries, address lists, and external map lookup links by default and does not show official exact points.'}</div>
    {view === 'overview' && <Overview summary={activeSummary} language={language} />}{view === 'districts' && <div className="chart-grid"><BarChart title={zh ? '各行政區業者數' : 'Operators by district'} data={activeSummary.byDistrict.map((item) => ({ label: item.districtName, value: item.count }))} /><BarChart title={zh ? '各道路業者數' : 'Operators by road name'} data={activeSummary.byRoadName.map((item) => ({ label: item.roadName, value: item.count }))} /></div>}{view === 'directory' && <><div className="section-heading inline"><div /><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆符合紀錄' : 'matching records'}</span></strong></div><Directory records={filtered} language={language} /></>}{view === 'compare' && <Compare summary={activeSummary} related={related} language={language} />}{view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料內容' : 'Data contents'}</h3><p>{zh ? '臺北市合法電子遊戲場業者清冊提供臺北市合法登記電子遊戲場業者公開資料，欄位包含序號、公司或商業名稱、統一編號、行政區、營業場所地址與備註。本網站保留來源欄位，並整理為行政區分布、業者清單、地址查詢與 regulated business directory 資料探索。' : 'Taipei licensed electronic game arcade operator records provide public records of legally registered electronic game arcade operators in Taipei. Fields include sequence number, company or business name, business registration number, district, business premises address, and notes. This site preserves the source fields and organizes the data into district distribution, operator directory, address lookup, and regulated business directory data exploration.'}</p></article><article><h3>{zh ? '座標限制' : 'Coordinate limits'}</h3><p>{zh ? '本資料提供行政區與營業場所地址，但未提供官方經緯度。本網站預設以行政區彙總、地址清單與外部地圖查詢呈現；若日後加入地理編碼點位，應明確標示為依地址產生之近似位置，非產業局商業處提供之官方座標。' : 'This data provides district and business premises address but does not provide official coordinates. This site shows district summaries, address lists, and external map lookup links by default. If geocoded points are added later, they should be clearly labeled as approximate locations generated from addresses, not official coordinates provided by the Office of Commerce.'}</p></article><article><h3>{zh ? '解讀限制' : 'Interpretation limits'}</h3><p>{zh ? '本資料僅供合法電子遊戲場業者公開資料查詢與 regulated industry directory 資料探索使用，不代表即時營業狀態、營業時間、入場資格、年齡限制判定、消費建議、遊戲內容評價、治安風險、違規紀錄、法律意見、投資建議、信用評等或官方背書。' : 'This data is for licensed electronic game arcade operator public-record lookup and regulated industry directory data exploration only. It does not represent real-time operating status, opening hours, admission eligibility, age-restriction determination, consumer advice, game content evaluation, public-safety risk, violation record, legal advice, investment advice, credit rating, or official endorsement.'}</p></article><article><h3>{zh ? '資料來源' : 'Source'}</h3><p><a href="https://data.taipei/dataset/detail?id=20774fbb-5671-4850-b307-af6b5976077d" target="_blank" rel="noreferrer">{zh ? '臺北市合法電子遊戲場業者清冊' : 'Taipei Licensed Electronic Game Arcade Operator Records'} ↗</a></p></article></div>}</section></>;
}
