import { useEffect, useMemo, useState } from 'react';
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet';
import { DISTRICTS, TAIPEI_DISTRICT_CENTROIDS } from './lib/civicGroups';
import { buildLicensedPawnshopDirectorySummary, filterLicensedPawnshops } from './lib/licensedPawnshopDirectory';
import type { BusinessPremisesPublicLiabilityInsuranceSummary, BusinessRegistrationChangeSummary, CompanyRegistrationChangeSummary, ConsumerDisputeAbsentBusinessOperatorSummary, LaborStandardActViolationSummary, Language, LicensedPawnshopDirectoryFilters, LicensedPawnshopDirectoryRecord, LicensedPawnshopDirectorySummary, PawnshopLicenseNumberFormat } from './types';

const emptyFilters: LicensedPawnshopDirectoryFilters = { search: '', district: '', cityCounty: '', licenseNumberFormat: '', roadName: '', cityCountyIsTaipei: '', addressParsed: '' };
const fmt = (value?: number) => value === undefined ? '-' : value.toLocaleString();
const formatLabels: Record<PawnshopLicenseNumberFormat, { zh: string; en: string }> = {
  simple_numeric: { zh: '純數字', en: 'Numeric' }, numeric_with_dash: { zh: '數字含連字號', en: 'Numeric with dash' }, mixed: { zh: '混合格式', en: 'Mixed' }, missing: { zh: '缺漏', en: 'Missing' }, unknown: { zh: '未知', en: 'Unknown' },
};
const label = (labels: { zh: string; en: string }, language: Language) => labels[language];
const options = <T extends string>(values: Array<T | undefined>) => [...new Set(values.filter(Boolean) as T[])].sort((a, b) => a.localeCompare(b));

function BarChart({ title, data }: { title: string; data: Array<{ label: string; value: number }> }) {
  const max = Math.max(...data.map((item) => item.value), 1);
  return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) => <div className="bar-row wide-label" key={item.label}><span title={item.label}>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{fmt(item.value)}</b></div>)}</div></section>;
}

function Filters({ filters, setFilters, records, language }: { filters: LicensedPawnshopDirectoryFilters; setFilters: (filters: LicensedPawnshopDirectoryFilters) => void; records: LicensedPawnshopDirectoryRecord[]; language: Language }) {
  const zh = language === 'zh', update = (key: keyof LicensedPawnshopDirectoryFilters, value: string) => setFilters({ ...filters, [key]: value });
  return <aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(event) => update('search', event.target.value)} placeholder={zh ? '搜尋許可證號、當舖名稱、地址或道路' : 'Search license number, pawnshop name, address, or road'} /></label>
    <div className="filter-grid grant-filters">
      <label>{zh ? '行政區' : 'District'}<select value={filters.district} onChange={(event) => update('district', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{DISTRICTS.map((district) => <option key={district}>{district}</option>)}</select></label>
      <label>{zh ? '縣市' : 'City / county'}<select value={filters.cityCounty} onChange={(event) => update('cityCounty', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.cityCountyNormalized)).map((city) => <option key={city}>{city}</option>)}</select></label>
      <label>{zh ? '許可證號格式' : 'License number format'}<select value={filters.licenseNumberFormat} onChange={(event) => update('licenseNumberFormat', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.licenseNumberFormat)).map((type) => <option key={type} value={type}>{label(formatLabels[type], language)}</option>)}</select></label>
      <label>{zh ? '道路' : 'Road'}<select value={filters.roadName} onChange={(event) => update('roadName', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.roadName)).map((road) => <option key={road}>{road}</option>)}</select></label>
      <label>{zh ? '縣市為臺北市' : 'City/county is Taipei'}<select value={filters.cityCountyIsTaipei} onChange={(event) => update('cityCountyIsTaipei', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>
      <label>{zh ? '地址已解析' : 'Address parsed'}<select value={filters.addressParsed} onChange={(event) => update('addressParsed', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>
    </div>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => setFilters(emptyFilters)}>{zh ? '清除篩選' : 'Clear filters'}</button>}</aside>;
}

function Overview({ summary, language }: { summary: LicensedPawnshopDirectorySummary; language: Language }) {
  const zh = language === 'zh';
  const cards = [[zh ? '合法當舖數' : 'Licensed pawnshop count', summary.totalRecords], [zh ? '不重複許可證號數' : 'Unique license number count', summary.uniqueLicenseNumberCount], [zh ? '涵蓋行政區數' : 'Districts covered', summary.taipeiDistrictCount], [zh ? '不重複營業地址數' : 'Unique business address count', summary.uniqueBusinessAddressCount], [zh ? '縣市數' : 'City/county count', summary.cityCountyCount], [zh ? '地址已解析行政區數' : 'Records with parsed district', summary.recordsWithParsedDistrictFromAddress], [zh ? '當舖最多行政區' : 'Top district by pawnshop count', summary.byDistrict[0]?.district ?? '-'], [zh ? '當舖最多道路' : 'Top road by pawnshop count', summary.byRoadName[0]?.roadName ?? '-'], [zh ? '重複地址數' : 'Duplicate address count', summary.dataQuality.duplicateBusinessAddressCount], [zh ? '地址未解析數' : 'Unparsed address count', summary.dataQuality.unparsedAddressDistrictCount]];
  return <><div className="notice subtle">{zh ? '此圖僅整理當舖業資料清冊中的序號、許可證號、當舖名稱、營業地址與縣市欄位，不代表即時營業狀態、消費糾紛紀錄、違法紀錄、執法案件、信用評等、貸款建議、金融建議、法律意見、服務品質排名或官方推薦。' : 'This chart only organizes sequence number, license number, pawnshop name, business address, and city/county fields from licensed pawnshop directory data. It does not represent real-time operating status, consumer dispute records, violation records, law enforcement cases, credit ratings, loan advice, financial advice, legal advice, service quality ranking, or official recommendation.'}</div><div className="summary-grid">{cards.map(([key, value]) => <article key={key}><span>{key}</span><strong>{typeof value === 'number' ? fmt(value) : value}</strong></article>)}</div>
    <div className="chart-grid"><BarChart title={zh ? '各行政區當舖數' : 'Pawnshops by district'} data={summary.byDistrict.map((item) => ({ label: item.district, value: item.pawnshopCount }))} /><BarChart title={zh ? '各道路當舖數' : 'Pawnshops by road'} data={summary.byRoadName.slice(0, 30).map((item) => ({ label: item.roadName, value: item.count }))} /><BarChart title={zh ? '許可證號格式分布' : 'License number format distribution'} data={summary.byLicenseNumberFormat.map((item) => ({ label: label(formatLabels[item.licenseNumberFormat], language), value: item.count }))} /><BarChart title={zh ? '縣市分布' : 'City/county distribution'} data={summary.byCityCounty.map((item) => ({ label: item.cityCounty, value: item.count }))} /><BarChart title={zh ? '地址已解析與未解析數' : 'Parsed vs unparsed address count'} data={[{ label: zh ? '已解析' : 'Parsed', value: summary.recordsWithParsedDistrictFromAddress }, { label: zh ? '未解析' : 'Unparsed', value: summary.dataQuality.unparsedAddressDistrictCount }]} /></div></>;
}

function PawnshopMap({ summary, language, viewDistrict }: { summary: LicensedPawnshopDirectorySummary; language: Language; viewDistrict: (district: string) => void }) {
  const zh = language === 'zh', max = Math.max(...summary.byDistrict.map((district) => district.pawnshopCount), 1);
  return <div className="map-wrap"><div className="notice">{zh ? '當舖業資料清冊提供營業地址但未提供官方經緯度。本模組以地址解析行政區後進行行政區彙總，並提供外部地圖查詢連結；不代表精確座標、即時營業狀態、消費糾紛紀錄、違法紀錄、信用評等、貸款建議、法律意見或官方推薦。' : 'Licensed pawnshop directory data provides business addresses but does not provide official coordinates. This module summarizes records by parsed district and provides external map lookup links. It does not represent exact coordinates, real-time operating status, consumer dispute records, violation records, credit ratings, loan advice, legal advice, or official recommendation.'}</div><MapContainer center={[25.072, 121.54]} zoom={11} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap contributors &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" />{summary.byDistrict.map((district) => {
    const point = TAIPEI_DISTRICT_CENTROIDS[district.district];
    return point && <CircleMarker key={district.district} center={[point.latitude, point.longitude]} radius={10 + 26 * Math.sqrt(district.pawnshopCount / max)} pathOptions={{ fillColor: '#b7864c', fillOpacity: .76, color: '#fff7e8', weight: 2 }}><Popup><div className="map-popup"><strong>{zh ? '合法當舖行政區分布' : 'Licensed Pawnshop District Distribution'}</strong><p>{zh ? '行政區' : 'District'}: {district.district}</p><p>{zh ? '當舖數' : 'Pawnshop count'}: {fmt(district.pawnshopCount)}</p><p>{zh ? '本圖以地址解析後的行政區彙總呈現，不代表精確座標、即時營業狀態、消費糾紛紀錄、違法紀錄、信用評等、貸款建議、法律意見或官方推薦。' : 'This map shows district-level summaries based on parsed addresses and does not represent exact coordinates, real-time operating status, consumer dispute records, violation records, credit ratings, loan advice, legal advice, or official recommendation.'}</p><button onClick={() => viewDistrict(district.district)}>{zh ? '查看清單' : 'View directory'}</button></div></Popup></CircleMarker>;
  })}</MapContainer></div>;
}

function Directory({ records, language }: { records: LicensedPawnshopDirectoryRecord[]; language: Language }) {
  const zh = language === 'zh';
  const [limit, setLimit] = useState(80);
  useEffect(() => setLimit(80), [records]);
  return <><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['許可證號', '當舖名稱', '行政區', '營業地址', '縣市', '地圖查詢', '來源明細'] : ['License number', 'Pawnshop name', 'District', 'Business address', 'City / county', 'Map lookup', 'Source details']).map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{records.slice(0, limit).map((record) => <tr key={record.id}><td>{record.licenseNumber}</td><th>{record.pawnshopName}</th><td>{record.taipeiDistrict ?? '-'}</td><td>{record.businessAddress}</td><td>{record.cityCounty ?? '-'}</td><td>{record.googleMapsQuery ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.googleMapsQuery)}`} target="_blank" rel="noreferrer">{zh ? '地圖查詢' : 'Map lookup'}</a> : '-'}</td><td><details><summary>{zh ? '來源明細' : 'Source details'}</summary><dl><div><dt>{zh ? '序號' : 'Sequence number'}</dt><dd>{record.sourceSequenceNumber ?? '-'}</dd></div><div><dt>{zh ? '正規化許可證號' : 'Normalized license number'}</dt><dd>{record.licenseNumberNormalized ?? '-'}</dd></div><div><dt>{zh ? '許可證號格式' : 'License number format'}</dt><dd>{label(formatLabels[record.licenseNumberFormat], language)}</dd></div><div><dt>{zh ? '道路' : 'Road'}</dt><dd>{record.roadName ?? '-'}</dd></div><div><dt>{zh ? '縣市為臺北市' : 'City/county is Taipei'}</dt><dd>{record.cityCountyIsTaipei ? (zh ? '是' : 'Yes') : (zh ? '否' : 'No')}</dd></div><div><dt>{zh ? '位置精度' : 'Location precision'}</dt><dd>{record.locationPrecision}</dd></div><div><dt>{zh ? '資料來源' : 'Source'}</dt><dd>{record.source}</dd></div><div><dt>{zh ? '解讀限制' : 'Disclaimer'}</dt><dd>{zh ? '不代表即時營業狀態、消費糾紛紀錄、違法紀錄、執法案件、信用評等、貸款建議、投資建議、金融建議、法律意見、服務品質排名、官方推薦或官方背書。' : 'Does not represent real-time operating status, consumer dispute records, violation records, law enforcement cases, credit ratings, loan advice, investment advice, financial advice, legal advice, service quality ranking, official recommendation, or endorsement.'}</dd></div></dl></details></td></tr>)}</tbody></table></div>{!records.length && <p className="empty">{zh ? '沒有符合條件的紀錄。' : 'No records match these filters.'}</p>}{limit < records.length && <button className="load-more" onClick={() => setLimit(limit + 80)}>{zh ? '載入更多' : 'Load more'} · {records.length - limit}</button>}</>;
}

function Compare({ summary, related, language }: { summary: LicensedPawnshopDirectorySummary; related: { businessChanges?: BusinessRegistrationChangeSummary; companyChanges?: CompanyRegistrationChangeSummary; consumerDispute?: ConsumerDisputeAbsentBusinessOperatorSummary; publicLiability?: BusinessPremisesPublicLiabilityInsuranceSummary; laborViolations?: LaborStandardActViolationSummary }; language: Language }) {
  const zh = language === 'zh';
  const rows = [{ label: zh ? '合法當舖' : 'Licensed pawnshops', value: summary.totalRecords }, ...(related.businessChanges ? [{ label: zh ? '商業異動' : 'Business changes', value: related.businessChanges.totalRecords }] : []), ...(related.companyChanges ? [{ label: zh ? '公司異動' : 'Company changes', value: related.companyChanges.totalRecords }] : []), ...(related.consumerDispute ? [{ label: zh ? '消費爭議不到場' : 'Consumer dispute notices', value: related.consumerDispute.totalRecords }] : []), ...(related.publicLiability ? [{ label: zh ? '公共意外險' : 'Public liability insurance', value: related.publicLiability.totalRecords }] : [])], max = Math.max(...rows.map((row) => row.value), 1);
  return <div className="notes-grid"><article><h3>{zh ? '與商業登記資料比較' : 'Compare Business Registration Records'}</h3><p>{zh ? '當舖業資料清冊與商業或公司登記異動資料性質不同。即使可用名稱或地址比對，也不應直接推論即時營業狀態、信用狀態、違法狀態或法律責任。' : 'Licensed pawnshop directory data and business or company registration change records have different meanings. Even if name or address matching is possible, the combined data should not be used to infer real-time operating status, credit status, violation status, or legal liability.'}</p></article><article><h3>{zh ? '與消費及保險公開資料比較' : 'Compare Consumer & Insurance Records'}</h3><p>{zh ? '當舖業資料清冊不是消費爭議、保險或勞基法違規資料，不應以本名冊推論消費糾紛、服務品質、保險風險、責任狀態或勞動法規遵循。' : 'The pawnshop directory is not consumer dispute, insurance, or labor violation data and should not be used to infer disputes, service quality, insurance risk, liability status, or labor-law compliance.'}</p></article><article><h3>{zh ? '模組紀錄數' : 'Module record counts'}</h3><div className="bars">{rows.map((row) => <div className="bar-row wide-label" key={row.label}><span>{row.label}</span><div><i style={{ width: `${Math.max(2, row.value / max * 100)}%` }} /></div><b>{fmt(row.value)}</b></div>)}</div></article></div>;
}

export default function LicensedPawnshopDirectoryModule({ records, summary, related, language }: { records: LicensedPawnshopDirectoryRecord[]; summary: LicensedPawnshopDirectorySummary; related: { businessChanges?: BusinessRegistrationChangeSummary; companyChanges?: CompanyRegistrationChangeSummary; consumerDispute?: ConsumerDisputeAbsentBusinessOperatorSummary; publicLiability?: BusinessPremisesPublicLiabilityInsuranceSummary; laborViolations?: LaborStandardActViolationSummary }; language: Language }) {
  const zh = language === 'zh';
  const [view, setView] = useState<'overview' | 'map' | 'licenses' | 'directory' | 'compare' | 'notes'>('overview');
  const [filters, setFilters] = useState(emptyFilters);
  const filtered = useMemo(() => filterLicensedPawnshops(records, filters), [records, filters]);
  const activeSummary = useMemo(() => Object.values(filters).some(Boolean) ? buildLicensedPawnshopDirectorySummary(filtered) : summary, [filtered, filters, summary]);
  const openDistrict = (district: string) => { setFilters({ ...emptyFilters, district }); setView('directory'); };
  const views = [['overview', zh ? '總覽' : 'Overview'], ['map', zh ? '行政區分布' : 'District Distribution'], ['licenses', zh ? '許可證號' : 'License Numbers'], ['directory', zh ? '當舖清單' : 'Pawnshop Directory'], ['compare', zh ? '與公開資料比較' : 'Compare Records'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  return <><Filters filters={filters} setFilters={setFilters} records={records} language={language} /><section className="workspace"><div className="section-heading"><p>05B / BUSINESS REGISTRATION, LICENSED TRADES & PUBLIC SAFETY RECORDS</p><h2>{zh ? '當舖業資料清冊' : 'Licensed Pawnshop Directory'}</h2><span>{zh ? '查詢臺北市政府警察局合法當舖業資料清冊，包含許可證號、當舖名稱、營業地址與縣市，作為特許行業、商業登記與公共安全公開資訊。' : 'Look up Taipei City Police Department legal pawnshop registry records, including license number, pawnshop name, business address, and city/county as licensed trade, business registry, and public safety public information.'}</span></div><div className="subtabs">{views.map(([id, text]) => <button className={view === id ? 'active' : ''} onClick={() => setView(id)} key={id}>{text}</button>)}</div><div className="notice subtle">{zh ? '當舖業資料清冊為臺北市公開資料中的合法當舖業資料清冊，僅供查詢來源欄位與統計整理，不代表即時營業狀態、服務品質排名、消費糾紛紀錄、違法紀錄、執法案件、信用評等、貸款建議、投資建議、法律意見、金融建議、官方推薦或官方背書。' : 'Licensed pawnshop directory data is Taipei public-data information about legal pawnshop businesses. It is for source-field lookup and statistical organization only and does not represent real-time operating status, service quality ranking, consumer disputes, violations, law enforcement cases, credit ratings, loan advice, investment advice, legal/financial advice, recommendation, or endorsement.'}</div>
    {view === 'overview' && <Overview summary={activeSummary} language={language} />}{view === 'map' && <PawnshopMap summary={activeSummary} language={language} viewDistrict={openDistrict} />}{view === 'licenses' && <div className="chart-grid"><BarChart title={zh ? '許可證號格式分布' : 'License number format distribution'} data={activeSummary.byLicenseNumberFormat.map((item) => ({ label: label(formatLabels[item.licenseNumberFormat], language), value: item.count }))} /><BarChart title={zh ? '縣市分布' : 'City/county distribution'} data={activeSummary.byCityCounty.map((item) => ({ label: item.cityCounty, value: item.count }))} /></div>}{view === 'directory' && <><div className="section-heading inline"><div /><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆符合紀錄' : 'matching records'}</span></strong></div><Directory records={filtered} language={language} /></>}{view === 'compare' && <Compare summary={activeSummary} related={related} language={language} />}{view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料內容' : 'Data contents'}</h3><p>{zh ? '當舖業資料清冊提供臺北市政府警察局合法當舖業資料，欄位包含序號、許可證號、當舖名稱、營業地址與縣市。本網站保留來源欄位，並從營業地址解析臺北市行政區與道路名稱，整理為行政區分布、許可證號與當舖清單。資料未提供官方經緯度，因此預設不顯示精確點位。' : 'Licensed pawnshop directory data provides Taipei City Police Department legal pawnshop records. Fields include sequence number, license number, pawnshop name, business address, and city/county. This site preserves the source fields, parses Taipei districts and road names from business addresses, and organizes the data into district distribution, license numbers, and a pawnshop directory. The data does not provide official coordinates, so exact points are not shown by default.'}</p></article><article><h3>{zh ? '解讀限制' : 'Interpretation limits'}</h3><p>{zh ? '本資料為合法當舖業資料清冊，僅供查詢來源欄位與統計整理，不代表即時營業狀態、消費糾紛紀錄、違法紀錄、執法案件、信用評等、貸款建議、投資建議、金融建議、法律意見、服務品質排名、官方推薦或官方背書。' : 'This data is a legal pawnshop registry for source-field lookup and statistical organization only. It does not represent real-time operating status, consumer dispute records, violation records, law enforcement cases, credit ratings, loan advice, investment advice, financial advice, legal advice, service quality ranking, official recommendation, or official endorsement.'}</p></article><article><h3>{zh ? '資料來源' : 'Source'}</h3><p><a href="https://data.taipei/dataset/detail?id=024da777-25b0-4bee-b1b9-2f8ceb8bd68a" target="_blank" rel="noreferrer">{zh ? '臺北市政府警察局當舖業資料清冊' : 'Taipei City Police Department Licensed Pawnshop Directory'} ↗</a></p></article></div>}</section></>;
}
