import { useEffect, useMemo, useState } from 'react';
import { buildLicensedAnimalMedicineSellerSummary, filterLicensedAnimalMedicineSellers } from './lib/licensedAnimalMedicineSellers';
import type { AnimalMedicineSellerGeocodingStatus, AnimalMedicineSellerLocationPrecision, Language, LicensedAnimalMedicineSellerFilters, LicensedAnimalMedicineSellerRecord, LicensedAnimalMedicineSellerSummary } from './types';

const empty: LicensedAnimalMedicineSellerFilters = { search: '', districtNameFromAddress: '', roadName: '', hasBusinessRegistrationNumber: '', businessRegistrationNumberValidFormat: '', hasCompanyPhone: '', addressUsesOldTaipeiText: '', addressOutsideTaipeiHint: '', addressLooksLikeMultiFloorOrUnit: '', locationPrecision: '', geocodingStatus: '' };
const optionValues = <T extends string>(records: LicensedAnimalMedicineSellerRecord[], field: (r: LicensedAnimalMedicineSellerRecord) => T | undefined) => [...new Set(records.flatMap((r) => field(r) ?? []))].sort((a, b) => a.localeCompare(b, 'zh-Hant'));
const precisionLabel = (p: AnimalMedicineSellerLocationPrecision, zh: boolean) => ({ district_address: zh ? '行政區與地址' : 'District and address', geocoded_address_approximate: zh ? '近似地理編碼地址' : 'Approximate geocoded address', district_only: zh ? '僅行政區' : 'District only', address_only_unparsed_district: zh ? '僅地址，未解析行政區' : 'Address only, district unparsed', outside_taipei_or_old_address_hint: zh ? '疑似臺北市外或舊式地址' : 'Possible outside-Taipei or old address', missing: zh ? '缺漏' : 'Missing' }[p]);
const geocodingLabel = (s: AnimalMedicineSellerGeocodingStatus, zh: boolean) => ({ not_attempted: zh ? '未嘗試' : 'Not attempted', not_geocoded_address_only: zh ? '未地理編碼，僅地址' : 'Not geocoded, address only', geocoded_approximate: zh ? '近似地理編碼' : 'Approximate geocoded', failed: zh ? '地理編碼失敗' : 'Failed', not_applicable: zh ? '不適用' : 'Not applicable' }[s]);
const fmt = (n?: number) => n === undefined ? '-' : n.toLocaleString();
function Bar({ title, rows }: { title: string; rows: Array<{ label: string; count: number }> }) { const max = Math.max(...rows.map((r) => r.count), 1); return <section className="chart"><h3>{title}</h3><div className="bars">{rows.map((r) => <div className="bar-row wide-label" key={r.label}><span title={r.label}>{r.label}</span><div><i style={{ width: `${Math.max(2, r.count / max * 100)}%` }} /></div><b>{fmt(r.count)}</b></div>)}</div></section>; }

function Filters({ records, filters, setFilters, language }: { records: LicensedAnimalMedicineSellerRecord[]; filters: LicensedAnimalMedicineSellerFilters; setFilters: (filters: LicensedAnimalMedicineSellerFilters) => void; language: Language }) {
  const zh = language === 'zh', update = (key: keyof LicensedAnimalMedicineSellerFilters, value: string) => setFilters({ ...filters, [key]: value });
  const yesNo = (key: keyof LicensedAnimalMedicineSellerFilters, label: string) => <label>{label}<select value={filters[key]} onChange={(e) => update(key, e.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>;
  return <aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(e) => update('search', e.target.value)} placeholder={zh ? '搜尋許可證、統一編號、公司名稱、地址或電話' : 'Search license number, business registration number, company name, address, or phone'} /></label><div className="filter-grid grant-filters">
    <label>{zh ? '行政區' : 'District'}<select value={filters.districtNameFromAddress} onChange={(e) => update('districtNameFromAddress', e.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{optionValues(records, (r) => r.districtNameFromAddress).map((v) => <option key={v}>{v}</option>)}</select></label>
    <label>{zh ? '道路' : 'Road'}<select value={filters.roadName} onChange={(e) => update('roadName', e.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{optionValues(records, (r) => r.roadName).map((v) => <option key={v}>{v}</option>)}</select></label>
    {yesNo('hasBusinessRegistrationNumber', zh ? '有統一編號' : 'Has business registration number')}{yesNo('businessRegistrationNumberValidFormat', zh ? '統一編號格式有效' : 'Valid business registration number format')}{yesNo('hasCompanyPhone', zh ? '有公司電話' : 'Has company phone')}{yesNo('addressUsesOldTaipeiText', zh ? '舊式臺北地址文字' : 'Old Taipei address text')}{yesNo('addressOutsideTaipeiHint', zh ? '疑似臺北市外地址' : 'Possible outside-Taipei address')}{yesNo('addressLooksLikeMultiFloorOrUnit', zh ? '多樓層或單位地址' : 'Multi-floor or unit address')}
    <label>{zh ? '位置精度' : 'Location precision'}<select value={filters.locationPrecision} onChange={(e) => update('locationPrecision', e.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{optionValues(records, (r) => r.locationPrecision).map((v) => <option key={v} value={v}>{precisionLabel(v, zh)}</option>)}</select></label>
    <label>{zh ? '地理編碼狀態' : 'Geocoding status'}<select value={filters.geocodingStatus} onChange={(e) => update('geocodingStatus', e.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{optionValues(records, (r) => r.geocodingStatus).map((v) => <option key={v} value={v}>{geocodingLabel(v, zh)}</option>)}</select></label>
  </div>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => setFilters(empty)}>{zh ? '清除篩選' : 'Clear filters'}</button>}</aside>;
}

function Directory({ records, language }: { records: LicensedAnimalMedicineSellerRecord[]; language: Language }) {
  const zh = language === 'zh';
  const [limit, setLimit] = useState(100);
  useEffect(() => setLimit(100), [records]);
  return <><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['販賣業許可證', '統一編號', '公司名稱', '行政區', '公司地址', '公司電話', '地圖查詢', '來源明細'] : ['Seller license number', 'Business registration number', 'Company name', 'District', 'Company address', 'Company phone', 'Map lookup', 'Source details']).map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{records.slice(0, limit).map((r) => <tr key={r.id}><td>{r.sellerLicenseNumber}</td><td>{r.businessRegistrationNumber ?? '—'}</td><th>{r.companyName}</th><td>{r.districtNameFromAddress ?? '—'}</td><td>{r.companyAddress}</td><td>{r.companyPhone ?? '—'}</td><td>{r.googleMapsQuery ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(r.googleMapsQuery)}`} target="_blank" rel="noreferrer">{zh ? '地圖查詢' : 'Map lookup'}</a> : '—'}</td><td><details><summary>{zh ? '來源明細' : 'Source details'}</summary><dl><div><dt>{zh ? '許可證序號' : 'License sequence'}</dt><dd>{r.sellerLicenseNumberSequence ?? '—'}</dd></div><div><dt>{zh ? '統一編號格式有效' : 'Valid business registration number format'}</dt><dd>{r.businessRegistrationNumberValidFormat ? (zh ? '是' : 'Yes') : (zh ? '否' : 'No')}</dd></div><div><dt>{zh ? '道路' : 'Road'}</dt><dd>{r.roadName ?? '—'}</dd></div><div><dt>{zh ? '舊式臺北地址文字' : 'Old Taipei address text'}</dt><dd>{r.addressUsesOldTaipeiText ? (zh ? '是' : 'Yes') : (zh ? '否' : 'No')}</dd></div><div><dt>{zh ? '疑似臺北市外地址' : 'Possible outside-Taipei address'}</dt><dd>{r.addressOutsideTaipeiHint ? (zh ? '是' : 'Yes') : (zh ? '否' : 'No')}</dd></div><div><dt>{zh ? '位置精度' : 'Location precision'}</dt><dd>{precisionLabel(r.locationPrecision, zh)}</dd></div><div><dt>{zh ? '地理編碼狀態' : 'Geocoding status'}</dt><dd>{geocodingLabel(r.geocodingStatus, zh)}</dd></div><div><dt>{zh ? '資料來源' : 'Source'}</dt><dd>{r.source} · {r.sourceAgency}</dd></div></dl></details></td></tr>)}</tbody></table></div>{!records.length && <p className="empty">{zh ? '沒有符合條件的紀錄。' : 'No records match these filters.'}</p>}{limit < records.length && <button className="load-more" onClick={() => setLimit(limit + 100)}>{zh ? '載入更多' : 'Load more'} · {records.length - limit}</button>}</>;
}

export default function LicensedAnimalMedicineSellersModule({ records, summary, language, related }: { records: LicensedAnimalMedicineSellerRecord[]; summary: LicensedAnimalMedicineSellerSummary; language: Language; related?: { animalHospitals?: number; veterinarians?: number; businessChanges?: number; companyChanges?: number } }) {
  const zh = language === 'zh', [view, setView] = useState<'overview' | 'districts' | 'directory' | 'quality' | 'compare' | 'notes'>('overview'), [filters, setFilters] = useState(empty);
  const filtered = useMemo(() => filterLicensedAnimalMedicineSellers(records, filters), [records, filters]);
  const active = useMemo(() => Object.values(filters).some(Boolean) ? buildLicensedAnimalMedicineSellerSummary(filtered) : summary, [filtered, filters, summary]);
  const views = [['overview', zh ? '總覽' : 'Overview'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['directory', zh ? '許可證與公司清單' : 'License & Company Directory'], ['quality', zh ? '地址資料品質' : 'Address Data Quality'], ['compare', zh ? '與動物相關資料比較' : 'Compare Animal-Related Records'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  const cards = [[zh ? '動物用藥業者紀錄數' : 'Animal medicine seller record count', active.totalRecords], [zh ? '可解析行政區數' : 'Parsed district count', active.districtCount], [zh ? '不重複販賣業許可證數' : 'Unique seller license number count', active.uniqueSellerLicenseNumberCount], [zh ? '不重複統一編號數' : 'Unique business registration number count', active.uniqueBusinessRegistrationNumberCount], [zh ? '有統一編號紀錄數' : 'Records with business registration number', active.recordsWithBusinessRegistrationNumber], [zh ? '有公司電話紀錄數' : 'Records with company phone', active.recordsWithCompanyPhone], [zh ? '已解析行政區紀錄數' : 'Records with parsed district', active.recordsWithParsedDistrict], [zh ? '未解析行政區紀錄數' : 'Records with unparsed district', active.recordsWithUnparsedDistrict], [zh ? '舊式臺北地址文字紀錄數' : 'Records with old Taipei address text', active.recordsWithOldTaipeiAddressText], [zh ? '疑似臺北市外地址紀錄數' : 'Records with possible outside-Taipei address', active.recordsWithOutsideTaipeiAddressHint], [zh ? '業者最多行政區' : 'Top district by seller count', active.byDistrict[0]?.districtName ?? '—'], [zh ? '業者最多道路' : 'Top road by seller count', active.byRoadName[0]?.roadName ?? '—']];
  return <><Filters records={records} filters={filters} setFilters={setFilters} language={language} /><section className="workspace"><div className="section-heading"><p>08B / ANIMAL PROTECTION, VETERINARY & ANIMAL MEDICINE BUSINESSES</p><h2>{zh ? '動物用藥品販賣業者名冊' : 'Licensed Animal Medicine Sellers'}</h2><span>{zh ? '查詢臺北市動物用藥品販賣業者公開資料，包含販賣業許可證、統一編號、公司名稱、公司地址與公司電話。' : 'Look up Taipei animal medicine seller public records, including seller license number, business registration number, company name, company address, and company phone.'}</span></div><div className="subtabs">{views.map(([id, label]) => <button className={view === id ? 'active' : ''} onClick={() => setView(id)} key={id}>{label}</button>)}</div><div className="notice subtle">{zh ? '臺北市動物用藥品販賣業者名冊提供公司地址，但未提供官方經緯度。本模組預設以行政區彙總、地址清單與外部地圖查詢呈現，不顯示官方精確點位。' : 'Animal medicine seller records provide company addresses but do not provide official coordinates. This module uses district summaries, address lists, and external map lookup links by default and does not show official exact points.'}</div>
    {view === 'overview' && <><div className="summary-grid">{cards.map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{typeof value === 'number' ? value.toLocaleString() : value}</strong></article>)}</div><div className="chart-grid"><Bar title={zh ? '各行政區動物用藥業者數' : 'Animal medicine sellers by district'} rows={active.byDistrict.map((d) => ({ label: d.districtName, count: d.count }))} /><Bar title={zh ? '各道路動物用藥業者數' : 'Animal medicine sellers by road name'} rows={active.byRoadName.slice(0, 30).map((d) => ({ label: d.roadName, count: d.count }))} /><Bar title={zh ? '有無統一編號紀錄' : 'Records with / without business registration number'} rows={[{ label: zh ? '有統一編號' : 'With business registration number', count: active.recordsWithBusinessRegistrationNumber }, { label: zh ? '無統一編號' : 'Without business registration number', count: active.totalRecords - active.recordsWithBusinessRegistrationNumber }]} /><Bar title={zh ? '有無公司電話紀錄' : 'Records with / without company phone'} rows={[{ label: zh ? '有公司電話' : 'With company phone', count: active.recordsWithCompanyPhone }, { label: zh ? '無公司電話' : 'Without company phone', count: active.totalRecords - active.recordsWithCompanyPhone }]} /></div></>}
    {view === 'districts' && <div className="chart-grid"><Bar title={zh ? '各行政區動物用藥業者數' : 'Animal medicine sellers by district'} rows={active.byDistrict.map((d) => ({ label: d.districtName, count: d.count }))} /><Bar title={zh ? '各道路動物用藥業者數' : 'Animal medicine sellers by road name'} rows={active.byRoadName.slice(0, 50).map((d) => ({ label: d.roadName, count: d.count }))} /><Bar title={zh ? '共用地址數' : 'Shared address count'} rows={active.topSharedAddresses.map((d) => ({ label: d.companyAddress, count: d.count }))} /></div>}
    {view === 'directory' && <><div className="section-heading inline"><div /><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆符合紀錄' : 'matching records'}</span></strong></div><Directory records={filtered} language={language} /></>}
    {view === 'quality' && <div className="chart-grid"><Bar title={zh ? '地址解析狀態' : 'Address parsing status'} rows={[{ label: zh ? '已解析行政區' : 'Parsed district', count: active.recordsWithParsedDistrict }, { label: zh ? '未解析行政區' : 'Unparsed district', count: active.recordsWithUnparsedDistrict }]} /><Bar title={zh ? '地址資料品質' : 'Address data quality'} rows={[{ label: zh ? '舊式臺北地址文字' : 'Old Taipei address text', count: active.recordsWithOldTaipeiAddressText }, { label: zh ? '疑似臺北市外地址' : 'Possible outside-Taipei address', count: active.recordsWithOutsideTaipeiAddressHint }, { label: zh ? '多樓層或單位地址' : 'Multi-floor or unit address', count: active.recordsWithMultiFloorOrUnitAddress }]} /><Bar title={zh ? '統一編號格式有效性' : 'Business registration number format validity'} rows={[{ label: zh ? '有效' : 'Valid', count: active.recordsWithValidBusinessRegistrationNumberFormat }, { label: zh ? '缺漏或無效' : 'Missing or invalid', count: active.totalRecords - active.recordsWithValidBusinessRegistrationNumberFormat }]} /></div>}
    {view === 'compare' && <><div className="notice subtle">{zh ? '動物用藥品販賣業者名冊、動物醫院名冊、獸醫師資訊與商業/公司登記異動資料性質不同，不應合併推論診療能力、用藥建議、即時營業狀態、許可證即時有效性或完整法規遵循狀態。' : 'Animal medicine seller, animal hospital, veterinarian, and business/company registration change records have different meanings. Do not merge them to infer medical-care capability, medication advice, real-time operating status, real-time license validity, or complete compliance status.'}</div><Bar title={zh ? '相關動物與商業資料紀錄數比較' : 'Related animal and business record counts'} rows={[{ label: zh ? '動物用藥業者' : 'Animal medicine sellers', count: summary.totalRecords }, { label: zh ? '動物醫院' : 'Animal hospitals', count: related?.animalHospitals ?? 0 }, { label: zh ? '獸醫師資訊' : 'Veterinarians', count: related?.veterinarians ?? 0 }, { label: zh ? '商業異動' : 'Business changes', count: related?.businessChanges ?? 0 }, { label: zh ? '公司異動' : 'Company changes', count: related?.companyChanges ?? 0 }].filter((r) => r.count)} /></>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料內容' : 'Data contents'}</h3><p>{zh ? '臺北市動物用藥品販賣業者名冊提供動物用藥品販賣業者公開資料，欄位包含販賣業許可證、統一編號、公司名稱、公司地址與公司電話。本網站保留來源欄位，並整理為行政區分布、許可證與公司清單、地址資料品質及動物保護與獸醫相關業者目錄資料探索。' : 'Taipei animal medicine seller records provide public information about animal medicine sellers. Fields include seller license number, business registration number, company name, company address, and company phone. This site preserves the source fields and organizes district distribution, license and company directory, address data quality, and animal protection / veterinary-related business directory exploration.'}</p></article><article><h3>{zh ? '解讀限制' : 'Interpretation limits'}</h3><p>{zh ? '本資料不代表即時營業狀態、即時販售狀態、藥品品項、藥品安全性、產品品質、處方或用藥建議、動物診療建議、許可證即時有效性、完整法規遵循狀態、消費建議、投資建議、信用評等、法律意見或官方背書。' : 'This data does not represent real-time operating status, real-time sales availability, medicine items, medicine safety, product quality, prescription or medication advice, animal medical advice, real-time license validity, complete compliance status, consumer advice, investment advice, credit rating, legal advice, or official endorsement.'}</p></article><article><h3>{zh ? '資料來源' : 'Source'}</h3><p><a href="https://data.taipei/dataset/detail?id=9100b52e-f939-492f-9a8f-ba0adbd304ce" target="_blank" rel="noreferrer">{zh ? '臺北市動物用藥品販賣業者名冊' : 'Taipei animal medicine seller records'} ↗</a></p></article></div>}</section></>;
}
