import { useEffect, useMemo, useState } from 'react';

type Record = { id: string; sourceSequenceNumber: string; institutionName: string; postalCode: string; districtName: string; address: string; phone: string; hasPhone: boolean; hasAddress: boolean; googleMapsQuery: string };
type Report = { duplicates: string[]; missingNames: string[]; missingAddresses: string[]; malformedPhones: string[]; unknownPostalCodes: string[]; unresolvedDistricts: string[] };
type ChartItem = { label: string; value: number };
const missing = '—';
const Chart = ({ title, data }: { title: string; data: ChartItem[] }) => { const max = Math.max(1, ...data.map((item) => item.value)); return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) => <div className="bar-row wide-label" key={item.label}><span>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{item.value}</b></div>)}</div></section>; };

export default function OptometryInstitutionsModule({ language }: { language: 'zh' | 'en' }) {
  const zh = language === 'zh'; const t = (chinese: string, english: string) => zh ? chinese : english;
  const [records, setRecords] = useState<Record[]>([]); const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState(false);
  const [view, setView] = useState('overview'); const [search, setSearch] = useState(''); const [district, setDistrict] = useState(''); const [postalCode, setPostalCode] = useState(''); const [phone, setPhone] = useState(''); const [address, setAddress] = useState(''); const [sort, setSort] = useState('name'); const [page, setPage] = useState(1);
  useEffect(() => { const base = `${import.meta.env.BASE_URL}data/optometry-institutions/`; fetch(`${base}records.json`).then((response) => { if (!response.ok) throw new Error(); return response.json(); }).then(setRecords).catch(() => setError(true)); fetch(`${base}conversion-report.json`).then((response) => response.ok ? response.json() : null).then(setReport).catch(() => setReport(null)); }, []);
  const resetPage = (set: (value: string) => void, value: string) => { set(value); setPage(1); };
  const filtered = useMemo(() => records.filter((record) => { const query = search.trim().toLowerCase(); return (!query || [record.institutionName, record.districtName, record.postalCode, record.address, record.phone].join(' ').toLowerCase().includes(query)) && (!district || record.districtName === district) && (!postalCode || record.postalCode === postalCode) && (!phone || (phone === 'yes' ? record.hasPhone : !record.hasPhone)) && (!address || (address === 'yes' ? record.hasAddress : !record.hasAddress)); }), [records, search, district, postalCode, phone, address]);
  const countBy = (key: 'districtName' | 'postalCode') => [...new Set(filtered.map((record) => record[key]).filter(Boolean))].map((label) => ({ label, value: filtered.filter((record) => record[key] === label).length })).sort((a, b) => b.value - a.value || a.label.localeCompare(b.label, 'zh-Hant'));
  const byDistrict = useMemo(() => countBy('districtName'), [filtered]); const byPostalCode = useMemo(() => countBy('postalCode'), [filtered]);
  const summary = useMemo(() => ({ total: filtered.length, uniqueNames: new Set(filtered.map((record) => record.institutionName).filter(Boolean)).size, districts: byDistrict.length, postcodes: byPostalCode.length, phones: filtered.filter((record) => record.hasPhone).length, addresses: filtered.filter((record) => record.hasAddress).length, topDistrict: byDistrict[0]?.label || missing }), [filtered, byDistrict, byPostalCode]);
  const sorted = useMemo(() => [...filtered].sort((a, b) => sort === 'district' ? a.districtName.localeCompare(b.districtName, 'zh-Hant') || a.institutionName.localeCompare(b.institutionName, 'zh-Hant') : sort === 'postalCode' ? a.postalCode.localeCompare(b.postalCode) || a.institutionName.localeCompare(b.institutionName, 'zh-Hant') : sort === 'id' ? a.sourceSequenceNumber.localeCompare(b.sourceSequenceNumber, undefined, { numeric: true }) : a.institutionName.localeCompare(b.institutionName, 'zh-Hant')), [filtered, sort]);
  const pages = Math.max(1, Math.ceil(sorted.length / 25)); const rows = sorted.slice((Math.min(page, pages) - 1) * 25, Math.min(page, pages) * 25);
  const copy = (value: string) => value && <button type="button" className="copy-button" aria-label={t('複製', 'Copy')} onClick={() => navigator.clipboard?.writeText(value)}>{t('複製', 'Copy')}</button>;
  const mapLink = (query: string) => query ? <a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`}>{t('地圖查詢', 'Map lookup')}</a> : missing;
  const download = () => { const quote = (value: string) => `"${value.replaceAll('"', '""')}"`; const content = [['ID', 'Institution name', 'District', 'Postal code', 'Address', 'Phone'], ...filtered.map((record) => [record.sourceSequenceNumber, record.institutionName, record.districtName, record.postalCode, record.address, record.phone])].map((line) => line.map(quote).join(',')).join('\n'); const url = URL.createObjectURL(new Blob(['\uFEFF', content], { type: 'text/csv;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'optometry-institutions-filtered.csv'; anchor.click(); URL.revokeObjectURL(url); };
  if (error) return <section className="workspace"><div className="notice">{t('無法載入本機資料檔。', 'The local data file could not be loaded.')}</div></section>;
  const phoneData = [{ label: t('有電話', 'With phone'), value: summary.phones }, { label: t('無電話', 'Without phone'), value: summary.total - summary.phones }]; const addressData = [{ label: t('有地址', 'With address'), value: summary.addresses }, { label: t('無地址', 'Without address'), value: summary.total - summary.addresses }];
  return <section className="workspace"><div className="section-heading"><p>MEDICAL PROVIDERS / VISION CARE & OPTOMETRY</p><h2>{t('臺北市驗光所', 'Taipei Optometry Institutions')}</h2><span>{t('公開名錄、行政區統計與外部地址查詢；不建立精確地圖標記。', 'Public directory, district summaries, and external address lookup only; no exact map markers.')}</span></div>
    <div className="subtabs">{[['overview', t('總覽', 'Overview')], ['districts', t('行政區分布', 'District Distribution')], ['postcodes', t('郵遞區號分布', 'Postal Code Distribution')], ['directory', t('驗光所名錄', 'Optometry Institution Directory')], ['quality', t('資料品質', 'Data Quality')], ['notes', t('資料說明', 'Data Notes')]].map(([id, label]) => <button type="button" className={view === id ? 'active' : ''} key={id} onClick={() => { setView(id); setPage(1); }}>{label}</button>)}</div>
    <aside className="filters"><label className="search"><input value={search} onChange={(event) => resetPage(setSearch, event.target.value)} placeholder={t('搜尋機構、行政區、郵遞區號、地址或電話', 'Search institution, district, postal code, address, or phone')} /></label><div className="filter-grid"><label>{t('行政區', 'District')}<select value={district} onChange={(event) => resetPage(setDistrict, event.target.value)}><option value="">{t('全部', 'All')}</option>{[...new Set(records.map((record) => record.districtName).filter(Boolean))].map((item) => <option key={item}>{item}</option>)}</select></label><label>{t('郵遞區號', 'Postal code')}<select value={postalCode} onChange={(event) => resetPage(setPostalCode, event.target.value)}><option value="">{t('全部', 'All')}</option>{[...new Set(records.map((record) => record.postalCode).filter(Boolean))].sort().map((item) => <option key={item}>{item}</option>)}</select></label>{[[t('有電話', 'Has phone'), phone, setPhone], [t('有地址', 'Has address'), address, setAddress]].map(([label, value, set]) => <label key={String(label)}>{String(label)}<select value={String(value)} onChange={(event) => resetPage(set as (value: string) => void, event.target.value)}><option value="">{t('全部', 'All')}</option><option value="yes">{t('是', 'Yes')}</option><option value="no">{t('否', 'No')}</option></select></label>)}</div></aside>
    {view === 'overview' && <><div className="notice subtle">{t('本資料為臺北市驗光所公開名錄，僅供醫療院所與公共資料查詢參考，不代表即時營運狀態、預約狀態、服務項目、費用、驗光品質、眼科醫療能力、診斷、治療、眼鏡或隱形眼鏡供應或官方推薦。實際服務請向機構或臺北市政府衛生局確認。', 'This dataset is a public directory of optometry institutions in Taipei. It does not represent real-time operating status, appointment availability, available services, fees, optometry quality, ophthalmic medical capability, diagnosis, treatment, eyewear or contact-lens availability, or official recommendation. Confirm current services with the institution or Taipei City Department of Health.')}</div><div className="summary-grid">{[[t('機構總數', 'Total institutions'), summary.total], [t('不重複機構名稱', 'Unique institution names'), summary.uniqueNames], [t('涵蓋行政區', 'Districts covered'), summary.districts], [t('郵遞區號數', 'Postal codes represented'), summary.postcodes], [t('有電話紀錄', 'Records with phone'), summary.phones], [t('有地址紀錄', 'Records with addresses'), summary.addresses], [t('機構最多的行政區', 'District with most institutions'), summary.topDistrict]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div><Chart title={t('各行政區機構數', 'Institutions by district')} data={byDistrict} /></>}
    {view === 'districts' && <><Chart title={t('各行政區機構數', 'Institutions by district')} data={byDistrict} /><Chart title={t('有無電話紀錄', 'Records with and without phone')} data={phoneData} /><Chart title={t('有無可用地址紀錄', 'Records with and without usable addresses')} data={addressData} /></>}
    {view === 'postcodes' && <Chart title={t('各郵遞區號機構數', 'Institutions by postal code')} data={byPostalCode} />}
    {view === 'directory' && <><div className="section-heading inline"><p>{t('篩選後紀錄', 'Filtered records')}</p><strong>{sorted.length}</strong><button type="button" onClick={download}>{t('下載篩選後 CSV', 'Download filtered CSV')}</button><label>{t('排序', 'Sort')}<select value={sort} onChange={(event) => { setSort(event.target.value); setPage(1); }}><option value="name">{t('機構名稱', 'Institution name')}</option><option value="district">{t('行政區', 'District')}</option><option value="postalCode">{t('郵遞區號', 'Postal code')}</option><option value="id">ID</option></select></label></div><div className="comparison-scroll procurement-table"><table><thead><tr>{[t('序號', 'ID'), t('機構名稱', 'Institution name'), t('行政區', 'District'), t('郵遞區號', 'Postal code'), t('地址', 'Address'), t('電話', 'Phone'), t('地圖查詢', 'Map lookup')].map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((record) => <tr key={record.id}><td>{record.sourceSequenceNumber || missing}</td><th>{record.institutionName || missing}</th><td>{record.districtName || missing}</td><td>{record.postalCode || missing}</td><td>{record.address || missing} {copy(record.address)}</td><td>{record.phone ? <><a href={`tel:${record.phone.replace(/[^\d+]/g, '')}`}>{record.phone}</a> {copy(record.phone)}</> : missing}</td><td>{mapLink(record.googleMapsQuery)}</td></tr>)}</tbody></table></div><div className="pagination"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>{t('上一頁', 'Previous')}</button><span>{page} / {pages}</span><button type="button" disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>{t('下一頁', 'Next')}</button></div></>}
    {view === 'quality' && <div className="notes-grid"><article><h3>{t('資料品質', 'Data quality')}</h3><p>{t(`可瀏覽紀錄 ${records.length} 筆。重複 ${report?.duplicates.length ?? 0} 筆、缺少名稱 ${report?.missingNames.length ?? 0} 筆、缺少地址 ${report?.missingAddresses.length ?? 0} 筆、電話格式待確認 ${report?.malformedPhones.length ?? 0} 筆、未知郵遞區號 ${report?.unknownPostalCodes.length ?? 0} 筆、無法可靠判定行政區 ${report?.unresolvedDistricts.length ?? 0} 筆。`, `There are ${records.length} browseable records. The conversion report has ${report?.duplicates.length ?? 0} duplicate rows, ${report?.missingNames.length ?? 0} missing names, ${report?.missingAddresses.length ?? 0} missing addresses, ${report?.malformedPhones.length ?? 0} phone values to verify, ${report?.unknownPostalCodes.length ?? 0} unknown postal codes, and ${report?.unresolvedDistricts.length ?? 0} unresolved districts.`)}</p></article></div>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{t('資料範圍', 'Data scope')}</h3><p>{t('地址僅供外部地圖查詢，不表示醫療診斷、治療或服務可用性。本頁不提供視力診斷、處方、治療或隱形眼鏡建議。', 'Addresses are for external map search only and do not establish medical diagnosis, treatment, or service availability. This page does not provide vision diagnosis, prescription, treatment, or contact-lens advice.')}</p></article></div>}
  </section>;
}
