import { useEffect, useMemo, useState } from 'react';

type Language = 'zh' | 'en';
type Clinic = {
  id: string; sourceSequenceNumber: string; institutionName: string; postalCode: string; districtName: string;
  address: string; phoneRaw: string; phoneNumbers: string[]; hasAddress: boolean; hasPhone: boolean;
  hasResolvedDistrict: boolean; externalMapQuery: string; sourceValues: Record<string, string>;
};
type View = 'find' | 'directory' | 'districts' | 'contact' | 'quality' | 'notes';
const districtOrder = ['中正區', '大同區', '中山區', '松山區', '大安區', '萬華區', '信義區', '士林區', '北投區', '內湖區', '南港區', '文山區'];
const missing = '—';

function val(value: string) { return value || missing; }
function mapUrl(query: string) { return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`; }
function telHref(value: string) { const digits = value.replace(/[^\d+]/g, ''); return digits.length >= 7 ? `tel:${digits}` : ''; }
function csvEscape(value: string) { return `"${value.replaceAll('"', '""')}"`; }

function BarChart({ title, rows }: { title: string; rows: Array<{ label: string; value: number }> }) {
  const max = Math.max(...rows.map((row) => row.value), 1);
  return <article className="pt-chart"><div className="pt-chart-title"><h3>{title}</h3><span>{rows.reduce((sum, row) => sum + row.value, 0).toLocaleString()}</span></div><div className="pt-bars">{rows.map((row) => <div className="pt-bar-row" key={row.label}><span>{row.label}</span><div><i style={{ width: `${Math.max(row.value ? 3 : 0, row.value / max * 100)}%` }} /></div><b>{row.value}</b></div>)}</div></article>;
}

export default function PhysicalTherapyClinicsModule({ language }: { language: Language }) {
  const zh = language === 'zh';
  const [records, setRecords] = useState<Clinic[]>([]);
  const [metadata, setMetadata] = useState<{ csvUpdateDate?: string; metadataUpdateDate?: string; sourceUrl?: string; ingestedAt?: string }>({});
  const [view, setView] = useState<View>('find');
  const [search, setSearch] = useState('');
  const [district, setDistrict] = useState('');
  const [postalCode, setPostalCode] = useState('');
  const [phoneFilter, setPhoneFilter] = useState('');
  const [addressFilter, setAddressFilter] = useState('');
  const [page, setPage] = useState(1);
  const [sort, setSort] = useState<'name' | 'district' | 'postal'>('name');
  const [expanded, setExpanded] = useState<string | null>(null);
  const [copied, setCopied] = useState('');
  const pageSize = 10;

  useEffect(() => {
    Promise.all([
      fetch(`${import.meta.env.BASE_URL}data/physical-therapy-clinics/records.json`).then((res) => res.json()),
      fetch(`${import.meta.env.BASE_URL}data/physical-therapy-clinics/metadata.json`).then((res) => res.json()),
    ]).then(([nextRecords, nextMetadata]) => { setRecords(nextRecords); setMetadata(nextMetadata); }).catch(() => { setRecords([]); });
  }, []);

  const districts = useMemo(() => [...new Set(records.map((record) => record.districtName).filter(Boolean))].sort((a, b) => districtOrder.indexOf(a) - districtOrder.indexOf(b)), [records]);
  const filtered = useMemo(() => {
    const query = search.trim().toLocaleLowerCase();
    return records.filter((record) => {
      const haystack = [record.institutionName, record.districtName, record.postalCode, record.address, record.phoneRaw].join(' ').toLocaleLowerCase();
      return (!query || haystack.includes(query)) && (!district || record.districtName === district) && (!postalCode || record.postalCode === postalCode) && (!phoneFilter || (phoneFilter === 'yes' ? record.hasPhone : !record.hasPhone)) && (!addressFilter || (addressFilter === 'yes' ? record.hasAddress : !record.hasAddress));
    }).sort((a, b) => (sort === 'district' ? a.districtName.localeCompare(b.districtName, 'zh-Hant') : sort === 'postal' ? a.postalCode.localeCompare(b.postalCode) : a.institutionName.localeCompare(b.institutionName, 'zh-Hant')) || a.sourceSequenceNumber.localeCompare(b.sourceSequenceNumber));
  }, [records, search, district, postalCode, phoneFilter, addressFilter, sort]);
  useEffect(() => setPage(1), [search, district, postalCode, phoneFilter, addressFilter, sort]);
  const stats = useMemo(() => ({ total: filtered.length, uniqueNames: new Set(filtered.map((record) => record.institutionName).filter(Boolean)).size, districts: new Set(filtered.map((record) => record.districtName).filter(Boolean)).size, postalCodes: new Set(filtered.map((record) => record.postalCode).filter(Boolean)).size, addresses: filtered.filter((record) => record.hasAddress).length, phones: filtered.filter((record) => record.hasPhone).length, resolved: filtered.filter((record) => record.hasResolvedDistrict).length }), [filtered]);
  const suspectedDuplicates = useMemo(() => new Set([...new Set(records.map((record) => record.institutionName).filter(Boolean))].filter((name) => new Set(records.filter((record) => record.institutionName === name).map((record) => record.address)).size > 1)).size, [records]);
  const districtRows = useMemo(() => districts.map((name) => ({ label: name, value: filtered.filter((record) => record.districtName === name).length })).filter((row) => row.value), [districts, filtered]);
  const postalRows = useMemo(() => [...new Set(filtered.map((record) => record.postalCode).filter(Boolean))].sort().map((code) => ({ label: code, value: filtered.filter((record) => record.postalCode === code).length })), [filtered]);
  const paged = filtered.slice((page - 1) * pageSize, page * pageSize);
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const copy = async (key: string, text: string) => { if (!text) return; await navigator.clipboard?.writeText(text); setCopied(key); window.setTimeout(() => setCopied(''), 1200); };
  const exportCsv = () => { const headers = ['ID', 'Clinic', 'District', 'Postal code', 'Address', 'Telephone']; const lines = [headers, ...filtered.map((record) => [record.sourceSequenceNumber, record.institutionName, record.districtName, record.postalCode, record.address, record.phoneRaw])].map((line) => line.map((value) => csvEscape(value)).join(',')); const blob = new Blob([`\uFEFF${lines.join('\n')}`], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'taipei-physical-therapy-clinics-filtered.csv'; anchor.click(); URL.revokeObjectURL(url); };
  const tabs: Array<[View, string, string]> = [['find', zh ? '找物理治療' : 'Find Physical Therapy', '01'], ['directory', zh ? '診所名錄' : 'Clinic Directory', '02'], ['districts', zh ? '行政區分布' : 'District Distribution', '03'], ['contact', zh ? '聯絡資訊' : 'Contact Information', '04'], ['quality', zh ? '資料品質' : 'Data Quality', '05'], ['notes', zh ? '資料說明' : 'Data Notes', '06']];
  const reset = () => { setSearch(''); setDistrict(''); setPostalCode(''); setPhoneFilter(''); setAddressFilter(''); };
  return <section className="workspace physical-therapy-module">
    <div className="pt-hero"><div><p className="eyebrow">PUBLIC HEALTHCARE DIRECTORY / 01</p><h2>{zh ? '臺北市物理治療所' : 'Taipei Physical Therapy Clinics'}</h2><p className="pt-lede">{zh ? '用來源紀錄找到物理治療所，按名稱、行政區、郵遞區號、地址或電話查找。' : 'Find source-recorded physical therapy clinics by name, district, postal code, address, or telephone.'}</p></div><div className="pt-source"><span>{zh ? '來源資料集' : 'SOURCE DATASET'}</span><strong>臺北市物理治療所</strong><a href={metadata.sourceUrl} target="_blank" rel="noreferrer">{zh ? '查看臺北市資料大平臺 ↗' : 'View Taipei Open Data ↗'}</a></div></div>
    <div className="pt-notice"><span>i</span><p>{zh ? '本目錄反映來源更新時間的物理治療所紀錄，不代表目前營業、即時預約、治療項目、費用、保險給付、品質或推薦。' : 'This directory reflects physical therapy clinic records at the source update time and does not establish current operation, immediate appointment availability, or availability of specific treatments.'}</p></div>
    <nav className="pt-tabs" aria-label={zh ? '物理治療所模組導覽' : 'Physical therapy clinic views'}>{tabs.map(([id, label, number]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}><span>{number}</span>{label}</button>)}</nav>
    <div className="pt-filter-panel"><div className="pt-filter-heading"><div><p className="eyebrow">{zh ? '找一間診所' : 'FIND A CLINIC'}</p><h3>{zh ? '搜尋來源紀錄' : 'Search source records'}</h3></div><span>{filtered.length.toLocaleString()} {zh ? '筆符合' : 'matching records'}</span></div><label className="pt-search"><span aria-hidden="true">⌕</span><input aria-label={zh ? '關鍵字搜尋' : 'Keyword search'} value={search} onChange={(event) => setSearch(event.target.value)} placeholder={zh ? '搜尋診所名稱、地址、電話…' : 'Search clinic, address, phone…'} /></label><div className="pt-filter-grid"><label>{zh ? '行政區' : 'District'}<select value={district} onChange={(event) => setDistrict(event.target.value)}><option value="">{zh ? '全部行政區' : 'All districts'}</option>{districts.map((item) => <option key={item}>{item}</option>)}</select></label><label>{zh ? '郵遞區號' : 'Postal code'}<select value={postalCode} onChange={(event) => setPostalCode(event.target.value)}><option value="">{zh ? '全部郵遞區號' : 'All postal codes'}</option>{[...new Set(records.map((record) => record.postalCode).filter(Boolean))].sort().map((item) => <option key={item}>{item}</option>)}</select></label><label>{zh ? '電話' : 'Telephone'}<select value={phoneFilter} onChange={(event) => setPhoneFilter(event.target.value)}><option value="">{zh ? '不限' : 'Any'}</option><option value="yes">{zh ? '有電話' : 'Has telephone'}</option><option value="no">{zh ? '未提供電話' : 'No telephone'}</option></select></label><label>{zh ? '完整地址' : 'Complete address'}<select value={addressFilter} onChange={(event) => setAddressFilter(event.target.value)}><option value="">{zh ? '不限' : 'Any'}</option><option value="yes">{zh ? '有地址' : 'Has address'}</option><option value="no">{zh ? '未提供地址' : 'No address'}</option></select></label></div><div className="pt-filter-actions"><button className="ghost-button" onClick={reset}>{zh ? '清除篩選' : 'Clear filters'}</button><button className="outline-button" onClick={exportCsv}>⇩ {zh ? '匯出篩選 CSV' : 'Export filtered CSV'}</button></div></div>
    {view === 'find' && <><div className="pt-stat-grid">{[[zh ? '來源紀錄' : 'Source records', stats.total], [zh ? '不重複機構名稱' : 'Unique names', stats.uniqueNames], [zh ? '涵蓋行政區' : 'Districts covered', stats.districts], [zh ? '郵遞區號' : 'Postal codes', stats.postalCodes], [zh ? '完整地址' : 'Complete addresses', stats.addresses], [zh ? '有電話' : 'With telephone', stats.phones]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{Number(value).toLocaleString()}</strong></article>)}</div><div className="pt-insight"><div><p className="eyebrow">{zh ? '搜尋便利性' : 'SEARCH CONVENIENCE'}</p><h3>{district ? `${district} · ${zh ? '目前篩選結果' : 'current filter'}` : (zh ? '目前篩選結果' : 'Current filter')}</h3></div><p>{zh ? `目前有 ${stats.total} 筆來源紀錄，其中 ${stats.phones} 筆有電話、${stats.addresses} 筆有地址，涵蓋 ${stats.postalCodes} 個郵遞區號。` : `${stats.total} source-recorded clinics match. ${stats.phones} include telephone information, ${stats.addresses} include addresses, and ${stats.postalCodes} postal codes are represented.`}</p></div><div className="pt-results-header"><div><p className="eyebrow">{zh ? '快速找診所' : 'QUICK DISCOVERY'}</p><h3>{zh ? '結果預覽' : 'Result preview'}</h3></div><button className="text-button" onClick={() => setView('directory')}>{zh ? '查看完整名錄 →' : 'Open full directory →'}</button></div><div className="pt-card-grid">{paged.slice(0, 6).map((record) => <ClinicCard key={record.id} record={record} zh={zh} copy={copy} copied={copied} />)}</div></>}
    {view === 'directory' && <div className="pt-directory"><div className="pt-results-header"><div><p className="eyebrow">{zh ? '診所名錄' : 'CLINIC DIRECTORY'}</p><h3>{filtered.length.toLocaleString()} {zh ? '筆來源紀錄' : 'source records'}</h3></div><label className="pt-sort">{zh ? '排序' : 'Sort'}<select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="name">{zh ? '診所名稱' : 'Clinic name'}</option><option value="district">{zh ? '行政區' : 'District'}</option><option value="postal">{zh ? '郵遞區號' : 'Postal code'}</option></select></label></div><div className="pt-table-wrap"><table><thead><tr>{[zh ? '序號 / ID' : 'ID', zh ? '機構名稱' : 'Clinic', zh ? '行政區' : 'District', zh ? '郵遞區號' : 'Postal code', zh ? '地址' : 'Address', zh ? '電話' : 'Telephone', zh ? '地圖查詢' : 'Map lookup', zh ? '資料狀態' : 'Data status'].map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{paged.map((record) => <tr key={record.id}><td className="mono">{val(record.sourceSequenceNumber)}</td><td><strong>{val(record.institutionName)}</strong><button className="row-detail" onClick={() => setExpanded(expanded === record.id ? null : record.id)} aria-expanded={expanded === record.id}>{expanded === record.id ? '−' : '+'} {zh ? '原始欄位' : 'Source details'}</button>{expanded === record.id && <div className="source-details">{Object.entries(record.sourceValues).map(([key, value]) => <div key={key}><span>{key}</span><b>{val(value)}</b></div>)}</div>}</td><td>{val(record.districtName)}</td><td className="mono">{val(record.postalCode)}</td><td><span>{val(record.address)}</span>{record.address && <button className="copy-button" onClick={() => copy(`address-${record.id}`, record.address)}>{copied === `address-${record.id}` ? '✓' : 'Copy'}</button>}</td><td>{record.phoneRaw ? <>{telHref(record.phoneRaw) ? <a className="tel-link" href={telHref(record.phoneRaw)}>{record.phoneRaw}</a> : <span>{record.phoneRaw}</span>}<button className="copy-button" onClick={() => copy(`phone-${record.id}`, record.phoneRaw)}>{copied === `phone-${record.id}` ? '✓' : 'Copy'}</button></> : missing}</td><td>{record.externalMapQuery && <a className="map-link" href={mapUrl(record.externalMapQuery)} target="_blank" rel="noreferrer">↗ {zh ? '查地圖' : 'Open map'}</a>}</td><td><span className="status-pill">{record.hasPhone ? '● ' : '○ '}{record.hasPhone && record.hasAddress ? (zh ? '資料完整' : 'Address + phone') : (zh ? '部分欄位' : 'Partial fields')}</span></td></tr>)}</tbody></table>{!paged.length && <p className="empty">{zh ? '沒有符合篩選條件的來源紀錄。' : 'No source records match these filters.'}</p>}</div><div className="pt-pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>←</button><span>{page} / {totalPages}</span><button disabled={page >= totalPages} onClick={() => setPage(page + 1)}>→</button></div></div>}
    {view === 'districts' && <div className="pt-view-grid"><BarChart title={zh ? '物理治療所來源紀錄／行政區' : 'Clinic records by district'} rows={districtRows} /><BarChart title={zh ? '物理治療所來源紀錄／郵遞區號' : 'Clinic records by postal code'} rows={postalRows} /><section className="pt-copy-panel"><p className="eyebrow">{zh ? '描述性資料洞察' : 'DESCRIPTIVE INSIGHT'}</p><h3>{zh ? '行政區涵蓋' : 'District coverage'}</h3><p>{zh ? `目前篩選結果涵蓋 ${stats.districts} 個行政區。紀錄較少不代表服務不足，也不代表需求、品質或可近性。` : `The current filter covers ${stats.districts} districts. Fewer source records do not establish underservice, demand, quality, or accessibility.`}</p></section></div>}
    {view === 'contact' && <div className="pt-view-grid"><BarChart title={zh ? '電話資訊' : 'Telephone coverage'} rows={[{ label: zh ? '有電話' : 'With telephone', value: stats.phones }, { label: zh ? '未提供電話' : 'No telephone', value: stats.total - stats.phones }]} /><BarChart title={zh ? '地址資訊' : 'Address coverage'} rows={[{ label: zh ? '有完整地址' : 'Complete address', value: stats.addresses }, { label: zh ? '未提供地址' : 'No address', value: stats.total - stats.addresses }]} /><BarChart title={zh ? '行政區解析' : 'District resolution'} rows={[{ label: zh ? '已解析行政區' : 'Resolved district', value: stats.resolved }, { label: zh ? '未解析行政區' : 'Unresolved district', value: stats.total - stats.resolved }]} /></div>}
    {view === 'quality' && <div className="pt-quality-grid"><div className="pt-quality-score"><p className="eyebrow">{zh ? '資料品質檢查' : 'DATA QUALITY CHECKS'}</p><strong>{records.length}</strong><span>{zh ? '筆保留來源紀錄' : 'source rows retained'}</span></div>{[[zh ? '缺少機構名稱' : 'Missing institution name', records.filter((record) => !record.institutionName).length], [zh ? '缺少地址' : 'Missing address', records.filter((record) => !record.hasAddress).length], [zh ? '缺少電話' : 'Missing telephone', records.filter((record) => !record.hasPhone).length], [zh ? '未解析行政區' : 'Unresolved district', records.filter((record) => !record.hasResolvedDistrict).length], [zh ? '同名多地址' : 'Same name, multiple addresses', suspectedDuplicates]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{Number(value).toLocaleString()}</strong></article>)}</div>}
    {view === 'notes' && <div className="pt-notes-grid"><article><p className="eyebrow">{zh ? '來源與更新' : 'SOURCE & UPDATES'}</p><h3>{zh ? '資料時間' : 'Dataset dates'}</h3><dl><div><dt>{zh ? 'CSV 更新' : 'CSV update'}</dt><dd>{val(metadata.csvUpdateDate ?? '')}</dd></div><div><dt>{zh ? '詮釋資料更新' : 'Metadata update'}</dt><dd>{val(metadata.metadataUpdateDate ?? '')}</dd></div><div><dt>{zh ? '本地匯入' : 'Ingested locally'}</dt><dd>{metadata.ingestedAt ? new Date(metadata.ingestedAt).toLocaleDateString() : missing}</dd></div></dl></article><article><p className="eyebrow">{zh ? '位置限制' : 'LOCATION LIMITATION'}</p><h3>{zh ? '只提供地圖查詢' : 'Map lookup only'}</h3><p>{zh ? '官方資料提供地址但沒有確認座標。本模組不自動地理編碼、不建立精確標記，地圖按鈕會將來源地址交給外部地圖服務查詢。' : 'The source provides addresses but no confirmed coordinates. This module does not geocode or create exact markers; map actions pass the source address to an external map service.'}</p></article><article><p className="eyebrow">{zh ? '使用提醒' : 'USE WITH CARE'}</p><h3>{zh ? '行政聯絡資料' : 'Administrative contact records'}</h3><p>{zh ? '電話、地址與機構名稱是來源更新時間的公開行政資料。請直接向機構或臺北市政府衛生局確認實際服務、預約、費用、保險與專業資格。' : 'Names, addresses, and telephone numbers are public administrative source records at update time. Confirm actual services, appointments, fees, insurance, and professional qualifications directly with the institution or Taipei City Department of Health.'}</p></article></div>}
  </section>;
}

function ClinicCard({ record, zh, copy, copied }: { record: Clinic; zh: boolean; copy: (key: string, text: string) => void; copied: string }) {
  return <article className="pt-clinic-card"><div className="pt-card-top"><span className="record-id">#{record.sourceSequenceNumber}</span><span className="status-pill">{record.hasPhone ? (zh ? '有電話' : 'Telephone listed') : (zh ? '未提供電話' : 'No telephone')}</span></div><h4>{val(record.institutionName)}</h4><p className="pt-address"><b>{val(record.districtName)} · {val(record.postalCode)}</b><br />{val(record.address)}</p><div className="pt-card-actions">{record.phoneRaw ? <>{telHref(record.phoneRaw) ? <a className="tel-link" href={telHref(record.phoneRaw)}>☎ {record.phoneRaw}</a> : <span className="muted">{record.phoneRaw}</span>}</> : <span className="muted">{missing}</span>}<button className="icon-button" onClick={() => copy(`card-${record.id}`, `${record.institutionName} ${record.address} ${record.phoneRaw}`)}>{copied === `card-${record.id}` ? '✓' : 'Copy'}</button><a className="map-link" href={mapUrl(record.externalMapQuery)} target="_blank" rel="noreferrer">↗ {zh ? '地圖查詢' : 'Map lookup'}</a></div><small>{zh ? '來源紀錄；請自行確認目前服務資訊。' : 'Source-recorded information; confirm current details directly.'}</small></article>;
}
