import { useEffect, useMemo, useState } from 'react';

interface Institution { id: string; sourceId: string; institutionType: string; institutionTypeNormalized: string; districtName: string; institutionName: string; address: string; phone: string; hasPhone: boolean; googleMapsQuery: string; }
const MISSING = '—'; const DISTRICTS = ['中正區', '大同區', '中山區', '松山區', '大安區', '萬華區', '信義區', '士林區', '北投區', '內湖區', '南港區', '文山區'];
function Chart({ title, data }: { title: string; data: Array<{ label: string; value: number }> }) { const max = Math.max(1, ...data.map((item) => item.value)); return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) => <div className="bar-row wide-label" key={item.label}><span>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{item.value}</b></div>)}</div></section>; }
export default function PsychiatricRehabilitationAndNursingInstitutionsModule({ language }: { language: 'zh' | 'en' }) {
  const zh = language === 'zh'; const [records, setRecords] = useState<Institution[]>([]); const [loadError, setLoadError] = useState(false); const [view, setView] = useState<'overview' | 'districts' | 'types' | 'directory' | 'quality' | 'notes'>('overview'); const [search, setSearch] = useState(''); const [district, setDistrict] = useState(''); const [type, setType] = useState(''); const [phone, setPhone] = useState(''); const [sort, setSort] = useState('name'); const [page, setPage] = useState(1);
  useEffect(() => { fetch(`${import.meta.env.BASE_URL}data/psychiatric-rehabilitation-and-nursing-institutions/records.json`).then((response) => { if (!response.ok) throw new Error(String(response.status)); return response.json(); }).then(setRecords).catch(() => setLoadError(true)); }, []);
  const filtered = useMemo(() => { const query = search.trim().toLocaleLowerCase(); return records.filter((record) => (!query || [record.institutionName, record.institutionType, record.districtName, record.address, record.phone].join(' ').toLocaleLowerCase().includes(query)) && (!district || record.districtName === district) && (!type || record.institutionType === type) && (!phone || (phone === 'yes' ? record.hasPhone : !record.hasPhone))); }, [records, search, district, type, phone]);
  const byDistrict = useMemo(() => DISTRICTS.map((label) => ({ label, value: filtered.filter((record) => record.districtName === label).length })).filter((item) => item.value), [filtered]); const byType = useMemo(() => [...new Set(filtered.map((record) => record.institutionType).filter(Boolean))].map((label) => ({ label, value: filtered.filter((record) => record.institutionType === label).length })), [filtered]);
  const summary = useMemo(() => ({ total: filtered.length, unique: new Set(filtered.map((record) => record.institutionName).filter(Boolean)).size, districts: byDistrict.length, types: byType.length, phones: filtered.filter((record) => record.hasPhone).length, topDistrict: [...byDistrict].sort((a, b) => b.value - a.value)[0]?.label ?? '', topType: [...byType].sort((a, b) => b.value - a.value)[0]?.label ?? '' }), [filtered, byDistrict, byType]);
  const quality = useMemo(() => ({ duplicateRows: records.length - new Set(records.map((record) => `${record.institutionName}|${record.address}|${record.phone}`)).size, missingNames: records.filter((record) => !record.institutionName).length, missingAddresses: records.filter((record) => !record.address).length, malformedPhones: records.filter((record) => record.phone && !/^[+()\d\s-]{6,}$/.test(record.phone)).length, unknownDistricts: records.filter((record) => record.districtName && !DISTRICTS.includes(record.districtName)).length, unknownTypes: records.filter((record) => record.institutionTypeNormalized === 'unknown').length }), [records]);
  const sorted = useMemo(() => [...filtered].sort((a, b) => sort === 'district' ? a.districtName.localeCompare(b.districtName, 'zh-Hant') : sort === 'type' ? a.institutionType.localeCompare(b.institutionType, 'zh-Hant') : a.institutionName.localeCompare(b.institutionName, 'zh-Hant')), [filtered, sort]); const pageSize = 25; const pages = Math.max(1, Math.ceil(sorted.length / pageSize)); const rows = sorted.slice((Math.min(page, pages) - 1) * pageSize, Math.min(page, pages) * pageSize); const reset = (action: () => void) => { action(); setPage(1); };
  const download = () => { const headings = ['ID', 'Institution name', 'Institution type', 'District', 'Address', 'Phone']; const quote = (value: string) => `"${value.replaceAll('"', '""')}"`; const csv = [headings, ...filtered.map((record) => [record.sourceId, record.institutionName, record.institutionType, record.districtName, record.address, record.phone])].map((row) => row.map(quote).join(',')).join('\n'); const url = URL.createObjectURL(new Blob(['\uFEFF', csv], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'psychiatric-rehabilitation-and-nursing-institutions-filtered.csv'; link.click(); URL.revokeObjectURL(url); };
  const map = (value: string) => value ? <a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(value)}`}>{zh ? '地圖查詢' : 'Map lookup'}</a> : MISSING; const copy = (value: string) => value && <button type="button" className="copy-button" onClick={() => navigator.clipboard?.writeText(value)}>{zh ? '複製' : 'Copy'}</button>;
  if (loadError) return <section className="workspace"><div className="notice">{zh ? '無法載入本機資料檔。' : 'The local data file could not be loaded.'}</div></section>;
  return <section className="workspace"><div className="section-heading"><p>MENTAL HEALTH / PUBLIC DIRECTORY</p><h2>{zh ? '精神復健暨精神護理機構' : 'Psychiatric Rehabilitation and Nursing Institutions'}</h2><span>{zh ? '公開名冊與行政區彙整；地址僅提供外部地圖搜尋，不建立精確地圖標記。' : 'Public directory and district summaries; external address lookup only, with no exact map markers.'}</span></div><div className="subtabs">{([['overview', zh ? '總覽' : 'Overview'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['types', zh ? '機構類型' : 'Institution Types'], ['directory', zh ? '機構名冊' : 'Institution Directory'], ['quality', zh ? '資料品質' : 'Data Quality'], ['notes', zh ? '資料說明' : 'Data Notes']] as const).map(([id, label]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => { setView(id); setPage(1); }}>{label}</button>)}</div><aside className="filters"><label className="search"><input value={search} onChange={(event) => reset(() => setSearch(event.target.value))} placeholder={zh ? '搜尋機構名稱、類型、行政區、地址或電話' : 'Search institution, type, district, address, or phone'} /></label><div className="filter-grid"><label>{zh ? '行政區' : 'District'}<select value={district} onChange={(event) => reset(() => setDistrict(event.target.value))}><option value="">{zh ? '全部' : 'All'}</option>{DISTRICTS.filter((value) => records.some((record) => record.districtName === value)).map((value) => <option key={value}>{value}</option>)}</select></label><label>{zh ? '機構類型' : 'Institution type'}<select value={type} onChange={(event) => reset(() => setType(event.target.value))}><option value="">{zh ? '全部' : 'All'}</option>{[...new Set(records.map((record) => record.institutionType).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select></label><label>{zh ? '有電話' : 'Has phone'}<select value={phone} onChange={(event) => reset(() => setPhone(event.target.value))}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '有' : 'Yes'}</option><option value="no">{zh ? '無' : 'No'}</option></select></label></div></aside>
    {view === 'overview' && <><div className="notice subtle">{zh ? '本資料為臺北市精神復健暨精神護理機構公開名冊，不代表即時營運、目前容量、收治或轉介資格、可提供服務、費用、醫療品質、照護適切性、緊急能力或官方推薦。實際服務與資格請向機構或臺北市政府衛生局確認。' : 'This dataset is a public directory of psychiatric rehabilitation and psychiatric nursing institutions in Taipei. It does not represent real-time operating status, current capacity, admission or referral eligibility, available services, fees, medical quality, suitability of care, emergency capability, or official recommendation. Confirm current services, eligibility, and other information with the institution or Taipei City Department of Health.'}</div><div className="summary-grid">{[[zh ? '機構總數' : 'Total institutions', summary.total], [zh ? '不重複機構名稱' : 'Unique institution names', summary.unique], [zh ? '涵蓋行政區' : 'Districts covered', summary.districts], [zh ? '機構類型數' : 'Institution types', summary.types], [zh ? '有電話紀錄' : 'Records with phone', summary.phones], [zh ? '機構最多行政區' : 'Top district', summary.topDistrict || MISSING], [zh ? '最常見機構類型' : 'Most common type', summary.topType || MISSING]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div><Chart title={zh ? '各行政區機構數' : 'Institutions by district'} data={byDistrict} /></>}
    {view === 'districts' && <Chart title={zh ? '各行政區機構數' : 'Institutions by district'} data={byDistrict} />}
    {view === 'types' && <><Chart title={zh ? '各機構類型數' : 'Institutions by type'} data={byType} /><Chart title={zh ? '各行政區機構類型數' : 'Institution types by district'} data={byDistrict} /><Chart title={zh ? '有無電話紀錄' : 'Records with and without phone'} data={[{ label: zh ? '有' : 'With', value: summary.phones }, { label: zh ? '無' : 'Without', value: summary.total - summary.phones }]} /></>}
    {view === 'directory' && <><div className="section-heading inline"><p>{zh ? '篩選後紀錄' : 'Filtered records'}</p><strong>{sorted.length}</strong><button type="button" onClick={download}>{zh ? '下載篩選 CSV' : 'Download filtered CSV'}</button><label>{zh ? '排序' : 'Sort'}<select value={sort} onChange={(event) => { setSort(event.target.value); setPage(1); }}><option value="name">{zh ? '依機構名稱' : 'Institution name'}</option><option value="type">{zh ? '依機構類型' : 'Institution type'}</option><option value="district">{zh ? '依行政區' : 'District'}</option></select></label></div><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['序號', '機構名稱', '機構類型', '行政區', '地址', '電話', '地圖查詢'] : ['ID', 'Institution name', 'Institution type', 'District', 'Address', 'Phone', 'Map lookup']).map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((record) => <tr key={record.id}><td>{record.sourceId || MISSING}</td><th>{record.institutionName || MISSING}</th><td>{record.institutionType || MISSING}</td><td>{record.districtName || MISSING}</td><td>{record.address || MISSING} {copy(record.address)}</td><td>{record.phone ? <><a href={`tel:${record.phone.replace(/[^\d+]/g, '')}`}>{record.phone}</a> {copy(record.phone)}</> : MISSING}</td><td>{map(record.googleMapsQuery)}</td></tr>)}</tbody></table></div><div className="pagination"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>{zh ? '上一頁' : 'Previous'}</button><span>{page} / {pages}</span><button type="button" disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>{zh ? '下一頁' : 'Next'}</button></div></>}
    {view === 'quality' && <div className="notes-grid"><article><h3>{zh ? '資料品質報告' : 'Data quality report'}</h3><p>{zh ? `重複列 ${quality.duplicateRows} 筆；缺少機構名稱 ${quality.missingNames} 筆；缺少地址 ${quality.missingAddresses} 筆；電話格式異常 ${quality.malformedPhones} 筆；未知行政區 ${quality.unknownDistricts} 筆；未知機構類型 ${quality.unknownTypes} 筆。` : `Duplicate rows: ${quality.duplicateRows}; missing institution names: ${quality.missingNames}; missing addresses: ${quality.missingAddresses}; malformed phones: ${quality.malformedPhones}; unknown districts: ${quality.unknownDistricts}; unknown institution types: ${quality.unknownTypes}.`}</p></article><article><h3>{zh ? '類型處理方式' : 'Type handling'}</h3><p>{zh ? '僅依來源的機構類型欄位分類，保留原始值，不從機構名稱推論服務、收治條件、容量、專科或照護程度。' : 'Types are classified only from the source institution-type field and preserve its original value; the directory does not infer services, admission conditions, capacity, specialty, or level of care from names.'}</p></article></div>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料範圍' : 'Data scope'}</h3><p>{zh ? '本機 JSON 來自臺北市政府衛生局公開資料。名冊不得用於推論診斷、治療適切性、照護程度、醫療品質或緊急能力。' : 'The local JSON is based on Taipei City Department of Health public data. Directory inclusion must not be used to infer diagnosis, treatment suitability, level of care, medical quality, or emergency capability.'}</p></article><article><h3>{zh ? '位置資訊' : 'Location information'}</h3><p>{zh ? '來源沒有確認的官方座標，因此不建立精確地圖標記或自動地理編碼；地址僅提供外部地圖搜尋。' : 'The source has no confirmed official coordinates, so it creates no exact map markers or automatic geocoding; addresses only provide external map search.'}</p></article></div>}
  </section>;
}
