import { useEffect, useMemo, useState } from 'react';
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet';
import { DISTRICTS, TAIPEI_DISTRICT_CENTROIDS } from './lib/civicGroups';
import { buildPubliclyFundedHpvVaccinationProviderSummary, filterPubliclyFundedHpvVaccinationProviders } from './lib/publiclyFundedHpvVaccinationProviders';
import type { Language, PubliclyFundedHpvVaccinationProviderFilters, PubliclyFundedHpvVaccinationProviderRecord, PubliclyFundedHpvVaccinationProviderSummary } from './types';

const emptyFilters: PubliclyFundedHpvVaccinationProviderFilters = { search: '', district: '', districtCode: '', roadName: '', hasPhone: '', phoneType: '', districtMismatch: '' };
const fmt = (value?: number) => value === undefined ? '—' : value.toLocaleString();
const disclaimer = (zh: boolean) => zh ? '公費HPV疫苗特約醫療院所資料為臺北市公開資料中的公費HPV疫苗接種服務特約醫療院所名冊，僅供查詢行政區代碼、醫療院所名稱、地址與聯絡電話等來源欄位使用，不代表即時門診時間、即時預約名額、疫苗庫存、接種資格、費用標準、醫療建議、疫苗接種建議、服務品質排名或官方背書。' : 'Publicly funded HPV vaccination provider data is Taipei public-data directory information for medical institutions contracted to provide publicly funded HPV vaccination services. It is for source-field lookup only and does not represent real-time clinic hours, appointment availability, vaccine stock, eligibility, fees, medical advice, vaccination advice, service quality ranking, or official endorsement.';
const mapNotice = (zh: boolean) => zh ? '公費HPV疫苗特約醫療院所資料未提供官方經緯度，地圖以行政區彙總呈現，不代表精確院所位置、即時門診時間、預約名額、疫苗庫存或接種資格。' : 'Publicly funded HPV vaccination provider data does not provide official coordinates. The map shows district-level summaries and does not represent exact provider locations, real-time clinic hours, appointment availability, vaccine stock, or vaccination eligibility.';

function Bar({ title, rows }: { title: string; rows: Array<{ label: string; count: number }> }) {
  const max = Math.max(...rows.map((row) => row.count), 1);
  return <section className="chart"><h3>{title}</h3><div className="bars">{rows.map((row) => <div className="bar-row wide-label" key={row.label}><span title={row.label}>{row.label}</span><div><i style={{ width: `${Math.max(2, row.count / max * 100)}%` }} /></div><b>{fmt(row.count)}</b></div>)}</div></section>;
}

function Filters({ records, filters, setFilters, language }: { records: PubliclyFundedHpvVaccinationProviderRecord[]; filters: PubliclyFundedHpvVaccinationProviderFilters; setFilters: (filters: PubliclyFundedHpvVaccinationProviderFilters) => void; language: Language }) {
  const zh = language === 'zh', update = (key: keyof PubliclyFundedHpvVaccinationProviderFilters, value: string) => setFilters({ ...filters, [key]: value });
  const options = <T extends string>(values: Array<T | undefined>) => [...new Set(values.filter(Boolean) as T[])].sort((a, b) => a.localeCompare(b));
  const yesNo = <><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '有' : 'Yes'}</option><option value="no">{zh ? '無' : 'No'}</option></>;
  return <aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(event) => update('search', event.target.value)} placeholder={zh ? '搜尋醫療院所名稱、行政區、地址或電話' : 'Search provider name, district, address, or phone'} /></label><div className="filter-grid grant-filters">
    <label>{zh ? '行政區' : 'District'}<select value={filters.district} onChange={(event) => update('district', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{DISTRICTS.map((district) => <option key={district}>{district}</option>)}</select></label>
    <label>{zh ? '行政區代碼' : 'District code'}<select value={filters.districtCode} onChange={(event) => update('districtCode', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.districtCode)).map((code) => <option key={code}>{code}</option>)}</select></label>
    <label>{zh ? '道路' : 'Road'}<select value={filters.roadName} onChange={(event) => update('roadName', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.roadName)).map((road) => <option key={road}>{road}</option>)}</select></label>
    <label>{zh ? '有電話' : 'Has phone'}<select value={filters.hasPhone} onChange={(event) => update('hasPhone', event.target.value)}>{yesNo}</select></label>
    <label>{zh ? '電話類型' : 'Phone type'}<select value={filters.phoneType} onChange={(event) => update('phoneType', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{['taipei_landline', 'other_landline', 'mobile', 'extension', 'multiple', 'missing', 'unknown'].map((type) => <option value={type} key={type}>{type}</option>)}</select></label>
    <label>{zh ? '行政區代碼與地址不一致' : 'District code / address mismatch'}<select value={filters.districtMismatch} onChange={(event) => update('districtMismatch', event.target.value)}>{yesNo}</select></label>
  </div>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => setFilters(emptyFilters)}>{zh ? '清除篩選' : 'Clear filters'}</button>}</aside>;
}

function Overview({ summary, language }: { summary: PubliclyFundedHpvVaccinationProviderSummary; language: Language }) {
  const zh = language === 'zh';
  return <><div className="notice subtle">{disclaimer(zh)}</div><div className="summary-grid">{[
    [zh ? 'HPV疫苗特約院所數' : 'HPV vaccination provider count', summary.totalRecords],
    [zh ? '涵蓋行政區數' : 'Districts covered', summary.districtCount],
    [zh ? '不重複地址數' : 'Unique address count', summary.uniqueAddressCount],
    [zh ? '不重複電話數' : 'Unique phone count', summary.uniquePhoneCount],
    [zh ? '有電話紀錄數' : 'Records with phone', summary.recordsWithPhone],
    [zh ? '有行政區代碼對應紀錄' : 'Records with district-code mapping', summary.dataQuality.districtCodeMapped],
    [zh ? '有地址行政區解析紀錄' : 'Records with district parsed from address', summary.dataQuality.districtFromAddressParsed],
    [zh ? '行政區不一致紀錄' : 'District mismatch count', summary.recordsWithDistrictMismatch],
    [zh ? '院所最多行政區' : 'Top district by provider count', summary.byDistrict[0]?.district ?? '—'],
  ].map(([label, value]) => <article key={label}><span>{label}</span><strong>{typeof value === 'number' ? fmt(value) : value}</strong></article>)}</div><div className="chart-grid"><Bar title={zh ? '各行政區院所數' : 'Providers by district'} rows={summary.byDistrict.map((item) => ({ label: item.district, count: item.providerCount }))} /><Bar title={zh ? '各行政區代碼院所數' : 'Providers by district code'} rows={summary.byDistrictCode.map((item) => ({ label: `${item.districtCode} ${item.districtFromCode ?? ''}`, count: item.providerCount }))} /><Bar title={zh ? '電話有無' : 'Phone availability'} rows={[{ label: zh ? '有電話' : 'Has phone', count: summary.phoneQuality.hasPhone }, { label: zh ? '無電話' : 'Missing phone', count: summary.phoneQuality.missingPhone }]} /><Bar title={zh ? '院所最多道路' : 'Top roads by provider count'} rows={summary.byRoadName.slice(0, 20).map((item) => ({ label: item.roadName, count: item.count }))} /></div></>;
}

function DistrictMap({ summary, language, openDistrict }: { summary: PubliclyFundedHpvVaccinationProviderSummary; language: Language; openDistrict: (district: string) => void }) {
  const zh = language === 'zh', max = Math.max(...summary.byDistrict.map((item) => item.providerCount), 1);
  return <div className="map-wrap"><div className="notice">{mapNotice(zh)}</div><MapContainer center={[25.072, 121.54]} zoom={11} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap contributors &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" />{summary.byDistrict.map((district) => { const point = TAIPEI_DISTRICT_CENTROIDS[district.district]; return point && <CircleMarker key={district.district} center={[point.latitude, point.longitude]} radius={10 + 28 * Math.sqrt(district.providerCount / max)} pathOptions={{ fillColor: '#6b7dbb', fillOpacity: .74, color: '#fff7e8', weight: 2 }}><Popup><div className="map-popup"><strong>{district.district}</strong><p>{zh ? '院所數' : 'Provider count'}: {fmt(district.providerCount)}</p><small>{zh ? '本圖以行政區彙總呈現，不代表精確院所位置、即時門診時間、預約名額、疫苗庫存或接種資格。' : 'This map shows district-level summaries and does not represent exact provider locations, real-time clinic hours, appointment availability, vaccine stock, or vaccination eligibility.'}</small><button onClick={() => openDistrict(district.district)}>{zh ? '查看清單' : 'View directory'}</button></div></Popup></CircleMarker>; })}</MapContainer></div>;
}

function Directory({ records, language }: { records: PubliclyFundedHpvVaccinationProviderRecord[]; language: Language }) {
  const zh = language === 'zh';
  const [limit, setLimit] = useState(80);
  useEffect(() => setLimit(80), [records]);
  return <><h3>{zh ? '公費HPV疫苗特約醫療院所清單' : 'Publicly Funded HPV Vaccination Provider Directory'}</h3><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['醫療院所名稱', '行政區', '地址', '聯絡電話', '地圖查詢', '來源明細'] : ['Provider name', 'District', 'Address', 'Phone', 'Map lookup', 'Source details']).map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{records.slice(0, limit).map((record) => <tr key={record.id}><th>{record.providerName}</th><td>{record.district ?? '—'}</td><td>{record.address ?? '—'}</td><td>{record.phoneDialHref ? <a href={record.phoneDialHref}>{record.phoneDisplay ?? record.phone}</a> : record.phoneDisplay ?? record.phone ?? '—'}</td><td>{record.googleMapsQuery ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.googleMapsQuery)}`} target="_blank" rel="noreferrer">{zh ? '地圖查詢' : 'Map lookup'}</a> : '—'}</td><td><details><summary>{zh ? '來源明細' : 'Source details'}</summary><p>{zh ? '項次' : 'Sequence number'}: {record.sourceSequenceNumber ?? '—'}<br />{zh ? '行政區代碼' : 'District code'}: {record.districtCode ?? '—'}<br />{zh ? '代碼對應行政區' : 'District from code'}: {record.districtFromCode ?? '—'}<br />{zh ? '地址解析行政區' : 'District from address'}: {record.districtFromAddress ?? '—'}<br />{zh ? '行政區不一致' : 'District mismatch'}: {record.districtMismatch ? (zh ? '是' : 'Yes') : (zh ? '否' : 'No')}<br />{zh ? '道路' : 'Road'}: {record.roadName ?? '—'}<br />{zh ? '電話類型' : 'Phone type'}: {record.phoneType}<br />{record.source} / {record.sourceAgency}<br />{disclaimer(zh)}</p></details></td></tr>)}</tbody></table></div>{!records.length && <p className="empty">{zh ? '沒有符合條件的紀錄。' : 'No records match these filters.'}</p>}{limit < records.length && <button className="load-more" onClick={() => setLimit(limit + 80)}>{zh ? '載入更多' : 'Load more'} · {records.length - limit}</button>}</>;
}

export default function PubliclyFundedHpvVaccinationProvidersModule({ records, summary, language, related }: { records: PubliclyFundedHpvVaccinationProviderRecord[]; summary: PubliclyFundedHpvVaccinationProviderSummary; language: Language; related?: { vaccinationProviders?: number; telepsychology?: number; elderlyWelfare?: number } }) {
  const zh = language === 'zh';
  const [view, setView] = useState<'overview' | 'districts' | 'directory' | 'compare' | 'notes'>('overview');
  const [filters, setFilters] = useState(emptyFilters);
  const filtered = useMemo(() => filterPubliclyFundedHpvVaccinationProviders(records, filters), [records, filters]);
  const active = useMemo(() => Object.values(filters).some(Boolean) ? buildPubliclyFundedHpvVaccinationProviderSummary(filtered) : summary, [filtered, filters, summary]);
  const openDistrict = (district: string) => { setFilters({ ...emptyFilters, district }); setView('directory'); };
  const views = [['overview', zh ? '總覽' : 'Overview'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['directory', zh ? '醫療院所清單' : 'Provider Directory'], ['compare', zh ? '與其他預防接種資料比較' : 'Compare Vaccination Records'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  return <><Filters records={records} filters={filters} setFilters={setFilters} language={language} /><section className="workspace"><div className="section-heading"><p>03 / HEALTHCARE & VACCINATION PUBLIC RECORDS</p><h2>{zh ? '公費HPV疫苗特約醫療院所' : 'Publicly Funded HPV Vaccination Providers'}</h2><span>{zh ? '查詢臺北市提供公費HPV疫苗接種服務之特約醫療院所，包含行政區代碼、醫療院所名稱、地址與聯絡電話等公開資料。' : 'Look up Taipei medical institutions contracted to provide publicly funded HPV vaccination services, including district code, provider name, address, and phone from public data.'}</span></div><div className="subtabs">{views.map(([id, label]) => <button className={view === id ? 'active' : ''} onClick={() => setView(id)} key={id}>{label}</button>)}</div><div className="section-heading inline"><div><p>{zh ? '篩選結果' : 'Filtered records'}</p></div><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆' : 'records'}</span></strong></div>
    {view === 'overview' && <Overview summary={active} language={language} />}
    {view === 'districts' && <DistrictMap summary={active} language={language} openDistrict={openDistrict} />}
    {view === 'directory' && <Directory records={filtered} language={language} />}
    {view === 'compare' && <><div className="notice subtle">{zh ? '公費HPV疫苗特約醫療院所與各項預防接種合約醫療院所資料性質相關但不完全相同。前者聚焦公費HPV疫苗接種服務，後者涵蓋多種預防接種服務類別；兩者不應直接合併解讀為相同服務清冊。' : 'Publicly funded HPV vaccination providers and broader contracted vaccination medical provider records are related but not identical. The former focuses on publicly funded HPV vaccination services, while the latter covers multiple vaccination service categories. They should not be merged as the same service directory.'}</div><Bar title={zh ? '相關醫療/照護資料紀錄數比較' : 'Related healthcare/care record counts'} rows={[{ label: zh ? 'HPV疫苗院所' : 'HPV providers', count: summary.totalRecords }, { label: zh ? '各項預防接種合約院所' : 'Contracted vaccination providers', count: related?.vaccinationProviders ?? 0 }, { label: zh ? '通訊心理諮商機構' : 'Telepsychology institutions', count: related?.telepsychology ?? 0 }, { label: zh ? '老人福利機構' : 'Elderly welfare institutions', count: related?.elderlyWelfare ?? 0 }].filter((row) => row.count)} /></>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料內容' : 'Data contents'}</h3><p>{zh ? '公費HPV疫苗特約醫療院所資料提供臺北市提供公費HPV疫苗接種服務之醫療院所公開資料，欄位包含項次、行政區、醫療院所名稱、地址與聯絡電話。本網站將來源行政區代碼對應為臺北市行政區名稱，並從地址解析行政區與道路名稱，整理為行政區分布與醫療院所清單。資料未提供官方經緯度，因此預設不顯示精確點位。' : 'Publicly funded HPV vaccination provider data provides Taipei public records for medical institutions offering publicly funded HPV vaccination services. Fields include sequence number, district, provider name, address, and phone. This site maps the source district code to Taipei district names, parses district and road name from addresses, and organizes district distribution and a provider directory. The data does not provide official coordinates, so exact points are not shown by default.'}</p></article><article><h3>{zh ? '解讀限制' : 'Interpretation limits'}</h3><p>{disclaimer(zh)}</p></article><article><h3>{zh ? '資料來源' : 'Source'}</h3><p><a href="https://data.taipei/dataset/detail?id=96f143fe-4c95-4d88-9985-77f28e2d2c3d" target="_blank" rel="noreferrer">{zh ? '臺北市公費HPV疫苗特約醫療院所' : 'Taipei publicly funded HPV vaccination providers'} ↗</a></p></article></div>}
  </section></>;
}
