import { useMemo, useState } from 'react';
import { buildSeniorGroupMealServiceSiteSummary, filterSeniorGroupMealServiceSites } from './lib/seniorGroupMealServiceSites';
import type { Language, SeniorGroupMealServiceSiteFilters, SeniorGroupMealServiceSiteRecord, SeniorGroupMealServiceSiteSummary } from './types';

const emptyFilters: SeniorGroupMealServiceSiteFilters = { search: '', district: '', hasPhone: '' };
const disclaimer = (zh: boolean) => zh
  ? '本資料為臺北市老人共餐單位公開資料，僅供社福服務據點與公共資料查詢參考，不代表即時供餐、服務資格、名額、費用、營業時間、餐點內容、服務品質、營養或醫療建議。實際服務資訊請向各據點或臺北市政府社會局確認。'
  : 'This dataset is for public lookup of Taipei senior group-meal service sites. It does not represent real-time meal availability, eligibility, capacity, fees, operating hours, menu content, service quality, nutritional advice, or medical advice. Confirm current service information with the individual site or Taipei City Department of Social Welfare.';
const BarChart = ({ title, data }: { title: string; data: Array<{ label: string; value: number }> }) => {
  const max = Math.max(...data.map((item) => item.value), 1);
  return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) => <div className="bar-row wide-label" key={item.label}><span>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{item.value.toLocaleString()}</b></div>)}</div></section>;
};

export default function SeniorGroupMealServiceSitesModule({ records, summary, language }: { records: SeniorGroupMealServiceSiteRecord[]; summary: SeniorGroupMealServiceSiteSummary; language: Language }) {
  const zh = language === 'zh';
  const [view, setView] = useState<'overview' | 'districts' | 'directory' | 'quality' | 'notes'>('overview');
  const [filters, setFilters] = useState(emptyFilters);
  const filtered = useMemo(() => filterSeniorGroupMealServiceSites(records, filters), [records, filters]);
  const activeSummary = useMemo(() => Object.values(filters).some(Boolean) ? buildSeniorGroupMealServiceSiteSummary(filtered) : summary, [filtered, filters, summary]);
  const districts = [...new Set(records.map((record) => record.districtNameNormalized).filter(Boolean))].sort((a, b) => a!.localeCompare(b!)) as string[];
  const views = [['overview', zh ? '總覽' : 'Overview'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['directory', zh ? '共餐據點名冊' : 'Service Site Directory'], ['quality', zh ? '資料品質' : 'Data Quality'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  return <><aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} placeholder={zh ? '搜尋據點名稱、行政區、地址或電話' : 'Search site name, district, address, or phone'} /></label><div className="filter-grid"><label>{zh ? '行政區' : 'District'}<select value={filters.district} onChange={(event) => setFilters({ ...filters, district: event.target.value })}><option value="">{zh ? '全部' : 'All'}</option>{districts.map((district) => <option key={district} value={district}>{district}</option>)}</select></label><label>{zh ? '有聯絡電話' : 'Has phone'}<select value={filters.hasPhone} onChange={(event) => setFilters({ ...filters, hasPhone: event.target.value })}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '有' : 'Yes'}</option><option value="no">{zh ? '無' : 'No'}</option></select></label></div>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => setFilters(emptyFilters)}>{zh ? '清除篩選' : 'Clear filters'}</button>}</aside>
    <section className="workspace"><div className="section-heading"><p>06 / SOCIAL WELFARE & SENIOR SERVICES</p><h2>{zh ? '老人共餐單位一覽表' : 'Senior Group Meal Service Sites'}</h2><span>{zh ? '依公開資料瀏覽老人共餐單位的行政區、地址與聯絡電話；僅提供行政區彙整與外部地圖查詢。' : 'Browse published senior group-meal service site names, districts, addresses, and phone numbers with district summaries and external map lookup.'}</span></div><div className="subtabs">{views.map(([id, label]) => <button className={view === id ? 'active' : ''} key={id} onClick={() => setView(id)}>{label}</button>)}</div><div className="section-heading inline"><p>{zh ? '篩選後紀錄' : 'Filtered records'}</p><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆' : 'records'}</span></strong></div>
      {view === 'overview' && <><div className="notice subtle">{disclaimer(zh)}</div><div className="summary-grid">{[[zh ? '共餐服務據點' : 'Total service sites', activeSummary.totalRecords], [zh ? '涵蓋行政區' : 'Districts covered', activeSummary.districtCount], [zh ? '不重複據點名稱' : 'Unique site names', activeSummary.uniqueSiteNameCount], [zh ? '有聯絡電話紀錄' : 'Records with phone', activeSummary.recordsWithPhone], [zh ? '據點最多行政區' : 'District with most sites', activeSummary.byDistrict[0]?.district ?? '-']].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{typeof value === 'number' ? value.toLocaleString() : value}</strong></article>)}</div><div className="chart-grid"><BarChart title={zh ? '各行政區共餐據點數' : 'Service sites by district'} data={activeSummary.byDistrict.map((item) => ({ label: item.district, value: item.count }))} /><BarChart title={zh ? '電話欄位完整度' : 'Records with and without phone'} data={[{ label: zh ? '有電話' : 'With phone', value: activeSummary.recordsWithPhone }, { label: zh ? '無電話' : 'Without phone', value: activeSummary.recordsWithoutPhone }]} /></div></>}
      {view === 'districts' && <><div className="notice">{zh ? '本資料未提供已確認的官方座標。本頁僅呈現行政區彙整，未建立精確地圖標記，也不會自動將地址轉換為座標。' : 'This dataset has no confirmed official coordinates. This view provides district summaries only; it creates no exact map markers and does not automatically geocode addresses.'}</div><BarChart title={zh ? '各行政區共餐據點數' : 'Service sites by district'} data={activeSummary.byDistrict.map((item) => ({ label: item.district, value: item.count }))} /></>}
      {view === 'directory' && <div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['序號', '據點名稱', '行政區', '據點地址', '聯絡電話', '地圖查詢'] : ['ID', 'Site name', 'District', 'Address', 'Phone', 'Map lookup']).map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{filtered.map((record) => <tr key={record.id}><td>{record.sourceSequenceNumber ?? '-'}</td><th>{record.siteName ?? '-'}</th><td>{record.districtName ?? '-'}</td><td>{record.address ?? '-'}</td><td>{record.phone ?? '-'}</td><td>{record.googleMapsQuery ? <a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.googleMapsQuery)}`}>{zh ? '地圖查詢' : 'Map lookup'}</a> : '-'}</td></tr>)}</tbody></table>{!filtered.length && <p className="empty">{zh ? '沒有符合篩選條件的紀錄。' : 'No records match these filters.'}</p>}</div>}
      {view === 'quality' && <div className="notes-grid"><article><h3>{zh ? '欄位完整度' : 'Field completeness'}</h3><p>{zh ? `地址：${activeSummary.recordsWithAddress.toLocaleString()} 筆；電話：${activeSummary.recordsWithPhone.toLocaleString()} 筆；無電話：${activeSummary.recordsWithoutPhone.toLocaleString()} 筆。` : `Addresses: ${activeSummary.recordsWithAddress.toLocaleString()}; phone numbers: ${activeSummary.recordsWithPhone.toLocaleString()}; no phone number: ${activeSummary.recordsWithoutPhone.toLocaleString()}.`}</p></article><article><h3>{zh ? '處理方式' : 'Processing'}</h3><p>{zh ? '電話與行政區代碼均以文字處理；轉換支援 UTF-8-SIG、Big5 與 CP950。' : 'Phone numbers and district codes are handled as strings; conversion supports UTF-8-SIG, Big5, and CP950.'}</p></article></div>}
      {view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料使用說明' : 'Data notes'}</h3><p>{disclaimer(zh)}</p></article><article><h3>{zh ? '位置資訊限制' : 'Location limitation'}</h3><p>{zh ? '地址僅用於外部地圖查詢；資料不含已確認官方座標，因此不會產生精確據點標記或自動地理編碼。' : 'Addresses are used only for external map lookup. The source has no confirmed official coordinates, so the app does not create exact site markers or automatically geocode addresses.'}</p></article></div>}
    </section></>;
}
