import { useEffect, useMemo, useState } from 'react';
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet';
import { DISTRICTS, TAIPEI_DISTRICT_CENTROIDS } from './lib/civicGroups';
import { buildShelteredWorkshopDirectorySummary, filterShelteredWorkshops } from './lib/shelteredWorkshopDirectory';
import type { BusinessRegistrationChangeSummary, CompanyRegistrationChangeSummary, DisabilityEmploymentResourceSummary, ElderlyWelfareInstitutionSummary, LaborStandardActViolationSummary, Language, RegisteredLaborUnionSummary, ShelteredWorkshopBusinessItemCategory, ShelteredWorkshopDirectoryFilters, ShelteredWorkshopDirectoryRecord, ShelteredWorkshopDirectorySummary, ShelteredWorkshopServiceCategory } from './types';

const emptyFilters: ShelteredWorkshopDirectoryFilters = { search: '', sourceYear: '', businessItem: '', businessItemCategory: '', serviceCategory: '', district: '', roadName: '', hasContact: '', hasPhone: '', phoneType: '', unifiedBusinessNumberValid: '', addressParsed: '' };
const fmt = (value?: number) => value === undefined ? '-' : value.toLocaleString();
const businessLabels: Record<ShelteredWorkshopBusinessItemCategory, { zh: string; en: string }> = {
  retail: { zh: '零售業', en: 'Retail' }, food_and_beverage: { zh: '餐飲與食品', en: 'Food & beverage' }, gas_station: { zh: '加油站與充電', en: 'Gas station / charging' }, manufacturing: { zh: '製造加工', en: 'Manufacturing / processing' }, cleaning_service: { zh: '清潔服務', en: 'Cleaning service' }, assistive_device_service: { zh: '輔具服務', en: 'Assistive device service' }, laundry: { zh: '洗衣服務', en: 'Laundry' }, auto_service: { zh: '汽車服務', en: 'Auto service' }, office_support: { zh: '辦公室支援', en: 'Office support' }, printing_packaging: { zh: '印刷包裝', en: 'Printing / packaging' }, maintenance_repair: { zh: '維修服務', en: 'Maintenance / repair' }, agriculture_food_processing: { zh: '農產食品加工', en: 'Agriculture / food processing' }, mixed: { zh: '混合型', en: 'Mixed' }, other_service: { zh: '其他服務', en: 'Other service' }, unknown: { zh: '未知', en: 'Unknown' },
};
const serviceLabels: Record<ShelteredWorkshopServiceCategory, { zh: string; en: string }> = {
  workshop_business: { zh: '工場營業服務', en: 'Workshop business' }, food_retail_service: { zh: '食品與零售服務', en: 'Food / retail service' }, cleaning_or_laundry: { zh: '清潔或洗衣', en: 'Cleaning or laundry' }, assistive_support: { zh: '輔具支持', en: 'Assistive support' }, vehicle_related_service: { zh: '車輛相關服務', en: 'Vehicle-related service' }, office_or_packaging_support: { zh: '辦公或包裝支援', en: 'Office or packaging support' }, other: { zh: '其他', en: 'Other' }, unknown: { zh: '未知', en: 'Unknown' },
};
const label = (labels: { zh: string; en: string }, language: Language) => labels[language];
const options = <T extends string>(values: Array<T | undefined>) => [...new Set(values.filter(Boolean) as T[])].sort((a, b) => a.localeCompare(b));

function BarChart({ title, data }: { title: string; data: Array<{ label: string; value: number }> }) {
  const max = Math.max(...data.map((item) => item.value), 1);
  return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) => <div className="bar-row wide-label" key={item.label}><span title={item.label}>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{fmt(item.value)}</b></div>)}</div></section>;
}

function Filters({ filters, setFilters, records, language }: { filters: ShelteredWorkshopDirectoryFilters; setFilters: (filters: ShelteredWorkshopDirectoryFilters) => void; records: ShelteredWorkshopDirectoryRecord[]; language: Language }) {
  const zh = language === 'zh', update = (key: keyof ShelteredWorkshopDirectoryFilters, value: string) => setFilters({ ...filters, [key]: value });
  return <aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(event) => update('search', event.target.value)} placeholder={zh ? '搜尋工場名稱、營業項目、地址、電話或統一編號' : 'Search workshop name, business item, address, phone, or business number'} /></label>
    <div className="filter-grid grant-filters">
      <label>{zh ? '資料年度' : 'Source year'}<select value={filters.sourceYear} onChange={(event) => update('sourceYear', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.sourceYear ? String(record.sourceYear) : undefined)).map((year) => <option key={year}>{year}</option>)}</select></label>
      <label>{zh ? '營業項目' : 'Business item'}<select value={filters.businessItem} onChange={(event) => update('businessItem', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.businessItem)).map((item) => <option key={item}>{item}</option>)}</select></label>
      <label>{zh ? '營業項目類別' : 'Business category'}<select value={filters.businessItemCategory} onChange={(event) => update('businessItemCategory', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.flatMap((record) => record.businessItemCategories)).map((type) => <option key={type} value={type}>{label(businessLabels[type], language)}</option>)}</select></label>
      <label>{zh ? '服務類別' : 'Service category'}<select value={filters.serviceCategory} onChange={(event) => update('serviceCategory', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.flatMap((record) => record.serviceCategories)).map((type) => <option key={type} value={type}>{label(serviceLabels[type], language)}</option>)}</select></label>
      <label>{zh ? '行政區' : 'District'}<select value={filters.district} onChange={(event) => update('district', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{DISTRICTS.map((district) => <option key={district}>{district}</option>)}</select></label>
      <label>{zh ? '道路' : 'Road'}<select value={filters.roadName} onChange={(event) => update('roadName', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.roadName)).map((road) => <option key={road}>{road}</option>)}</select></label>
      <label>{zh ? '有聯絡人' : 'Has contact'}<select value={filters.hasContact} onChange={(event) => update('hasContact', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '有' : 'Yes'}</option><option value="no">{zh ? '無' : 'No'}</option></select></label>
      <label>{zh ? '有電話' : 'Has phone'}<select value={filters.hasPhone} onChange={(event) => update('hasPhone', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '有' : 'Yes'}</option><option value="no">{zh ? '無' : 'No'}</option></select></label>
      <label>{zh ? '電話類型' : 'Phone type'}<select value={filters.phoneType} onChange={(event) => update('phoneType', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.phoneType)).map((type) => <option key={type}>{type}</option>)}</select></label>
      <label>{zh ? '統一編號格式有效' : 'Valid business number'}<select value={filters.unifiedBusinessNumberValid} onChange={(event) => update('unifiedBusinessNumberValid', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>
      <label>{zh ? '地址已解析' : 'Address parsed'}<select value={filters.addressParsed} onChange={(event) => update('addressParsed', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>
    </div>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => setFilters(emptyFilters)}>{zh ? '清除篩選' : 'Clear filters'}</button>}</aside>;
}

function Overview({ summary, language }: { summary: ShelteredWorkshopDirectorySummary; language: Language }) {
  const zh = language === 'zh';
  const cards = [[zh ? '庇護工場數' : 'Sheltered workshop count', summary.totalRecords], [zh ? '資料年度' : 'Source year', summary.latestSourceYear ?? '-'], [zh ? '營業項目數' : 'Business item count', summary.uniqueBusinessItemCount], [zh ? '服務類別數' : 'Service category count', summary.serviceCategoryCount], [zh ? '涵蓋行政區數' : 'Districts covered', summary.taipeiDistrictCount], [zh ? '有聯絡人紀錄數' : 'Records with contact', summary.recordsWithContact], [zh ? '有電話紀錄數' : 'Records with phone', summary.recordsWithPhone], [zh ? '有統一編號紀錄數' : 'Records with business number', summary.recordsWithUnifiedBusinessNumber], [zh ? '最多營業項目' : 'Top business item', summary.topBusinessItems[0]?.businessItem ?? '-'], [zh ? '最多行政區' : 'Top district', summary.byDistrict[0]?.district ?? '-'], [zh ? '地址未解析數' : 'Unparsed address count', summary.dataQuality.unparsedAddressDistrictCount]];
  return <><div className="notice subtle">{zh ? '此模組整理臺北市庇護工場名冊欄位，不代表職缺、即時服務量能、安置保證、補助資格、身心障礙鑑定、品質排名、無障礙認證、法規遵循、採購或消費建議。' : 'This module organizes Taipei sheltered workshop directory fields. It does not represent job vacancies, real-time capacity, placement guarantees, subsidy eligibility, disability assessment, quality ranking, accessibility certification, legal compliance, procurement, or consumption recommendation.'}</div>
    <div className="summary-grid">{cards.map(([key, value]) => <article key={key}><span>{key}</span><strong>{typeof value === 'number' ? fmt(value) : value}</strong></article>)}</div>
    <div className="chart-grid"><BarChart title={zh ? '各行政區工場數' : 'Workshops by district'} data={summary.byDistrict.map((item) => ({ label: item.district, value: item.workshopCount }))} /><BarChart title={zh ? '各營業項目工場數' : 'Workshops by business item'} data={summary.topBusinessItems.slice(0, 30).map((item) => ({ label: item.businessItem, value: item.count }))} /><BarChart title={zh ? '各營業項目類別工場數' : 'Workshops by business category'} data={summary.byBusinessItemCategory.map((item) => ({ label: label(businessLabels[item.businessItemCategory], language), value: item.count }))} /><BarChart title={zh ? '各服務類別工場數' : 'Workshops by service category'} data={summary.byServiceCategory.map((item) => ({ label: label(serviceLabels[item.serviceCategory], language), value: item.count }))} /><BarChart title={zh ? '電話類型分布' : 'Phone type distribution'} data={Object.entries(summary.phoneQuality).filter(([key]) => key !== 'hasPhone').map(([label, value]) => ({ label, value }))} /></div></>;
}

function WorkshopMap({ summary, language, viewDistrict }: { summary: ShelteredWorkshopDirectorySummary; language: Language; viewDistrict: (district: string) => void }) {
  const zh = language === 'zh', max = Math.max(...summary.byDistrict.map((district) => district.workshopCount), 1);
  return <div className="map-wrap"><div className="notice">{zh ? '資料未提供官方經緯度。本圖只以地址解析後的行政區中心點呈現彙總，不是精確工場位置。' : 'The source does not provide official coordinates. This map only shows district-centroid summaries from parsed addresses, not exact workshop locations.'}</div>
    <MapContainer center={[25.072, 121.54]} zoom={11} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap contributors &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" />{summary.byDistrict.map((district) => {
      const point = TAIPEI_DISTRICT_CENTROIDS[district.district];
      return point && <CircleMarker key={district.district} center={[point.latitude, point.longitude]} radius={10 + 26 * Math.sqrt(district.workshopCount / max)} pathOptions={{ fillColor: '#8b6bb7', fillOpacity: .76, color: '#fff7e8', weight: 2 }}><Popup><div className="map-popup"><strong>{zh ? '庇護工場行政區分布' : 'Sheltered Workshop District Distribution'}</strong><p>{zh ? '行政區' : 'District'}: {district.district}</p><p>{zh ? '工場數' : 'Workshop count'}: {fmt(district.workshopCount)}</p><p>{zh ? '行政區彙總，不代表精確座標、職缺、服務量能、補助資格、品質排名或官方背書。' : 'District-level summary only; not exact coordinates, vacancies, capacity, eligibility, quality ranking, or endorsement.'}</p><button onClick={() => viewDistrict(district.district)}>{zh ? '查看清單' : 'View directory'}</button></div></Popup></CircleMarker>;
    })}</MapContainer></div>;
}

function Directory({ records, language }: { records: ShelteredWorkshopDirectoryRecord[]; language: Language }) {
  const zh = language === 'zh';
  const [limit, setLimit] = useState(80);
  useEffect(() => setLimit(80), [records]);
  return <><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['工場名稱', '營業項目', '行政區', '地址', '聯絡人', '電話', '統一編號', '地圖查詢', '來源明細'] : ['Workshop name', 'Business item', 'District', 'Address', 'Contact', 'Phone', 'Business number', 'Map lookup', 'Source details']).map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{records.slice(0, limit).map((record) => <tr key={record.id}><th>{record.workshopName}</th><td>{record.businessItem ?? '-'}</td><td>{record.taipeiDistrict ?? '-'}</td><td>{record.address ?? '-'}</td><td>{record.contactName ?? '-'}</td><td>{record.phoneDialHref ? <a href={record.phoneDialHref}>{record.phoneDisplay ?? record.phone}</a> : record.phoneDisplay ?? record.phone ?? '-'}</td><td>{record.unifiedBusinessNumber ?? '-'}</td><td>{record.googleMapsQuery ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.googleMapsQuery)}`} target="_blank" rel="noreferrer">{zh ? '地圖查詢' : 'Map lookup'}</a> : '-'}</td><td><details><summary>{zh ? '來源明細' : 'Source details'}</summary><dl><div><dt>{zh ? '編號' : 'Sequence'}</dt><dd>{record.sourceSequenceNumber ?? '-'}</dd></div><div><dt>{zh ? '資料年度' : 'Source year'}</dt><dd>{record.sourceRocYearRaw ?? '-'} / {record.sourceYear ?? '-'}</dd></div><div><dt>{zh ? '營業類別' : 'Business categories'}</dt><dd>{record.businessItemCategories.map((type) => label(businessLabels[type], language)).join('、')}</dd></div><div><dt>{zh ? '服務類別' : 'Service categories'}</dt><dd>{record.serviceCategories.map((type) => label(serviceLabels[type], language)).join('、')}</dd></div><div><dt>{zh ? '道路' : 'Road'}</dt><dd>{record.roadName ?? '-'}</dd></div><div><dt>{zh ? '電話類型' : 'Phone type'}</dt><dd>{record.phoneType}</dd></div><div><dt>{zh ? '統一編號格式' : 'Business number format'}</dt><dd>{record.unifiedBusinessNumberValidFormat ? (zh ? '有效' : 'Valid') : (zh ? '無效或缺漏' : 'Invalid or missing')}</dd></div><div><dt>{zh ? '位置精度' : 'Location precision'}</dt><dd>{record.locationPrecision}</dd></div><div><dt>{zh ? '解讀限制' : 'Disclaimer'}</dt><dd>{zh ? '不代表職缺、即時服務量能、安置保證、補助資格、品質排名、無障礙認證、法規遵循、採購或消費建議、醫療或法律意見、官方背書。' : 'Does not represent vacancies, real-time capacity, placement guarantees, subsidy eligibility, quality ranking, accessibility certification, legal compliance, procurement or consumption recommendation, medical/legal advice, or endorsement.'}</dd></div></dl></details></td></tr>)}</tbody></table></div>{!records.length && <p className="empty">{zh ? '沒有符合條件的紀錄。' : 'No records match these filters.'}</p>}{limit < records.length && <button className="load-more" onClick={() => setLimit(limit + 80)}>{zh ? '載入更多' : 'Load more'} · {records.length - limit}</button>}</>;
}

function Compare({ summary, related, language }: { summary: ShelteredWorkshopDirectorySummary; related: { disabilityEmployment?: DisabilityEmploymentResourceSummary; laborUnions?: RegisteredLaborUnionSummary; laborViolations?: LaborStandardActViolationSummary; businessChanges?: BusinessRegistrationChangeSummary; companyChanges?: CompanyRegistrationChangeSummary; elderlyWelfare?: ElderlyWelfareInstitutionSummary }; language: Language }) {
  const zh = language === 'zh';
  const rows = [{ label: zh ? '庇護工場' : 'Sheltered workshops', value: summary.totalRecords }, ...(related.disabilityEmployment ? [{ label: zh ? '身障就業資源' : 'Disability employment resources', value: related.disabilityEmployment.totalRecords }] : []), ...(related.laborUnions ? [{ label: zh ? '工會名單' : 'Labor unions', value: related.laborUnions.totalRecords }] : []), ...(related.businessChanges ? [{ label: zh ? '商業異動' : 'Business changes', value: related.businessChanges.totalRecords }] : []), ...(related.companyChanges ? [{ label: zh ? '公司異動' : 'Company changes', value: related.companyChanges.totalRecords }] : [])], max = Math.max(...rows.map((row) => row.value), 1);
  return <div className="notes-grid"><article><h3>{zh ? '與勞動及登記資料比較' : 'Compare Labor & Registry Records'}</h3><p>{zh ? '庇護工場名冊是工場通訊與營業項目清冊，不應直接合併解讀為身障就業資源地圖、工會名單、勞基法違規、商業/公司登記或老人福利機構資料。除非有可靠共享識別碼與人工確認，僅作分開比較。' : 'Sheltered workshop directory records are workshop contact and business-item records. They should not be merged with disability employment resources, labor unions, labor violation records, business/company registrations, or elderly welfare institutions without reliable shared identifiers and manual confirmation.'}</p></article>{related.laborViolations && <article><h3>{zh ? '不得推論違規狀態' : 'No compliance inference'}</h3><p>{zh ? '庇護工場名冊不是勞基法違規紀錄，不應用來推論法規遵循或違規狀態。' : 'The sheltered workshop directory is not a labor violation record and should not be used to infer legal compliance or violation status.'}</p></article>}{related.elderlyWelfare && <article><h3>{zh ? '社福機構資料區別' : 'Welfare institution distinction'}</h3><p>{zh ? '老人福利機構名冊與庇護工場名冊的服務對象與資料目的不同，不應合併為同一服務類型。' : 'Elderly welfare institution records and sheltered workshop records have different service populations and data purposes and should not be merged as one service type.'}</p></article>}<article><h3>{zh ? '模組紀錄數' : 'Module record counts'}</h3><div className="bars">{rows.map((row) => <div className="bar-row wide-label" key={row.label}><span>{row.label}</span><div><i style={{ width: `${Math.max(2, row.value / max * 100)}%` }} /></div><b>{fmt(row.value)}</b></div>)}</div></article></div>;
}

export default function ShelteredWorkshopDirectoryModule({ records, summary, related, language }: { records: ShelteredWorkshopDirectoryRecord[]; summary: ShelteredWorkshopDirectorySummary; related: { disabilityEmployment?: DisabilityEmploymentResourceSummary; laborUnions?: RegisteredLaborUnionSummary; laborViolations?: LaborStandardActViolationSummary; businessChanges?: BusinessRegistrationChangeSummary; companyChanges?: CompanyRegistrationChangeSummary; elderlyWelfare?: ElderlyWelfareInstitutionSummary }; language: Language }) {
  const zh = language === 'zh';
  const [view, setView] = useState<'overview' | 'map' | 'business' | 'services' | 'directory' | 'compare' | 'notes'>('overview');
  const [filters, setFilters] = useState(emptyFilters);
  const filtered = useMemo(() => filterShelteredWorkshops(records, filters), [records, filters]);
  const activeSummary = useMemo(() => Object.values(filters).some(Boolean) ? buildShelteredWorkshopDirectorySummary(filtered) : summary, [filtered, filters, summary]);
  const openDistrict = (district: string) => { setFilters({ ...emptyFilters, district }); setView('directory'); };
  const views = [['overview', zh ? '總覽' : 'Overview'], ['map', zh ? '行政區分布' : 'District Distribution'], ['business', zh ? '營業項目' : 'Business Items'], ['services', zh ? '服務類別' : 'Service Categories'], ['directory', zh ? '工場清單' : 'Workshop Directory'], ['compare', zh ? '與勞動及登記資料比較' : 'Compare Labor & Registry Records'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  return <><Filters filters={filters} setFilters={setFilters} records={records} language={language} /><section className="workspace"><div className="section-heading"><p>04B / LABOR, EMPLOYMENT & VOCATIONAL REHABILITATION PUBLIC RECORDS</p><h2>{zh ? '庇護工場名冊' : 'Sheltered Workshop Directory'}</h2><span>{zh ? '查詢臺北市庇護工場名稱、營業項目、聯絡人、地址、電話與統一編號；地圖僅呈現行政區彙總。' : 'Look up Taipei sheltered workshop names, business items, contacts, addresses, phone numbers, and unified business numbers; the map shows district summaries only.'}</span></div><div className="subtabs">{views.map(([id, text]) => <button className={view === id ? 'active' : ''} onClick={() => setView(id)} key={id}>{text}</button>)}</div><div className="notice subtle">{zh ? '庇護工場名冊僅供來源欄位查詢與統計整理，不代表職缺、即時服務量能、安置保證、補助或福利資格、職業重建或身障鑑定、品質排名、無障礙認證、法規遵循、採購或消費建議、醫療或法律意見、官方背書。' : 'Sheltered workshop directory data is for source-field lookup and statistical organization only. It does not represent vacancies, real-time capacity, placement guarantees, subsidy/welfare eligibility, vocational rehabilitation or disability assessment, quality ranking, accessibility certification, legal compliance, procurement or consumption recommendation, medical/legal advice, or endorsement.'}</div>
    {view === 'overview' && <Overview summary={activeSummary} language={language} />}{view === 'map' && <WorkshopMap summary={activeSummary} language={language} viewDistrict={openDistrict} />}{view === 'business' && <div className="chart-grid"><BarChart title={zh ? '各營業項目工場數' : 'Workshops by business item'} data={activeSummary.topBusinessItems.map((item) => ({ label: item.businessItem, value: item.count }))} /><BarChart title={zh ? '各營業項目類別工場數' : 'Workshops by business category'} data={activeSummary.byBusinessItemCategory.map((item) => ({ label: label(businessLabels[item.businessItemCategory], language), value: item.count }))} /></div>}{view === 'services' && <div className="chart-grid"><BarChart title={zh ? '各服務類別工場數' : 'Workshops by service category'} data={activeSummary.byServiceCategory.map((item) => ({ label: label(serviceLabels[item.serviceCategory], language), value: item.count }))} /><BarChart title={zh ? '資源最多道路' : 'Top roads'} data={activeSummary.byRoadName.slice(0, 30).map((item) => ({ label: item.roadName, value: item.count }))} /></div>}{view === 'directory' && <><div className="section-heading inline"><div /><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆符合紀錄' : 'matching records'}</span></strong></div><Directory records={filtered} language={language} /></>}{view === 'compare' && <Compare summary={activeSummary} related={related} language={language} />}{view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料內容' : 'Data contents'}</h3><p>{zh ? '來源欄位包含編號、年度、工場名稱、營業項目、聯絡人、地址、電話與統一編號。本網站保留來源欄位，解析民國年度、臺北市行政區與道路名稱，並依營業項目產生輔助分類。' : 'Source fields include sequence number, year, workshop name, business item, contact, address, phone, and unified business number. This site preserves the fields, parses ROC years, Taipei districts, and road names, and derives helper categories from business items.'}</p></article><article><h3>{zh ? '位置限制' : 'Location limits'}</h3><p>{zh ? '來源沒有官方經緯度，因此不做地理編碼、不顯示精確點位，也不提供「附近」功能；僅以行政區中心點呈現彙總並提供外部地圖查詢。' : 'The source has no official coordinates, so this module performs no geocoding, shows no exact points, and provides no near-me feature. It only shows district-centroid summaries and external map lookup links.'}</p></article><article><h3>{zh ? '資料來源' : 'Source'}</h3><p><a href="https://data.taipei/dataset/detail?id=fb88e4fd-c287-4fbb-91ab-0ed1fbeaf28c" target="_blank" rel="noreferrer">{zh ? '臺北市庇護工場名冊' : 'Taipei Sheltered Workshop Directory'} ↗</a></p></article></div>}</section></>;
}
