import { useEffect, useMemo, useState } from 'react';
import { buildSpecificPetBusinessEvaluationSummary, filterSpecificPetBusinessEvaluations } from './lib/specificPetBusinessEvaluationResults';
import type { Language, SpecificPetBusinessEvaluationFilters, SpecificPetBusinessEvaluationGradeCategory, SpecificPetBusinessEvaluationRecord, SpecificPetBusinessEvaluationSummary, SpecificPetBusinessGeocodingStatus, SpecificPetBusinessItemCategory, SpecificPetBusinessLocationPrecision } from './types';

const empty: SpecificPetBusinessEvaluationFilters = { search: '', evaluationYear: '', latestYearOnly: '', districtName: '', evaluationGrade: '', evaluationGradeCategory: '', businessItem: '', businessItemCategory: '', licenseExpirationYear: '', hasPhone: '', hasPostalCode: '', postalCodeValidFormat: '', locationPrecision: '', geocodingStatus: '' };
const options = <T extends string | number>(records: SpecificPetBusinessEvaluationRecord[], field: (r: SpecificPetBusinessEvaluationRecord) => T | undefined) => [...new Set(records.flatMap((r) => field(r) ?? []))].sort((a, b) => String(a).localeCompare(String(b), 'zh-Hant'));
const gradeLabel = (g: SpecificPetBusinessEvaluationGradeCategory, zh: boolean) => ({ excellent: zh ? '優等' : 'Excellent', good: zh ? '良等' : 'Good', passed: zh ? '合格' : 'Passed', needs_improvement: zh ? '待改善' : 'Needs improvement', not_rated: zh ? '未評' : 'Not rated', other: zh ? '其他' : 'Other', unknown: zh ? '未知' : 'Unknown' }[g]);
const itemLabel = (c: SpecificPetBusinessItemCategory, zh: boolean) => ({ sale: zh ? '買賣' : 'Sale', breeding: zh ? '繁殖' : 'Breeding', boarding: zh ? '寄養' : 'Boarding', retail: zh ? '零售' : 'Retail', other: zh ? '其他' : 'Other', unknown: zh ? '未知' : 'Unknown' }[c]);
const precisionLabel = (p: SpecificPetBusinessLocationPrecision, zh: boolean) => ({ district_address: zh ? '行政區與地址' : 'District and address', geocoded_address_approximate: zh ? '近似地理編碼地址' : 'Approximate geocoded address', district_only: zh ? '僅行政區' : 'District only', address_only_unparsed_district: zh ? '僅地址，未解析行政區' : 'Address only, district unparsed', missing: zh ? '缺漏' : 'Missing' }[p]);
const geocodingLabel = (s: SpecificPetBusinessGeocodingStatus, zh: boolean) => ({ not_attempted: zh ? '未嘗試' : 'Not attempted', not_geocoded_address_only: zh ? '未地理編碼，僅地址' : 'Not geocoded, address only', geocoded_approximate: zh ? '近似地理編碼' : 'Approximate geocoded', failed: zh ? '地理編碼失敗' : 'Failed', not_applicable: zh ? '不適用' : 'Not applicable' }[s]);
const fmt = (n?: number) => n === undefined ? '-' : n.toLocaleString();
function Bar({ title, rows }: { title: string; rows: Array<{ label: string; count: number }> }) { const max = Math.max(...rows.map((r) => r.count), 1); return <section className="chart"><h3>{title}</h3><div className="bars">{rows.map((r) => <div className="bar-row wide-label" key={r.label}><span title={r.label}>{r.label}</span><div><i style={{ width: `${Math.max(2, r.count / max * 100)}%` }} /></div><b>{fmt(r.count)}</b></div>)}</div></section>; }

function Filters({ records, filters, setFilters, latestYear, language }: { records: SpecificPetBusinessEvaluationRecord[]; filters: SpecificPetBusinessEvaluationFilters; setFilters: (filters: SpecificPetBusinessEvaluationFilters) => void; latestYear?: number; language: Language }) {
  const zh = language === 'zh', update = (key: keyof SpecificPetBusinessEvaluationFilters, value: string) => setFilters({ ...filters, [key]: value });
  const yesNo = (key: keyof SpecificPetBusinessEvaluationFilters, label: string) => <label>{label}<select value={filters[key]} onChange={(e) => update(key, e.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>;
  return <aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(e) => update('search', e.target.value)} placeholder={zh ? '搜尋年度、特寵業字號、公司名稱、地址、營業項目或評鑑等級' : 'Search year, license number, company name, address, business items, or evaluation grade'} /></label><div className="filter-grid grant-filters">
    <label>{zh ? '評鑑年度' : 'Evaluation year'}<select value={filters.evaluationYear} onChange={(e) => update('evaluationYear', e.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records, (r) => r.sourceEvaluationYearRoc).map((v) => <option key={v}>{v}</option>)}</select></label>
    <label>{zh ? '僅最新年度' : 'Latest year only'}<select value={filters.latestYearOnly} onChange={(e) => update('latestYearOnly', e.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{latestYear ?? '—'}</option></select></label>
    <label>{zh ? '行政區' : 'District'}<select value={filters.districtName} onChange={(e) => update('districtName', e.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records, (r) => r.districtName).map((v) => <option key={v}>{v}</option>)}</select></label>
    <label>{zh ? '評鑑等級類別' : 'Evaluation grade category'}<select value={filters.evaluationGradeCategory} onChange={(e) => update('evaluationGradeCategory', e.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records, (r) => r.evaluationGradeCategory).map((v) => <option key={v} value={v}>{gradeLabel(v, zh)}</option>)}</select></label>
    <label>{zh ? '營業項目類別' : 'Business item category'}<select value={filters.businessItemCategory} onChange={(e) => update('businessItemCategory', e.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.flatMap((r) => r.businessItemCategories.map((c) => ({ ...r, one: c }))), (r) => (r as any).one).map((v) => <option key={v} value={v}>{itemLabel(v, zh)}</option>)}</select></label>
    {yesNo('hasPhone', zh ? '有電話' : 'Has phone')}{yesNo('hasPostalCode', zh ? '有郵遞區號' : 'Has postal code')}{yesNo('postalCodeValidFormat', zh ? '郵遞區號格式有效' : 'Valid postal code')}
    <label>{zh ? '位置精度' : 'Location precision'}<select value={filters.locationPrecision} onChange={(e) => update('locationPrecision', e.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records, (r) => r.locationPrecision).map((v) => <option key={v} value={v}>{precisionLabel(v, zh)}</option>)}</select></label>
    <label>{zh ? '地理編碼狀態' : 'Geocoding status'}<select value={filters.geocodingStatus} onChange={(e) => update('geocodingStatus', e.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records, (r) => r.geocodingStatus).map((v) => <option key={v} value={v}>{geocodingLabel(v, zh)}</option>)}</select></label>
  </div>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => setFilters(empty)}>{zh ? '清除篩選' : 'Clear filters'}</button>}</aside>;
}

function Directory({ records, language }: { records: SpecificPetBusinessEvaluationRecord[]; language: Language }) {
  const zh = language === 'zh';
  const [limit, setLimit] = useState(120);
  useEffect(() => setLimit(120), [records]);
  return <><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['評鑑年度', '特寵業字號', '許可證有效期限', '許可證登記公司名', '行政區', '地址', '電話', '營業項目', '評鑑等級', '地圖查詢', '來源明細'] : ['Evaluation year', 'License number', 'License expiration date', 'Registered company name', 'District', 'Address', 'Phone', 'Business items', 'Evaluation grade', 'Map lookup', 'Source details']).map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{records.slice(0, limit).map((r) => <tr key={r.id}><td>{r.sourceEvaluationYearRoc}</td><td>{r.specificPetBusinessLicenseNumber}</td><td>{r.licenseExpirationDateRaw ?? '—'}</td><th>{r.registeredCompanyName}</th><td>{r.districtName}</td><td>{r.address}</td><td>{r.phone ?? '—'}</td><td>{r.businessItems.join('、') || '—'}</td><td>{r.evaluationGrade ?? '—'}</td><td>{r.googleMapsQuery ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(r.googleMapsQuery)}`} target="_blank" rel="noreferrer">{zh ? '地圖查詢' : 'Map lookup'}</a> : '—'}</td><td><details><summary>{zh ? '來源明細' : 'Source details'}</summary><dl><div><dt>{zh ? '來源資源' : 'Source resource'}</dt><dd>{r.sourceResourceName}</dd></div><div><dt>{zh ? '郵遞區號' : 'Postal code'}</dt><dd>{r.postalCode ?? '—'}</dd></div><div><dt>{zh ? '道路' : 'Road'}</dt><dd>{r.roadName ?? '—'}</dd></div><div><dt>{zh ? '營業項目類別' : 'Business item categories'}</dt><dd>{r.businessItemCategories.map((c) => itemLabel(c, zh)).join('、')}</dd></div><div><dt>{zh ? '評鑑類別' : 'Grade category'}</dt><dd>{gradeLabel(r.evaluationGradeCategory, zh)}</dd></div><div><dt>{zh ? '位置精度' : 'Location precision'}</dt><dd>{precisionLabel(r.locationPrecision, zh)}</dd></div><div><dt>{zh ? '地理編碼狀態' : 'Geocoding status'}</dt><dd>{geocodingLabel(r.geocodingStatus, zh)}</dd></div><div><dt>{zh ? '資料來源' : 'Source'}</dt><dd>{r.source} · {r.sourceAgency}</dd></div></dl></details></td></tr>)}</tbody></table></div>{limit < records.length && <button className="load-more" onClick={() => setLimit(limit + 120)}>{zh ? '載入更多' : 'Load more'} · {records.length - limit}</button>}</>;
}

export default function SpecificPetBusinessEvaluationResultsModule({ records, summary, language, related }: { records: SpecificPetBusinessEvaluationRecord[]; summary: SpecificPetBusinessEvaluationSummary; language: Language; related?: { animalHospitals?: number; animalMedicineSellers?: number; veterinarians?: number; businessChanges?: number; companyChanges?: number } }) {
  const zh = language === 'zh', [view, setView] = useState<'overview' | 'latest' | 'districts' | 'grades' | 'items' | 'years' | 'directory' | 'quality' | 'compare' | 'notes'>('overview'), [filters, setFilters] = useState(empty);
  const filtered = useMemo(() => filterSpecificPetBusinessEvaluations(records, filters, summary.latestEvaluationYearRoc), [records, filters, summary.latestEvaluationYearRoc]);
  const active = useMemo(() => Object.values(filters).some(Boolean) ? buildSpecificPetBusinessEvaluationSummary(filtered) : summary, [filtered, filters, summary]);
  const latestRows = useMemo(() => records.filter((r) => r.sourceEvaluationYearRoc === summary.latestEvaluationYearRoc), [records, summary.latestEvaluationYearRoc]);
  const views = [['overview', zh ? '總覽' : 'Overview'], ['latest', zh ? '最新年度評鑑' : 'Latest Year'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['grades', zh ? '評鑑等級' : 'Evaluation Grades'], ['items', zh ? '營業項目' : 'Business Items'], ['years', zh ? '年度比較' : 'Year Comparison'], ['directory', zh ? '業者清單' : 'Business Directory'], ['quality', zh ? '資料品質' : 'Data Quality'], ['compare', zh ? '與動物相關資料比較' : 'Compare Animal-Related Records'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  const cards = [[zh ? '評鑑紀錄數' : 'Evaluation record count', active.totalRecords], [zh ? '最新評鑑年度' : 'Latest evaluation year', active.latestEvaluationYearRoc], [zh ? '最新年度紀錄數' : 'Latest-year records', active.recordsInLatestYear], [zh ? '可用評鑑年度數' : 'Available evaluation years', active.evaluationYearCount], [zh ? '涵蓋行政區數' : 'Districts covered', active.districtCount], [zh ? '不重複特寵業字號數' : 'Unique license number count', active.uniqueLicenseNumberCount], [zh ? '不重複公司數' : 'Unique company count', active.uniqueCompanyNameCount], [zh ? '有電話紀錄數' : 'Records with phone', active.recordsWithPhone], [zh ? '最多評鑑等級' : 'Most common evaluation grade', active.byEvaluationGrade[0]?.evaluationGrade ?? '—'], [zh ? '最多營業項目類別' : 'Most common business item category', active.byBusinessItemCategory[0] ? itemLabel(active.byBusinessItemCategory[0].businessItemCategory, zh) : '—']];
  return <><Filters records={records} filters={filters} setFilters={setFilters} latestYear={summary.latestEvaluationYearRoc} language={language} /><section className="workspace"><div className="section-heading"><p>08C / ANIMAL PROTECTION & PET BUSINESSES</p><h2>{zh ? '特定寵物業評鑑成果' : 'Specific Pet Business Evaluation Results'}</h2><span>{zh ? '查詢臺北市特定寵物業評鑑成果公開資料，包含特寵業字號、許可證有效期限、登記公司名、行政區、地址、電話、營業項目與評鑑等級。' : 'Look up Taipei specific pet business evaluation result public records, including license number, license expiration date, registered company name, district, address, phone, business items, and evaluation grade.'}</span></div><div className="subtabs">{views.map(([id, label]) => <button className={view === id ? 'active' : ''} onClick={() => setView(id)} key={id}>{label}</button>)}</div><div className="notice subtle">{zh ? '本資料僅供公開資料查詢與評鑑結果資料探索，不代表即時營業狀態、即時許可證有效性、寵物健康或品質保證、消費建議、購買建議、獸醫診療建議、用藥建議或官方推薦。' : 'This data is for public-record lookup and evaluation-result data exploration only. It does not represent real-time operating status, real-time license validity, pet health or quality guarantees, consumer advice, purchase advice, veterinary medical advice, medication advice, or official recommendation.'}</div>
    {view === 'overview' && <><div className="summary-grid">{cards.map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{typeof value === 'number' ? value.toLocaleString() : value ?? '—'}</strong></article>)}</div><div className="chart-grid"><Bar title={zh ? '各年度紀錄數' : 'Records by evaluation year'} rows={active.byEvaluationYear.map((y) => ({ label: String(y.sourceEvaluationYearRoc), count: y.count }))} /><Bar title={zh ? '最新年度各行政區業者數' : 'Latest-year businesses by district'} rows={buildSpecificPetBusinessEvaluationSummary(latestRows).byDistrict.map((d) => ({ label: d.districtName, count: d.count }))} /><Bar title={zh ? '最新年度評鑑等級' : 'Latest-year evaluation grades'} rows={buildSpecificPetBusinessEvaluationSummary(latestRows).byEvaluationGrade.map((g) => ({ label: g.evaluationGrade, count: g.count }))} /><Bar title={zh ? '最新年度營業項目類別' : 'Latest-year business item categories'} rows={buildSpecificPetBusinessEvaluationSummary(latestRows).byBusinessItemCategory.map((i) => ({ label: itemLabel(i.businessItemCategory, zh), count: i.count }))} /></div></>}
    {view === 'latest' && <Directory records={latestRows} language={language} />}
    {view === 'districts' && <div className="chart-grid"><Bar title={zh ? '各行政區紀錄數' : 'Records by district'} rows={active.byDistrict.map((d) => ({ label: d.districtName, count: d.count }))} /><Bar title={zh ? '最新年度各行政區業者數' : 'Latest-year businesses by district'} rows={active.byDistrict.map((d) => ({ label: d.districtName, count: d.latestYearCount }))} /></div>}
    {view === 'grades' && <div className="chart-grid"><Bar title={zh ? '評鑑等級分布' : 'Evaluation grade distribution'} rows={active.byEvaluationGrade.map((g) => ({ label: g.evaluationGrade, count: g.count }))} /><Bar title={zh ? '最新年度評鑑等級' : 'Latest-year evaluation grades'} rows={active.byEvaluationGrade.map((g) => ({ label: g.evaluationGrade, count: g.latestYearCount }))} /></div>}
    {view === 'items' && <Bar title={zh ? '營業項目類別' : 'Business item categories'} rows={active.byBusinessItemCategory.map((i) => ({ label: itemLabel(i.businessItemCategory, zh), count: i.count }))} />}
    {view === 'years' && <div className="chart-grid"><Bar title={zh ? '年度紀錄數比較' : 'Year-over-year record count'} rows={active.byEvaluationYear.map((y) => ({ label: String(y.sourceEvaluationYearRoc), count: y.count }))} />{active.yearComparison.map((year) => <Bar key={year.sourceEvaluationYearRoc} title={`${year.sourceEvaluationYearRoc} ${zh ? '評鑑等級' : 'evaluation grades'}`} rows={year.byEvaluationGrade.map((g) => ({ label: g.evaluationGrade, count: g.count }))} />)}</div>}
    {view === 'directory' && <><div className="section-heading inline"><div /><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆符合紀錄' : 'matching records'}</span></strong></div><Directory records={filtered} language={language} /></>}
    {view === 'quality' && <div className="chart-grid"><Bar title={zh ? '資料品質' : 'Data quality'} rows={[{ label: zh ? '缺郵遞區號' : 'Missing postal code', count: active.dataQuality.missingPostalCodeCount }, { label: zh ? '無效郵遞區號' : 'Invalid postal code', count: active.dataQuality.invalidPostalCodeCount }, { label: zh ? '缺電話' : 'Missing phone', count: active.dataQuality.missingPhoneCount }, { label: zh ? '未知評鑑等級' : 'Unknown grade', count: active.dataQuality.unknownEvaluationGradeCount }]} /></div>}
    {view === 'compare' && <><div className="notice subtle">{zh ? '特定寵物業評鑑、動物醫院、獸醫師資訊、動物用藥業者與商業/公司資料性質不同，不應合併推論診療能力、用藥建議、寵物品質、即時營業狀態或完整法規遵循狀態。' : 'Pet business evaluation, animal hospital, veterinarian, animal medicine seller, and business/company records have different meanings. Do not merge them to infer medical-care capability, medication advice, pet quality, real-time operating status, or complete compliance status.'}</div><Bar title={zh ? '相關動物與商業資料紀錄數比較' : 'Related animal and business record counts'} rows={[{ label: zh ? '寵物業評鑑' : 'Pet business evaluations', count: summary.totalRecords }, { label: zh ? '動物醫院' : 'Animal hospitals', count: related?.animalHospitals ?? 0 }, { label: zh ? '動物用藥業者' : 'Animal medicine sellers', count: related?.animalMedicineSellers ?? 0 }, { label: zh ? '獸醫師資訊' : 'Veterinarians', count: related?.veterinarians ?? 0 }, { label: zh ? '商業異動' : 'Business changes', count: related?.businessChanges ?? 0 }, { label: zh ? '公司異動' : 'Company changes', count: related?.companyChanges ?? 0 }].filter((r) => r.count)} /></>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '資料內容' : 'Data contents'}</h3><p>{zh ? '臺北市特定寵物業評鑑成果提供特定寵物業者評鑑結果與業者相關資訊，欄位包含縣市、行政區、郵遞區號、特寵業字號、許可證有效期限、許可證登記公司名、電話、地址、營業項目與評鑑等級。' : 'Taipei specific pet business evaluation records provide evaluation results and related business information for specific pet businesses. Fields include city/county, district, postal code, license number, license expiration date, registered company name, phone, address, business items, and evaluation grade.'}</p></article><article><h3>{zh ? '座標限制' : 'Coordinate limits'}</h3><p>{zh ? '本資料提供業者地址，但未提供官方經緯度。本網站預設以行政區彙總、地址清單與外部地圖查詢呈現，不顯示官方精確點位。' : 'This data provides business addresses but does not provide official coordinates. This site shows district summaries, address lists, and external map lookup links by default and does not show official exact points.'}</p></article><article><h3>{zh ? '資料來源' : 'Source'}</h3><p><a href="https://data.taipei/dataset/detail?id=c32bc515-c984-4929-881f-31528e24fb13" target="_blank" rel="noreferrer">{zh ? '臺北市特定寵物業評鑑成果' : 'Taipei specific pet business evaluation results'} ↗</a></p></article></div>}</section></>;
}
