import { useEffect, useMemo, useState } from 'react';
import { fullPhone, normalizeTravelMedicineText, type MpoxVaccinationStatus, type TravelMedicineClinicRecord } from './lib/travelMedicineClinics';

type Language = 'zh' | 'en';
type View = 'find' | 'directory' | 'mpox' | 'districts' | 'quality' | 'notes';
const dataRoot = `${import.meta.env.BASE_URL}data/travel-medicine-clinics`;

const mpoxLabels: Record<MpoxVaccinationStatus, { zh: string; en: string }> = {
  available: { zh: '來源列示可自費接種', en: 'Listed as available' },
  not_available: { zh: '來源列示未提供', en: 'Listed as not available' },
  conditional: { zh: '需確認條件', en: 'Conditions require confirmation' },
  unknown: { zh: '來源未註明', en: 'Not specified' },
};
const viewLabels: Record<View, { zh: string; en: string }> = {
  find: { zh: '尋找旅遊醫學服務', en: 'Find Travel Medicine Services' }, directory: { zh: '醫療機構名冊', en: 'Institution Directory' }, mpox: { zh: 'M痘自費接種', en: 'Mpox Vaccination' }, districts: { zh: '行政區分布', en: 'District Distribution' }, quality: { zh: '資料品質', en: 'Data Quality' }, notes: { zh: '資料說明', en: 'Data Notes' },
};
const csvCell = (value: string | null | undefined) => `"${(value ?? '').replaceAll('"', '""')}"`;

export default function TravelMedicineClinicsModule({ language }: { language: Language }) {
  const [records, setRecords] = useState<TravelMedicineClinicRecord[]>([]); const [report, setReport] = useState<any>(null); const [error, setError] = useState(false);
  const [view, setView] = useState<View>('find'); const [query, setQuery] = useState(''); const [city, setCity] = useState(''); const [district, setDistrict] = useState(''); const [department, setDepartment] = useState(''); const [mpox, setMpox] = useState<MpoxVaccinationStatus | ''>(''); const [hasPhone, setHasPhone] = useState(''); const [sort, setSort] = useState<'hospital' | 'city' | 'mpox'>('hospital'); const [page, setPage] = useState(1);
  const t = (zh: string, en: string) => language === 'zh' ? zh : en;
  useEffect(() => { Promise.all([fetch(`${dataRoot}/records.json`).then((r) => r.ok ? r.json() : Promise.reject()), fetch(`${dataRoot}/conversion-report.json`).then((r) => r.ok ? r.json() : null)]).then(([nextRecords, nextReport]) => { setRecords(nextRecords); setReport(nextReport); }).catch(() => setError(true)); }, []);
  const cities = useMemo(() => [...new Set(records.map((record) => record.cityName).filter(Boolean))].sort(), [records]);
  const districts = useMemo(() => [...new Set(records.map((record) => record.districtName).filter(Boolean))].sort(), [records]);
  const departments = useMemo(() => [...new Set(records.map((record) => record.department).filter(Boolean))].sort(), [records]);
  const filtered = useMemo(() => { const normalizedQuery = normalizeTravelMedicineText(query); return records.filter((record) => (!normalizedQuery || normalizeTravelMedicineText([record.hospitalName, record.departmentRaw, record.cityName, record.districtName ?? '', record.postalCode, record.address, record.phoneRaw, record.mpoxSelfPaidVaccinationRaw].join(' ')).includes(normalizedQuery)) && (!city || record.cityName === city) && (!district || record.districtName === district) && (!department || record.department === department) && (!mpox || record.mpoxSelfPaidVaccination === mpox) && (!hasPhone || (hasPhone === 'yes' ? record.hasPhone : !record.hasPhone))); }, [records, query, city, district, department, mpox, hasPhone]);
  useEffect(() => setPage(1), [query, city, district, department, mpox, hasPhone, sort]);
  const ordered = [...filtered].sort((a, b) => sort === 'city' ? a.cityName.localeCompare(b.cityName, 'zh-Hant') || a.hospitalName.localeCompare(b.hospitalName, 'zh-Hant') : sort === 'mpox' ? a.mpoxSelfPaidVaccination.localeCompare(b.mpoxSelfPaidVaccination) || a.hospitalName.localeCompare(b.hospitalName, 'zh-Hant') : a.hospitalName.localeCompare(b.hospitalName, 'zh-Hant'));
  const pageSize = 12; const pageCount = Math.max(1, Math.ceil(ordered.length / pageSize)); const pageRows = ordered.slice((page - 1) * pageSize, page * pageSize);
  const byDistrict = group(filtered.filter((record) => record.districtName), (record) => record.districtName ?? '').sort((a, b) => b.count - a.count || a.name.localeCompare(b.name, 'zh-Hant'));
  const byDepartment = group(filtered, (record) => record.department).sort((a, b) => b.count - a.count || a.name.localeCompare(b.name, 'zh-Hant'));
  const byMpox = (Object.keys(mpoxLabels) as MpoxVaccinationStatus[]).map((status) => ({ name: mpoxLabels[status][language], count: filtered.filter((record) => record.mpoxSelfPaidVaccination === status).length }));
  const listedMpox = filtered.filter((record) => record.mpoxSelfPaidVaccination === 'available').length;
  const copy = async (value: string) => { try { await navigator.clipboard.writeText(value); } catch { /* clipboard permission may be unavailable */ } };
  const exportCsv = () => { const headers = ['郵遞區號', '縣市', '醫院名稱', '科別', '電話', '分機', '地址', 'M痘疫苗自費接種服務', '衍生行政區', 'M痘衍生狀態']; const csv = [headers, ...filtered.map((record) => [record.sourceValues['郵遞區號'], record.sourceValues['縣市'], record.sourceValues['醫院名稱'], record.sourceValues['科別'], record.sourceValues['電話'], record.sourceValues['分機'], record.sourceValues['地址'], record.sourceValues['M痘疫苗自費接種服務'], record.districtName ?? '', record.mpoxSelfPaidVaccination])].map((row) => row.map(csvCell).join(',')).join('\n'); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: 'text/csv;charset=utf-8' })); anchor.download = 'taipei-travel-medicine-clinics.csv'; anchor.click(); URL.revokeObjectURL(anchor.href); };
  if (error) return <section className="module-panel"><h1>{t('旅遊醫學門診醫院名冊', 'Travel Medicine Clinics')}</h1><p>{t('本機資料檔無法載入。請先執行資料轉換。', 'The local dataset could not be loaded. Run its conversion command first.')}</p></section>;
  return <section className="module-panel generated-module"><p className="eyebrow">{t('醫療資源名冊', 'HEALTHCARE RESOURCE DIRECTORY')}</p><h1>{t('旅遊醫學門診醫院名冊', 'Travel Medicine Clinics')}</h1><p className="module-intro">{t('依臺北市政府衛生局公開資料，搜尋旅遊醫學門診合約醫院的聯絡與地址資訊。', 'Search contact and address details for contracted travel-medicine outpatient hospitals in Taipei City Department of Health open data.')}</p><p className="muted">{t('這是來源更新時間的行政名冊，不表示即時門診、預約、疫苗庫存、資格、價格或醫療品質。', 'This is an administrative directory at the source update time; it does not establish real-time clinics, appointments, vaccine stock, eligibility, prices, or clinical quality.')}</p>
    <div className="subtabs" role="tablist" aria-label={t('資料檢視', 'Data views')}>{(Object.keys(viewLabels) as View[]).map((item) => <button key={item} type="button" className={view === item ? 'active' : ''} role="tab" aria-selected={view === item} onClick={() => setView(item)}>{viewLabels[item][language]}</button>)}</div>
    <div className="filters filter-grid"><label>{t('關鍵字', 'Keyword')}<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('醫院、科別、地址、電話或 M 痘欄位', 'Hospital, department, address, phone, or mpox field')} /></label><label>{t('縣市', 'City')}<select value={city} onChange={(event) => setCity(event.target.value)}><option value="">{t('全部', 'All')}</option>{cities.map((item) => <option key={item}>{item}</option>)}</select></label><label>{t('臺北行政區', 'Taipei district')}<select value={district} onChange={(event) => setDistrict(event.target.value)}><option value="">{t('全部', 'All')}</option>{districts.map((item) => <option key={item}>{item}</option>)}</select></label><label>{t('科別', 'Department')}<select value={department} onChange={(event) => setDepartment(event.target.value)}><option value="">{t('全部', 'All')}</option>{departments.map((item) => <option key={item}>{item}</option>)}</select></label><label>{t('自費 M 痘接種', 'Self-paid mpox vaccination')}<select value={mpox} onChange={(event) => setMpox(event.target.value as MpoxVaccinationStatus | '')}><option value="">{t('全部', 'All')}</option>{(Object.keys(mpoxLabels) as MpoxVaccinationStatus[]).map((item) => <option key={item} value={item}>{mpoxLabels[item][language]}</option>)}</select></label><label>{t('電話', 'Telephone')}<select value={hasPhone} onChange={(event) => setHasPhone(event.target.value)}><option value="">{t('全部', 'All')}</option><option value="yes">{t('有電話', 'Has phone')}</option><option value="no">{t('無電話', 'No phone')}</option></select></label><button type="button" className="button-secondary" onClick={() => setMpox('available')}>{t('只看來源列示 M 痘自費接種', 'Show source-listed self-paid mpox')}</button><button type="button" className="button-secondary" onClick={exportCsv}>{t('匯出目前篩選 CSV', 'Export filtered CSV')}</button></div>
    <div className="summary-grid"><article><span>{t('來源列數', 'Source rows')}</span><strong>{filtered.length}</strong></article><article><span>{t('不同醫院名稱', 'Unique hospital names')}</span><strong>{new Set(filtered.map((record) => normalizeTravelMedicineText(record.hospitalName))).size}</strong></article><article><span>{t('縣市數', 'Cities')}</span><strong>{new Set(filtered.map((record) => record.cityName)).size}</strong></article><article><span>{t('臺北行政區數', 'Taipei districts')}</span><strong>{new Set(filtered.map((record) => record.districtName).filter(Boolean)).size}</strong></article><article><span>{t('來源列示 M 痘自費接種', 'Source-listed self-paid mpox')}</span><strong>{listedMpox}</strong></article><article><span>{t('有電話紀錄', 'Records with telephone')}</span><strong>{filtered.filter((record) => record.hasPhone).length}</strong></article></div>
    {view === 'find' && <><p className="muted">{t(`目前篩選有 ${filtered.length} 筆來源紀錄；${listedMpox} 筆由來源明確標示自費 M 痘接種服務。`, `The filters contain ${filtered.length} source records; ${listedMpox} are explicitly listed by the source for self-paid mpox vaccination.`)}</p><div className="notes-grid">{pageRows.map((record) => <ClinicCard key={record.id} record={record} language={language} copy={copy} />)}</div><Pager page={page} pageCount={pageCount} setPage={setPage} language={language} /></>}
    {view === 'directory' && <><div className="directory-toolbar"><label>{t('排序', 'Sort')}<select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="hospital">{t('醫院名稱', 'Hospital')}</option><option value="city">{t('縣市', 'City')}</option><option value="mpox">{t('M 痘來源狀態', 'Mpox source status')}</option></select></label><span>{t(`顯示 ${ordered.length} 筆`, `Showing ${ordered.length} records`)}</span></div><div className="comparison-scroll"><table className="procurement-table"><thead><tr><th>{t('醫院', 'Hospital')}</th><th>{t('縣市／行政區', 'City / district')}</th><th>{t('科別', 'Department')}</th><th>{t('電話', 'Telephone')}</th><th>{t('M 痘來源狀態', 'Mpox source status')}</th><th>{t('地圖', 'Map')}</th></tr></thead><tbody>{pageRows.map((record) => <tr key={record.id}><th>{record.hospitalName || '—'}</th><td>{record.cityName || '—'}{record.districtName ? ` / ${record.districtName}` : ''}</td><td>{record.departmentRaw || '—'}</td><td>{record.phone ? <a href={`tel:${record.phone.replace(/[^+\d]/g, '')}`}>{fullPhone(record.phone, record.extension, language)}</a> : '—'}</td><td><span className="status-badge">{mpoxLabels[record.mpoxSelfPaidVaccination][language]}</span></td><td><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.externalMapQuery)}`}>{t('地圖查詢', 'Map lookup')}</a></td></tr>)}</tbody></table></div><Pager page={page} pageCount={pageCount} setPage={setPage} language={language} /></>}
    {view === 'mpox' && <><p className="muted">{t('「來源列示可自費接種」只反映來源欄位的明確標示，不表示目前有庫存、可預約或符合資格。', '“Listed as available” reflects only an explicit source field, not current stock, appointments, or eligibility.')}</p><BarTable title={t('M 痘自費接種來源狀態', 'Source-recorded self-paid mpox status')} rows={byMpox} /><div className="notes-grid">{filtered.filter((record) => record.mpoxSelfPaidVaccination === 'available').map((record) => <ClinicCard key={record.id} record={record} language={language} copy={copy} />)}</div></>}
    {view === 'districts' && <BarTable title={t('臺北行政區的來源列數', 'Source rows by Taipei district')} rows={byDistrict} note={t('僅顯示可保守判讀為臺北行政區的紀錄；數字為來源列數，不是服務量或醫院排名。', 'Only records conservatively resolved to a Taipei district are shown. Counts are source rows, not service volume or hospital rankings.')} />}
    {view === 'quality' && <div className="notes-grid"><article><h2>{t('轉換檢查', 'Conversion checks')}</h2><p>{t(`轉換報告問題計數：${report?.travelMedicineClinics?.issueCount ?? '—'}。所有原始欄位會保留，未能判讀的行政區或 M 痘欄位不會被補值。`, `Conversion-report issue count: ${report?.travelMedicineClinics?.issueCount ?? '—'}. All source fields are retained; unresolved districts and mpox values are never filled in.`)}</p></article><article><h2>{t('資料完整度', 'Contact completeness')}</h2><p>{t(`電話：${filtered.filter((record) => record.hasPhone).length}；分機：${filtered.filter((record) => record.hasExtension).length}；地址：${filtered.filter((record) => record.hasAddress).length}。`, `Telephone: ${filtered.filter((record) => record.hasPhone).length}; extension: ${filtered.filter((record) => record.hasExtension).length}; address: ${filtered.filter((record) => record.hasAddress).length}.`)}</p></article></div>}
    {view === 'notes' && <div className="notes-grid"><article><h2>{t('來源與更新', 'Source and updates')}</h2><p><a href="https://data.taipei/dataset/detail?id=49ebc8c7-c015-406f-a8f4-051d580cfc8c" target="_blank" rel="noreferrer">{t('旅遊醫學門診醫院名冊（臺北市資料大平臺）', 'Travel Medicine Outpatient Hospital Directory (Taipei Open Data Platform)')}</a></p><p>{t('來源資料更新：2026-06-16；詮釋資料更新：2026-07-16；更新頻率：不定期。', 'Source data updated 2026-06-16; metadata updated 2026-07-16; update frequency: irregular.')}</p></article><article><h2>{t('使用提醒', 'Use note')}</h2><p>{t('本資料集是旅遊醫學門診合約醫院據點名冊。請向醫療機構或臺北市政府衛生局確認門診時間、疫苗、庫存、資格、價格與預約程序。', 'This dataset is a directory of contracted travel-medicine outpatient hospital locations. Confirm clinic hours, vaccines, stock, eligibility, prices and appointments with the institution or Taipei City Department of Health.')}</p></article></div>}
  </section>;
}

function group(records: TravelMedicineClinicRecord[], key: (record: TravelMedicineClinicRecord) => string) { const values = new Map<string, number>(); records.forEach((record) => { const name = key(record); if (name) values.set(name, (values.get(name) ?? 0) + 1); }); return [...values.entries()].map(([name, count]) => ({ name, count })); }
function BarTable({ title, rows, note }: { title: string; rows: Array<{ name: string; count: number }>; note?: string }) { const max = Math.max(1, ...rows.map((row) => row.count)); return <section className="chart"><h2>{title}</h2>{note && <p className="muted">{note}</p>}<div className="bars">{rows.map((row) => <div className="bar-row wide-label" key={row.name}><span>{row.name}</span><div><i style={{ width: `${row.count / max * 100}%` }} /></div><b>{row.count}</b></div>)}</div></section>; }
function Pager({ page, pageCount, setPage, language }: { page: number; pageCount: number; setPage: (value: number | ((current: number) => number)) => void; language: Language }) { return <div className="pagination"><button type="button" disabled={page <= 1} onClick={() => setPage((current) => current - 1)}>{language === 'zh' ? '上一頁' : 'Previous'}</button><span>{page} / {pageCount}</span><button type="button" disabled={page >= pageCount} onClick={() => setPage((current) => current + 1)}>{language === 'zh' ? '下一頁' : 'Next'}</button></div>; }
function ClinicCard({ record, language, copy }: { record: TravelMedicineClinicRecord; language: Language; copy: (value: string) => void }) { const t = (zh: string, en: string) => language === 'zh' ? zh : en; const phone = fullPhone(record.phone, record.extension, language); return <article><h2>{record.hospitalName || '—'}</h2><p>{[record.cityName, record.districtName, record.departmentRaw].filter(Boolean).join(' · ') || '—'}</p><p>{record.address || '—'}</p><p>{record.phone ? <a href={`tel:${record.phone.replace(/[^+\d]/g, '')}`}>{phone}</a> : '—'}</p><p><span className="status-badge">{mpoxLabels[record.mpoxSelfPaidVaccination][language]}</span>{record.mpoxSelfPaidVaccinationRaw && <small> {record.mpoxSelfPaidVaccinationRaw}</small>}</p><p><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.externalMapQuery)}`}>{t('地圖查詢', 'Map lookup')}</a>{record.phone && <> · <button type="button" className="link-button" onClick={() => copy(phone)}>{t('複製電話', 'Copy phone')}</button></>}{record.address && <> · <button type="button" className="link-button" onClick={() => copy(record.address)}>{t('複製地址', 'Copy address')}</button></>}</p><details><summary>{t('來源欄位', 'Source fields')}</summary><dl>{Object.entries(record.sourceValues).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value || '—'}</dd></div>)}</dl></details></article>; }
