import { useEffect, useMemo, useState } from 'react';
import { buildVeterinarianProfessionalRegistrySummary, filterVeterinarianProfessionalRegistry } from './lib/veterinarianProfessionalRegistry';
import type { BusinessRegistrationChangeSummary, CompanyRegistrationChangeSummary, ConsumerDisputeAbsentBusinessOperatorSummary, LaborStandardActViolationSummary, Language, RegisteredAnimalHospitalSummary, VeterinarianPracticeLicenseNumberFormat, VeterinarianProfessionalRegistryFilters, VeterinarianProfessionalRegistryRecord, VeterinarianProfessionalRegistrySummary } from './types';

const emptyFilters: VeterinarianProfessionalRegistryFilters = { search: '', cityCode: '', cityCounty: '', licenseNumberFormat: '', serviceVeterinaryInstitutionName: '', cityCountyIsTaipei: '' };
const fmt = (value?: number) => value === undefined ? '-' : value.toLocaleString();
const formatLabels: Record<VeterinarianPracticeLicenseNumberFormat, { zh: string; en: string }> = {
  taipei_veterinarian_practice_license: { zh: '臺北市獸醫師執業執照', en: 'Taipei veterinarian practice license' },
  other_veterinarian_license: { zh: '其他獸醫執照格式', en: 'Other veterinarian license' },
  numeric_only: { zh: '純數字', en: 'Numeric only' },
  mixed: { zh: '混合格式', en: 'Mixed' },
  missing: { zh: '缺漏', en: 'Missing' },
  unknown: { zh: '未知', en: 'Unknown' },
};
const label = (labels: { zh: string; en: string }, language: Language) => labels[language];
const options = <T extends string>(values: Array<T | undefined>) => [...new Set(values.filter(Boolean) as T[])].sort((a, b) => a.localeCompare(b, 'zh-Hant'));

function BarChart({ title, data }: { title: string; data: Array<{ label: string; value: number }> }) {
  const max = Math.max(...data.map((item) => item.value), 1);
  return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) => <div className="bar-row wide-label" key={item.label}><span title={item.label}>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / max * 100)}%` }} /></div><b>{fmt(item.value)}</b></div>)}</div></section>;
}

function Filters({ filters, setFilters, records, language }: { filters: VeterinarianProfessionalRegistryFilters; setFilters: (filters: VeterinarianProfessionalRegistryFilters) => void; records: VeterinarianProfessionalRegistryRecord[]; language: Language }) {
  const zh = language === 'zh', update = (key: keyof VeterinarianProfessionalRegistryFilters, value: string) => setFilters({ ...filters, [key]: value });
  return <aside className="filters"><label className="search"><span aria-hidden="true">⌕</span><input value={filters.search} onChange={(event) => update('search', event.target.value)} placeholder={zh ? '搜尋姓名、執業執照字號或服務獸醫診療機構' : 'Search name, practice license number, or service veterinary institution'} /></label>
    <div className="filter-grid grant-filters">
      <label>{zh ? '縣市代碼' : 'City code'}<select value={filters.cityCode} onChange={(event) => update('cityCode', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.cityCodeNormalized)).map((cityCode) => <option key={cityCode}>{cityCode}</option>)}</select></label>
      <label>{zh ? '縣市' : 'City / county'}<select value={filters.cityCounty} onChange={(event) => update('cityCounty', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.cityCountyNormalized)).map((city) => <option key={city}>{city}</option>)}</select></label>
      <label>{zh ? '執業執照格式' : 'Practice license format'}<select value={filters.licenseNumberFormat} onChange={(event) => update('licenseNumberFormat', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.practiceLicenseNumberFormat)).map((type) => <option key={type} value={type}>{label(formatLabels[type], language)}</option>)}</select></label>
      <label>{zh ? '服務獸醫診療機構' : 'Service veterinary institution'}<select value={filters.serviceVeterinaryInstitutionName} onChange={(event) => update('serviceVeterinaryInstitutionName', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option>{options(records.map((record) => record.serviceVeterinaryInstitutionNameNormalized)).map((name) => <option key={name}>{name}</option>)}</select></label>
      <label>{zh ? '縣市為臺北市' : 'City/county is Taipei'}<select value={filters.cityCountyIsTaipei} onChange={(event) => update('cityCountyIsTaipei', event.target.value)}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '是' : 'Yes'}</option><option value="no">{zh ? '否' : 'No'}</option></select></label>
    </div>{Object.values(filters).some(Boolean) && <button className="text-button" onClick={() => setFilters(emptyFilters)}>{zh ? '清除篩選' : 'Clear filters'}</button>}</aside>;
}

function Overview({ summary, language }: { summary: VeterinarianProfessionalRegistrySummary; language: Language }) {
  const zh = language === 'zh';
  const cards = [
    [zh ? '獸醫師紀錄' : 'Veterinarian records', summary.totalRecords],
    [zh ? '不重複姓名' : 'Unique names', summary.uniqueVeterinarianNameCount],
    [zh ? '不重複執業執照字號' : 'Unique practice license numbers', summary.uniquePracticeLicenseNumberCount],
    [zh ? '服務獸醫診療機構數' : 'Service veterinary institutions', summary.uniqueServiceVeterinaryInstitutionNameCount],
    [zh ? '臺北市縣市紀錄' : 'Taipei city/county records', summary.recordsWithTaipeiCityCounty],
    [zh ? '重複執照字號列數' : 'Duplicate license-number rows', summary.dataQuality.duplicatePracticeLicenseNumberCount],
  ];
  return <><div className="notice subtle">{zh ? '獸醫師資訊資料未提供地址、行政區、電話或官方經緯度。本模組以資料表、查詢與機構統計呈現，不顯示地圖點位。' : 'Veterinarian registry data does not provide address, district, phone, or official coordinates. This module is shown as a data table, search view, and institution-level summary with no map points.'}</div><div className="summary-grid">{cards.map(([key, value]) => <article key={key}><span>{key}</span><strong>{typeof value === 'number' ? fmt(value) : value}</strong></article>)}</div>
    <div className="chart-grid"><BarChart title={zh ? '服務獸醫診療機構前 30 名' : 'Top 30 service veterinary institutions'} data={summary.topServiceVeterinaryInstitutions.map((item) => ({ label: item.serviceVeterinaryInstitutionName, value: item.veterinarianCount }))} /><BarChart title={zh ? '執業執照字號格式' : 'Practice license number format'} data={summary.byLicenseNumberFormat.map((item) => ({ label: label(formatLabels[item.practiceLicenseNumberFormat], language), value: item.count }))} /><BarChart title={zh ? '縣市分布' : 'City/county distribution'} data={summary.byCityCounty.map((item) => ({ label: item.cityCounty, value: item.count }))} /></div></>;
}

function Directory({ records, language }: { records: VeterinarianProfessionalRegistryRecord[]; language: Language }) {
  const zh = language === 'zh';
  const [limit, setLimit] = useState(100);
  useEffect(() => setLimit(100), [records]);
  return <><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['縣市', '姓名', '執業執照字號', '服務獸醫診療機構名稱', '來源明細'] : ['City / county', 'Name', 'Practice license number', 'Service veterinary institution', 'Source details']).map((item) => <th key={item}>{item}</th>)}</tr></thead><tbody>{records.slice(0, limit).map((record) => <tr key={record.id}><td>{record.cityCounty ?? '-'}</td><th>{record.veterinarianName}</th><td>{record.practiceLicenseNumber}</td><td>{record.serviceVeterinaryInstitutionName}</td><td><details><summary>{zh ? '來源明細' : 'Source details'}</summary><dl><div><dt>{zh ? '縣市代碼' : 'City code'}</dt><dd>{record.cityCode ?? '-'}</dd></div><div><dt>{zh ? '執照格式' : 'License format'}</dt><dd>{label(formatLabels[record.practiceLicenseNumberFormat], language)}</dd></div><div><dt>{zh ? '執照發照縣市候選' : 'Issued city candidate'}</dt><dd>{record.practiceLicenseIssuedCityCodeCandidate ?? '-'}</dd></div><div><dt>{zh ? '機構比對鍵' : 'Institution match key'}</dt><dd>{record.possibleAnimalHospitalMatchKey ?? '-'}</dd></div><div><dt>{zh ? '資料來源' : 'Source'}</dt><dd>{record.source}</dd></div><div><dt>{zh ? '來源機關' : 'Source agency'}</dt><dd>{record.sourceAgency}</dd></div></dl></details></td></tr>)}</tbody></table></div>{!records.length && <p className="empty">{zh ? '沒有符合條件的紀錄。' : 'No records match these filters.'}</p>}{limit < records.length && <button className="load-more" onClick={() => setLimit(limit + 100)}>{zh ? '載入更多' : 'Load more'} · {records.length - limit}</button>}</>;
}

function Compare({ summary, related, language }: { summary: VeterinarianProfessionalRegistrySummary; related: { animalHospitals?: RegisteredAnimalHospitalSummary; businessChanges?: BusinessRegistrationChangeSummary; companyChanges?: CompanyRegistrationChangeSummary; consumerDispute?: ConsumerDisputeAbsentBusinessOperatorSummary; laborViolations?: LaborStandardActViolationSummary }; language: Language }) {
  const zh = language === 'zh';
  const rows = [{ label: zh ? '獸醫師資訊' : 'Veterinarian registry', value: summary.totalRecords }, ...(related.animalHospitals ? [{ label: zh ? '動物醫院一覽表' : 'Registered animal hospitals', value: related.animalHospitals.totalRecords }] : []), ...(related.businessChanges ? [{ label: zh ? '商業異動' : 'Business changes', value: related.businessChanges.totalRecords }] : []), ...(related.companyChanges ? [{ label: zh ? '公司異動' : 'Company changes', value: related.companyChanges.totalRecords }] : [])], max = Math.max(...rows.map((row) => row.value), 1);
  return <div className="notes-grid"><article><h3>{zh ? '與動物醫院名冊的關係' : 'Relationship to animal hospital data'}</h3><p>{zh ? '本模組保留服務獸醫診療機構名稱，但未建立官方地址或服務關係。若與動物醫院名冊比對，僅能視為正規化名稱的非官方輔助比對。' : 'This module preserves service veterinary institution names but does not create official address or service relationships. Matching with animal hospital records should be treated only as non-official normalized-name assistance.'}</p></article><article><h3>{zh ? '與商業、公司、爭議資料比較' : 'Compare business, company, and dispute data'}</h3><p>{zh ? '獸醫師資訊不是商業登記、公司登記、消費爭議、勞動違規或品質評價資料，不應用來推論即時營業、服務品質、申訴、懲戒或法律狀態。' : 'Veterinarian registry data is not business registration, company registration, consumer dispute, labor violation, or quality-rating data and should not be used to infer real-time operation, service quality, complaints, discipline, or legal status.'}</p></article><article><h3>{zh ? '模組紀錄數' : 'Module record counts'}</h3><div className="bars">{rows.map((row) => <div className="bar-row wide-label" key={row.label}><span>{row.label}</span><div><i style={{ width: `${Math.max(2, row.value / max * 100)}%` }} /></div><b>{fmt(row.value)}</b></div>)}</div></article></div>;
}

export default function VeterinarianProfessionalRegistryModule({ records, summary, related, language }: { records: VeterinarianProfessionalRegistryRecord[]; summary: VeterinarianProfessionalRegistrySummary; related: { animalHospitals?: RegisteredAnimalHospitalSummary; businessChanges?: BusinessRegistrationChangeSummary; companyChanges?: CompanyRegistrationChangeSummary; consumerDispute?: ConsumerDisputeAbsentBusinessOperatorSummary; laborViolations?: LaborStandardActViolationSummary }; language: Language }) {
  const zh = language === 'zh';
  const [view, setView] = useState<'overview' | 'institutions' | 'licenses' | 'directory' | 'compare' | 'notes'>('overview');
  const [filters, setFilters] = useState(emptyFilters);
  const filtered = useMemo(() => filterVeterinarianProfessionalRegistry(records, filters), [records, filters]);
  const activeSummary = useMemo(() => Object.values(filters).some(Boolean) ? buildVeterinarianProfessionalRegistrySummary(filtered) : summary, [filtered, filters, summary]);
  const views = [['overview', zh ? '總覽' : 'Overview'], ['institutions', zh ? '機構統計' : 'Institutions'], ['licenses', zh ? '執照格式' : 'Licenses'], ['directory', zh ? '資料表' : 'Directory'], ['compare', zh ? '與公開資料比較' : 'Compare Records'], ['notes', zh ? '資料說明' : 'Data Notes']] as const;
  return <><Filters filters={filters} setFilters={setFilters} records={records} language={language} /><section className="workspace"><div className="section-heading"><p>06B / ANIMAL MEDICAL & WELFARE PUBLIC RECORDS</p><h2>{zh ? '獸醫師資訊' : 'Veterinarian Professional Registry'}</h2><span>{zh ? '查詢臺北市獸醫師資料，包含縣市代碼、縣市、姓名、執業執照字號與服務獸醫診療機構名稱。' : 'Look up Taipei veterinarian records including city code, city/county, name, practice license number, and service veterinary medical institution name.'}</span></div><div className="subtabs">{views.map(([id, text]) => <button className={view === id ? 'active' : ''} onClick={() => setView(id)} key={id}>{text}</button>)}</div><div className="notice subtle">{zh ? '獸醫師資訊為臺北市公開資料中的獸醫師資料，僅供查詢來源欄位使用，不代表即時執業狀態、門診時間、急診服務、預約可用性、專科認證、服務品質排名、醫療建議、申訴或懲戒紀錄、法律意見、官方推薦或官方背書。' : 'Veterinarian professional registry data is Taipei public-data information about veterinarians. It is for looking up source fields only and does not represent real-time practice status, clinic hours, emergency service, appointment availability, specialist certification, service quality ranking, medical advice, complaint or disciplinary records, legal advice, official recommendation, or official endorsement.'}</div>
    {view === 'overview' && <Overview summary={activeSummary} language={language} />}{view === 'institutions' && <BarChart title={zh ? '服務獸醫診療機構人數統計' : 'Service veterinary institution counts'} data={activeSummary.byServiceVeterinaryInstitution.map((item) => ({ label: item.serviceVeterinaryInstitutionName, value: item.veterinarianCount }))} />}{view === 'licenses' && <div className="chart-grid"><BarChart title={zh ? '執業執照字號格式' : 'Practice license number format'} data={activeSummary.byLicenseNumberFormat.map((item) => ({ label: label(formatLabels[item.practiceLicenseNumberFormat], language), value: item.count }))} /><BarChart title={zh ? '縣市分布' : 'City/county distribution'} data={activeSummary.byCityCounty.map((item) => ({ label: item.cityCounty, value: item.count }))} /></div>}{view === 'directory' && <><div className="section-heading inline"><div /><strong>{filtered.length.toLocaleString()} <span>{zh ? '筆符合紀錄' : 'matching records'}</span></strong></div><Directory records={filtered} language={language} /></>}{view === 'compare' && <Compare summary={activeSummary} related={related} language={language} />}{view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '地圖與點位限制' : 'Map and location limits'}</h3><p>{zh ? '獸醫師資訊資料提供縣市、姓名、執業執照字號與服務獸醫診療機構名稱，但未提供地址、行政區、電話或官方經緯度。本模組預設以資料表、查詢與機構統計呈現，不顯示地圖點位。若與動物醫院名冊進行名稱比對，應標示為非官方比對結果，不應視為官方地址或服務關係。' : 'Veterinarian registry data provides city/county, name, practice license number, and service veterinary institution name, but does not provide address, district, phone, or official coordinates. This module is shown as a data table, search view, and institution-level summary by default, with no map points. If matched with an animal hospital directory by name, the match should be labeled as a non-official matching result and should not be treated as official address or service relationship data.'}</p></article><article><h3>{zh ? '解讀限制' : 'Interpretation limits'}</h3><p>{zh ? '實際執業狀態、服務內容、門診資訊、專科資格、醫療需求與最新資料請以獸醫師本人、服務獸醫診療機構、臺北市政府產業發展局動物保護處、主管機關及官方公告為準。' : 'Actual practice status, services, clinic information, specialist qualifications, medical needs, and latest data should be verified with the veterinarian, service veterinary medical institution, Taipei City Animal Protection Office, competent authorities, and official announcements.'}</p></article><article><h3>{zh ? '資料來源' : 'Source'}</h3><p><a href="https://data.taipei/dataset/detail?id=4173b423-0c34-468e-a16d-5a7e7a06148e" target="_blank" rel="noreferrer">{zh ? '臺北市獸醫師資訊' : 'Taipei Veterinarian Professional Registry'} ↗</a></p></article></div>}</section></>;
}
