import { useEffect, useMemo, useState } from 'react';

interface VisuallyImpairedMassageEstablishment {
  id: string;
  sourceSequenceNumber: string;
  yearRaw: string;
  year: number | null;
  establishmentName: string;
  address: string;
  districtName: string;
  openingHoursRaw: string;
  googleMapsQuery: string;
}

const MISSING = '—';
const DISTRICTS = ['中正區', '大同區', '中山區', '松山區', '大安區', '萬華區', '信義區', '士林區', '北投區', '內湖區', '南港區', '文山區'];

function BarChart({ title, data }: { title: string; data: Array<{ label: string; value: number }> }) {
  const maximum = Math.max(1, ...data.map((item) => item.value));
  return <section className="chart"><h3>{title}</h3><div className="bars">{data.map((item) => <div className="bar-row wide-label" key={item.label}><span>{item.label}</span><div><i style={{ width: `${Math.max(2, item.value / maximum * 100)}%` }} /></div><b>{item.value}</b></div>)}</div></section>;
}

export default function VisuallyImpairedMassageEstablishmentsModule({ language }: { language: 'zh' | 'en' }) {
  const zh = language === 'zh';
  const [records, setRecords] = useState<VisuallyImpairedMassageEstablishment[]>([]);
  const [loadError, setLoadError] = useState(false);
  const [view, setView] = useState<'overview' | 'districts' | 'annual' | 'directory' | 'quality' | 'notes'>('overview');
  const [search, setSearch] = useState(''); const [year, setYear] = useState(''); const [district, setDistrict] = useState(''); const [openingHours, setOpeningHours] = useState(''); const [sort, setSort] = useState('name'); const [page, setPage] = useState(1);

  useEffect(() => { fetch(`${import.meta.env.BASE_URL}data/visually-impaired-massage-establishments/records.json`).then((response) => { if (!response.ok) throw new Error(String(response.status)); return response.json(); }).then(setRecords).catch(() => setLoadError(true)); }, []);
  const filtered = useMemo(() => {
    const query = search.trim().toLocaleLowerCase();
    return records.filter((record) => (!query || [record.establishmentName, record.districtName, record.address, record.openingHoursRaw, record.yearRaw, record.year].join(' ').toLocaleLowerCase().includes(query)) && (!year || String(record.year) === year) && (!district || record.districtName === district) && (!openingHours || (openingHours === 'yes' ? Boolean(record.openingHoursRaw) : !record.openingHoursRaw)));
  }, [records, search, year, district, openingHours]);
  const districtCounts = useMemo(() => DISTRICTS.map((label) => ({ label, value: new Set(filtered.filter((record) => record.districtName === label).map((record) => record.establishmentName)).size })).filter((item) => item.value), [filtered]);
  const annualCounts = useMemo(() => [...new Set(filtered.map((record) => record.year).filter((value): value is number => value !== null))].sort((a, b) => a - b).map((value) => ({ label: String(value), value: filtered.filter((record) => record.year === value).length })), [filtered]);
  const summary = useMemo(() => ({ total: filtered.length, unique: new Set(filtered.map((record) => record.establishmentName).filter(Boolean)).size, latestYear: Math.max(...filtered.map((record) => record.year ?? 0), 0) || null, districts: new Set(filtered.map((record) => record.districtName).filter(Boolean)).size, withHours: filtered.filter((record) => record.openingHoursRaw).length, topDistrict: [...districtCounts].sort((a, b) => b.value - a.value)[0]?.label ?? '' }), [filtered, districtCounts]);
  const sorted = useMemo(() => [...filtered].sort((a, b) => sort === 'year' ? (b.year ?? 0) - (a.year ?? 0) : sort === 'district' ? a.districtName.localeCompare(b.districtName, 'zh-Hant') : a.establishmentName.localeCompare(b.establishmentName, 'zh-Hant')), [filtered, sort]);
  const pageSize = 25; const pages = Math.max(1, Math.ceil(sorted.length / pageSize)); const rows = sorted.slice((Math.min(page, pages) - 1) * pageSize, Math.min(page, pages) * pageSize);
  const reset = (action: () => void) => { action(); setPage(1); };
  const downloadCsv = () => { const headers = ['ID', 'Year', 'Establishment', 'District', 'Address', 'Opening hours']; const value = (text: string | number | null) => `"${String(text ?? '').replaceAll('"', '""')}"`; const content = [headers, ...filtered.map((record) => [record.sourceSequenceNumber, record.yearRaw, record.establishmentName, record.districtName, record.address, record.openingHoursRaw])].map((row) => row.map(value).join(',')).join('\n'); const url = URL.createObjectURL(new Blob(['\uFEFF', content], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'visually-impaired-massage-establishments-filtered.csv'; link.click(); URL.revokeObjectURL(url); };
  const mapLink = (address: string) => address ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`} target="_blank" rel="noreferrer">{zh ? '地圖查詢' : 'Map lookup'}</a> : MISSING;
  if (loadError) return <section className="workspace"><div className="notice">{zh ? '無法載入本機資料檔。' : 'The local data file could not be loaded.'}</div></section>;
  return <section className="workspace"><div className="section-heading"><p>DISABILITY EMPLOYMENT / COMMUNITY SERVICES</p><h2>{zh ? '視障按摩院所名冊' : 'Visually Impaired Massage Establishments'}</h2><span>{zh ? '公開歷年名冊與行政區彙整；僅提供外部地址查詢，不建立精確地圖標記。' : 'Public annual directory and district summaries; external address lookup only, with no exact map markers.'}</span></div>
    <div className="subtabs">{([['overview', zh ? '總覽' : 'Overview'], ['districts', zh ? '行政區分布' : 'District Distribution'], ['annual', zh ? '年度紀錄' : 'Annual Records'], ['directory', zh ? '院所名冊' : 'Establishment Directory'], ['quality', zh ? '資料品質' : 'Data Quality'], ['notes', zh ? '資料說明' : 'Data Notes']] as const).map(([id, label]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => { setView(id); setPage(1); }}>{label}</button>)}</div>
    <aside className="filters"><label className="search"><input value={search} onChange={(event) => reset(() => setSearch(event.target.value))} placeholder={zh ? '搜尋院所、行政區、地址、營業時間或年度' : 'Search establishment, district, address, opening hours, or year'} /></label><div className="filter-grid"><label>{zh ? '年度' : 'Year'}<select value={year} onChange={(event) => reset(() => setYear(event.target.value))}><option value="">{zh ? '全部' : 'All'}</option>{[...new Set(records.map((record) => record.year).filter((value): value is number => value !== null))].sort((a, b) => b - a).map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label>{zh ? '行政區' : 'District'}<select value={district} onChange={(event) => reset(() => setDistrict(event.target.value))}><option value="">{zh ? '全部' : 'All'}</option>{DISTRICTS.filter((value) => records.some((record) => record.districtName === value)).map((value) => <option key={value}>{value}</option>)}</select></label><label>{zh ? '有營業時間資訊' : 'Has opening-hour information'}<select value={openingHours} onChange={(event) => reset(() => setOpeningHours(event.target.value))}><option value="">{zh ? '全部' : 'All'}</option><option value="yes">{zh ? '有' : 'Yes'}</option><option value="no">{zh ? '無' : 'No'}</option></select></label></div></aside>
    {view === 'overview' && <><div className="notice subtle">{zh ? '本資料為臺北市視障按摩小站及曾獲選為優良按摩院之公開名冊。年度、地址及營業時間皆為來源紀錄，不代表目前營運、即時預約、服務內容、價格、從業資格、服務品質、醫療效果或官方推薦；請向院所或臺北市勞動主管機關確認最新資訊。' : 'This dataset is a public directory of Taipei visually impaired massage stations and establishments previously selected as quality massage providers. Year, address, and opening-hour information are source records and do not confirm current operation, real-time appointment availability, services, prices, practitioner qualifications, service quality, medical effects, or official recommendation. Confirm current services directly with the establishment or the relevant Taipei City labor authority.'}</div><div className="summary-grid">{[[zh ? '紀錄總數' : 'Total records', summary.total], [zh ? '不重複院所' : 'Unique establishments', summary.unique], [zh ? '最新可用年度' : 'Latest available year', summary.latestYear ?? MISSING], [zh ? '涵蓋行政區' : 'Districts covered', summary.districts], [zh ? '有營業時間資訊' : 'Records with opening-hour information', summary.withHours], [zh ? '院所最多行政區' : 'District with most establishments', summary.topDistrict || MISSING]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div><BarChart title={zh ? '各行政區院所數' : 'Establishments by district'} data={districtCounts} /></>}
    {view === 'districts' && <BarChart title={zh ? '各行政區院所數' : 'Establishments by district'} data={districtCounts} />}
    {view === 'annual' && <><BarChart title={zh ? '各年度紀錄數' : 'Records by year'} data={annualCounts} /><BarChart title={zh ? '有無營業時間資訊' : 'Records with and without opening-hour information'} data={[{ label: zh ? '有' : 'With', value: summary.withHours }, { label: zh ? '無' : 'Without', value: summary.total - summary.withHours }]} /></>}
    {view === 'directory' && <><div className="section-heading inline"><p>{zh ? '篩選後紀錄' : 'Filtered records'}</p><strong>{sorted.length}</strong><button type="button" onClick={downloadCsv}>{zh ? '下載篩選 CSV' : 'Download filtered CSV'}</button><label>{zh ? '排序' : 'Sort'}<select value={sort} onChange={(event) => { setSort(event.target.value); setPage(1); }}><option value="name">{zh ? '依院所名稱' : 'Establishment name'}</option><option value="year">{zh ? '依年度' : 'Year'}</option><option value="district">{zh ? '依行政區' : 'District'}</option></select></label></div><div className="comparison-scroll procurement-table"><table><thead><tr>{(zh ? ['編號', '院所名稱', '年度', '行政區', '地址', '營業時間', '地圖查詢'] : ['ID', 'Establishment', 'Year', 'District', 'Address', 'Opening hours', 'Map lookup']).map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((record) => <tr key={record.id}><td>{record.sourceSequenceNumber || MISSING}</td><th>{record.establishmentName || MISSING}</th><td>{record.yearRaw || MISSING}</td><td>{record.districtName || MISSING}</td><td>{record.address || MISSING}</td><td>{record.openingHoursRaw || MISSING}</td><td>{mapLink(record.googleMapsQuery)}</td></tr>)}</tbody></table></div><div className="pagination"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>{zh ? '上一頁' : 'Previous'}</button><span>{page} / {pages}</span><button type="button" disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>{zh ? '下一頁' : 'Next'}</button></div></>}
    {view === 'quality' && <div className="notes-grid"><article><h3>{zh ? '欄位完整性' : 'Field completeness'}</h3><p>{zh ? `篩選後 ${summary.withHours} 筆具營業時間文字，${summary.total - summary.withHours} 筆未提供。缺少值以「${MISSING}」顯示，不會轉為 0。` : `${summary.withHours} filtered records contain opening-hour text and ${summary.total - summary.withHours} do not. Missing values display as “${MISSING}”, never as zero.`}</p></article><article><h3>{zh ? '年度解析' : 'Year parsing'}</h3><p>{zh ? '本頁保留原始年度文字，並將民國年度轉為西元年度供篩選與彙整；缺少或無法解析的年度不會視為 0。' : 'The page preserves source year text and converts ROC years to Gregorian years for filtering and summaries; missing or unparseable years are never treated as zero.'}</p></article></div>}
    {view === 'notes' && <div className="notes-grid"><article><h3>{zh ? '來源與範圍' : 'Source and scope'}</h3><p>{zh ? '本機 JSON 來自臺北市勞動局重建處公開資料，含視障按摩小站及曾獲選優良按摩院的歷年紀錄。歷史列入名冊不等同於目前營運或服務可用。' : 'The local JSON comes from Taipei City Department of Labor public data and contains annual records for visually impaired massage stations and establishments previously selected as quality massage providers. Historical inclusion does not confirm current operation or availability.'}</p></article><article><h3>{zh ? '位置資訊' : 'Location information'}</h3><p>{zh ? '來源沒有確認的官方座標，因此不建立精確地圖標記或自動地理編碼；地址僅提供外部地圖搜尋。' : 'The source has no confirmed official coordinates, so it creates no exact map markers or automatic geocoding; addresses only provide external map search.'}</p></article></div>}
  </section>;
}
